### ISSUE TITLE
GitHub release not created since 6.0.1

### ISSUE THREAD

**Issue by MikeFarrington** [nuke-build/nuke#1002]
### Usage Information

GitHub automations

### Description

I am just getting started on Nuke and was trying to understand what has been changed and added over time. 

I happened to notice that GitHub [tags](https://github.com/nuke-build/nuke/tags) are being created on each new release, but not GitHub [releases](https://github.com/nuke-build/nuke/releases).  None have been created since 6.0.1 in January.

I was able to see that descriptive release posts with changlogs are getting posted to the Glitter discussions in what appear to be an automated fashion.  I assume that the GitHub releases with these same changelogs are supposed to be getting created, but that automation has broken along the way.

So, this is just a "heads up" in case it hasn't been noticed yet.  I don't have any experience running a public github repo, perhaps they are being created as pre-releases which are not visible to non-admins.

### Reproduction Steps

see description

### Expected Behavior

see description

### Actual Behavior

see description

**Comment by valadas** [comment]
I don't know if it is on purpose or if something broke and it's a manual process done once in a while. But... Yeah, I was kind of expecting releases (and release notes) on GitHub but it is apparently mainly maintained in this file: https://github.com/nuke-build/nuke/blob/develop/CHANGELOG.md

**Comment by MikeFarrington** [comment]
Thanks, that's good to know.  I edited my post to add that perhaps the automation is creating the releases as pre-release, and non-admins cannot see them?  So, it may appear to be working properly for the admins.
