### ISSUE TITLE
Build not failing on error

### ISSUE THREAD

**Issue by RexTremendae** [nuke-build/nuke#1009]
### Usage Information

NUKE Execution Engine version 6.2.1 (Windows,.NETCoreApp,Version=v6.0)

### Description

In some cases when the build script outputs errors, the whole build is still reported as successful.

### Reproduction Steps

* Create a new nuke project, `nuke :setup` and select all default options.

* Add a powershell script, `fail.ps1` in the project root, containing the following line of code:
`Write-Error 'failure!'`

* Add a new nuke target in Build.cs:
```
    Target Fail => _ => _
        .Executes(() =>
        {
            PowerShellTasks.PowerShell(settings =>
                settings.SetFile("fail.ps1"));
        });
```
(requires `using Nuke.Common.Tools.PowerShell;`)

* Run `nuke fail`

### Expected Behavior

When errors occur during the build and are reported as `[ERR]` I would expect the build to fail.

### Actual Behavior

There are errors during the build that are reported as `[ERR]`, but the build still succeeds.

**Comment by matkoch** [comment]
See https://nuke.build/faq/ and it would be nice if you could star the project :)

**Comment by RexTremendae** [comment]
Well, the FAQ doesn't really help me. In my example, the PowerShell script is reporting an actual error (well, it is just calling Write-Error, but the external tool could be reporting an important error that I need to be aware of). I don't want the build process to accept that error, even if it logs it as an error in the output.
My point is: I can't find a way to fail the build when there is an actual error logged in the output. I tried overriding the logger, but even if I throw an error when type is Err, the build still succeeds.

**Comment by matkoch** [comment]
As long as your script returns with exit code `0`, the build won't fail. If you can't change the exit code, you'd need to check the whole list of output. For instance using `PowerShell(...).EnsureOnlyStd()`.

**Comment by RexTremendae** [comment]
But the Nuke build system has actually identified the output row as an error, it is adding it to the error summary. It feels a bit inconsistent behavior to not fail the build when there are lines reported as errors. Wouldn't it be an idea to have some kind of setting that says "treat any error as error"? It would be very convenient if we are actually talking about real errors from third party tools. I do understand that some tools are overusing the error channel, but that doesn't mean we can't trust any tool that uses it...

**Comment by matkoch** [comment]
No, this is too unreliable considering the number of tools that are supported. Adding `EnsureOnlyStd` is not a big deal in my opinion.
