### ISSUE TITLE
InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by soerenOsisa** [nuke-build/nuke#1014]
### Usage Information

Nuke v6.2.1 .NET 6.0.400

### Description

When the Nuke build reaches the Test Target it fails because nuke is trying to load the SDK with MSBuild which appearently doesnt use the right path and thus fails to find the SDK. Executing the Tests in Visual Studio and over the commandline works.

### Reproduction Steps

nuke inside root to setup build folder. select solution from src with included test project. run nuke

### Expected Behavior

running tests without invalidprojectexception error

### Actual Behavior

Test               Failed        < 1sec   // InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found. [...]\project.Tests\project.Tests.csproj

**Comment by matkoch** [comment]
not actionable / low effort issue
