### ISSUE TITLE
Add support to set azure pool name to use on-prem agents

### ISSUE THREAD

**Issue by MarkZither** [nuke-build/nuke#1019]
### Description

When using Azure Pipelines you can use an on-premise agent by setting pool to something like
    `pool: my-onprem-windows-pool`

Currently when the azure pipeline yml file is produced the output is like
```
    pool:
      vmImage: 'windows-latest'
```

This is defined in https://github.com/nuke-build/nuke/blob/553ec3ab0db17b85813c1a99563f9519ec2098da/source/Nuke.Common/CI/AzurePipelines/Configuration/AzurePipelinesJob.cs#L33 

```
                if (Image != null)
                {
                    using (writer.WriteBlock("pool:"))
                    {
                        writer.WriteLine($"vmImage: {Image.Value.GetValue().SingleQuote().SingleQuote()}");
                    }
                }
```

I propose changing the logic in that file to allow for the on-prem agent, which will mean changes to https://github.com/nuke-build/nuke/blob/develop/build/Build.CI.AzurePipelines.cs or https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/CI/AzurePipelines/AzurePipelinesAttribute.cs to allow for the new parameter.

### Usage Example

```code
Instead of specifying a PipelineImage we would specify the pool name and maybe we will need to OS, not sure about that yet.
	[AzurePipelines(
		//AzurePipelinesImage.UbuntuLatest,
		//AzurePipelinesImage.WindowsLatest,
		//AzurePipelinesImage.MacOsLatest,
                AzurePipelinesPool(?OS)
		InvokedTargets = new[] { nameof(Compile)})]
```

### Alternative

I think the alternative is amending the produced yml before committing.

**Comment by matkoch** [comment]
Hi @MarkZither, feel free to send a PR.

**Comment by MarkZither** [comment]
Will do, hopefully tomorrow at least a WIP for some comments on the approach.
