### ISSUE TITLE
Net 7.0 support - nuke --plan does to seem to do anything 

### ISSUE THREAD

**Issue by Simonl9l** [nuke-build/nuke#1023]
### Description

Net 7.0 Is in RC 1 status, is there a plan to support it at release?

so far I note that --plan does not work

```
nuke --plan --verbose
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Microsoft (R) .NET SDK version 7.0.100-rc.1.22431.12 
```

I have a GitHub Actions setup 
```C#
[GitHubActions(
    "continuous",
    GitHubActionsImage.UbuntuLatest,
    On = new[] { GitHubActionsTrigger.Push },
    InvokedTargets = new[] { nameof(Compile) })]
```

and expect the workflow to be generated.

**Comment by matkoch** [comment]
`net7.0` is supported ootb because nuke targets `netcoreapp3.1`. if there are any issues, I will take a look at them once its released.
