### ISSUE TITLE
Creating release for Octopus with multiline release notes results in error

### ISSUE THREAD

**Issue by pavlinyordanov** [nuke-build/nuke#1033]
### Usage Information

NUKE v6.2.1 / .NET v6.0 / Windows 10

### Description

Passing multiline release notes to OctopusCreateRelease method via SetReleaseNotes results in error. This is due to the fact that the release notes are passed in the form of "--releasenotes=value" which results in the value being broken by the newlines. The solution would be for the release notes to be passed in the form of --release notes "value", although this way has a risk of its own(if the release notes contain quotes, it will also fail, though they can be replaced with single quotes). It is not anything major as i've added workarounds. Feel free to close the issue if it is meaningless.

### Reproduction Steps

```
string releaseNotes = "random commit message 1 \n random commit message 2"
OctopusCreateRelease(_ => _
.SetApiKey("OctopusApiKey")
.SetServer("OctopusServer")
.SetProject("ProjectName")
.SetReleaseNotes(releaseNotes));
```

### Expected Behavior

An Octopus release should be successfully created.

### Actual Behavior

The build/step fails.

### Known Workarounds

1. Use Octopus method and pass parameters manually, ex. Octopus(create-release --server OctopusServer --apiKey ApiKey --project ProjectName --channel Channel --releaseNotes "Release Notes")
2. Use --releaseNotesFile instead of --releaseNotes

**Comment by matkoch** [comment]
<img width="1275" alt="JetBrains Rider-EAP-nuke-common – ArgumentsTest cs-2022-11-29-g0dGFAtO@2x" src="https://user-images.githubusercontent.com/5005566/204436030-02c0b9ed-5427-43b6-a51b-140b779a35f3.png">
