### ISSUE TITLE
Encountering "Sequence contains no matching element" when attempting to use 'component-based' build approaches and accessing members from parent Build

### ISSUE THREAD

**Issue by bhehe** [nuke-build/nuke#1036]
### Usage Information

Nuke 6.2.1, .NET 6

### Description

I am attempting to start establishing reusable assets for our builds as they've grown to be complex enough to warrant using a build base class and then weaving in the additional per-implementation specific needs through composition.

I started off following examples from the docs ( https://nuke.build/docs/sharing/build-components/ ) and then evolved them a bit further to meet my specific needs and confirm that the approach I was wanting to use for managing '_shared state_' between the various Target implementations and providing configuration/behavioral parameters would work. For that reason, I do not leverage the 'default implementations' on Interfaces as is shown in the examples; Rather, the interfaces serve as contracts between the DependsOn<T> uses and then the main Build class implements those per-Target interfaces. Additionally, the actual Target implementation classes implement the interface as well to be sure they remain in alignment.

After decomposing everything into interfaces/classes-per-Target implementation I ran into an odd behavior where the build would not run at all. I wouldn't even see the Nuke logo/banner.  Rather, I would get the "**_Sequence contains no matching element_**" error.  I do not see any stack trace being emitted to the console, but it does appear in the build log which is included in the _Actual Behavior_ section below.

With that initial failed outcome, I switched over to a "_dumbed down_" solution & build test rig to do some experiments and see if I could find the root-cause for the failure by working with a simpler version. In my example/test rig I first verified things would work with simple console output statements for each Target; Then when I tried to actually add behavior where I accessed a member of the main Build class itself, I could repro the issue.  What surprised me is that it was failing simply from accessing an **AbsolutePath** member being exposed on the Build class.

### Reproduction Steps

using Nuke.Common;
using Nuke.Common.IO;
using Nuke.Common.ProjectModel;
using System;

public class Build : NukeBuild
    , IClean
    , IRestore
    , ICompile
{
    public static int Main()
    {
        return Execute<Build>(x => x.Compile);
    }

    [Parameter("Configuration to build - Default is 'Debug' (local) or 'Release' (server)")]
    public Configuration Configuration { get; } = IsLocalBuild ? Configuration.Debug : Configuration.Release;

    [Solution]
    public Solution Solution { get; set; }

    public AbsolutePath SourceDirectory = RootDirectory / "src";
    public AbsolutePath ArtifactsDirectory = RootDirectory / "artifacts";

    public Target Clean => new CleanTargetImpl(this).Clean;

    public Target Restore => new RestoreTargetImpl(this).Restore;

    public Target Compile => new CompileTargetImpl(this).Compile;
}

public interface IClean
{
    Target Clean { get; }
}

public class CleanTargetImpl : IClean
{
    Build _build;

    public CleanTargetImpl(Build build) // Capture a reference so we can access shared state managed on the Build class itself.
    {
        _build = build;
    }

    public Target Clean => _ => _
        .Executes(() =>
        {
            Console.WriteLine("Clean");

            var artDir = _build.ArtifactsDirectory; // Accessing the member causes the issue; Comment it out & the Build works.
        });
}

public interface IRestore
{
    Target Restore { get; }
}

public class RestoreTargetImpl : IRestore
{
    Build _build;

    public RestoreTargetImpl(Build build)
    {
        _build = build;
    }

    public Target Restore => _ => _
            .DependsOn<IClean>(t => t.Clean)
            .Executes(() =>
            {
                Console.WriteLine("Restore");
            });
}

public interface ICompile
{
    Target Compile { get; }
}

public class CompileTargetImpl : ICompile
{
    Build _build;

    public CompileTargetImpl(Build build)
    {
        _build = build;
    }

    public Target Compile => _ => _
        .DependsOn<IRestore>(t => t.Restore)
        .Executes(() =>
        {
            Console.WriteLine("Compile");
        });
}

### Expected Behavior

- Builds can be broken down into _Component-based Targets_ for compositional approaches.
- Components can reference exposed members on the 'parent' **Build** class - of the **AbsolutePath** type.
- All Targets can be executed without failure.

### Actual Behavior

Build fails immediately with the following error when accessing an **AbsolutePath** member on the **Build** class:

"Sequence contains no matching element"

> 10:21:45.152 | V |                      | Target-unrelated exception was thrown
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Nuke.Common.Execution.ExecutableTargetFactory.<>c__DisplayClass1_0.<<ApplyDependencies>g__GetDependencies|0>d.MoveNext() in /_/source/Nuke.Common/Execution/ExecutableTargetFactory.cs:line 77
   at NuGet.Packaging.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
   at Nuke.Common.Execution.ExecutableTargetFactory.ApplyDependencies(ExecutableTarget executable, IReadOnlyCollection`1 executables) in /_/source/Nuke.Common/Execution/ExecutableTargetFactory.cs:line 87
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Nuke.Common.Execution.ExecutableTargetFactory.CreateAll[T](T build, Expression`1[] defaultTargetExpressions) in /_/source/Nuke.Common/Execution/ExecutableTargetFactory.cs:line 65
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions) in /_/source/Nuke.Common/Execution/BuildManager.cs:line 44

### Regression?

Unknown; 1st time attempting to decompose builds into components.

### Known Workarounds

Perhaps forego using **AbsolutePath** types entirely. That is an experiment I'm going to evaluate next. If a simple String works that may be what I use in the interim.

**Comment by bhehe** [comment]
**Update:** switching the exposed values on the Build class to simply be a String typed variable didn't change the behavior; The same error/stack-trace occurs.

**Comment by bhehe** [comment]
For reference, I tried another variant to see if I could workaround this issue. What is really surprising to me is that the code within the body of the expression is having this type of influence on the Nuke helper code for the **ExecutableTargetFactory**; I wouldn't expect it to have any awareness or insights into what the target is actually doing or using within the expression.

In this case, the same failure occurs once the code uses any of the dependent state/configuration. For this variant I didn't pass in via the constructor a reference to anything that is an INukeBuild type to see if that had any bearing on the discovery related code. Rather I just created a simple 'configuration' object and passed that in instead.  

I can verify that the sub-component for the Clean target IS getting created successfully and IS capturing the reference passed in via the ctor.  Another observation is that I see the ctor logging statement I added occurs **twice** - and then we see the failure message for the "_Sequence contains no matching element_" as we had before.

My Build class then implement an instance of the 'build output configuration' object and passes that in rather than a reference to "this" as it did before.



public interface IBuildOutputConfig
{
    string ArtifactsDirectory { get; }
}

public class BuildOutputConfig : IBuildOutputConfig
{
    public string ArtifactsDirectory { get; set; }
}

public interface IClean
{
    Target Clean { get; }
}

public class CleanTargetImpl : IClean
{
    IBuildOutputConfig _buildOutputConfig;

    public CleanTargetImpl(IBuildOutputConfig buildOutputConfig) // Capture a reference so we can access shared state managed on the Build class itself.
    {
        Console.WriteLine("ctor => CleanTargetImpl");
        _buildOutputConfig = buildOutputConfig; // Constructor is called, does capture reference. But is ran twice when build works.
    }

    public Target Clean => _ => _
        .Executes(() =>
        {
            Console.WriteLine("Clean");
            var artDir = _buildOutputConfig.ArtifactsDirectory;
        });
}

**Comment by matkoch** [comment]
no idea what you're doing here, but it doesn't work that way

**Comment by bhehe** [comment]
Can you explain why basic C# techniques wouldn't work here? Are you saying we can only do decomposition if we use the default implementation approach in the interfaces?  

Was looking for something helpful to allow use of decomposition/component-based approach that didn't require default implementations.

I don't see why this wouldn't be valid to use. It seems like the discovery code is barfing on a scenario that it should handle (nothing found).

**Comment by matkoch** [comment]
basic oop is probably the reason why it _doesn't_ work. you're free to inspect the source code, but as far as i'm concerned, this is not a design i ever intended to support.

**Comment by bhehe** [comment]
Can you then elaborate on how you would expect someone to implement a 'component-based' build where there is a component for a given Target and, in that implementation, there is a need to share some configuration/state that would ideally be expressed on the main build class itself?

The examples in the documentation work for super simple scenarios, but if you have any type of shared state/config - i.e., let's say a 'PublishedVersionNumber' property or something like that, we cannot do that using interfaces with default implementations.

**Comment by matkoch** [comment]
I'm afraid you're on your own with this. As I said it's not meant to be used in such a way. For sharing state, I see no reason why you wouldn't want to just declare a static class that holds the information.
