### ISSUE TITLE
Option to exclude the logs folder from the NUKE project

### ISSUE THREAD

**Issue by jwfx** [nuke-build/nuke#1039]
### Description

By default the `.nuke\temp` folder is included as `logs` into the solution. This has the unfortunate side effect that using "Find in files" results in Rider always get spammed with irrelevant entries from these log files.

Excluding the folder via .csproj does not seem to work. I assume because the `Nuke.Common.targets` is included afterwards.

It would be good extending [Nuke.Common.targets](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Nuke.Common.targets#L28) with a property that would allow exclusion.

```
<None Condition="'$(NukeExcludeLogs)' != 'True'" Include="$(NukeRootDirectory)\.nuke\temp\build*.log" Exclude="$(NukeRootDirectory)\.nuke\temp\build-attempt.log" LinkBase="logs" />
```

The property could then be used in build.csproj like

```
<PropertyGroup>
  <NukeExcludeLogs>True</NukeExcludeLogs>
</PropertyGroup>
```

### Usage Example

```code
(Example above, this box does not seem to support markdown...)
```

### Alternative

None to my knowledge.

**Comment by matkoch** [comment]
No votes here, but if you want, send a PR. If you do, please also cover the other linked directories.

**Comment by MichalSznajder** [comment]
Thank's for this! Search in files in Rider won't have hickups anylonger.
