### ISSUE TITLE
Helm timeout argument requires a duration unit suffix

### ISSUE THREAD

**Issue by lynkz-matt-psaltis** [nuke-build/nuke#1043]
### Usage Information

6.2.1 / 6.0 / 6.0 / Windows

### Description

Using latest 3.10.1 Helm executable from: https://github.com/helm/helm/releases
Current Helm documentation references Go formatted durations:
https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback

Current command format:
https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/Helm/Helm.json#L152

Suggested change:
`"format": "--timeout {value}s",`

There's some additional instances of this issue in this same file.

### Reproduction Steps

Using any of the Helm commands:

Additionally from the command line:

`helm upgrade --timeout 900`

Error: invalid argument "900" for "--timeout" flag: time: missing unit in duration "900"

```
var settings = new HelmUpgradeSettings();
settings
            .SetRelease(Name)
            .SetNamespace(Namespace)
            .EnableWait()
            .SetTimeout(900); 

HelmUpgrade(settings);
```

### Expected Behavior

Timeout should be correctly applied to the generated Helm command and the helm command succeeds

### Actual Behavior

An command format error is thrown indicating --timeout argument is not in the correct format

### Regression?

No I think just originally built against Helm 1?

### Known Workarounds

Use the argument configurator to override.

**Comment by matkoch** [comment]
see contrib guidelines
