### ISSUE TITLE
Dotnet local tools support

### ISSUE THREAD

**Issue by AntonC9018** [nuke-build/nuke#1050]
### Description

Support for injecting tools installed with `dotnet tool`.

### Resolution

Add a static method to `ToolResolver` for getting a locally or globally installed tool by name. This should read and cache in memory the information from the tool manifest.

### Alternative

Right now it's not obvious how to do it. I guess the best way is specifying a custom tool installation directory, but then you lose the benefits of caching, and tools installed this way are not added to the tool manifest, which means they won't be restored on `dotnet tool restore`. You shouldn't submit them to source control either, that's not a good solution, since the executable might be native to a particular platform.
One could say "duh, just use a package that provides a wrapper for this tool". But many even documented tools don't have these. [Library Manager](https://learn.microsoft.com/en-us/aspnet/core/client-side/libman/libman-cli?view=aspnetcore-6.0), for example.

**Comment by matkoch** [comment]
I don't see a reason to support tools installed through tool manifests. The current way is not much different, except that versions are defined in the `csproj` file.

Question though, why is it not obvious? From my point of view, it's all mentioned in the docs.

**Comment by AntonC9018** [comment]
> 

dotnet local tools are never mentioned in the docs

**Comment by matkoch** [comment]
Tools in .NET are always distributed via NuGet packages. Anything like "global tool" or "local tool" is just another label. They all follow the same principle which is explained here: https://nuke.build/docs/common/cli-tools/
