### ISSUE TITLE
GitVersion.Tool fails to be injected inside a GitHub Action workflow that uses actions/checkout@v2 or actions/checkout@v3

### ISSUE THREAD

**Issue by BusHero** [nuke-build/nuke#1052]
### Usage Information

6.0.1 / 6.1.1 / dotnet7 / GitHub Actions

### Description

**GIVEN** I've forked [nuke.bug](https://github.com/BusHero/nuke.bug) repo
**WHEN** I'm running the [continous.yml](https://github.com/BusHero/nuke.bug/blob/master/.github/workflows/continous.yml) workflow
**THEN** all the jobs ran successful

The bug is not present when running locally.

### Reproduction Steps

1. Fork the [nuke.bug](https://github.com/BusHero/nuke.bug) repo
2. Run the [continous.yml](https://github.com/BusHero/nuke.bug/blob/master/.github/workflows/continous.yml) workflow

### Expected Behavior

All the jobs ran successful

### Actual Behavior

Jobs that used **actions/checkout@v2** and **actions/checkout@v3** have failed

### Regression?

Seems like all versions of nuke are affected.
I've checked multiple versions of nuke and multiple versions of GitVersion.Tool, all of which has the problem.
The bug is not present when running locally, only inside a GitHub action, and only with aforementioned versions of **actions/checkout**.

### Known Workarounds

Use actions/checkout@v1

**Comment by BusHero** [comment]
Apparently, **fetch-depth: 0** fixes the problem. So you should use:
```
- uses: actions/checkout@v3
  with:
    fetch-depth: 0
```
I'm embarrassed.
Shame on me

**Comment by valadas** [comment]
Yes, that is the fix, and the docs say to run the build verbose to troubleshoot value injection issues, then if you do you get a bit of an error message to go by. Not super clear but after the first time you get into this problem, you kinda get the hang of it. Would be nice to add this info to the Nuke documentation about GitVersion examples though.

**Comment by BusHero** [comment]
Well, I was running in the verbose mode, but the message you get after it is not clear at all. 
The only reason I've found the fix is that I've looked at the workflow that nuke is using to build itself.

**Comment by valadas** [comment]
@matkoch would it be possible to mention that gotcha in the docs for the GitVersion example:
![image](https://user-images.githubusercontent.com/6371568/201488971-86fcef97-43d8-4c44-8088-68815ccc8425.png)

**Comment by matkoch** [comment]
People can post in discussions or Slack/Discord, but I'm not keen to document 3rd party tools on the website and having to keep that information up-to-date.
