### ISSUE TITLE
GitHubActions with Produces operation does not work

### ISSUE THREAD

**Issue by yakimovim** [nuke-build/nuke#1053]
### Usage Information

Nuke version 6.2.1, .NET SDK version 7.0.100

### Description

I want to use GitHubActions support and produce some artifacts. But when I use `Produces` method on my task, I got the following error:

```
Expected object of type 'Nuke.Common.IO.AbsolutePath' to be not null (Parameter 'left')
```

### Reproduction Steps

```cs
[GitHubActions(
    "continuous",
    GitHubActionsImage.WindowsLatest,
    On = new[] { GitHubActionsTrigger.Push },
    InvokedTargets = new[] { nameof(Compile) })]
class Build : NukeBuild
{
    public static int Main () => Execute<Build>(x => x.Compile);

    [Parameter()]
    readonly AbsolutePath PackagesDirectory;

    Target Compile => _ => _
        .Produces(PackagesDirectory / "*.zip")
        .Executes(() =>
        {
            Log.Information($"Root directory: {RootDirectory}");
            Log.Information($"Temporary directory: {TemporaryDirectory}");
        });

}
```

### Expected Behavior

I'd expect this build to execute without errors even on local computer.

### Actual Behavior

I have got the following error message:

```
Expected object of type 'Nuke.Common.IO.AbsolutePath' to be not null (Parameter 'left')
```

**Comment by matkoch** [comment]
parameters can't be used there

**Comment by yakimovim** [comment]
Is it possible to provide more meaningful error message in this case? Also, could you mention this information in [the documentation](https://nuke.build/docs/cicd/github-actions/#artifacts), please? Thank you!
