### ISSUE TITLE
build.sh cript file is created with windows-style \r\n line endings.

### ISSUE THREAD

**Issue by voroninp** [nuke-build/nuke#1059]
### Usage Information

6.2.1/7.0.100/.net7.0/Win11 (linux docker container)

### Description

When I run nuke in docker with:
```
RUN /bin/bash ./build.sh
```

I get this error: 
> ./build.sh: line 2: $'\r': command not found

After converting file to unix line endings, everything works fine.

### Reproduction Steps

Described above.

dockerfile:
```
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /build
COPY . .
RUN /bin/bash ./build.sh
```

### Expected Behavior

File should be generated with encoding approprate for linux.

### Actual Behavior

File contains `\r\n` line endings.

### Regression?

I don't know, never used Nuke before.

### Known Workarounds

Converting file manually.

**Comment by Baune8D** [comment]
Are you copying `build.sh` from a Windows filesystem to Docker? I saw the same issue when first cloning a repo containing a Nuke project to Windows with `autocrlf`, and then copying that project to a Linux Docker container. We solved it by settings `text=auto eol=lf` in `.gitattributes`
