### ISSUE TITLE
Add support for using ReSharper settings/profile to InspectCode --profile

### ISSUE THREAD

**Issue by DaveSenn** [nuke-build/nuke#1062]
### Description

InspectCode support using custom R# settings for code inspection. Such a settings file can be specified using the `--profile` argument. See: https://jetbrains.com.xy2401.com/help/resharper/InspectCode.html

This option enables sharing of R# settings between VS and InspectCode. This is important (for me at least) to make sure InspectCode checks for issues based on my coding style configuration.

If you like I could try to create a PR for this. 

### Usage Example

```code
var settings = new ReSharperInspectCodeSettings()
    .SetProfile( PathToFile );
```

### Alternative

I don't know another way how this could be achieved.

**Comment by matkoch** [comment]
PR is okay, i will close already.
