### ISSUE TITLE
Skipped target still triggers other target

### ISSUE THREAD

**Issue by DavidGhetto** [nuke-build/nuke#1076]
### Usage Information

NUKE 6.2.1 with .NET 6 on Windows 10

### Description

I have a target OctopusPack with a OnlyWhenDynamic condition
I have other targets OctopusPush and OctopusRelease that should run only if that target was not skipped but I cannot achieve this.

If I use Triggers(OctopusPush) on OctopusPack, and I run `nuke OctopusPack`, it still triggers OctopusPush when skipped:

> OctopusPack        Skipped                // SkipReason: (value(Build).BuildVersion != null)
OctopusPush        Failed        < 1sec   // ArgumentException: Expected object of type 'Semver.SemVersion' to be not null (Parameter 'BuildVersion')

### Reproduction Steps

Define a null field for the condition:

`object obj = null;`

Define a target that asserts `obj` is not null:

```
Target OctopusPush => _ => _
        .Executes(() =>
        {
            obj .NotNull();
        });
```

Define a target that is skipped when `obj `is null and triggers the previous target

```
Target OctopusPack => _ => _
        .OnlyWhenDynamic(() => obj != null)
        .Triggers(OctopusPush)
        .Executes(() =>
        {
           
        });

```

Run the OctopusPack target

### Expected Behavior

Both target are skipped

### Actual Behavior

Only the first target is skipped and the build fails

═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
OctopusPack2       Skipped                // SkipReason: (value(Build).obj != null)
OctopusPush        Failed        < 1sec   // ArgumentException: Expected object of type 'System.Object' to be not null (Parameter 'obj')
───────────────────────────────────────
Total                            < 1sec

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Doesn't work like this with triggers. You can use `DependsOn` instead.
