### ISSUE TITLE
Duplicate dictionary key when using more than one `OnlyWhenDynamic` condition and one of the conditions evaluate to false

### ISSUE THREAD

**Issue by DaveSenn** [nuke-build/nuke#1078]
### Usage Information

6.3.0

### Description

There is a new problem with the latest nuke version 6.3.0. 
The problem did not exist in 6.2.1.

The build fails with the following error message: `An item with the same key has already been added. Key: OnlyWhen`

Full stacktrace:
```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: OnlyWhen
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Nuke.Common.Utilities.Collections.DictionaryExtensions.AddPair[TKey,TValue](IDictionary`2 dictionary, TKey key, TValue value) in C:\_git\nuke\source\Nuke.Common\Utilities\Collections\Dictionary.AddKeyValue.cs:line 19
```

### Reproduction Steps

```c#
using System;
using System.Linq;

public sealed class Build : NukeBuild
{
    public static int Main() =>
        Execute<Build>( x => x.Default );

    #region Privates

    Target Default => _ => _
        .OnlyWhenDynamic( () => false )
        .OnlyWhenDynamic( () => false )
        .Executes( () =>
        {
        } );

    #endregion
}
```

Conditions:
- Target must have more than one condition `OnlyWhenDynamic`
- At least one condition must evaluate to false

### Expected Behavior

I see two options:

1. Nuke does not support multiple conditions `OnlyWhenDynamic`:
    Nuke should throw an exception on when a target has more than one condition. Maybe add it to the doc as well.

2. Nuke supports multiple conditions `OnlyWhenDynamic`:
    `BuildExecutor.HasSkippingCondition` could be changed to only set `target.OnlyWhen` once.
    Or `DictionaryExtensions` could be changed to support mutiple conditions. Maybe with a implementation combinding values when a item with the same key already exists.

### Actual Behavior

Build should finish successful or fail as early as possible.

### Regression?

Yes

### Known Workarounds

Add only a single condition to a target.

### Could you help with a pull-request?

Yes

**Comment by ricaun** [comment]
I have the same problem, my library does not work anymore using `Nuke.Common` version 6.3.0
Using 6.2.1 works fine.

**Comment by DaveSenn** [comment]
@matkoch do you want a PR for this issue?

**Comment by matkoch** [comment]
no it's fine, i just need some time to do another release
