### ISSUE TITLE
Nuke's Rider plugin doesn't recognize existing  run configuration after upgrading to 2022.3

### ISSUE THREAD

**Issue by jvmlet** [nuke-build/nuke#1079]
### Usage Information

Plugin version : NUKE Support 2022.3.0

### Description

This is what I see when editing previous `Run configuration`
![image](https://user-images.githubusercontent.com/6664858/208420538-7568663f-fb71-4bbf-86e6-2bffd8b7e45e.png)

### Reproduction Steps

Upgrade to  `2022.3`

### Expected Behavior

Previous configs are runnable

### Actual Behavior

Configuration are disabled

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
This is known, but I'm not planning to investigate this, since you can easily recreate the configuration.

**Comment by jvmlet** [comment]
For those suffering from the same, just open `workspace.xml` under `.idea\${prjName}` folder and change `factoryName="NUKE"` attribute to  `factoryName=".NET Project"` for each `configuration` node.
30 predefined run configurations was  not so easy to redefine manually.
