### ISSUE TITLE
build.ps1 outputs errors about "dotnet --version" if the right SDK is not there

### ISSUE THREAD

**Issue by dennisdoomen** [nuke-build/nuke#1087]
### Usage Information

6.3.0

### Description

When the `global.json` dictates a specific version for which there's no SDK, the resulting log always includes warnings like:

```
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible .NET SDK was not found.

Requested SDK version: 6.0.301
```

### Reproduction Steps

1. Update the `global.json` so a points to an SDK version you don't have and set `rollForward` to `disable`
2. Run `build.ps1` or `nuke`

### Expected Behavior

This error isn't displayed in the log. 

### Actual Behavior

See description

### Known Workarounds

Change line 38 of the `build.ps1` script to redirect the error output from `dotnet --version` to $null using `$(dotnet --version 2>$null)`. However, this requires disabling the strict mode. Otherwise it won't accept `$null` anywhere.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
This is on TeamCity ?

**Comment by matkoch** [comment]
Just for reference: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-7.3

The important part for a PR would be to bring `build.sh` in sync. Unfortunately, I can't test either. My Windows agent has the required version. A Linux agent I don't have at all.

**Comment by dennisdoomen** [comment]
> This is on TeamCity ?

Yes, but locally as well. 

> The important part for a PR would be to bring build.sh in sync. Unfortunately, I can't test either. My Windows agent has the required version. A Linux agent I don't have at all.

We have mixed Windows and Linux agents, and it doesn't happen on Linux.

**Comment by matkoch** [comment]
I think I will let this be the responsibility of the user. `2>$null` doesn't work with older versions of PowerShell, even with strict mode disabled.

But please let me know if you have any other suggestions.

**Comment by matkoch** [comment]
Could you try this?

```
if ($null -ne (Get-Command "dotnet" -ErrorAction SilentlyContinue) -and `
     $(& cmd /C "dotnet --version 2>nul") -and $LASTEXITCODE -eq 0) {
    $env:DOTNET_EXE = (Get-Command "dotnet").Path
}
```
