### ISSUE TITLE
Support plain mermaid output with Nuke --plan 

### ISSUE THREAD

**Issue by zplan** [nuke-build/nuke#1089]
### Description

The html plan output already contains the mermaid syntax in the html source code. The new feature should allow the export only the plain mermaid syntax into a file. 
Some good reasons for the feature:
- html does not allow to zoom big targets-tree plan properly 
- plain mermaid diagrams can be viewed and modified with a lot of different mermaid editors
- I want to automatically embed my Nuke plans into my existing markdown documentation as mermaid with ```mermaid

### Usage Example

```
nuke --plan --format=mermaid
nuke --plan --format=html  
```
html can still be the default when no format parameter is specified

### Alternative

Open the html page and copy&paste the mermaid part manually

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Not planned at the moment.
