### ISSUE TITLE
DotNetRun - application arguments enclosed in quotes

### ISSUE THREAD

**Issue by Robware** [nuke-build/nuke#109]
When specifying arguments for DotNetRun with spaces in, the arguments are enclosed in quotes which cause the arguments to not be passed to the program to be run ([see here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21)). Using the = sign works to avoid this, but is only available if you have one argument.

Using `SetApplicationArguments($"--ExampleArgument=asd")`:
`"C:\Program Files\dotnet\dotnet.exe" run --configuration Debug --project ExampleProject -- --ExampleArgument=asd`

Using `SetApplicationArguments($"--ExampleArgument asd")`:
`"C:\Program Files\dotnet\dotnet.exe" run --configuration Debug --project ExampleProject -- "--ExampleArgument asd"`

**Comment by matkoch** [comment]
Thanks for the report. Just committed a fix. Watch out for version 0.6.0-alpha0109 on https://www.nuget.org/packages/Nuke.Common/absoluteLatest.
