### ISSUE TITLE
Change instructions & dependency on NuGet.CommandLine

### ISSUE THREAD

**Issue by lanierhall** [nuke-build/nuke#1093]
### Usage Information

Nuke 6.3.0 / Nuget 6.4.0 / .NET 7 / Windows

### Description

Trying to use nuget with Nuke, I got an error that told me to install NuGet.CommandLine. There is no NuGet.CommandLine 6.4.0 but this is the version needed to restore a .net7 solution. I sidestepped this issue by using choco install nuget.commandline (they have a 6.4.0 version through slim wrapping) turns out I didn't need to as I can specify the exe location instead of normal. It looks like microsoft has a package called NuGet.CommandLine.Xplat that may be the replacement going forward. (It has 6.4.0 version but NuGet.CommandLine stops at 6.3.x)

### Reproduction Steps

Attempt to get NuGet working with NuGet.CommandLine in a .net7 project/solution.

### Expected Behavior

The help command in the error message should work and be up to date.

### Actual Behavior

The help command from the error message will fail if you try to get 6.4.0 version

### Regression?

Not really, kind of a progression. The frameworks are changing from underneath you.

### Known Workarounds

Just download nuget.exe v6.4.0 and specify the exe location in your build.

### Could you help with a pull-request?

No

**Comment by lanierhall** [comment]
I don't fully understand the last question, I'll provide anything I can with followup questions or feedback on a code review, but that's the limit of my time right now.

**Comment by ErisApps** [comment]
Seems like [NuGet.CommandLine 6.4.0](https://www.nuget.org/packages/NuGet.CommandLine) is available since a few days on NuGet now.
