### ISSUE TITLE
Setup script crashes if InternetExplorer was not started once

### ISSUE THREAD

**Issue by arxae** [nuke-build/nuke#11]
When running the setup.ps1 script it will ask target platform, but when answering the question, the script instantly crashes. Using Start-Transcript i found that the error is:

    "The response content cannot be parsed because the Internet Explorer engine is not available."

I hadn't started regular, non-edge internet explorer yet. But after i started it and chose the "use recommended settings", the script ran without problems

**Comment by matkoch** [comment]
@arxae thanks for your report. A quick StackOverflow search revealed that we can [add a parameter](https://stackoverflow.com/a/38054505/568266) `-UseBasicParsing`, however, I guess you've already started IE once and cannot check if this actually fixes the problem.

**Comment by arxae** [comment]
I currently have no computer that has not started IE to test it on. Maybe set up a VM? 

Because it hard crashes the powershell window (forgot to mention that), so getting the error is only possible with Start-Transcript. It's not very clear what had to be done

**Comment by matkoch** [comment]
The hard crash is due to some specifics in the powershell preamble. I guess if you start like `powershell .\setup.ps1` it willl correctly report that error. Something that I didn't have the time yet to investigate.

**Comment by arxae** [comment]
I tried doing that, but it also takes the shell down with it. Also tried with CMD (and then powershell .\setup.ps1), but still takes down the shell. Using > to output produced an empty file (which makes sense, since it outputs after the command is done).

**Comment by matkoch** [comment]
Would it be possible for you to have a troubleshooting meeting with me via Skype or TeamViewer?

**Comment by arxae** [comment]
I currently don't have this problem anymore. Opening IE and applying the default setting fixed it. But it's a pretty obscure issue if you don't know what is happening, that's why i opened this ticket :P

**Comment by matkoch** [comment]
I will eventually add this to the [troubleshooting section](http://www.nuke.build/getting-started.html#troubleshooting). But that the shell closed, even if you invoke `powershell .\setup.ps1` sounds quite strange to me.
