### ISSUE TITLE
GitHubTasks IsGitHubRepository throws an exception if the GitRepository does not have any defined remotes.

### ISSUE THREAD

**Issue by williamb1024** [nuke-build/nuke#1102]
### Usage Information

6.3.0

### Description

GitHubTasks IsGitHubRepository method throws a NullReferenceException when a repository does not have any defined remotes.

This leads to the CodeGenerationTask failing, although I suspect there would be a number of other locations where the error would likely appear.

```
 error MSB4018: The "CodeGenerationTask" task failed unexpectedly.
 error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
 error MSB4018:    at Nuke.Common.Tools.GitHub.GitHubTasks.IsGitHubRepository(GitRepository repository) in /_/source/Nuke.Common/Tools/GitHub/GitHubTasks.cs:line 118
 error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.<>c__DisplayClass20_0.<ExecuteInner>g__GetSourceFile|4(Tool tool) in /_/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 53
```

### Reproduction Steps

Perform a task that uses IsGitHubRepository on a repository that does not have any remotes.

### Expected Behavior

The exception should not be thrown.

### Actual Behavior

An NullReferenceException is thrown.

### Known Workarounds

Add a remote to the repository.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Feel free to send a pull-request. Will close though.

**Comment by ianflett** [comment]
Amusingly, just found this because I was working on adding it having discovered it earlier today. I have a fix, so I'll get a PR up ASAP.
