### ISSUE TITLE
LatestMavenVersionAttribute doesn't work consistently across different Maven repositories

### ISSUE THREAD

**Issue by ErisApps** [nuke-build/nuke#1103]
### Usage Information

Nuke 6.3.0 / .NET SDK version 7.0.101 / .NET 6 / Mac OS X 13.1

### Description

The LatestMavenVersion attribute throws an exception when used for Apache Maven because  no elements were found. This is in turn because of a bug in the URL construction which results in just a HTML page being returned.

The URL construction issue in question is a discrepancy between Maven API implementations regarding the (currently harcoded) section **"m2"**, which is correct for the Gradle API, but apparently not for Apache Maven API which uses **"maven2"**.

Eg:
https://plugins.gradle.org/m2/org/jetbrains/ ...
vs
https://repo.maven.apache.org/maven2/org/jetbrains/ ...

### Reproduction Steps

```csharp
[LatestMavenVersion(
    repository: "plugins.gradle.org",
    groupId: "org.jetbrains.kotlin.jvm",
    artifactId: "org.jetbrains.kotlin.jvm.gradle.plugin")]
readonly string GradleMavenVersion;

[LatestMavenVersion(
    repository: "repo.maven.apache.org",
    groupId: "org.jetbrains.kotlin.jvm",
    artifactId: "org.jetbrains.kotlin.jvm.gradle.plugin")]
readonly string ApacheMavenVersion;

Target PrintMavenVersions => _ => _
    .Executes(() =>
    {
        Logger.Info($"Latest Gradle Maven Version: {GradleMavenVersion}");
        Logger.Info($"Latest Apache Maven Version: {ApacheMavenVersion}");
    });
```

### Expected Behavior

Doesn't throw an error and prints the versions for both Gradle and Apache correctly in console.

```
╬═══════════════════════
║ PrintMavenVersions
╬══════════════
​
05:08:21 [INF] Latest Gradle Maven Version: 1.8.0-RC2
05:08:21 [INF] Latest Apache Maven Version: 1.8.0-RC2
```

### Actual Behavior

```log
05:08:20 [WRN] Could not inject value for Build.ApacheMavenVersion
System.Xml.XmlException: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text)
   at Nuke.Common.IO.XmlTasks.XmlPeekFromString(String content, String xpath, ValueTuple`2[] namespaces) in /_/source/Nuke.Common/IO/XmlTasks.cs:line 27
   at Nuke.Common.Tooling.LatestMavenVersionAttribute.GetValue(MemberInfo member, Object instance) in /_/source/Nuke.Common/Tooling/LatestMavenVersionAttribute.cs:line 32
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.TryGetValue(MemberInfo member, Object instance) in /_/source/Nuke.Common/ValueInjection/ValueInjectionAttributeBase.cs:line 25
```

```
╬═══════════════════════
║ PrintMavenVersions
╬══════════════
​
05:08:21 [INF] Latest Gradle Maven Version: 1.8.0-RC2
05:08:21 [INF] Latest Apache Maven Version:
```

### Regression?

Don't think this is a regression, but more like an oversight.
Not sure if the Maven API implementations are supposed to be standardized, and this is a one-off?

### Known Workarounds

It's possible to create a new attribute based on the existing LatestMavenVersionAttribute implementation, but with the `m2` section replaced by `maven2` and using the custom attribute when interacting with the Apache Maven repository.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
PR would be appreciated

**Comment by ErisApps** [comment]
I would gladly create a PR, but I'm not sure what the best way going forward would be for this issue.
I guess adding an optional parameter to override the "m2" part would be one way of fixing it, not sure if that's the most straightforward way (towards consumers) of fixing it though ?

**Comment by matkoch** [comment]
is it `maven2` instead of `m2` just for this repo or is this a general thing?

if it's general, then i'd say the attribute could automatically request both types and return the one where the request succeeded.

**Comment by ErisApps** [comment]
I did some more research into it and stumbled upon [a listing of several Maven repositories](https://mvnrepository.com/repos).

With this, I can safely conclude that there is no generalized API route prefix, as there are many other repositories which use neither `m2` nor `maven2`.

My proposed fix (which is a breaking change) is to just make the "m2" api prefix a part of the user-supplied repository argument, so the attribute after the changes would look like this.

```csharp
[LatestMavenVersion(
    repository: "https://plugins.gradle.org/m2/",
    groupId: "org.jetbrains.kotlin.jvm",
    artifactId: "org.jetbrains.kotlin.jvm.gradle.plugin")]
readonly string GradleMavenVersion;

[LatestMavenVersion(
    repository: "repo.maven.apache.org/maven2",
    groupId: "org.jetbrains.kotlin.jvm",
    artifactId: "org.jetbrains.kotlin.jvm.gradle.plugin")]
readonly string ApacheMavenVersion;
```

Please note that the leading `https://` and trailing `/` can still be optionally used as well and will be trimmed away in the attribute code and later on reconstructed when needed (as it already happens in the current version) .

**Comment by ErisApps** [comment]
Hii, with the release of 7.0, I'd like to remind you that the site (https://nuke.build/docs/common/versioning/#dependency-based-versioning) needs to be updated as well to reflect the changes done in the linked ticket.
