### ISSUE TITLE
Nuke.Common.Tools.*: Use custom logger

### ISSUE THREAD

**Issue by ITaluone** [nuke-build/nuke#1105]
### Description

It would be helpful (at least for the `DockerTasks`) to override the logger. Because docker's progress is printed to stderr, NUKE prints all progress as [ERR]. 

### Usage Example

In the custom logger I would do something like this:

```csharp
 DockerBuild(s => s
      .SetPath("path")
      .SetTag("myTag"), (_, msg) => Information(msg));
```

### Alternative

Now I am supressing the whole build output with `SetQuiet(true)`, but it would be interesting to see the progress.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
See FAQ, build execution.

**Comment by ITaluone** [comment]
Thanks :)

**Comment by ITaluone** [comment]
BTW:
![image](https://user-images.githubusercontent.com/44049228/211816953-ac76a552-72c0-4a0b-ad37-4c70143b758b.png)

;)

**Comment by matkoch** [comment]
Btw
![Microsoft Edge-New Issue · nuke-buildnuke-2023-01-11-bt8Fz3lu@2x](https://user-images.githubusercontent.com/5005566/211851271-c4adccf5-9e80-4d9c-883c-15a28d631fef.png)
![Microsoft Edge-nukeCONTRIBUTING md at develop · nuke-buildnuke-2023-01-11-tmW5l3JL@2x](https://user-images.githubusercontent.com/5005566/211851281-645d5ec2-3fbc-4bb5-bc4a-c2a98f9ef3d4.png)
