### ISSUE TITLE
Skipped targets with `OnlyWhenDynamic` does not skip dependencies

### ISSUE THREAD

**Issue by ITaluone** [nuke-build/nuke#1107]
### Usage Information

6.3.0

### Description

Suppose you have a `Target` defined like this:

```csharp
Target DoSomething => _ => _
        .OnlyWhenDynamic(() => condition)
        .WhenSkipped(DependencyBehavior.Skip)
        .DependsOn(
            A,
            B,
            C)
        .Executes(() =>
        {
        });
```

and the condition evaluates to `false`, the dependencies (A, B and C) are not skipped (as I would expect, because of `.WhenSkipped(DependencyBehavior.Skip)`.

What I am doing wrong here? Is this supposed to happen?

### Reproduction Steps

A target like this:

```csharp
Target DoSomething => _ => _
        .OnlyWhenDynamic(() => condition)
        .WhenSkipped(DependencyBehavior.Skip)
        .DependsOn(
            A,
            B,
            C)
        .Executes(() =>
        {
        });
```

### Expected Behavior

Because of the dynamic condition is `false`, it should skip the target, and because of the `.WhenSkipped(DependencyBehavior.Skip)` it should skip its dependencies.

### Actual Behavior

Is skipping only the target `DoSomething`, the dependencies won't be skipped. 

### Regression?

No

### Known Workarounds

Skipping every dependency with the same condition

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
`WhenSkipped` is only for static conditions. See documentation.
