### ISSUE TITLE
Documentation on `.OnlyWhenStatic()` is slightly inconsistent

### ISSUE THREAD

**Issue by ITaluone** [nuke-build/nuke#1112]
### Usage Information

6.3.0

### Description

Take the documentation:
![image](https://user-images.githubusercontent.com/44049228/212058888-a274d4af-3d86-4213-b44c-f1cc93e647a9.png)

and compare to the XML summary:
![image](https://user-images.githubusercontent.com/44049228/212059681-5f18f16d-f3d6-4a89-8da2-ac2866485256.png)

After checking it seems that the XML summary is correct here, because this does not work:

```csharp
class Build : NukeBuild
{
    [Parameter] readonly bool DoIt;

    Target A => _ => _
    .Executes(() =>  { });

    Target B => _ => _
    .DepensOn(A)
    .OnlyWhenStatic(() => !DoIt)
    .Executes(() => { });
```

**Comment by matkoch** [comment]
Absolutely unclear what you mean

**Comment by IT-VBFK** [comment]
In the documentation on nuke.build it states: "Define a condition that is checked before A and B execute" which states to me that "things" that might exist before target A and B (let's say injecting a parameter) are executed.

The XML summary on the other hand states to me, that after instantiating the `Build` class the condition is checked. (seems to be this behaviour)

**Comment by matkoch** [comment]
i still don't see how these are different
