### ISSUE TITLE
Source generating Solution configurations

### ISSUE THREAD

**Issue by jnyrup** [nuke-build/nuke#1113]
### Description

Having `StronglyTypedSolutionGenerator` to generate type-safe `Path`s for solutions folders is immensely useful.
I'm proposing to also source generate build configurations from the solution file.

A possible downside is that it to some degree bifurcates `Solution` as it then contains both `Configurations` and the source generated `Configuration`.

### Usage Example

```cs
DotNetBuild(s => s
    .SetProjectFile(Solution)
    .SetConfiguration(Solution.Configuration.Release));
```

### Alternative

Manually writing the string
```cs
DotNetBuild(s => s
    .SetProjectFile(Solution)
    .SetConfiguration("Release"));
```

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
What if there's a project or solution folder called `Configurations` ?

**Comment by jnyrup** [comment]
Right... 
A source generated `Configurations` property will simply hide the derived `Nuke.Common.ProjectModel.Solution.Configurations`.
So we cannot source generate any additional members that could name conflict with folders/projects.

An alternative would be to source generate it into a another class?

```cs
[SolutionConfigurations]
Configurations Configurations;

...

DotNetBuild(s => s
    .SetProjectFile(Solution)
    .SetConfiguration(Configurations.Release));
```

**Comment by matkoch** [comment]
Hi Jonas,

I don't think I will put effort in this. It's nice to have configurations generated, but on the other hand it will rarely change (unlike projects in the solution).
