### ISSUE TITLE
Use `long?` (or `string`)  for `JobId` in `Tools.CoverallsNet`

### ISSUE THREAD

**Issue by IT-VBFK** [nuke-build/nuke#1116]
### Description

When passing the `GitHubActions.RunId` as `JobId`.. that does not work anymore.. since the run id is beyond `int.MaxValue`.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/49762557/212992842-9d93ec08-23e2-434a-a0a4-28b45771b049.png">

### Could you help with a pull-request?

Maybe.. How does the `CoverallsNet.Generated.cs` generates? Do I only need to change `int` to `long` and rebuild?

**Comment by ITaluone** [comment]
The main problem here is the overflow that happens.

To avoid this `string` would be enough.. because on CLI it is just `string`
