### ISSUE TITLE
Setting ProcessCustomLogger on tool settings to any Action will cause target to fail with SerializationException

### ISSUE THREAD

**Issue by emilevr** [nuke-build/nuke#1117]
### Usage Information

6.3.0 / 6.0.401 / net6.0 / Windows 10

### Description

I am trying to get rid of [ERR] on every output line when using DockerBuild task (because docker CLI outputs progress to stderr).

A ProcessCustomLogger override set on ToolSettings (in this case DockerBuildSettings) seems to fit the bill. However, if I set it to any Action then the build target will fail with: "SerializationException: Serializing delegates is not supported on this platform". 

The exception is being raised by BinaryFormatter in Nuke.Common.Tooling.SettingsEntityExtensions.NewInstance and makes sense. Tried various options, but since the BinaryFormatter instance is not exposed it is not possible to use ISerializationSurrogate and the like. Since creation of the settings instance is also internal it is not possible to create a wrapper instance and use serialization attributes to customise the serialization.

**Questions**
* What is the purpose of the ProcessCustomLogger override?
* How is the ProcessCustomLogger override supposed to be used?

### Reproduction Steps

```CSharp
DockerBuild(
  _ => _.SetProcessCustomLogger((outputType, message) => { })
  ...)
```

### Expected Behavior

Would expect the override action to be called for log output.

### Actual Behavior

The build target fails with "SerializationException: Serializing delegates is not supported on this platform".

### Regression?

New feature in 6.3.0

### Known Workarounds

Probably the simplest option is to change the Serilog Logger to a new instance with a custom console sink, _only while the DockerBuild tasks run_.

This is what I am using:
```CSharp
internal class DockerBuildLogSanitiser : IDisposable, ILogEventSink
{
  private readonly ILogger _originalLogger;

  public DockerBuildLogSanitiser()
  {
    _originalLogger = Log.Logger;
    Log.Logger = new LoggerConfiguration()
      .WriteTo.Sink(this)
      .CreateLogger();
  }

  public void Dispose() => Log.Logger = _originalLogger;

  public void Emit(LogEvent logEvent) =>
    // We simply output the messages without prefixing with the log level, as Docker build outputs progress
    // to stderr and those are incorrectly coming through as log level Error.
    Console.WriteLine(logEvent.RenderMessage());
}
```
... and then:
```CSharp
using (new DockerBuildLogSanitiser())
{
  DockerBuild(_ => _. ...);
}
```

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Please see https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md
