### ISSUE TITLE
Dotnet Test Return Code on Bitbucket Pipelines not correct interpreted

### ISSUE THREAD

**Issue by fabEps** [nuke-build/nuke#1118]
### Usage Information

Nuke 6.3.0 / SDK 7.0.100 / Framework net7.0 / OS Windows 10

### Description

I observed a wrong behavior of the Bitbucket Pipelines Script Runner - I'm not sure if this is a bug:

Running tests in NUKE with DotNetTest won't indicate a failing build, if one of the unit tests is failing:
![image](https://user-images.githubusercontent.com/93125173/213708729-9d4ca48a-8e9c-44c5-b21e-2d975321e373.png)

The reason is the returned exit code which is negative, but it should be a positive value to indicate BB a failed build. A workaround is currently adapting the build.ps1 script as follows:
```
if ($LASTEXITCODE) { 
	if($LASTEXITCODE -lt 0) {
		exit 1
	}
	exit $LASTEXITCODE 	
```

instead of the default logic:
```
if ($LASTEXITCODE) { 
	exit $LASTEXITCODE 	
```

I'm not sure if BB causes the problem or if it's possible to solve this on NUKE side. 
Adapting each bootstrapper script file on creating a new build project could lead to missing this step.

### Reproduction Steps

```
    Target RunTest => _ => _
        .DependsOn(CompileTests)
        .Executes(() =>
        {
            DotNetTest(t => t
                .SetConfiguration(Configuration)
                .EnableNoBuild()
                .SetResultsDirectory(TestResultDirectory)
                .CombineWith(TestProjects, (ts, p) => ts
                    .SetProjectFile(p)
                    .SetLoggers($"trx;LogFileName={p.Name}.trx")));
        });
```

### Expected Behavior

Build should fail if unit test is failing:
![image](https://user-images.githubusercontent.com/93125173/213713242-8ca24eb1-eaa6-4f31-9004-ef7f598c7c91.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/93125173/213708729-9d4ca48a-8e9c-44c5-b21e-2d975321e373.png)

### Known Workarounds

```
if ($LASTEXITCODE) { 
	if($LASTEXITCODE -lt 0) {
		exit 1
	}
	exit $LASTEXITCODE 	
```

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Usually, anything that's not 0 should be considered a faulty execution. The majority of tools works this way. @lahma or @chaquotay uses/used Bitbucket, do you have any experience here?

**Comment by chaquotay** [comment]
We currently use Bamboo (also from Atlassian, but as far as I know not related to Bitbucket), so I don't have any Bitbucket experience 😕

**Comment by lahma** [comment]
We're running on bitbucket pipelines with nuke and failed tests error the pipeline. Maybe need to look into it more. Can those parallel tests affect final exit code?
