### ISSUE TITLE
build.ps1 error with version 0.6 related to vswhere.exe

### ISSUE THREAD

**Issue by GammaWolf** [nuke-build/nuke#112]
build.ps1 started to fail with an error starting with version 0.6 while it worked with the previous version.
It looks like it can't find the vswhere file or path. Then I assume an empty string as the path is passed and causes the error. 

error:

> 2018-08-08T08:20:55.9558440Z ##[error]Unbehandelte Ausnahme: System.InvalidOperationException: Der Prozess kann nicht gestartet werden, da ein Dateiname nicht angegeben wurde.
>    bei System.Diagnostics.Process.Start()
>    bei Nuke.MSBuildLocator.Program.MSBuildLocator.GetProcessOutput(String arguments)
>    bei Nuke.MSBuildLocator.Program.MSBuildLocator.GetVSWhereInstallation(String products, IReadOnlyCollection`1 requires, Boolean legacy)
>    bei Nuke.MSBuildLocator.Program.MSBuildLocator.TryGetMSBuildPath(String products, IReadOnlyCollection`1 requires, Boolean legacy)
>    bei Nuke.MSBuildLocator.Program.MSBuildLocator.Resolve()
>    bei Nuke.MSBuildLocator.Program.Main(String[] args)
> <REPLACEDPATH>\build.ps1 : 
> Der Ausdruck nach "&" in einem Pipelineelement hat ein ungültiges Objekt erzeugt. Der Ausdruck muss einen 
> Befehlsnamen, Skriptblock oder ein CommandInfo-Objekt ergeben.
> In Zeile:1 Zeichen:1

The exception message could be translated to: The process can't be started, because no file name was specified.

Here's the full output:
[NukeBuildPs1Error.txt](https://github.com/nuke-build/nuke/files/2269842/NukeBuildPs1Error.txt)

I've forced Nuke.MSBuildLocator in the build.ps1 to version 0.5 to fix it.

**Comment by arodus** [comment]
Hi GammaWolf, 
we updated the MSBuildLocator to use vswhere in the latest version. This prevents using a msbuild version without the required components. This update also requires a change in the buildscript for the build to work again. 
You can either just execute the nuke setup again using the Nuke global tool with the command `nuke !setup`. Or change [this line](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.GlobalTool/templates/build.netfx.ps1#L45) manually in your script.

**Comment by matkoch** [comment]
Or `nuke :setup`, depending on your installed version.

Is there any reason why your're using the netfx bootstrapping instead of netcore? Because with netcore tooling you'll also be able to build netfx projects. Many folks confuse this, and we're constantly trying to make this clearer during the setup process.

**Comment by GammaWolf** [comment]
Thank you, it does work with the modified script that specifies the vswhere path.

I've used netfx bootstrapping because I do not have any netcore projects, so I felt it wasn't necessary to have the added dependency.

**Comment by dnknitro** [comment]
The link from "Or change this line manually in your script." doesn't work.
`$MSBuildFile = & "$TempDirectory\Nuke.MSBuildLocator\tools\Nuke.MSBuildLocator.exe"`
should be replaced with 
`$MSBuildFile = & "$TempDirectory\Nuke.MSBuildLocator\tools\Nuke.MSBuildLocator.exe" "$TempDirectory\vswhere\tools\vswhere.exe"`
