### ISSUE TITLE
Exception is thrown when trying to get Logging.Level after setting not mapped LogEventLevel in Logging.LevelSwitch.MinimumLevel

### ISSUE THREAD

**Issue by sandrofigo** [nuke-build/nuke#1133]
### Usage Information

6.3.0 / 7.0.101 / net6.0 / Windows

### Description

An exception is thrown when a `LogEventLevel` is set via `Logging.LevelSwitch.MinimumLevel` that is not mapped here: https://github.com/nuke-build/nuke/blob/d0605d9086c9fc852b3b72b96fcd359096ca77ad/source/Nuke.Build/Logging.cs#L41

From discussion: https://github.com/nuke-build/nuke/discussions/1132

### Reproduction Steps

1. Run the following sample
```csharp
using Nuke.Common;
using Nuke.Common.Execution;
using Serilog;
using Serilog.Events;

class Build : NukeBuild
{
    public static int Main() => Execute<Build>(x => x.Test);

    Target Test => _ => _
        .Executes(() =>
        {
            Logging.LevelSwitch.MinimumLevel = LogEventLevel.Information;

            Log.Information(Logging.Level.ToString());
        });
}
```

### Expected Behavior

No exception is thrown and log level is logged.

### Actual Behavior

Exception is thrown:
```csharp
System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'LevelSwitch')
Actual value was Information.
   at Nuke.Common.Execution.Logging.get_Level() in /_/source/Nuke.Common/Execution/Logging.cs:line 47
   at Build.<>c.<get_Test>b__2_1() in D:\sandr\Desktop\nuke_test\build\Build.cs:line 15
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
```

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Sooner or later the custom `LogLevel` should be obsoleted. I don't see this as a strong use-case though to keep the issue. Thanks for filing.

**Comment by bretthysuik** [comment]
> Sooner or later the custom `LogLevel` should be obsoleted. I don't see this as a strong use-case though to keep the issue. Thanks for filing.

If this is cancelled, what's the solution for the problem discussed [here](https://github.com/nuke-build/nuke/discussions/1132)?

**Comment by sandrofigo** [comment]
@bretthysuik If you want to filter certain log levels you could try to wrap `Log.Logger` with a new custom logger e.g.:
```csharp
Log.Logger = new LoggerConfiguration()
            .Enrich.FromLogContext()
            .WriteTo.Logger(Log.Logger) // Wrapping the default logger from NUKE
            // Filter, add sinks or extend logger here
            .CreateLogger();
```
You can do this globally in `OnBuildInitialized()` or redefine the logger inside a single target.
