### ISSUE TITLE
bump default value of GitVersionAttribute.Framework property from net5.0 to net6.0

### ISSUE THREAD

**Issue by sebuseba** [nuke-build/nuke#1136]
### Description

It's probably a minor thing but I think it would be a good idea to bump default value of `GitVersionAttribute.Framework` property from net5.0 to net6.0 - see https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/GitVersion/GitVersionAttribute.cs#L27

by default `GitVersion` tool integration should target a TFM for the tool which is still supported (net5.0 lifetime ended May 2022).

### Usage Example

no need to explicitly set the `Framework` property

### Alternative

set the `Framework` to `"net6.0"` manually

### Could you help with a pull-request?

Yes

**Comment by sebuseba** [comment]
thanks for the swift response.

I went trough `CONTRIBUTING.md` again I'm not quite sure I understand the current state of the issue 😅 

Did I end up in `Don't file issues for tool wrappers. Send a pull-request instead!` or has this been _"implemented"_ already and I'm just not able to locate where?

sorry for bothering if I missed something obvious.

cheers

**Comment by matkoch** [comment]
it's assigned to a milestone and marked as completed.. so will be released with the milestone

**Comment by sebuseba** [comment]
Awesome, thanks for the clarification.
