### ISSUE TITLE
Allow customizing logs

### ISSUE THREAD

**Issue by tyb-dev** [nuke-build/nuke#1139]
### Description

We would like to ship logs to Elastic or Splunk and disable the local build file. In essence, we'd like to suppress `Logging.Configure(build);` and execute our own logic. 

### Usage Example

```
    [SplunkLogging]
    class Build : NukeBuild,
```

### Alternative

There is no clean workaround today. What we can do is write an `IOnBuildCreated` to overwrite `Log.Logger` at runtime. However, at that point, 
- a few lines have already been written and 
- we cannot use `ExecutingTargetLogEventEnricher` because it's internal. 

(To avoid files being written, we can use `NUKE_INTERNAL_INTERCEPTOR` and redirect the console via `Console.SetOut` temporarily)

Suggestion:
- Add the enricher via extension method similar to `.ConfigureHost`, `.ConfigureInMemory`, so it can be used from a public context.
- Some mechanism to change the behavior of `Logging.Configure`, for example via static delegate/interface that we can set. 

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
`IOnBuildCreated` + overriding `Priority` should be enough

**Comment by tyb-dev** [comment]
We can override Log.Logger but then we lose access to `ExecutingTargetLogEventEnricher` which we cannot add due to it being internal. Can we introduce an extension method similar to `.ConfigureHost` that adds the `ExecutingTargetLogEventEnricher`? Happy to provide a PR for this.

**Comment by matkoch** [comment]
yes that's fine

**Comment by tyb-dev** [comment]
> yes that's fine

Reopen? Then I can invest some time into the PR
