### ISSUE TITLE
Allow passing arguments explicitly

### ISSUE THREAD

**Issue by tyb-dev** [nuke-build/nuke#1140]
### Description

For testing purposes, it would be great if we could pass arguments (`string[]`) to `NukeBuild.Execute` explicitly, instead of reading them through `Environment`. This is similar to ASP.NET where we can do so explicitly as well. 

### Usage Example

```
        public static int Main(string[] args)
        {
           return Execute<Build>(args);
        }
```

### Alternative

We can write a surrogate arguments file. 

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Don't see a lot of benefit in this.

**Comment by tyb-dev** [comment]
We are writing reusable Nuke targets and custom parameter injection attributes used by downstream teams. To test targets and attributes, we use xUnit and would now like to run Nuke from test code. 
To accomplish this, we need to pass arguments to Nuke. Currently, nuke retrieves those arguments through `Environment.GetCommandLineArgs` which cannot be influenced at test time.
I hope to have elaborated a bit more the benefit and I am happy to contribute a PR. Is this something you can consider? 

If not, what are ways we could test our targets and attributes without losing debuggability and mockability in our tests?
