### ISSUE TITLE
Possibility to add coverlet integration

### ISSUE THREAD

**Issue by lucascebertin** [nuke-build/nuke#115]
I'm playing with nuke right now and would be awesome to use tools that run on dotnet core ootb.

Coverlet looks promising...
https://github.com/tonerdo/coverlet

Another possible way is to enable custom parameters on DotNetTest wrapper. 
What you guys think about this integration?

**Comment by matkoch** [comment]
@lucascebertin thanks for reporting. We can surely add support for coverlet.

What do you mean about custom parameters? You already can call `DotNet("parameters")`. Or are you thinking of something else?

**Comment by lucascebertin** [comment]
Oh, sorry about that... the DotNet method works great and I already used it for my purpose.
I was thinking on pass /p:CoverletArguments directly on DotNetTest method...

**Comment by matkoch** [comment]
Note to self: adapt ProcessManager to use `dotnet` executable if appropriate.

**Comment by ElijahReva** [comment]
I manage to do this using next code
```
    Target Test => _ => _
            .DependsOn(Compile)
            .Executes(() =>
        {
            GlobFiles(TestsDirectory, "**/*.Tests.fsproj")
                .NotEmpty()
                .ForEach(project =>
                    DotNetTest(s => DefaultDotNetTest
                        .SetProjectFile(project)
                        .SetArgumentConfigurator(args => args
                            .Add("/p:CollectCoverage=true")
                            .Add("/p:CoverletOutputFormat=opencover"))));
        });
```
