### ISSUE TITLE
Auto-generated files do not include an auto-generated XML header

### ISSUE THREAD

**Issue by gtbuchanan** [nuke-build/nuke#1157]
### Usage Information

6.3.0

### Description

Files generated by the `Nuke.SourceGenerators` assembly (by `SolutionAttribute`, for example) do not have the `/// <auto-generated />` XML header. Without this header, the generated files will be analyzed by Roslyn Analyzers.

### Reproduction Steps

1. Create a build project using `nuke :setup`
2. Add a property and apply the `SolutionAttribute`
3. Enable `EnforceCodeStyleInBuild` and `TreatWarningsAsErrors` in the `csproj`.
4. Reference `StyleCop.Analyzers`
5. Correct analyzer issues in default files
6. Build (This will fail due to the analyzer issues in the generated file)

[Library.zip](https://github.com/nuke-build/nuke/files/11399851/Library.zip)

### Expected Behavior

Roslyn Analyzers do not trigger for files auto-generated by `Nuke.SourceGenerators`.

### Actual Behavior

Roslyn Analyzers trigger for files auto-generated by `Nuke.SourceGenerators`. In certain build configurations, this causes the build to fail.

### Regression?

I'm not sure.

### Known Workarounds

You can likely add the generated file name to `.editorconfig` to disable analyzers but it would be too much effort.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Feel free to send a PR
