### ISSUE TITLE
ArgumentStringHandler blocks usage of variables 

### ISSUE THREAD

**Issue by makp0** [nuke-build/nuke#1163]
### Usage Information

7.0.0, NET 7.0

### Description

ArgumentStringHandler does not allow variables to be passed as arguments.

### Reproduction Steps

var cloneCommand = "clone https://github.com/nuke-build/nuke.git";
Git(cloneCommand);

### Expected Behavior

There have to be an overload allowing to pass strings.

### Actual Behavior

Argument is 'value' while parameter is declared as 'ref'

### Regression?

Yes. It's a completely avoidable breaking change.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
How is it avoidable?

**Comment by matkoch** [comment]
FYI, this has been discussed here: https://github.com/nuke-build/nuke/issues/1007

From the upcoming blog post:

> As a consequence of introducing this feature, all `arguments` must be passed as interpolated strings; even if you’re invoking a tool without any arguments, you have to pass `$“”`. This has two reasons. On the one hand, interpolated string handlers cannot deal with constant strings. On the other hand, there can’t be another overload with just `string`, because interpolated strings composed of just constant strings would be handled by the `DefaultInterpolatedStringHandler`, which would render this feature unreliable.
