### ISSUE TITLE
Add support for exit code handling in the Lightweight API 

### ISSUE THREAD

**Issue by R01Ne** [nuke-build/nuke#1166]
### Description

With the Fluent API for built-in tools, exit code handlers can be added through `.SetProcessExitHandler(...)`. This functionality should be added to the Lightweight API as well, so that users can optionally handle non-zero exit codes.

### Usage Example

Suggested usage, based on the documentation at [https://nuke.build/docs/common/cli-tools/](https://nuke.build/docs/common/cli-tools/)
```
CorFlags(
    arguments: $"...",
    processExitHandler: p => p.ExitCode switch
    {
        -1 => throw new Exception("Invalid args"),
        >0 => throw new Exception($"{p.ExitCode} tests have failed"),
        _ => null
    });
```

### Alternative

Wrap the tool invocation in a try-catch and capture the ProcessException, and extract the exit code form there:

```
var toolExitCode = 0;
try
{
	CorFlags(arguments: ...);
}
catch (ProcessException ex)
{
	toolExitCode = ex.ExitCode;
}
``` 

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Please consider adding a star ;)

**Comment by R01Ne** [comment]
Amazing, thank you!
