### ISSUE TITLE
DockerTasks.DockerStackDeploy() produces wrong arguments string

### ISSUE THREAD

**Issue by oldmine** [nuke-build/nuke#1168]
### Usage Information

NUKE Execution Engine version 7.0.0 (Linux,.NETCoreApp,Version=v6.0)

### Description

Calling **DockerTasks.DockerStackDeploy()** with **Stack** option produces not acceptable arguments for Docker CLI

```
╬══════════════════
║ ExampleDeploy
╬═════════
​
01:34:51 [INF] > /usr/bin/docker stack deploy --compose-file exampleComposeFile.yml exampleStackName stack
01:34:51 [ERR] "docker stack deploy" requires exactly 1 argument.
01:34:51 [ERR] See 'docker stack deploy --help'.
01:34:51 [ERR] 
01:34:51 [ERR] Usage:  docker stack deploy [OPTIONS] STACK
01:34:51 [ERR] 
01:34:51 [ERR] Deploy a new stack or update an existing stack
01:34:51 [ERR] Target ExampleDeploy has thrown an exception
Nuke.Common.Tooling.ProcessException: Process 'docker' exited with code 1.
   > /usr/bin/docker stack deploy --compose-file exampleComposeFile.yml exampleStackName stack
   @ /home/oldmine/Projects/example/build/bin/Debug
Error output:
   "docker stack deploy" requires exactly 1 argument.
   See 'docker stack deploy --help'.
   
   Usage:  docker stack deploy [OPTIONS] STACK
   
   Deploy a new stack or update an existing stack
```

Probably problem in inheritance, because **DockerStackDeploySettings** inherit **DockerStackSettings**, and when arguments builds called method **ConfigureProcessArguments()** of **DockerStackDeploySettings** and of **DockerStackSettings** where adds extra `stack` argument

### Reproduction Steps

```
Target ExampleDeploy => _ => _
        .Executes(() =>
        {
            DockerTasks.DockerStackDeploy(_ => _
                .SetStack("exampleStackName")
                .AddComposeFile("exampleComposeFile.yml")
            );
        });
```

### Expected Behavior

`/usr/bin/docker stack deploy --compose-file exampleComposeFile.yml exampleStackName`

### Actual Behavior

`/usr/bin/docker stack deploy --compose-file exampleComposeFile.yml exampleStackName stack`

### Known Workarounds

* Don't use Stack option
* Use `DockerTasks.Docker($"stack deploy --compose-file exampleComposeFile.yml exampleStackName")`

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Please see https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#before-creating-an-issue
