### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#117]
- [x] External files
- [x] Parameter declaration
- [x] Split into sub articles
- [x] Elaborate more
- [ ] Playground/examples (integrate as tests)
- [x] CLT wrapper (exposed arguments on method level)
- [ ] Katas ?
- [ ] GIFs
- [ ] How to write a plugin? #15

**Comment by matkoch** [comment]
https://github.com/dotnet/docfx/issues/3207 - Performance
https://github.com/dotnet/docfx/issues/3211 - Value tuples unsupported

**Comment by werwolfby** [comment]
It still in progress, but at least already something:

![image](https://user-images.githubusercontent.com/705754/44303336-06fc3e80-a347-11e8-9dba-3da192840fc2.png)

It is not final solution it's workaround,

**Comment by werwolfby** [comment]
Now it is better:
![image](https://user-images.githubusercontent.com/705754/44303919-d079f000-a355-11e8-90af-fe7db950cee1.png)
Except type itself.

**Comment by matkoch** [comment]
That might be related to the xrefmaps..

**Comment by werwolfby** [comment]
Finally:
![image](https://user-images.githubusercontent.com/705754/44307449-84f23100-a3ab-11e8-906a-2b0b485c03c4.png)

Few more checks and will be ready to create PR in docfx.

But it will change in nuke.web as well. I think it is best what we can do now.
