### ISSUE TITLE
Change in 7.0.1 causes NonParameter values to be injected later than they have been previously.

### ISSUE THREAD

**Issue by david-driscoll** [nuke-build/nuke#1177]
### Usage Information

7.0.1 / 7 / net7.0 / Windows(linux and mac)

### Description

[This commit](https://github.com/nuke-build/nuke/commit/f124b45b4bc04204b6539ee4ad19b2f9f86d581f) changes the behavior of how non parameter values are injected (ie [Solution] and friends). Before it was checking `is ParameterAttribute` which would hit for anything derived from the attribute. I can see this being unintended, however with the change now any `IOnBuildInitialized` extensions have to push their priority after `InjectNonParameterValuesAttribute` in order to function as they have before.

My initial thought to fix this is to change the non parameter values to be injected during `IOnBuildCreated` instead of `IOnBuildInitialized`, however I don't know what the intended design decisions were originally, so it's hard to say if that's the "right" change.

### Reproduction Steps

I've created a repo with a simple reproduction of the issue: https://github.com/david-driscoll/nuke-repro

You will get presented with the following error:  `Expected object of type 'Nuke.Common.ProjectModel.Solution' to be not null (Parameter 'build.Solution')`
If you override and set the `Priority` of the test extension to -101 then it will work.

### Expected Behavior

The non parameter values should be injected before your extension is called.

### Actual Behavior

The non parameter values are not injected before your extension is called.

### Regression?

7.0.0

### Known Workarounds

Overriding the default `Priority` for any dependent `IOnBuildInitialized` extensions to `-101` 

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Hi David,

this change was intentional to allow Azure KeyVault attributes to be overwritten through parameters. I anticipate that the number of people affected by this is very small, so I would (unless there are more reports) ask you to adapt the priority.

**Comment by matkoch** [comment]
Closing this, because no other reports.
