### ISSUE TITLE
DotNet process is kept alive

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#118]

**Comment by markusamshove** [comment]
Is [this](https://github.com/akkadotnet/akka.net/issues/2848) related?
Their solution is killing the process before a build, which seems a bit strange if more than one dotnet project is build on the same server.

**Comment by matkoch** [comment]
https://github.com/dotnet/cli/issues/9458 and https://github.com/dotnet/cli/issues/9481#issuecomment-413054533

**Comment by LordMike** [comment]
Is this related to the new-ish build-server? 

`dotnet builder-server shutdown` f.ex.

EDIT: Just read the links - yea, it's the build-server :P

**Comment by matkoch** [comment]
Yes, but something like `--no-servers` would be desirable (see https://github.com/dotnet/cli/issues/9481#issuecomment-413058280)
