### ISSUE TITLE
Global Tool does not Download Packages if it references Nuke.Common through transitive dependency

### ISSUE THREAD

**Issue by EdLichtman** [nuke-build/nuke#1183]
### Usage Information

7.0.2 / 7.0.102 / net6.0 / win

### Description

I have a Global tool with a transitive dependency on Nuke.Common by using a PackageReference on an internal library.

So...
Tool => Depends on ReuseableTargets
ReuseableTargets => Depends on Nuke.Common

Therefore, through Transitive Dependency
Tool => Depends on Nuke.Common

However, when I package up the Tool that "only" has a transitive dependency, then the Nuke.MsBuildTasks.dll does not get utilized and therefore, no Nuke Tasks are run.

What caused me to discover this is, there is a NukePackPackageTools target that doesn't run when I utilize Nuke.Common via Transitive Dependency.

### Reproduction Steps

Download the repository here:
https://github.com/EdLichtman/SampleNukeGlobalToolIssue
from {root}/SampleNukeIssue, run 

```
dotnet tool restore
```

followed by
```
nuke
```

You will be prompted to see the "Working" example and the "Not Working" example.

what's happening is, the "Working" example adds Nuke.Common to the "GlobalTool" project. So when "Demonstration" tries to run "GlobalTool", there is no issue. 

The "Not Working" example removes the Nuke.Common package reference from the "GlobalTool" project. So when "Demonstration" tries to run "GlobalTool", you'll see that the NuGet.CommandLine tool was not packaged.

### Expected Behavior

I expect that if I'm writing a library, and that library has a dependency on Nuke.Common, and I can use functions, and constants, and targets from Nuke.Common, and everything appears to me as if Nuke.Common is installed, because by the transitive dependencies, it is installed... I expect to be able to use Nuke in it's correct form.

### Actual Behavior

I can ONLY use Nuke.Common if I directly reference. This is... ok, and it's a workaround, but the problem is that nothing tells me why it's not working. If you somehow removed the transitive dependency entirely so that I can't access Nuke.Common, it'd at least let me know that I have to import it myself. But instead I publish a tool thinking it will work, and then find out that it doesn't work.

### Regression?

Unsure.

### Known Workarounds

Adding Nuke.Common as a direct reference works. But the problem is that it took a few days to figure out why it wasn't working and it took about a week before I figured out _that_ it wasn't working. 

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
As already mentioned on Slack. This is most probably because MSBuild does not include files for `ProjectReference` items. You should be able to workaround that by specifying `Nuke.Common` as an explicit dependency.

**Comment by EdLichtman** [comment]
@matkoch I'd like to re-open this for discussion -- I was able to get a fix for this, and can even try to be an author for the fix if you're so inclined. The problem is if you are opposed to transitive Build and Analyzers

The premise is, the "Build,Analyzers" are excluded from consumption by children due to the nature of References. However, if we add PrivateAssets="none" to the nuke :setup template, then that's one solution.

The other is adding the proper documentation to the Global Builds page
https://nuke.build/docs/sharing/global-builds/

The idea is: "If you wish to create a CoreLibrary that dispenses targets and parameters, and Nuke.Common is a dependency on that CoreLibrary, then you must still include Nuke.Common in the consumer of the CoreLibrary, or, you can avoid this by adding PrivateAssets="none" to the CoreLibrary's Nuke.Common PackageReference."

A final, third option I haven't yet tested out -- there is a way to modify the NuSpec of Nuke.Common during the MSBuild process, at which point you can add:

```
      <group targetFramework="net6.0">
        <dependency id="Nuke.Common" version="7.0.2" include="Build,Analyzers" />
      </group>
```

I have yet to test that theory because the minimal steps I've produced to recreate overwrite the nuspec every time I run it, but I'm literally working on this general thing for my own company's internal library at the moment.
