### ISSUE TITLE
Using Arguments in combination with secrets in version 7

### ISSUE THREAD

**Issue by Droppers** [nuke-build/nuke#1196]
### Usage Information

7.0.2

### Description

We are looking to upgrade to the latest version of Nuke.

We extensively use the `Arguments` class for building command line arguments.  We depend on `Arguments` class because we have many instances were we conditionally add arguments to the builder.

We are running into an issue were we are not able to use the existing `Arguments` usages when executing a tool. In version <6 we are able to pass `Arguments.FilterSecrets` to the tool using the `outputFilter` parameter. Since this has been removed in the latest version in favour of the `ArgumentStringHandler`, this cannot be done anymore.

Is there a workaround available that will still allow us to use the `Arguments` builder in combination with secrets?

### Reproduction Steps

Our current usage:
```cs
var arguments = new Arguments()
    .Add("--secret {value}", "my-very-secret-secret", secret: true);
MyTool(arguments.RenderForExecution(), outputFilter: arguments.FilterSecrets);
//                                     ^ not possible anymore
```

### Expected Behavior

Be able to use `Arguments` in combination with filtering output secrets, similar as to how it was possible in Nuke <6.

### Actual Behavior

We cannot find a proper workaround for conditionally building arguments similar to `Arguments`.

### Known Workarounds

 - Write a wrapper builder around ArgumentStringHandler that implements the same behaviour as the `Arguments` builder.

### Could you help with a pull-request?

No

**Comment by andrew-from-toronto** [comment]
We are having issues with the new ArgumentStringHandler as well. One case we construct the argument string from a dictionary of values and then invoke the tool with the arg string, containing multiple args itself, as a single formatted string {args}. The handler then quotes the entire section and does quote escaping to each arg value. This broke quite a few things in our code base when I updated.

Concrete code that broke:

```
var argString = string.Join(" ", args.Select(kvp => $"-{kvp.Key} \"{kvp.Value}\""));
AzureSignTool($"sign {argString} {fileToSign}", workingDir);
```

**Comment by matkoch** [comment]
@andrew-from-toronto https://github.com/nuke-build/nuke/commit/972138c3d6da0272f192ab214f4f65b363c0081d

**Comment by andrew-from-toronto** [comment]
@matkoch We are on 7.0.2 so I'm not sure if that helped my case

**Comment by matkoch** [comment]
Sorry, only read the first part of the comment.

Sidenote: it would be much better in cases like this to submit a pull-request to support the given argument in the fluent API.

**Comment by Droppers** [comment]
> Sorry, only read the first part of the comment.
> 
> Sidenote: it would be much better in cases like this to submit a pull-request to support the given argument in the fluent API.

Is the sidenote meant as a reply on my issue, or on what @andrew-from-toronto said?

**Comment by matkoch** [comment]
@Droppers probably for both.

As far as I'm concerned everything works as intended. `Arguments` should've been made `internal` earlier. It leads to a lot of boilerplate code (which is only okay for the generated code where it's being used).
