### ISSUE TITLE
Executing git commit fails in version 7

### ISSUE THREAD

**Issue by yiwan74** [nuke-build/nuke#1199]
### Usage Information

7.0.2

### Description

This command works well in version 6.2.1
Git($"commit -m \"{(PublishPublic ? "Release" : "Internal release")} {_Version}\"");

and results in 
git commit -m "Internal release 1.0.1.0"

but in version 7.0.2 resulting git command has additional quotes:
git commit -m ""Internal release" 1.0.1.0"

### Reproduction Steps

This is test code:
![image](https://github.com/nuke-build/nuke/assets/14015195/95f0b878-2282-47f4-beda-2ab5606b753d)
and this image shows wrong command:
![image](https://github.com/nuke-build/nuke/assets/14015195/ac881cf7-9951-4613-8841-4d04b3f35acd)

### Expected Behavior

git commit -m "Internal release 1.0.1.0" instead of  git commit -m ""Internal release" 1.0.1.0"

### Actual Behavior

![image](https://github.com/nuke-build/nuke/assets/14015195/4a482a7f-47f3-4b14-9a1b-e595952ede5c)

### Regression?

Works well in 6.2.1

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
check in discussions

**Comment by valadas** [comment]
@yiwan74 this worked for me:

```
Git($"commit -m \"Commit generated files from first build.\"");
```

**Comment by yiwan74** [comment]
@valadas 
Thanks for suggestion. In my case using nq, as suggested in discussion about this issue, helped me.

So...

` Git($"commit -m \"{(PublishPublic ? "Release" : "Internal release")} {_Version}\"");`

results in incorrect command (double quoted argument):
` "C:\Program Files\Git\cmd\git.exe" commit -m ""Internal release" 1.1.1"`
 
 and using **:nq**
` Git($"commit -m \"{(PublishPublic ? "Release" : "Internal release"):nq} {_Version}\"");`

 results in correct formatted command:
` "C:\Program Files\Git\cmd\git.exe" commit -m "Internal release 1.1.1"`
