### ISSUE TITLE
Implicit addition of double quotes in AbsolutePath.ToString

### ISSUE THREAD

**Issue by cz-dev-ge** [nuke-build/nuke#1203]
### Usage Information

7.0.3 / .NET 7 / .NET 7 / Windows 10

### Description

After upgrading from 6.3.0 to 7.0.3 my `ToolResolver` created tool calls using implicit AbsolutePath's ToString failed.

I had a look into the code and it looked as if `nq` is the standard behaviour.

```cs
public override string ToString()
{
  return ((IFormattable)this).ToString(format: null, formatProvider: null);
}

public string ToString(string format)
{
  return ((IFormattable)this).ToString(format, formatProvider: null);
}

string IFormattable.ToString(string format, IFormatProvider formatProvider)
{
  return format switch
  {
    DoubleQuote => _path.DoubleQuote(),
    DoubleQuoteIfNeeded => _path.DoubleQuoteIfNeeded(),
    SingleQuote => _path.SingleQuote(),
    SingleQuoteIfNeeded => _path.SingleQuoteIfNeeded(),
    null or NoQuotes => _path,
    _ => throw new ArgumentException($"Format '{format}' is not recognized")
  };
}
```

So why does it add quotes here? Am I doing something wrong?

Best regards,
Georg

### Reproduction Steps

```cs
var directory = @"C:\Apps\My Folder\";
var myTool = ToolResolver.GetTool( @"C:\Apps\MyApp.exe" );

myTool( $@"-dir ""{directory}"" " );
```

### Expected Behavior

`C:\Apps\MyApp.exe -dir "C:\Apps\My Folder\"`

### Actual Behavior

`C:\Apps\MyApp.exe -dir ""C:\Apps\My Folder\""`

### Regression?

Yes

### Known Workarounds

`{directory:nq}`

### Could you help with a pull-request?

No

**Comment by cz-dev-ge** [comment]
Another example:

```cs
var myApp = ToolResolver.GetTool( AbsolutePath.Create( "C:" ) / "Apps" / "my.exe" );

var files = string.Join( ' ', new AbsolutePath[]
{
  AbsolutePath.Create( "C:" ) / "MyFolder",
  AbsolutePath.Create( "C:" ) / "My Target"
}.Select( item => $"{item:dn}" ) );

myApp($"{files}" );
```

Becomes:

`C:\Apps\my.exe C:\MyFolder \"C:\My Target\"
`

And even simpler:

```cs
var myTool = ToolResolver.GetTool( AbsolutePath.Create( "C:" ) / "Apps" / "my.exe" );
myTool( @"-myParameter=""X1"" " );
```

becomes:

`C:\Apps\my.exe -myParameter=\"X1\" `

**Comment by matkoch** [comment]
Intended behaviour. Also noted in the changelog. See `ArgumentStringHandler`.

**Comment by czdietrich** [comment]
That's a very weird decision. Why would one want to automatically quote strings that contain whitespaces. It's just a pure guess that this is the wanted choice when passing strings. I agree that auto-quoting `AbsolutePath`'s seems to be reasonable, but doing this for all strings really breaks intuition and creates more problems than it solves. :/
