### ISSUE TITLE
Solution source generator can't handle solution path from attribute / does not report exceptions properly

### ISSUE THREAD

**Issue by jwfx** [nuke-build/nuke#1205]
### Usage Information

NUKE 7.0.2 / SDK 7.0.304 / net6.0 / Win10 x64

### Description

There are two closely related issues:

1. The solution source generator does not work when using the `relativePath` constructor parameter of the `SolutionAttribute` instead of defining the solution name in `parameters.json`.
[This](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.SourceGenerators/StronglyTypedSolutionGenerator.cs#L47) part of the code only handles reading the `parameters.json` and subsequently throws when the key is not found.

3. Exceptions in the solution source generator are not caught and reported through the provided source generator logging facilities.
As a result the actual error is swallowed an only an unhelpful compiler error is shown, see "Actual Behavior"

I can provide a pull request that addresses both issues.

### Reproduction Steps

1. Clone NUKE repo
2. Remove `"Solution": "nuke-common.sln",` from `parameters.json`
3. Replace 
`[Solution(GenerateProjects = true)] readonly Solution Solution;`
with
`[Solution("nuke-common.sln", GenerateProjects = true)] readonly Solution Solution;`
in `build\Build.cs`
4. Run `nuke --help` or `dotnet build` in `build` project

### Expected Behavior

Compilation should succeed.

### Actual Behavior

Compilation breaks with opaque error message. 

```
C:\Program Files\dotnet\sdk\7.0.304\Roslyn\Microsoft.CSharp.Core.targets(80,5): error MSB6006: "csc.dll" exited with code 1. [D:\downloads\nuke\build\_build.csproj]
```

### Regression?

Not from what I can tell.

### Known Workarounds

Use solution name from `parameters.json`

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
@jwfx when you send a pull-request, please also consider that the solution argument could reference another field (not a constant).

**Comment by jwfx** [comment]
The only thing other than a string literal that the compiler lets me feed in is a reference to another const string field, so something like 

```
const string test = "nuke-common.sln";
[Solution(test, GenerateProjects = true)] readonly Solution Solution;
```
Otherwise I'm getting:
"An attribute argument must be a constant expression, 'typeof()' expression or array creation expression of an attribute parameter type"
The latter two of course don't work because they don't match the ctor signature.

Anything else I could be missing here?
