### ISSUE TITLE
VSCode Marketplace Page is broken

### ISSUE THREAD

**Issue by MartinSGill** [nuke-build/nuke#1208]
### Usage Information

n/a

### Description

VSCode Marketplace Page is broken, see image. Loads of broken links/images.

![image](https://github.com/nuke-build/nuke/assets/2271740/00954ca5-58a5-47f2-a2a6-072863617b30)

### Reproduction Steps

Go to website: https://marketplace.visualstudio.com/items?itemName=nuke.support

### Expected Behavior

It looks great and eveyone wants to install and use it!

### Actual Behavior

Lots of broken images/links

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Could you send a pull-request to update [the docs](https://github.com/nuke-build/nuke/blob/develop/docs/07-ide/vscode.md) with the information from the Marketplace site?

I don't think we need any additional images there, but a paragraph about the configuration. Please try to match the current style of the docs and don't just copy/paste if you decide to send a pull-request.

**Comment by MartinSGill** [comment]
This is what I believe you are asking me to do, please let me know if I misunderstood.

1. I Assume: The current marketplace doc is not in this repo
2. You wish to have the docs page (linked) become the new marketplace document (i.e. it will be used both on nuke.build and on marketplace.visualstudio.com/vscode)

**Comment by matkoch** [comment]
What's shown on the marketplace is the `README.md` from the VS Code repository. That is a private repository, and VS Code extensions don't allow to include images in the VSIX file (unlike VS extensions).

So my suggestion is to replace the `README.md` with just a link to the docs on nuke.build, and for that it would be good to transfer over the whole part about configuration.
