### ISSUE TITLE
Should `EntityFrameworkTasks` use `dotnet-ef.exe` rather than `dotnet.exe`

### ISSUE THREAD

**Issue by michael-wolfenden** [nuke-build/nuke#1213]
### Usage Information

NUKE Execution Engine version 7.0.2 (Windows,.NETCoreApp,Version=v6.0)

### Description

`EntityFrameworkTasks`  expects `dotnet-ef` to be added as a `dotnet tool` instead of allowing it to be added as a nuget package reference via `nuke :add-package dotnet-ef`

### Reproduction Steps

Given the following task:

```csharp
Target EF => _ => _
    .Executes(() =>
    {
        EntityFrameworkTasks.EntityFrameworkDatabaseDrop());
    });
```

Running `nuke EF` throws the following exception

```
09:27:02 [INF] > "C:\Program Files\dotnet\dotnet.exe" ef database drop
09:27:03 [ERR] Could not execute because the specified command or file was not found.
09:27:03 [ERR] Possible reasons for this include:
09:27:03 [ERR]   * You misspelled a built-in dotnet command.
09:27:03 [ERR]   * You intended to execute a .NET program, but dotnet-ef does not exist.
09:27:03 [ERR]   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

This is expected as I haven't added `dotnet-ef` to the project.

So I now run

```
nuke :add-package dotnet-ef
```

But running `nuke EF` throws the same exception

### Expected Behavior

I would expect that all that was required to use `EntityFrameworkTasks`  would be to install the  `dotnet-ef` nuget package via `nuke :add-package dotnet-ef`

### Actual Behavior

The actual behaviour is that you are required to install `dotnet-ef` as a dotnet tool via 

```
dotnet new tool-manifest
dotnet tool install dotnet-ef
```

### Known Workarounds

The issue stems from the tool using `dotnet.exe` as the tool executable rather than `dotnet-ef.exe`.

We could resolve `dotnet-ef` using 

```csharp
var dotnetEF = NuGetToolPathResolver.GetPackageExecutable(
    packageId: "dotnet-ef",
    packageExecutable: "dotnet-ef.exe");
```

But we would then have to change the tasks to not prefix the commands with `ef`. For example `ef database drop` would need to change to `database drop`

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Feel free to send a PR.

**Comment by michael-wolfenden** [comment]
@matkoch This would be a breaking change to anyone who had not installed `dotnet-ef` as a nuget package via `nuke :add-package dotnet-ef`. Are you still happy for the change to go ahead?
