### ISSUE TITLE
Rider plugin is incompatible with  2023.2

### ISSUE THREAD

**Issue by jvmlet** [nuke-build/nuke#1217]
### Usage Information

Rider 2023.2

### Description

Rider plugin is incompatible with  2023.2

### Reproduction Steps

Install rider plugin is incompatible with  2023.2

### Expected Behavior

Rider plugin to be compatible with  2023.2

### Actual Behavior

Rider plugin is incompatible with  2023.2

### Regression?

Rider plugin is compatible with  2023.1

### Could you help with a pull-request?

No

**Comment by chrisb92** [comment]
Is there any way we can help contribute to update the plugin? I tried hunting for the source code in the repo but I can't seem to find it. I'm assuming it's in a different repo to this?

**Comment by wtorricos** [comment]
I can also take a look, but like @chrisb92 I couldn't find the code for the plugin.

**Comment by mwasowski** [comment]
What worries me also is that the plugin is not available on any of the plugin Marketplaces (JetBrains or VisualStudio) 🤔

**Comment by hdocsek** [comment]
I use the plugin exclusively to launch debug sessions.
Until @matkoch gets around to bring the functionality back I figured the most pragmatic approach for me is to trigger `Debugger.Launch()` with a command line argument.

Might not be very elegant but does the job. 

```
public partial class Build : NukeBuild
{
    public static int Main(string[] args)
    {
        if (args.Any(a => a.Equals("--debug", StringComparison.OrdinalIgnoreCase)))
        {
            Debugger.Launch();
        }
        return Execute<Build>(x => x.Compile);
    }
    
    //...
}
```

Then I simply start your NUKE build from the command line like this
```
build.cmd [Target] --debug
```
I hope this helps others who are stuck with this.

**Comment by jvmlet** [comment]
> the most pragmatic approach for me is to trigger Debugger.Launch() with a command line argument.

What is wrong with just having `Debug` of `.Net Project` with exe path to `Build.exe` + `Program arguments` ?

![image](https://github.com/nuke-build/nuke/assets/6664858/a1b5b24b-8a34-45a0-b877-221d19630d08)

**Comment by hdocsek** [comment]
> What is wrong with just having `Debug` of `.Net Project` with exe path to `Build.exe`

Nothing wrong with it. It just happens that I have a lot of targets and I looked for a way to start any target in debug mode without having to edit the configuration. If I had just a couple of targets I would probably add a config for each and go with your approach instead.

**Comment by jvmlet** [comment]
@hdocsek , but hen you have to type `build.cmd [Target] --debug` every  time... instead  of having it defined once .
I also have lots of target + parameters .... Easier to have them defined  once , plus you can share them with your teams members

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/issues/1262
