### ISSUE TITLE
What happened to all the IDE extensions?

### ISSUE THREAD

**Issue by makp0** [nuke-build/nuke#1223]
### Usage Information

7.0

### Description

They're marked as unavailable on nuke.build as well as 404ing in marketplaces.
![CleanShot 2023-08-13 at 19 07 32](https://github.com/nuke-build/nuke/assets/22623598/52a2abcb-5779-4591-aa11-b73126d98681)
![CleanShot 2023-08-13 at 19 07 50](https://github.com/nuke-build/nuke/assets/22623598/9b1a6403-837f-42c3-bd63-b46795deb90d)

It sets a dangerous precedent for this package, as all the extensions are closed source. 

### Reproduction Steps

try to install an extension

### Expected Behavior

extension must be available

### Actual Behavior

They're marked as unavailable on nuke.build as well as 404ing in marketplaces.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
#1217

**Comment by makp0** [comment]
It's related, but not an answer.
 
Indeed, I've installed Rider 2023.2 and it is incompatible. 
It happens sometimes and normally I just downgrade and keep working, waiting for an update to a plugin.
BUT the Nuke Support plugin is missing from all marketplaces. I cannot install any version of it.

All my NUKE Rider build configurations have turned into pumpkins!

**Comment by makp0** [comment]
@matkoch, please, host a .jar binary of the latest plugin version and share a link

**Comment by matkoch** [comment]
There will be an update in the other issue once I get to it. For now, I'll be removing the links from the docs.
