### ISSUE TITLE
Changing Nuke.Common.ProjectModel.Solution.GetProject to include projects nested within solution folders

### ISSUE THREAD

**Issue by DanielFruerlund** [nuke-build/nuke#1224]
### Description

Nuke.Common.ProjectModel.Solution.GetProject(string name) in Nuke.Common version 7.0.2 looks only for projects that are direct descendants of the solution, thereby excluding projects nested within solution folders. [Link to source](https://github.com/nuke-build/nuke/blob/bbceff250ec4c9c604b33b38600ab9b4a4e17dac/source/Nuke.SolutionModel/Solution.cs#L102C43-L102C43) 

I would like to suggest changing this method to include projects nested within solution folders as well for a more expected behaviour.

As a side note, GetProject already went through a breaking change as it used to include all projects within a solution in earlier versions of Nuke.Common (6.3.0).

### Usage Example

`Project Project => Solution.GetProject("ProjectName");`

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/blob/bbceff250ec4c9c604b33b38600ab9b4a4e17dac/source/Nuke.SolutionModel/Solution.cs#L110-L117
