### ISSUE TITLE
Delayed parameter injection in 7.0.1 breaks existing extensions

### ISSUE THREAD

**Issue by tyb-dev** [nuke-build/nuke#1225]
### Usage Information

7.0.1

### Usage Information
7.0.1 / 7 / net7.0 / Windows(linux and mac)

### Description
After upgrading to 7.0.1, we are seeing `NullReferenceException`s with what appears to be the same root cause as [#1177](https://github.com/nuke-build/nuke/issues/1177). In our case, we have an `IOnBuildInitialized` which reads parameters. 

### Reference
[#1177](https://github.com/nuke-build/nuke/issues/1177)

### Reproduction Steps

See [#1177](https://github.com/nuke-build/nuke/issues/1177)

### Expected Behavior

See [#1177](https://github.com/nuke-build/nuke/issues/1177)

### Actual Behavior

See [#1177](https://github.com/nuke-build/nuke/issues/1177)

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Same response as #1177
