### ISSUE TITLE
Visual Studio Nuke Support Extension not found in VS Marketplace

### ISSUE THREAD

**Issue by RobSmyth** [nuke-build/nuke#1236]
### Usage Information

Windows OS

### Description

Today I'm unable to install the Nuke Support Visual Studio extension. It just does not show up in the VS market place and the link from an install on another PC gives a 404 error. Probably a VS Market place issue but to be sure ... has it been pulled?

### Reproduction Steps

1. Open Visual Studio 2022
2. Menu: Extensions | Manage Extensions
3. Select the Online tab on the Manage Extensions dialog
4. In the search type "Nuke"
5. Nothing useful found

1. In a browser go to https://marketplace.visualstudio.com/items?itemName=nuke.visualstudio
2. 404 error

### Expected Behavior

See Nuke extension in VS 2022 extension manager (online)

Be able to see Nuke extension in VS Marketplace.

### Actual Behavior

Not found / 404

### Could you help with a pull-request?

No

**Comment by BusHero** [comment]
The extension for Visual Studio Code is also missing

**Comment by RobSmyth** [comment]
I wonder if there is an alternative source for these releases. Currently it seems they are not available.

**Comment by laurentkempe** [comment]
The same for Rider. It seems that all of those IDE plugins have been removed on purpose. I read, as far I remember on nuke slack, that the plan is to provide a new set of plugins with enterprise grade support at a cost and free one with lower capabilities. I guess @matkoch could tell us more here.

**Comment by RobSmyth** [comment]
>  I read, as far I remember on nuke slack, that the plan is to provide a new set of plugins with enterprise grade support at a cost

OMG, we will see ...

One thing to go commercial, another thing to try to remove what was already publicly released. If that is the case then it is question ethics ... should somebody else make the publicly released versions available?

But it is just speculation fueled by lack of response right now.

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/issues/1262

**Comment by RobSmyth** [comment]
@matkoch - I'm not sure what issue #1262 is about. This issue is about extensions that were on the VS market place no longer being there. Have they been removed deliberately? Will they be restored?

**Comment by RobSmyth** [comment]
What I'm seeing today is this: 
![image](https://github.com/nuke-build/nuke/assets/6183736/086a5bd7-1e59-48ea-a9a0-2ddbdb1f697a)

**Comment by matkoch** [comment]
Sorry, I thought it would be obvious when I closed this issue and linked to another. Yes, the new issue is the umbrella issue for all recent (similar) issues about IDE extensions.

**Comment by RobSmyth** [comment]
@matkoch - could you give an idea of why/how public releases have been removed from the Visual Marketplace?

Do we expect all to be restored?

**Comment by matkoch** [comment]
yea, I will do that [here](https://github.com/nuke-build/nuke/issues/1262) once I get to it
