### ISSUE TITLE
Cannot build dotnet 8 preview 7 apps on linux

### ISSUE THREAD

**Issue by rogerbriggen-securiton** [nuke-build/nuke#1238]
### Usage Information

7.0.3 / 8.0.100-preview.7.23376.3 / .Net 8 / Ubuntu Yammy

### Description

I use the microsoft .Net 8 Preview 7 SDK Docker Image where I build my Maui app. If I use the command line like dotnet build everything works fine.
If I use nuke, I get 
Compile
11:33:12     Target "Compile" has thrown an exception
11:33:12     [ERR] Target Compile has thrown an exception
11:33:12     System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
11:33:12     
11:33:12     File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
11:33:12        at Nuke.Common.ProjectModel.ProjectExtensions.GetProperty(Project project, String propertyName)
11:33:12        at Nuke.Common.ProjectModel.ProjectExtensions.GetProperty[T](Project project, String propertyName) in /_/source/Nuke.ProjectModel/Project.Properties.cs:line 32
11:33:12        at Build.GenerateVersionInfos(String& versionSuffix) in /data/build/ef497e914ee5fdcb/Edelweiss.GO.Build/Build.cs:line 924
11:33:12        at Build.<get_Compile>b__93_1() in /data/build/ef497e914ee5fdcb/Edelweiss.GO.Build/Build.cs:line 246
11:33:12        at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
11:33:12        at System.Collections.Generic.List`1.ForEach(Action`1 action)
11:33:12        at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119

For nuke there is Microsoft.NETCore.App 7.0.10 runtime (Beside Microsoft.NETCore.App 8.0.0-preview.7.23375.6 which is already there from Microsoft)

### Reproduction Steps

Get mcr.microsoft.com/dotnet/nightly/sdk:ARG TAG=8.0.100-preview.7-jammy and install dotnet 7 runtime for nuke
Use nuke to build a dotnet 8 application

### Expected Behavior

The application builds without errors

### Actual Behavior

Nuke crashes with an System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
11:33:12   

### Regression?

-

### Known Workarounds
Not a workaround but the same app builds fine on Windows with Nuke with .Net 8 Preview 7 (without docker)

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Not planning to check against preview releases, but feel free to investigate.
