### ISSUE TITLE
Divide and conquer repositories/packages

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#125]
### Proposal:
The new structure could look like this:

- nuke-build
  - core (formerly nuke)
    - Nuke.CodeGeneration
    - Nuke.Utilities
    - Nuke.MSBuildTasks
    - Nuke.MSBuildLocator
    - Nuke.GlobalTool
    - Nuke.Core (formerly Nuke.Common)

For each tool/use-case, there will be a separate repository with NuGet package. For instance for:

- nuke-build
  - msbuild (Nuke.MSBuild)
  - dotnet (Nuke.DotNet)
  - io (Nuke.IO)
  - compression (Nuke.Compression)
  - xunit (Nuke.Xunit)

### Benefits:
- Independent development of tasks with own release-notes
- Consistency. Currently, some tasks are in separate packages, while others are integrated
- Package dependencies for `xunit.runners.console` and similar (overwrite should be possible; make sure it's deterministic)

### Considerations:
- Manual vs. automatic task generation
- Update of README.md
- External files for reuse
- Rebuild on dependency updates (nuke or tool)
- Enable or disable issues?

### Drawbacks:
- Submitting PRs - mostly new tools - becomes certainly harder. Solvable via master repository?
- Legacy packages.config should be discontinued in this case

**Comment by ElijahReva** [comment]
Maybe also pack but not separate Nuget.Common.Testing in this case, so all child packages could share test abstractions too.

**Comment by matkoch** [comment]
I currently can't think of any common test infrastructure that could be shared :/ but as soon as the opportunity is given, sure!

**Comment by kysel** [comment]
I think it would be good to take inspiration from aspnetcore. So one master repository with many projects, one NuGet package per one project, and then one metapackage which contains everything.

**Comment by matkoch** [comment]
@kysel That's very difficult, because we're using GitVersion for semantic version generation. Changelog is another thing when releasing independently. Also, I like that multiple repositories can easier be managed in regards to contributors/owners.

It's a tricky question though. I'm also not 100% a fan of multiple repositories, but I guess it's the best way.

**Comment by kysel** [comment]
I am not talking about releasing projects/NuGets independently. Aspnetcore releases everything at once, so no problem with changelog, versioning etc. I think that managing dozen of repositories is more time consuming than creating bing one from which all NuGets are released. Contributions can be managed with labels which are, I think, better than separating issues over dozen of repositories.  It all depends on the required granularity, my idea was to split all tasks depending on the existing library to their respective NuGet package. This applies only to the future equivalent of `Nuke.Common`.

Contributions, let say _bigger_ tasks managed by the community should be in their own repositories for sure.

**Comment by matkoch** [comment]
Just a few unordered thoughts:

### Issues

Single-repo would be better. But for multi-repo, issues could be disabled for all repositories but the umbrella repo (nuke-build/nuke).

### Release Cycle

Releasing everything at once just feels strange. We already do this to a certain level with the packages Nuke.Common, Nuke.CodeGeneration, Nuke.GlobalTool and Nuke.MSBuildLocator. The latter package hasn't changed for ages, yet we publish it over and over again. 

### Changelog

Single-repo could either have a single changelog or multiple nested in folders. I don't like any of these two approaches. Single-changelog makes it hard to track changes specific to an addon. Multi-changelog is weird. Never saw this in practice. Multi-repo seems better to me. Single changelog at the root level.

### Third party addons

For single-repo  approach, they would become something _special_ - in a negative way. Multi-repo would render them to be just like any other package. Plus, they're easier to maintain under the nuke-build org.

**Comment by matkoch** [comment]
What is the reason to not split everything?

**Comment by matkoch** [comment]
Whatever the solution is, it should address the following aspects:

- Changelog management (Updating core should not _always_ require updating addons)
- Tagging/Versioning (Continuous semantic version numbers)
- Code owners (third party addon repositories)
- Issue creation (should not be too distributed)
- Release cycle management (addons must be able to be released independently)
- Cross-solution refactorings (changes in core packages should easily propagate to addons)
