### ISSUE TITLE
MSBuildTasks MaxCpuCount doesnt work as it supposed to when null is passed

### ISSUE THREAD

**Issue by JinsPeter** [nuke-build/nuke#1252]
### Usage Information

Any

### Description

MS Build accept a parameter  /maxcpucount which defaults to 1. This also has a feature to use all the CPUs of the running computer if the parameter is specified, but count is not specified 

I have tries to alter the 

### Reproduction Steps

Use the Built in MsBuildTasks and configure MaxCpuCount as null 
 
 ```
 MSBuildTasks.MSBuild(
     c => c.SetProjectFile(Solution)
           .SetMaxCpuCount(null));
           
```          

### Expected Behavior

The MsBuild command generated should have ` /maxcpucount` without a value appended,

Also, the MSBuildSettings.ResetMaxCpuCount() is supposed to set the value to 1 and not null.
Ideally we should have a method that does not accept a value (possibly a method with default parameter).

### Actual Behavior

The MsBuild command generated does not have ` /maxcpucount` making MsBuild to fallback the  default of 1.

### Regression?

I dont expect this to work with previous builds/releases

### Known Workarounds

Permananently hardcode a high value to use the MaxCpuCount

 ```
 MSBuildTasks.MSBuild(
     c => c.SetProjectFile(Solution)
           .SetMaxCpuCount(100));
           
```          

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
`Environment.ProcessorCount`
