### ISSUE TITLE
Add `dotnet workload` tools

### ISSUE THREAD

**Issue by ITaluone** [nuke-build/nuke#1253]
### Description

Add new tools so you can restore dotnet workloads.
As I am building and publishing a dotnet maui app with NUKE I have to update my dotnet maui workloads twice: First on my dev device and second on my build server.

This doesn't feel comfortable at all.

So I propose to add the tools for `dotnet workload` which are:
- dotnet workload install [workload_id]
- dotnet workload update
- dotnet workload restore [project | solution]
- ... (a few more which are not really useful for the build pipeline, like `list`, `search`, `uninstall`...)

### Usage Example

Same as the "normal" nuget restore:

```csharp
Target WorkloadRestore => _ => _
        .Executes(() =>
        {
            DotNetWorkloadRestore(s => s
                .SetProjectFile(Solution));
        });
```

### Alternative

Running `dotnet workload update` manually local and on the build machine.

### Could you help with a pull-request?

No

**Comment by candoumbe** [comment]
@ITaluone 
You could always resort to `DotNet("workload ....")` to run the commands you need to run.

I asked a related question on slack to add support for [Stryker](https://stryker-mutator.io/docs/stryker-net/) but got no answer so far.

**Comment by matkoch** [comment]
Feel free to send a [pull-request](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#before-creating-an-issue).

**Comment by matkoch** [comment]
@candoumbe csharp is generated from `json` files via the `GenerateTools` target.

**Comment by ITaluone** [comment]
#1255
