### ISSUE TITLE
Adding Wix4 installer

### ISSUE THREAD

**Issue by Simusharp** [nuke-build/nuke#1257]
### Description

Wix installer has been proposed multiple time (e.g. see #475). However, it didn't move forward since wix3 included multiple exe files in the package. This changes in wix4 which has one exe only (see https://wixtoolset.org/docs/tools/wixexe/). Therefore, I would like to revive this tool again.

### Could you help with a pull-request?

Yes

**Comment by nix63** [comment]
Maybe you can take a look at [wixsharp](https://github.com/oleg-shilo/wixsharp). 
Like Nuke, you can easily create a wix installer using c# instead of xml, then you can use dotnet build or run to create your installer.

**Comment by matkoch** [comment]
Feel free to create a pull-request. I will close the issue as per [contribution guidelines](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-an-issue). For more information, see the part about [when creating a pull-request](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-a-pull-request).
