### ISSUE TITLE
ArgumentStringHandler adds double quotes to an interpolated string using implicit conversion

### ISSUE THREAD

**Issue by avidenic** [nuke-build/nuke#1260]
### Usage Information

Nuke common: 7.0.2 / SDK version 7.0.400 / target net7.0 / OS windows 11

### Description

When passing an interpolated string to a CLI task that accepts CLI arguments using implicit conversion to `ArgumentStringHandler` , there are extra double quotes. 

### Reproduction Steps

```csharp
class Build : NukeBuild
{
    public static int Main() => Execute<Build>(x => x.ArgumentDemo);

    string Foo => "foo";
    string Bar => "bar";
    string Configuration => "config";

    string CommonParameters => $"-p {Foo} -s {Bar} -c {Configuration}";

    string SomeOtherParameter => "Parameter";

    Target ArgumentDemo => c => c
        .Executes(() =>
        {
            ArgumentStringHandlerDemo($"cli execution with parameters {SomeOtherParameter} {CommonParameters}");
        });

    private void ArgumentStringHandlerDemo(ArgumentStringHandler arguments)
    {
        Log.Information(arguments.ToStringAndClear());
    }
}
```

### Expected Behavior

Should produce `cli execution Parameter -p foo -s bar --configuration config`

### Actual Behavior

Produces `cli execution Parameter "-p foo -s bar --configuration config"`

### Known Workarounds

Do not pass interpolated string directly 

```csharp
ArgumentStringHandlerDemo($"cli execution with parameters {SomeOtherParameter} {CommonParameters}");
```

but instead assign it to a variable before:
```csharp
            var cliCommand = $"cli execution with parameters {SomeOtherParameter} {CommonParameters}";
            ArgumentStringHandlerDemo(cliCommand);
```

### Could you help with a pull-request?

Yes

**Comment by avidenic** [comment]
Sorry, I've seen this is fixed in 7.0.5

**Comment by Simonl9l** [comment]
Hi @matkoch - please advise on what the intended usage for this kind of command setup - without using interpolation?

In the use case of a custom tool `[PathVariable("my tool")] readily Tool MyTool` with a `MyTool.Invoke(cmd)` We see in the Tool code implementation there in an implicit `string` cast of the `arguments` to a `ArgumentStringHandler`; but this behavior does not seem to be documented. 

This seem to do more processing that has side effects, where we suspect it uses a code-generated implementation via the `[[InterpolatedStringHandler]` attribute that is opaque, like adding the extra quotes. 

It would be good for those using Nuke to be able to understand this better...?

Our solution we to entirely build the command, with any interpolations, outside/before of the `Tool.Invoke`, and pass that in. 

The implicit cast is not obvious unless ones IDE highlights them! This means folks get lost in thinking it is an error in their interpolation etc. than what is happening under the covers. 

The implicit frictions issues such as this cause, may have folks consider alternative build solutions.

**Comment by fvaillancourt** [comment]
Hi @matkoch, this might not be the same exact usage as above but I think this is a legitimate one that suffers from the bug.
`Git("commit -m \"Some commit message\"");`
I would expect this to work but it fails because it actually runs this, including the backslashes around message quotes
`"C:\Program Files\Git\cmd\git.exe" commit -m \"Some commit message\"`

**Comment by jboysen** [comment]
Hi @matkoch ,
We also experience problems with this new implementation, and it caused too many headaches to understand why our builds did not any longer succeed after upgrading Nuke.

We have this use case:
```csharp
var tag = "--tag \"always\"";
Npm($"start -- --dir ../spa --headless --key REDACTED --url {url} {tag}", e2eDir);
```

This gives this output:
`"C:\Program Files\nodejs\npm.cmd" start -- --dir ../spa --headless --key REDACTED --url REDACTED "--tag \"@always\""`
(notice the quotes around "--tag ..."

One would think we could then change (based on this issue):
```csharp
var tag = "--tag \"always\"";
var puppeteer = $"start -- --dir ../spa --headless --key REDACTED --url {url} {tag}";
Npm(puppeteer, e2eDir);
```

But this gives: `"C:\Program Files\nodejs\npm.cmd" start -- --dir ../spa --headless --key REDACTED --url REDACTED --tag \"@always\"`

Which is still not the expected: `"C:\Program Files\nodejs\npm.cmd" start -- --dir ../spa --headless --key REDACTED --url REDACTED  --tag "@always"`

How can we get it to not write out the back-slashes around the quotes of `@always`? The first snippet worked perfectly before the update of Nuke.

Edit: I just learned about the $@"... {tag:nq}" feature which solved it. Nevertheless, we still spent too much time on this issue :)

**Comment by bretthysuik** [comment]
@fvaillancourt did you find a workaround? I've got the exact same problem.

**Comment by fvaillancourt** [comment]
@bretthysuik Yes and no ... It was for commit messages so our commit message look_like_this_now_so_no_spaces

**Comment by bretthysuik** [comment]
@fvaillancourt after looking closer at @jboysen's comment, I got it working (the `nq` string format is the magic to get it working):

```c#
string commitCommand = "commit --message \"Some commit message\"";
Git($"{commitCommand:nq}");
```
