### ISSUE TITLE
IDE Extensions

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#1262]
WIP

**Comment by RobSmyth** [comment]
Hi, do you have any idea how or why the public releases are no longer available on VS Marketplace? Deliberately removed?

**Comment by matkoch** [comment]
@RobSmyth, can I ask you to be a little more patient? Please?

**Comment by RobSmyth** [comment]
OK, but understand that I'm not asking "when" but wanting to understand the "why" as that impacts decisions.

No bug to report, wanting to understand if a decision has been made to make them retrospectively unavailable.

**Comment by matkoch** [comment]
Yes, you've made that very clear in a number of posts. Still I'm gonna say: WIP.

**Comment by jvmlet** [comment]
@RobSmyth , meanwhile, you can implement it as composite debug profile in Rider. Have a look at build script and you will get the idea `how`

**Comment by jvmlet** [comment]
@RobSmyth, about the impact on decisions... IDE plugin should not be the deal breaker. I can't imagine doing CI/CD without Nuke, I would force the whole team to transition to java/Gradle rather than dealing with msbuild targets/vendor specific yaml files , ect.

**Comment by RobSmyth** [comment]
Hi @jvmlet, yea the IDE plugin is not a deal breaker but publishing of public apps with free distribution and changing the deal by removing them all (feels like they are being hidden) from download would be unethical. Of course, I have not got an answer yet but if that proves to be the case it would be deal breaker. It seems that the question of if deliberately removed, or why removed, is being avoided. That is seeding mistrust.

The apps have been distributed as free public distributions. Teams are adopting those tools and they are being used. But, suddenly they are no longer downloadable from a free hosting site. So there is a scramble for those who have not installed and/or setting a new box ... who has an installer? What happened?

Open source projects do go commercial. That is good and I welcome it. If there is something like that in plan this is very different ... what has been publicly released is being hidden without notice. It feels like betrayal and would be unethical. Not a great start to going commercial (if the case).

If so ... that is a deal breaker . Best to fork and move on.

If it is a support issue then it would be understandable to mention on the download page that the tool has proved to be buggy and without further community support is cannot be supported ... download without support.

**Comment by RobSmyth** [comment]
Perhaps just cut the loss and let us know why they have been removed.

**Comment by frosch95** [comment]
@RobSmyth as far as I remember, the IDE extension are not open source but a free gift. The open source part is Nuke, this repo. If the developer decides to remove the free gift, I think it is totally fine and has nothing to do with ethics.
I am thankful if the extensions return (doesn't matter if free or not) and if the extensions do not return fine.
Maybe someone else write extensions for one of the IDEs. I don't think it is forbidden to do so.

**Comment by jvmlet** [comment]
@RobSmyth , yeah, I see your point. Lets wait till WIP completes and get the official resolution details. 
At your place I would employ nuke till the official announcement and then decide, the learning curve and investment are minimal comparing with what you get and the beauty of the build graph.

**Comment by reijerh** [comment]
I feel words like 'unethical' and 'betrayal' might be a bit much mate. You're getting something for free without any guarantees or obligations.

It may often feel like a bait and switch, but honestly, OSS consumers may have become a little too accustomed to maintainers sacrificing their health for what has often become an obsessive hobby. Licenses like Apache, MIT, LGPL etc. kind of play into this.

"When invited to a free lunch, don't complain about the quality of the caviar."

**Comment by Matoyak** [comment]
May I suggest modifying the Docs to state whatever the current status of the IDE Extensions are? I just got handed a project to convert a complex Cake build chain into Nuke, and spent a while chasing my tail on the VS and VSC extensions. There are extensions out there that are not from the Nuke team that are named almost as if they are. Some clarity on the Doc pages would probably be a good idea. It sounds like they have been made private? If that's the case, the docs should be updated to say that things are changing, or temporarily down, or something.

**Comment by matkoch** [comment]
@Matoyak done

**Comment by yankun** [comment]
Anything new on this? I'm really missing the IDE integration.

**Comment by RogerDerekWeiss** [comment]
> Anything new on this? I'm really missing the IDE integration.

Yes please, as much as I appreciate that this is an opensource project powered by the good will of amazing developers, I feel the IDE integration was one of the strong points for adopting Nuke for rapid development especially when debugging.

**Comment by jvmlet** [comment]
@RogerDerekWeiss , @yankun 
It's easy to setup you build project debug configuration just by creating `.net run`  with `build.exe` passing target and arguments as parameters. `build`  project is marked as `no build`, in   `before  launch`  call `build.ps` with `--help` to compile  the build project before launching it.

**Comment by ihordyrman** [comment]
Additionally to what @jvmlet just said, you can create your launchSettings.json configuration and easily run/debug builds you need. 
It can look like this:
```json
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "profiles": {
    "Format": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "commandLineArgs": "--target Format --skip"
    },
    "Restore": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "commandLineArgs": "--target Restore --skip"
    },
    "Compile": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "commandLineArgs": "--target Compile --skip"
    },
    "IntegrationTests": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "commandLineArgs": "--target IntegrationTests --skip"
    },
    "E2ETests": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "commandLineArgs": "--target E2ETests --skip"
    },
    "OnCommit": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "commandLineArgs": "--target OnCommit"
    },
    "OnPush": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "commandLineArgs": "--target OnPush"
    }
  }
}
```
The skip parameter is optional. Use it when you don't want to wait for other steps to finish.

**Comment by matkoch** [comment]
[There's an update!](https://nuke.build/blog/2024/01/22/update-on-ide-extensions/)

This has taken me much longer than I expected. Maybe that's a good indicator of how critical the bus factor for NUKE actually is. I hope that everyone understands that with these changes I intend to solve this problem and allow the project to grow further. I cannot stress enough how helpful it would be if there were more "sustainability contributions" (especially code ownership) from the community.

**Comment by jvmlet** [comment]
Thanks, @matkoch , but `Debug` option is missing,  the   only  option available is `Run without dependencies` ...
Or is it for professionals only ?
Would be great to have comparison matrix somewhere ...

**Comment by matkoch** [comment]
@jvmlet, only run execution is part of the community edition. I will hopefully have some time to update the docs in the next few days. The Rider plugin already has the list of features in the description. Visual Studio doesn't give great room unfortunately to show this info.

**Comment by jvmlet** [comment]
Thanks, @matkoch , I'll stay with bespoke [solution ](https://github.com/nuke-build/nuke/issues/1262#issuecomment-1895370348) meanwhile then ..., but I gave you my ~~heart~~ star ;-)

**Comment by ITaluone** [comment]
Quote from https://nuke.build/blog/2024/01/22/update-on-ide-extensions/#extension-editions
> We'll also grant access to maintainers and active contributors of other projects to support the open-source community at large

What does the term "active contributors" mean exactly? 
n PRs per week, per month? 
n PRs in total, at m different public OSS repos?

It would be cool if this could be clarified :)

Thx

**Comment by matkoch** [comment]
That's an individual and case-by-case decision.
