### ISSUE TITLE
Add generatetool as option on nuke global tool

### ISSUE THREAD

**Issue by jhorn70** [nuke-build/nuke#1264]
### Description

Global Tool should be able to generate CLI wrapper from JSON file.  This should accept a single JSON definition file or search a folder structure for JSON files to build tools like the current GenerateTools target does.  This would be useful as it would remove the dependency for a user of Nuke to have to push a tool wrapper into the main source and build it using the target.  Currently it looks like the best way to accomplish this might be then copying the generated CS file into whichever build you need it in until it is included in the main source. 

### Usage Example

User may have a particular CLI tool which may not make sense to be a CLI tool supported in the main distribution of Nuke.  Users could create a JSON as part of the current build they are working on, use the global tool to generate the wrapper and be able to directly use the wrapper in their build.  

### Alternative

Copying generated file

### Could you help with a pull-request?

Yes

**Comment by jhorn70** [comment]
This is a pretty simple implementation.  I have it intially working with the following:

nuke ::generate-tools --directory <directory> or --file <file>

If directory is set it will scan the directory and all sub-directories.  If file it will only look at the file set.  One of them has to be set, but both cannot.

I could probably add the ability to declare the namespace prefix at a minimum.

**Comment by matkoch** [comment]
The `NukeSpecificationFiles` item group already does this during build project compilation.

See here: https://github.com/nuke-build/nuke/blob/develop/source/Nuke.MSBuildTasks/Nuke.MSBuildTasks.targets#L49-L56

**Comment by jhorn70** [comment]
> The `NukeSpecificationFiles` item group already does this during build project compilation.
> 
> See here: https://github.com/nuke-build/nuke/blob/develop/source/Nuke.MSBuildTasks/Nuke.MSBuildTasks.targets#L49-L56

Matt, any information on usage would be extremely helpful.

**Comment by PaulKlein** [comment]
FYI for anyone coming across this, I got it going by simply adding the following to my .csproj, pointing to my folder containing my definition JSON files:

```xml
    <ItemGroup>
        <NukeSpecificationFiles Include="ToolDefinitions/*.json" />
    </ItemGroup>
```
