### ISSUE TITLE
[Documentation]Build components documentation web broken

### ISSUE THREAD

**Issue by Rabosa616** [nuke-build/nuke#1265]
### Usage Information

Nuke.build website

### Description

When visiting the Build components documentation at:
https://nuke.build/docs/sharing/build-components/

It appears to be broken:
![image](https://github.com/nuke-build/nuke/assets/12774781/8322862e-f0ce-4264-b86c-919892f6bf97)

### Reproduction Steps

1. Navigate to https://nuke.build/docs/sharing/build-components/
2. The following image appears : ![image](https://github.com/nuke-build/nuke/assets/12774781/8322862e-f0ce-4264-b86c-919892f6bf97)

### Expected Behavior

Show the right website

### Actual Behavior

![image](https://github.com/nuke-build/nuke/assets/12774781/8322862e-f0ce-4264-b86c-919892f6bf97)

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
thanks for the report
