### ISSUE TITLE
DotNetVerbosity is case-sensitive - Nuke uses wrong case

### ISSUE THREAD

**Issue by Flaeng** [nuke-build/nuke#1266]
### Usage Information

Nuke 7.0.5 / Dotnet 7.0.102

### Description

Error when setting DotNetFormat.SetVerbosity

### Reproduction Steps

Create a class libary ("dotnet new classlib --name demo")
Setup nuke ("nuke :setup") using default options
Change Target Compile to
```Csharp
Target Compile => _ => _
        .DependsOn(Restore)
        .Executes(() =>
        {
            DotNetTasks.DotNetFormat(opts => opts
                .SetVerbosity(DotNetVerbosity.Diagnostic)
                .SetProject(RootDirectory / "demo")
            );
        });
```
Run "nuke"

### Expected Behavior

That it runs 
"format C:\repos\nuke-error\demo --verbosity diagnostic"
but it runs
"format C:\repos\nuke-error\demo --verbosity Diagnostic" (with uppercase)
dotnet does not accept this

### Actual Behavior

```
[ERR] Compile: Argument 'Diagnostic' not recognized. Must be one of:
[ERR] Compile:  'q'
[ERR] Compile:  'quiet'
[ERR] Compile:  'm'
[ERR] Compile:  'minimal'
[ERR] Compile:  'n'
[ERR] Compile:  'normal'
[ERR] Compile:  'd'
[ERR] Compile:  'detailed'
[ERR] Compile:  'diag'
[ERR] Compile:  'diagnostic'
[ERR] Compile: Target Compile has thrown an exception
```

### Known Workarounds

Write the parameter as a string and let nuke cast it to DotNetVerbosity
like so:
```
Target Compile => _ => _
        .DependsOn(Restore)
        .Executes(() =>
        {
            DotNetTasks.DotNetFormat(opts => opts
                .SetVerbosity("diagnostic")
                .SetProject(RootDirectory / "demo")
            );
        });
```

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Please have a look at our [CONTRIBUTING.md](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md), particularly the part about [when creating an issue](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-an-issue).
