### ISSUE TITLE
EnsureCleanDirectory fails its Assert because directory is deleted asynchronously

### ISSUE THREAD

**Issue by robertcoltheart** [nuke-build/nuke#127]
As I understand, `Directory.Delete` calls winapi `RemoveDirectory` which only marks the directory as deleted. Because `EnsureCleanDirectory` is asserting the removal of the directory directly after the actual deletion, there is a slight chance it will fail, even though the directory was actually removed. 

This is an issue I have hit multiple times in my builds.

**Comment by arodus** [comment]
Also had the problem several times but wasn't unable to locate the problem.
In that case we probably just should trust `Directory.Delete` and remove the assertion, or is there any case where the call can fail without an exception? @matkoch
