### ISSUE TITLE
`npm notice` logged as error when using NpmTasks

### ISSUE THREAD

**Issue by Danielku15** [nuke-build/nuke#1275]
### Usage Information

7.0.5

### Description

NPM like some other tools like to use stderr for certain no-error outputs and the `NpmTasks` already handle the [`npmWarn` and `npm WARN`](https://github.com/nuke-build/nuke/blob/dfa68bb28533e354ab16e951c44f8895716b9bf6/source/Nuke.Common/Tools/Npm/NpmTasks.cs#L21) prefixes. 

But Nuke misses to handle the `npm notice` prefix which should then be logged as normal information message.  

### Reproduction Steps

Setup a build where an NPM `pack` is called. `NpmTasks.Npm("pack", "path/to/package")`

### Expected Behavior

Any NPM stderr outputs prefixed with `npm notice` are logged by Nuke as `Log.Debug` message like stdout outputs.

### Actual Behavior

`npm notice` outputs are written via `Log.Error` causing it in build systems (like GitHub Actions) to be picked up as error leading to many incorrect error annotations (or potentially failed builds if the stderr is checked). 

![image](https://github.com/nuke-build/nuke/assets/674916/b7380ec0-3a54-47d9-bdd7-55bf9dbd8e42)
![image](https://github.com/nuke-build/nuke/assets/674916/2324ce12-f060-48df-9484-cdcc3f40e9dd)

### Regression?

No, this likely never worked. This issue could also be seen as an improvement rather than a bug. 

### Known Workarounds

Provide a custom logger to the the invocations. 

### Could you help with a pull-request?

Yes

**Comment by ITaluone** [comment]
Something like this: https://github.com/nuke-build/nuke/discussions/1017?

**Comment by Danielku15** [comment]
More like a very simple extension like this added to [here](
https://github.com/nuke-build/nuke/blob/dfa68bb28533e354ab16e951c44f8895716b9bf6/source/Nuke.Common/Tools/Npm/NpmTasks.cs#L19): 

```diff
            case OutputType.Err:
            {
                if (output.StartsWith("npmWARN") || output.StartsWith("npm WARN"))
                    Log.Warning(output);
+               else if(output.StartsWith("npm notice"))
+                   Log.Debug(output);
                else
                    Log.Error(output);

                break;
            }

```

**Comment by ITaluone** [comment]
What I've meant was something like this:

```csharp
NpmTasks.NpmLogger = (type, text) => Log.Debug(text);
```

**Comment by Danielku15** [comment]
This would not deliver the desired result. Warnings and errors should still be treated correctly unless they are prefixed. Hence my request is an extension to the existing default logger to handle the missing scenario.

**Comment by matkoch** [comment]
@Danielku15 feel free to send a PR
