### ISSUE TITLE
DotNetBuild reports each warning multiple times on Azure Pipelines

### ISSUE THREAD

**Issue by p-m-j** [nuke-build/nuke#1276]
### Usage Information

7.0.6 

### Description

Whilst running on Azure pipelines a logging command `##vso[task.logissue type=warning]` is output twice for each warning encountered during the build.

### Reproduction Steps

https://github.com/p-m-j/nuke-build-az-pipelines-duplicate-warnings

### Expected Behavior

Single task.log command per warning

### Actual Behavior

Multiple task.log command per warning

### Known Workarounds

Hack `-consoleLoggerParameters:NoSummary` into arguments

### Could you help with a pull-request?

Maybe

**Comment by matkoch** [comment]
Works as intended

**Comment by p-m-j** [comment]
I guess the capturing and reporting of warnings works as intended but it is frustrating to see double the warnings reported in the UI.

![image](https://github.com/nuke-build/nuke/assets/2056399/9fc48257-1886-4c8b-9452-26bbb46769ef)

~It would be far less frustrating if `DotNetBuildSettings` accepted more msbuild arguments to match the `dotnet build` command, then `-clp` could be passed down to msbuild without hacks.~

Edit: Workaround isn't too bad.

```csharp
            DotNetBuild(_ => _
                ...
              .SetProcessArgumentConfigurator(args => args.Add("-clp:NoSummary")));
```
