### ISSUE TITLE
Could not find 'git' when trying to update

### ISSUE THREAD

**Issue by pschimmel** [nuke-build/nuke#1277]
### Usage Information

7.0.2 (Windows,.NETCoreApp,Version=v6.0) / Win 10

### Description

I tried to execute an update by using
nuke :update command.

I got the following message while executing Update build scripts: 
Could not find 'git' via 'C:\Windows\System32\where.exe'.

### Reproduction Steps

Install 7.0.2, Try to update

### Expected Behavior

Update the build script to latest version

### Actual Behavior

Error message

### Regression?

Unknown

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Error message tells you exactly what's missing. Not a bug.
