### ISSUE TITLE
Getting Started page: broken link

### ISSUE THREAD

**Issue by ElijahReva** [nuke-build/nuke#128]
Hello!

https://nuke.build/getting-started.html

When I'm using next command, I'm getting error `404: Not Found`
```
powershell -Command iwr https://nuke.build/powershell -OutFile setup.ps1`
```

Edit:
Also  doesn't work
```
Install the global tool via dotnet tool install -g Nuke.GlobalTool
Invoke nuke :setup in a project of your choice
```

**Comment by matkoch** [comment]
We deprecated support for the PowerShell and Bash scripts in favor of the global tool. Documentation update will happen as soon as possible.

For the global tool, invoke “dotnet tool install -g Nuke.GlobalTool”

Sorry for the trouble :)

**Comment by ElijahReva** [comment]
Sorry, I just forget to update nuke before usage.
Next cmd helped
`dotnet tool update -g Nuke.GlobalTool`
