### ISSUE TITLE
Broken Link referencing GithubActions in Readme

### ISSUE THREAD

**Issue by OrgesKreka** [nuke-build/nuke#1284]
### Usage Information

-

### Description

The link that references the github action yaml  in the Readme looks like it is old and is broken: [https://github.com/nuke-build/nuke/blob/develop/.github/workflows/continuous.yml](url)

### Reproduction Steps

Go to Readme

### Expected Behavior

It should reference you to:
[https://github.com/nuke-build/nuke/blob/develop/.github/workflows/ubuntu-latest.yml](url)
or in the root:
[https://github.com/nuke-build/nuke/blob/develop/.github/workflows/](url)

### Actual Behavior

It refers to a broken link.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
feel free to send a PR
