### ISSUE TITLE
Locally connect to privet feed

### ISSUE THREAD

**Issue by AmeerMansourWSP** [nuke-build/nuke#1285]
### Usage Information

7.0.6/ 7 and 6 / .net framework 4.8 / windows

### Description

i have privet feed that has nuget packages that i uses. 
i get this error when i locally build my solution 
![image](https://github.com/nuke-build/nuke/assets/146998900/56547256-ce0b-433b-85ae-b81978cffeb8)

I can build it on azure pipelines using this target 
![image](https://github.com/nuke-build/nuke/assets/146998900/2cd1d028-4e81-4ac5-afff-f8ac241ba614)
so how do i authorize it using Pat Key for locally build? when i try to add it, it says that is already exists 

### Reproduction Steps

1-create project and consume any package in a private azure Artifacts feed 
2-create nuke project
3-build the project

### Expected Behavior

compile target to compile all project successfully 

### Actual Behavior

compile target throw unauthorized exception 

### Could you help with a pull-request?

No

**Comment by AmeerMansourWSP** [comment]
@matkoch 
sorry to bother you but do you know a workaround or something i can do to solve that ?

or provide away to access 
https://github.com/microsoft/artifacts-credprovider

i think it will be a solution to my issue

**Comment by pkudrel** [comment]
Try adding the source to your global `nuget.config`
`dotnet nuget add source URL_TO_AZURE_FEED -n FEED_NAME -u NOT_IMPORTANT -p TOKEN_FROM_ADO `

**Comment by AmeerMansourWSP** [comment]
yes i did that 
https://user-images.githubusercontent.com/146998900/280156450-2cd1d028-4e81-4ac5-afff-f8ac241ba614.png
but when running it locally , it will throw exception 
![image](https://github.com/nuke-build/nuke/assets/146998900/e5c5a594-432f-492e-8166-15d8c76c0b93)

and if not add it as it is already there , it will throw exception when trying to compile 
![image](https://github.com/nuke-build/nuke/assets/146998900/e976ba07-f10c-44bd-a4b8-8883c3ce4df7)

and i can not find a way to remove that existing one and then re-add it.

**Comment by pkudrel** [comment]
Remove it from `C:\Users\{USER}\AppData\Roaming\NuGet\nuget.config`
