### ISSUE TITLE
Global tool can't run in home directory of user

### ISSUE THREAD

**Issue by krankenbro** [nuke-build/nuke#1293]
### Usage Information

6.3.0-7.0.6 / Net 6 / Win, ubuntu, macos

### Description

I'd like to start my globaltool in user's home directory, but i'm getting an exception. (There is .nuke dir)
![image](https://github.com/nuke-build/nuke/assets/42555001/c1fef720-4fbd-43d0-bfd3-e811051b552d)
I guess that's because of this line:
https://github.com/nuke-build/nuke/blob/4d1293607c96d72490b2e099f06aa5c2fd98532b/source/Nuke.Build.Shared/Constants.cs#L54
Is it a bug or does this condition have a purpose?

### Reproduction Steps

Run globaltool in $HOME 

### Expected Behavior

it works

### Actual Behavior

This does not work

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
User home contains a general settings directory. So it cannot contain an actual build. Works as designed. Why execute it in home directory tho?

**Comment by krankenbro** [comment]
> User home contains a general settings directory. So it cannot contain an actual build. Works as designed. Why execute it in home directory tho?

I have several targets that doesn't build anything but sending some requests for example. When user starts his console, it is in $HOME and they need to change directory first
