### ISSUE TITLE
Update DocFx

### ISSUE THREAD

**Issue by DWIAltonaAnalytics** [nuke-build/nuke#1297]
### Description

currently the build in DocFx uses the nuget package `docfx_console` which is very outdated.

For example it seems to ignore some features within the config file and creates no output to the folder set in that file.

### Usage Example

Usage would be as before, but with more current docfx.

### Alternative

install docfx with `DotNetTasks.DotNetToolInstall(c=>c.SetPackageName("docfx"));` and call `DotNetTasks.DotNet($"docfx build {docFxConfigPath}");`

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
If you need any fixes, please send a PR.

**Comment by DWIAltonaAnalytics** [comment]
I think I would have to do that in my private time, so no promises.

**Comment by DWIAltonaAnalytics** [comment]
just a note for future reference: https://github.com/dotnet/docfx/issues/9100

I think a simple fix would be to change the DocFxPath to include the dotnet tool as an alternative before falling back to the console, setting the environment variable helps, too.

**Comment by GeorgDangl** [comment]
@DWIAltonaAnalytics, did you make any progress here? I also just discovered that we're using the deprecated version for DocFX, and while not pressing right now, I'm trying to plan for how to upgrade to a supported version.

**Comment by DWIAltonaAnalytics** [comment]
@GeorgDangl well.
```C#
    Target DocFx => _ => _
        .DependsOn(CompileAll)
        .DependsOn(VersionMd)
        .DependsOn(DotNetToolRestore)
        .Executes(
            () =>
            {
                AbsolutePath docFxConfigPath = RootDirectory / DocFxProject / "docfx.json";
                DotNetTasks.DotNet($"docfx metadata {docFxConfigPath}");

                DotNetTasks.DotNet($"docfx build {docFxConfigPath}");
            });
```
I am just not using the build in docfx tooling, but call it directly through dotnet.

This way it uses what ever docfx version was installed with `dotnet tool install` and I can update those regularly.

I think having dedicated methods for tools like docfx makes the code much easier to read and use, but it lacks the flexibility of just using the tool as is.

I did not have time to look at the nuke-code to change this, or make it configurable (which would be my prefered way.)

**Comment by oceanxmountain** [comment]
I am also interested in seeing this updated and willing to take a stab at a PR.

@DWIAltonaAnalytics could you describe a little more what you would hope the configurability to look like?

**Comment by DWIAltonaAnalytics** [comment]
I looked at the code again and found that one can (now?) use an environment variable `DOCFX_EXE` to give a path to docfx and only if that is not found will it install the nuget-package hardcoded in the DocFXTasks class.

(we also stopped using docfx)

sorry for the late reply.
