### ISSUE TITLE
Code generation with support for TeamCity features

### ISSUE THREAD

**Issue by JeanOncle** [nuke-build/nuke#1307]
### Description

We rely on the **commitStatusPublisher** and **dockerSupport** from TeamCity, to make sure pull requests don't get merged before a successful build. However Nuke doesn't have support for this.

I've forked Nuke and fixed it locally already, so I'm ready to submit a pull-request.

### Usage Example

For the commit status publisher you could add the following:
```
[TeamCity(
    CommitStatusPublisher = TeamCityCommitStatusPublisherPublishers.BitbucketServer,
    CommitStatusPublisherUrl = "https://bitbucket.onpremise",
    CommitStatusPublisherUsername = "username",
    CommitStatusPublisherPasswordOrToken= "password"
)]
```
For Docker support this should be added:
```
[TeamCity(
    DockerSupportRegistryId = "test",
    DockerSupportDeleteImagesFromRegistryOnServerCleanUp = true
)]
```

### Alternative

The alternative is to add these features manually to the settings.kts file (this has to be done after every new code generation).

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
You can apply changes directly from TeamCity UI, which will create patch files. Therefore, I don't think it makes sense to add more specialized properties to the generation.
