### ISSUE TITLE
Nuke fails to execute a build when root directory path contains a space

### ISSUE THREAD

**Issue by supertr0n** [nuke-build/nuke#1311]
### Usage Information

Nuke Global Tool 7.0.6 / macOS 14.2.1 (23C71)

### Description

When setting up Nuke for the first time in a repository (on macOS) where one or more of the parent directory names contains a space, the `nuke :setup` build scaffolding setup works, but trying to execute `nuke` for the first build results in an error.

I've seen two variations of the error, which contains either `No such file or directory` or `... is a directory`

I don't tend to have spaces in my git repo/project directory names (I'm not a monster...), but the parent directory where all my local repos reside does contain a space.

**Side note:**
Unfortunately, as a first time user of Nuke, troubleshooting was made slightly harder by the lack of a working "help" command.  Running `nuke --help` outside of a project directory does not provide any help text and running it inside my project directory resulted in the same `No such file or directory` error.  (My normal first troubleshooting step is to check the command help to look for arguments to increase output verbosity etc.)

### Reproduction Steps

```
# Create an empty git repo with a space in the directory name
mkdir "nuke-test with-space"
cd "nuke-test with-space"
git init

# Follow the steps to scaffold the build
nuke :setup 

# Try to execute the first build
nuke
```

Error:
`/bin/bash: /Users/testuser/nuke-test: No such file or directory`

### Expected Behavior

Nuke should run the scaffolded {empty} build successfully.

Commands like `nuke --help` should also work, even if the build command itself fails.

Sample output when I follow the exact repro steps *without* a space in the directory name:

```
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Microsoft (R) .NET SDK version 8.0.100

███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

NUKE Execution Engine version 7.0.6 (OSX,.NETCoreApp,Version=v6.0)


╬════════════
║ Restore
╬═══


╬════════════
║ Compile
╬═══


═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Restore            Succeeded     < 1sec
Compile            Succeeded     < 1sec
───────────────────────────────────────
Total                            < 1sec
═══════════════════════════════════════

Build succeeded on 15/01/2024 17:49:45. ＼（＾ᴗ＾）／
```

### Actual Behavior

An error is displayed:
`/bin/bash: /Users/testuser/nuke-test: No such file or directory`

Also all variations of the nuke command also fail, eg. `nuke --help`

### Known Workarounds

Ensure the root directory path contains no spaces.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Thanks for the report. Can't believe this was buggy the whole time. It will be fixed in the next version. In the meantime, you can call `build.ps1/sh`.

**Comment by supertr0n** [comment]
That was a super fast fix 👍 

I wasn't sure whether to suggest it in a separate issue, but I think it would be quite useful if `nuke --help` always returned some help output, whether inside a valid build directory or not.

If there is a `--help` command at all, then I think that by convention this command should *always* produce help output and not depend on being in a particular directory (I understand you can produce more *specific* help when you're inside a build directory).

At the moment `--help` outside of a valid build directory instead puts you into the "new build scaffolding" flow - which I think is unexpected.  It made hitting up against this bug doubly jarring for me as a first time user!
