### ISSUE TITLE
DotNetWorkload(Install|Update|Restore|Repair): Missing argument `--skip-sign-check`

### ISSUE THREAD

**Issue by ITaluone** [nuke-build/nuke#1313]
### Description

Add the argument `--skip-sign-check`.

When I added the workload commands, I "forgot" this argument, because it is documented nowhere. Is this a problem to add this? Asking because I cannot find an official documentation...

### Usage Example

```csharp
DotNetWorkloadRestore(s => s
                .SetProject(Solution)
                .DisableSignCheck());
```

or

```csharp
DotNetWorkloadRestore(s => s
                .SetProject(Solution)
                .EnableSkipSignCheck());
```

### Alternative

Nothing

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Feel free to create a pull-request. I will close the issue as per [contribution guidelines](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-an-issue). For more information, see the part about [when creating a pull-request](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-a-pull-request).

**Comment by ITaluone** [comment]
Yeah.. See my question about no offical documentation. Is this a problem?
