### ISSUE TITLE
Multi-target project results in Tools not resolving

### ISSUE THREAD

**Issue by Cjewett** [nuke-build/nuke#1319]
### Usage Information

Nuke Version 7.0.6 and 8.0.0

### Description

We have a Nuke C# project that we changed from a single target framework to multi-target. When multi-target is set by specifying `<TargetFrameworks>net7.0;net8.0</TargetFrameworks>` we run into an issue where building has parallelization issues. It looks like `<AppendTargetFrameworkToOutputPath>` is set to false, so we have overwritten it in our project to be set to true. That solves that problem. The next issue we run into is Tool resolution fails when running the application. 

### Reproduction Steps

Something like the below will result in a null object exception.
```
#if NET7_0
[NuGetPackage(
    packageId: "InternalTool",
    packageExecutable: "InternalTool.dll",
    Framework: "net7.0",
    Version: "1.0.0",
)]
#elif NET8_0
[NuGetPackage(
    packageId: "InternalTool",
    packageExecutable: "InternalTool.dll",
    Framework: "net8.0",
    Version: "1.0.0",
)]
#endif
public Tool InternalTool { get; set; }
```

csproj also has the `<PackageDownload Include="InternalTool" Version="[1.0.0]" />`

### Expected Behavior

Tool should resolve to what is specified in the attribute.

### Actual Behavior

Tool doesn't resolve and is null. 

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
You define `packageId` three times?

**Comment by Cjewett** [comment]
> You define `packageId` three times?

Just a typo. We specify the packageId, packageExecutable, Framework, and Version. I'll update the original post.

**Comment by matkoch** [comment]
I'd appreciate if you'd take the time to submit an actual compilable example. It's no fun fixing such obvious errors before actually investigating an issue.

**Comment by Cjewett** [comment]
@matkoch Reproduce is here: https://github.com/Cjewett/NukeMultiFrameworkBug/tree/main/Nuke.Build

**Comment by matkoch** [comment]
Please be aware that this is not an easy area to work on. Personally, I'm not very interested in changing anything because it's quite an edge case. So if you work on a PR, please make it easy to review.

**Comment by matkoch** [comment]
There's a spike in https://github.com/nuke-build/nuke/tree/spike/gh-1319. If you want this fixed, please improve on it carefully and test affected features (e.g., msbuild tasks). I will close this in the meantime though (because edge case).

**Comment by Cjewett** [comment]
Thanks, taking a look at it here: https://github.com/Cjewett/nuke/pull/1
Will reach out again once I feel like I've gone through the use cases and verified
