### ISSUE TITLE
`ObjectExtensions.Apply` conflicts with `SettingsEntityExtensions.Apply`

### ISSUE THREAD

**Issue by gtbuchanan** [nuke-build/nuke#1323]
### Usage Information

8.0.0

### Description

The `ObjectExtensions.Apply(TInput, Func<TInput, TOutput>)` extension method was added in v8.0.0. However, it conflicts with `SettingsEntityExtensions.Apply(T, Configure<T>)` when both namespaces are imported. This forces me to call `SettingsEntityExtensions.Apply` like a static method instead of an extension method or remove the usage altogether.

### Reproduction Steps

Add using statements for `Nuke.Common.Tooling` and `Nuke.Common.Utilities`, then try to call the aforementioned `Apply` overload.

### Expected Behavior

`SettingsEntityExtensions.Apply(T, Configure<T>)` should probably be removed in favor of `ObjectExtensions.Apply(TInput, Func<TInput, TOutput>)` so that this conflict doesn't exist, but this would be another breaking change.

### Actual Behavior

![image](https://github.com/nuke-build/nuke/assets/715687/2dbb5136-3021-4fde-8aad-173f07686012)

### Regression?

`ObjectExtensions.Apply` did not exist in v7.0.6 so it was not an issue.

### Known Workarounds

Call `Apply` like a static method instead of an extension method or remove the usage altogether.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
all working here
![2024-02-21-JetBrains Rider-EAP-nuke-common – ITest cs-002751](https://github.com/nuke-build/nuke/assets/5005566/be0aabde-1c92-4df6-a671-e452ef037edb)
