### ISSUE TITLE
The "PackPackageToolsTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by EdLichtman** [nuke-build/nuke#1329]
### Usage Information

8.0.0

### Description

When trying to dotnet pack my Nuke Dotnet Tool, I get the following exception. 

```
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018: The "PackPackageToolsTask" task failed unexpectedly. [C:\Source\nia\core-nuget-host\Packages\To
ols\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018: System.InvalidOperationException: Sequence contains more than one matching element [C:\Source\n
ia\core-nuget-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException() [C:\Source\nia\core-nuget-host\P
ackages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Bool
ean& found) [C:\Source\nia\core-nuget-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate) [
C:\Source\nia\core-nuget-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at Nuke.Common.Tooling.NuGetPackageResolver.GetGlobalInstalledPackage(String packageId, Vers
ionRange versionRange, AbsolutePath packagesConfigFile, Nullable`1 includePrereleases) in /_/source/Nuke.Tooling/NuGetPackageResolver.cs:line 217 [C:\Source\nia\core-nuget-host\Packages\
Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at Nuke.Common.Tooling.NuGetPackageResolver.GetGlobalInstalledPackage(String packageId, Stri
ng version, AbsolutePath packagesConfigFile) in /_/source/Nuke.Tooling/NuGetPackageResolver.cs:line 182 [C:\Source\nia\core-nuget-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.To
ol.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at Nuke.Common.Tooling.NuGetPackageResolver.<>c__DisplayClass3_0.<GetLocalInstalledPackagesF
romAssetsFile>b__1(ValueTuple`2 x) in /_/source/Nuke.Tooling/NuGetPackageResolver.cs:line 100 [C:\Source\nia\core-nuget-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() [C:\Source\nia\core-nug
et-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() [C:\Source\nia\core-nuget-hos
t\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray() [C:\Source\nia\core-n
uget-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at Nuke.MSBuildTasks.PackPackageToolsTask.ExecuteInner() in /_/source/Nuke.MSBuildTasks/Pack
PackageToolsTask.cs:line 35 [C:\Source\nia\core-nuget-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at Nuke.MSBuildTasks.ContextAwareTask.Execute() in /_/source/Nuke.MSBuildTasks/ContextAwareT
ask.cs:line 76 [C:\Source\nia\core-nuget-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Exec
ute() [C:\Source\nia\core-nuget-host\Packages\Tools\Publish\Tool\src\Nx.Tools.Publish.Tool.csproj]
C:\source\packages\nuke.common\8.0.0\build\Nuke.MSBuildTasks.targets(27,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecut
ionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Source\nia\core-nuget-host\Packages\Tools\Publish\Tool\src\N
x.Tools.Publish.Tool.csproj]
```

### Reproduction Steps

I cannot share the code or configuration that makes it like this because it is too complex, but if you can help me understand why this error would occur, I can assist in a reproducible description.

### Expected Behavior

I expect to be able to dotnet pack it.

### Actual Behavior

I cannot dotnet pack it.

### Regression?

It worked fine in nuke 7.0.5, but then it stopped working in 7.0.5. I think it has to do with how nuke interacts with the dotnet SDK.

### Known Workarounds

None. this is completely preventing me from submitting my work days before code freeze.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
I have no idea why this is happening. Feel free to investigate it further.

**Comment by EdLichtman** [comment]
I'm trying to build my own pre-release version of this. I put <Version> in the Directory.Build.props, and now I'm getting this build error: 

C:\source\packages\nuke.common\8.0.1-rc1\build\Nuke.MSBuildTasks.targets(27,5): error MSB4062: The "Nuke.MSBuildTasks.PackPackageToolsTask" task could not be loaded from the assembly C:\source\packages\nuke.common\8.0.1-rc1\build\\Nuk
e.MSBuildTasks.dll. Could not load file or assembly 'C:\source\packages\nuke.common\8.0.1-rc1\build\Nuke.MSBuildTasks.dll'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assem
bly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Source\nia\core-nuget-host\Packages\Tools\Microservices\Build\Tool\src\Nx.Tools.Microservices.B
uild.Tool.csproj]

This is because the dll isn't being packaged up. Is there anything special you do to "build the package correctly"? I notice that the <Using> task in the Nuke.MSBuildTasks.targets file very clearly looks in the /build directory, so there must be something wrong with the way I'm packing it.

**Comment by EdLichtman** [comment]
False alarm. I needed to build it first, since you build, then you don't pack MsBuildTasks, you pack them and if they didn't exist, well...

**Comment by EdLichtman** [comment]
Ok, so I haven't used Git in a while (been using Perforce), and like I said, I'm smack in the middle of code freeze and release over the next few days so I can't really make a commit. However, in NuGetPackageResolver, line 217, at the end of the method: 

`public static InstalledPackage GetGlobalInstalledPackage(string packageId, VersionRange versionRange, AbsolutePath packagesConfigFile, bool? includePrereleases = null)`

I changed the code to this:         

```
return versionRange == null
            ? candidatePackages.FirstOrDefault()
            : candidatePackages.SingleOrDefaultOrError(
                x => x.Version == versionRange.FindBestMatch(candidatePackages.Select(y => y.Version)), 
                $"Could not find best match for package: {packageId}. Found more than one best match for version range: {versionRange}");
```

And wound up with this error message:

 Could not find best match for package: dotnet-outdated-tool. Found more than one best match for version r
ange: [4.5.3, 4.5.3]


For reference, this is my PackageDownloads:
```
 <ItemGroup>
    <PackageDownload Include="dotnet-outdated-tool" Version="[4.5.3]" />
    <PackageDownload Include="NuGet.CommandLine" Version="[6.7.0]" />
  </ItemGroup>
```

**Comment by EdLichtman** [comment]
OH! Well that's interesting...

It seems that dotnet sdk has an update in which it didn't use the nuget.config for dotnet tools before, and now it does. So I never added dotnet-outdated-tool to our NuGet feed before, and was working with it.

Any chance you could add better logging to the next version of Nuke Build tasks?

**Comment by EdLichtman** [comment]
Actually, one more update. I did have 4.5.3 there, so it's also possible that  it's because I had dotnet-updated-tool as a global tool but not as a local tool? I almost wonder if it's reproduceable by having the tool global, and not local, and having a <PackageDownload>. Perhaps I'll come back to it in a week or two. That'll be my last update for now.

**Comment by matkoch** [comment]
Could you give a summary with all updates condensed?

**Comment by EdLichtman** [comment]
Yeah, I'm not entirely certain of what happened, but it was basically triggered by my having dotnet-outdated-tool as a global tool. So perhaps it's because I didn't have dotnet-outdated-tool configured in the .config folder of my nuke target. I'm not entirely certain. 

Regardless, I was hoping you could add better logging. There are a couple of places where you have .Single() when you have a function to help called .SingleOrError(), and adding more specific messages would have helped me figure this out on my own faster.

Regardless, I don't seem to have time to continue working on figuring out what went wrong, so I can close the issue -- just wanted to let you know about the culprit at this point.

I don't know if you see the updates once I close, so I'll leave it up to you to close when ready.
