### ISSUE TITLE
.NET Core tools cannot be run as they are attempted to be run with mono

### ISSUE THREAD

**Issue by simendsjo** [nuke-build/nuke#1330]
### Usage Information

running netcore tools on *nix

### Description

Nuke assumes .exe files on *nix will be .NET Framework, which means .NET Core/net5+ both require mono, but fails as mono cannot run them. I don't know if it is possible to easily detect which dotnet a file is, but maybe it should be made configurable?

https://github.com/nuke-build/nuke/blob/59bdf80fcbe9b11f9e443a701d455b5aaa58c532/source/Nuke.Tooling/ProcessTasks.cs#L140-L143

### Reproduction Steps

```xml
  <ItemGroup>
    <PackageDownload Include="OctopusTools" Version="[9.1.7]"/>
  </ItemGroup>
```

```csharp
 OctopusTasks.OctopusPack(_ => _.SetId("whatever"));
```
 

### Expected Behavior

octo.exe runs

### Actual Behavior

Get an error because mono cannot run the netcore application.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
if it's an `.exe`, it's built for windows. otherwise it should be a `.dll`.

**Comment by matkoch** [comment]
I guess what you want to use is https://www.nuget.org/packages/Octopus.DotNet.Cli
