### ISSUE TITLE
Star to Download Extensions Not Working

### ISSUE THREAD

**Issue by superdupersam** [nuke-build/nuke#1331]
### Usage Information

NA

### Description

Star to Download JetBrains Rider Extension is not working for me.

### Reproduction Steps

When I click on the Download link for JetBrains Rider below:
![image](https://github.com/nuke-build/nuke/assets/159593915/646251aa-12ef-4b4d-a52c-6b1a57210af0)

I am redirected to:
https://nuke.build/blog/2024/01/22/update-on-ide-extensions/#star-to-download

### Expected Behavior

Should start downloading the extension

### Actual Behavior

Redirects to the website:

https://nuke.build/blog/2024/01/22/update-on-ide-extensions/#star-to-download

### Regression?

No

### Known Workarounds

None

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
works on my end

**Comment by superdupersam** [comment]
Why was this closed without any questions?

**Comment by valadas** [comment]
@superdupersam I am not seeing a page that looks like the screenshot, have you tried https://nuke.build/docs/ide/resharper/ ?

**Comment by superdupersam** [comment]
> @superdupersam I am not seeing a page that looks like the screenshot, have you tried https://nuke.build/docs/ide/resharper/ ?

That's the account page that shows my login with my github account on nuke.build site:

https://nuke.build/account/

Got the same behavior with the link above.  I have a workaround now - used my home machine (a Mac).  It worked :-).  It could be something dumb about my work PC.

**Comment by Nefarion** [comment]
I have the same problem here, both in Edge and Firefox on Windows.

The request flow looks like this:
`/download/rider` -> 302 (Found) with redirect to `/api/download/rider`
`/api/download/rider` -> 302 (Found) with redirect to `/blog/2024/01/22/update-on-ide-extensions/#star-to-download`

Both Requests only have one Cookie present: `StaticWebAppsAuthCookie`

I have no access to a Mac (where it seems to work)

**Comment by matkoch** [comment]
@Nefarion you have a private account... try again
