### ISSUE TITLE
Remove `perl` dependency from unix bootstrap and use global.json directly

### ISSUE THREAD

**Issue by KuraiAndras** [nuke-build/nuke#1336]
### Description

The default bootstrap scripts should set the `-JSonFile|--jsonfile` parameter on the `dotnet-install` script if the `global.json` file exists. The main motivation for this is to remove `perl` as a dependency on the linux side.

### Alternative

Everyone who is interested in this can manually edit the bootstrap scripts and make it work differently

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Details in pull request
