### ISSUE TITLE
Latest NSwag 14.0.3  support

### ISSUE THREAD

**Issue by jvmlet** [nuke-build/nuke#1338]
### Usage Information

8.0.0

### Description

Please regenerate NSwag tool with latest  `14.0.3` version, [14.0.0](https://github.com/RicoSuter/NSwag/releases/tag/v14.0.0) introduced breaking changes (some commands were removed, arguments have changed).

### Reproduction Steps

Build project with `<PackageDownload Include="NSwag.MSBuild" Version="[14.0.3]" />`  fails with `NSwagTasks` developed with nuke `8.0.0`

### Expected Behavior

nswag.dll to be invoked with correct arguments

### Actual Behavior

```
09:56:30 [INF] > "C:\Program Files\dotnet\dotnet.exe" C:\Users\xxx\.nuget\packages\nswag.msbuild\14.0.3\tools\Net60\dotnet-nswag.dll swagger2csclient  PARAMETERS_REDUCTED
09:56:30 [DBG] NSwag command line tool for .NET Core Net60, toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
09:56:30 [DBG] Visit http://NSwag.org for more information.
09:56:30 [DBG] NSwag bin directory: C:\Users\xxx\.nuget\packages\nswag.msbuild\14.0.3\tools\Net60
09:56:30 [DBG] System.InvalidOperationException: The command 'swagger2csclient' could not be found.
```

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Feel free to create a pull-request. I will close the issue as per [contribution guidelines](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-an-issue). For more information, see the part about [when creating a pull-request](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-a-pull-request).

**Comment by jvmlet** [comment]
Some documentation about how to generate tools API would really help for contributions ...

**Comment by matkoch** [comment]
There are plenty of other pull requests for tool wrappers. And the target to invoke for tool generation is called `GenerateTools`

**Comment by matkoch** [comment]
There are a couple of [tagged pull-requests](https://github.com/nuke-build/nuke/pulls?q=is:pr+is:closed+label:area:tools) now too

**Comment by jvmlet** [comment]
Afair, there was section in the documentation describing how to generate api for third party tool.... Can't find it....

**Comment by matkoch** [comment]
There's a section in the link I already shared. Otherwise, feel free to use archive.org
