### ISSUE TITLE
AddRunSetting adds extra space to run setting

### ISSUE THREAD

**Issue by vsosinga** [nuke-build/nuke#1340]
### Usage Information

NUKE 8.0.0

### Description

When I add a run setting to my .NET test task using `AddRunSetting` an extra space is added to the key causing the command to not use the run setting.

### Reproduction Steps

```
  DotNetTasks.DotNetTest(settings =>
      settings.EnableNoRestore()
          .SetProjectFile(Solution)
          .AddRunSetting("collect", "Code Coverage"));
```

### Expected Behavior

The following command should be executed:
`"C:\Program Files\dotnet\dotnet.exe" test [solution] --no-restore --collect="Code Coverage"`

Note: no space between `--` and `collect`

### Actual Behavior

The following command is executed:
`"C:\Program Files\dotnet\dotnet.exe" test [solution] --no-restore -- collect="Code Coverage"`

Note: a space between `--` and `collect`

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Exactly the behavior that's expected. https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test#synopsis
