### ISSUE TITLE
ProjectExtensions.GetPackageReferenceVersion does not work with NuGet Central Package Management

### ISSUE THREAD

**Issue by MikeFarrington** [nuke-build/nuke#1351]
### Usage Information

8.0.0 / 8.0.202 / 8.0.3 / 23H2

### Description

This issue straddles the line between a bug and a feature idea.  It breaks expected behavior, but is due to a newish feature within NuGet ([Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management) introduced in v6.2, about two years ago).

GetPackageReferenceVersion returns string.empty when consuming NuGet packages using Central Package Management as the project's PackageReference element no longer contains a Version attribute.  When using CPM, the Version attribute is found elsewhere within a PackageVersion element located in a Directory.Packages.props file within the solution.

### Reproduction Steps

Implement Central Package Management within a solution, then attempt to use ProjectExtension.GetPackageReferenceVersion.

### Expected Behavior

Return the version of the NuGet package being consumed.

### Actual Behavior

An empty string is returned instead of the NuGet package version.

### Regression?

Unknown, but unlikely.  

### Known Workarounds

None

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
I see no point in supporting this. There's likely only one build project per solution.

**Comment by MikeFarrington** [comment]
Yes, there is only one build project in our solution, but I'm not really following why that is relevant.  Let me explain what I was trying to achieve...

I was attempting to use GetPackageReferenceVersion to fail our builds if certain NuGet package versions are present (due to known bugs in the package).  In my case, Microsoft.Data.SqlClient v5.2.0 has a bug that breaks an important yet infrequently used feature in our solution so I want to make sure nobody on our team accidentally upgrades that package to this specific version.

**Comment by matkoch** [comment]
You could load every project in the solution through msbuild infrastructure and check for the package and version. Take a look at the docs for more information.
