### ISSUE TITLE
Issue with formating logs on AzureDevops

### ISSUE THREAD

**Issue by ArkaHnat** [nuke-build/nuke#1361]
### Usage Information

Latest Nuke and dotnet 6.0, 

### Description

When looking on output on Azure DevopsServer logs are looking really unpreety. Locally everything is working correctly.

### Reproduction Steps

Run build on Azure Devops Server

### Expected Behavior

It should look like in here: https://nuke.build/docs/cicd/azure-pipelines/
![image](https://github.com/nuke-build/nuke/assets/140606399/be65608d-088e-42e1-bd9a-eda063a27351)

### Actual Behavior

Output looks like this:
![image](https://github.com/nuke-build/nuke/assets/140606399/a4c58563-4446-49e9-b9d7-97fe5abdda1b)

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Take a look here in the FAQ

![image](https://github.com/nuke-build/nuke/assets/5005566/d2d3d8d4-27a8-422e-bb1b-23ef6473a8a7)
