### ISSUE TITLE
Container build rootless for Kubernets 

### ISSUE THREAD

**Issue by LeeRoyManea** [nuke-build/nuke#1365]
Is there a way to build a container in kubernetes without root permission?
Podman or Buildah support would be great. 

Did someone managed to archiv with the current tools?

**Comment by eaglestorm** [comment]
Just a note, Podman is essentially the same as docker just a different exe for most commands and with Docker Desktop being commerical for any decent size organization support for this would be good and shouldn't be a lot of work.
