### ISSUE TITLE
Update actions/checkout, actions/cache and actions/upload-artifact to @v4 in generated Github Actions to use Node 20

### ISSUE THREAD

**Issue by ebjornset** [nuke-build/nuke#1367]
### Usage Information

nuke.common 8.0.0, .Net 6/7/8

### Description

Get this when running GitHub actions generated by nuke.common v 8.0.0:

1 warning
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Reproduction Steps

Generate a Github action that uses caching and upload some artifacts and run it on GitHub

### Expected Behavior

No warnings

### Actual Behavior

1 warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Could you help with a pull-request?

Yes

**Comment by ebjornset** [comment]
I just forked the repo and pulled down the code and noticed that its only actions/checkout left to update, since actions/cache and actions/upload-artifact is already updated to @v4 in develop

**Comment by lahma** [comment]
> I just forked the repo and pulled down the code and noticed that its only actions/checkout left to update, since actions/cache and actions/upload-artifact is already updated to @v4 in develop

https://github.com/nuke-build/nuke/pull/1298
