### ISSUE TITLE
Add support for slnx solution files

### ISSUE THREAD

**Issue by russgreen** [nuke-build/nuke#1375]
### Description

Deserialize .slnx files

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
https://x.com/csharpfritz/status/1779788209313997180?s=46&t=NUrofe3RSXN9uAagAPcV5g

**Comment by BrycensRanch** [comment]
Hi, can this issue be reopened? Microsoft changed their tone and it's implemented in the dotnet sdk, msbuild, and once Nuget's client is updated, it will support slnx.

build: switch to slnx


https://github.com/dotnet/msbuild/issues/10266

For editor support, recent versions of Rider already have it. For VSCode it is a work in progress.

https://github.com/dotnet/vscode-csharp/issues/7048

I have personally tested it on VSCode with the VSCode Solution Explorer extension and it works fine but granted it is readonly. https://github.com/fernandoescolar/vscode-solution-explorer/releases/tag/v0.8.7

**Comment by BrycensRanch** [comment]
Please disregard that commit message, I was upset by something else unrelated. I am willing to PR this feature as well.
