### ISSUE TITLE
MinVerDefaultPreReleasePhase is deprecated and will be removed

### ISSUE THREAD

**Issue by jamesshenry** [nuke-build/nuke#1379]
### Usage Information

8.0.0/8.0.204/8.0/Windows

### Description

When using `MinVerSettings.SetDefaultPreReleasePhase` an error is logged by minver-cli because that command option is now deprecated: https://github.com/adamralph/minver/blob/38681c8f283e109f4b2e0d212d761bd828d16802/minver-cli/Program.cs#L81

### Reproduction Steps

Call the minver cli in a Target:
```cs
    [MinVer] readonly MinVer MinVer;
    Target PrintVersion => _ => _
        .Executes(() =>
        {
            MinVerTasks.MinVer(_ => _
                .SetMinimumMajorMinor("1.0")
                .SetDefaultPreReleasePhase("preview.0")
            );
            Log.Information(MinVer.Version);
        });
```

### Expected Behavior

Should not get an error message

### Actual Behavior

```
[ERR] PrintVersion: MinVer: warning : MinVerDefaultPreReleasePhase is deprecated and will be removed in the next major version. Use MinVerDefaultPreReleaseIdentifiers instead, with an additional "0" identifier. For example, if you are setting MinVerDefaultPreReleasePhase to "preview", set MinVerDefaultPreReleaseIdentifiers to "preview.0" instead.
```

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Feel free to create a pull-request. I will close the issue as per [contribution guidelines](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-an-issue). For more information, see the part about [when creating a pull-request](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-a-pull-request).
