### ISSUE TITLE
Rider plugin out of date

### ISSUE THREAD

**Issue by JustASquid** [nuke-build/nuke#1380]
### Usage Information

N/A

### Description

The NUKE Support plugin for Rider is out of date.

`Incompatible: requires IDE build 231.* or earlier`

### Reproduction Steps

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Regression?

No

### Known Workarounds

None

### Could you help with a pull-request?

No

**Comment by JustASquid** [comment]
@matkoch Is the Rider plugin deprecated? Or just no resources to spend on getting it up to date?

**Comment by metalfork** [comment]
> @matkoch Is the Rider plugin deprecated? Or just no resources to spend on getting it up to date?

Same question here.
