### ISSUE TITLE
Support for new Codecov CLI

### ISSUE THREAD

**Issue by Xzelsius** [nuke-build/nuke#1382]
### Description

The currently provided Codecov tasks rely on the deprecated [Codecov.Tool](https://www.nuget.org/packages/Codecov.Tool) package.

Uploading coverage reports to Codecov should now be done using the [Codecov CLI](https://docs.codecov.com/docs/codecov-uploader)

### Usage Example

The built-in tasks for Codecov should provide wrappers for the following CLI commands

- create-commit
- create-report
- do-upload

The built-in Codecov target would wrap these three tasks to upload the Coverage reports.

### Alternative

Staying on the deprecated NuGet package or uploading Coverage reports outside of the NUKE build.

### Could you help with a pull-request?

No

**Comment by Xzelsius** [comment]
There is currently no NuGet package/tool available that packs the CLI.
I might be able to help with a PR, but would need some guidance to get it done properly.

**Comment by matkoch** [comment]
afaics, it's only distributed via pip/python. atm, I'm not planning to support tool path resolution / auto-download for that.
