### ISSUE TITLE
[GitLab] Add option to set collapsed=false on sections

### ISSUE THREAD

**Issue by Otiel** [nuke-build/nuke#1384]
### Description

`[collapsed=true]` is automatically set in GitLab job logs [sections](https://docs.gitlab.com/ee/ci/jobs/#pre-collapse-sections).

Could we have an option to disable this behavior?

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
sorry, not planned

**Comment by Otiel** [comment]
Even if I submit a PR?
