### ISSUE TITLE
Pipeline files no longer visible in VS

### ISSUE THREAD

**Issue by alex-zyl** [nuke-build/nuke#1391]
### Usage Information

8.0

### Description

Nuke build project included `ci` folder with linked pipeline yml file by default. Recently I noticed that it's no longer there. 
![image](https://github.com/nuke-build/nuke/assets/22393574/45bf778f-3526-4d6f-b2ad-dd6b823f4cdb)

### Reproduction Steps

1. Create new solution folder
2. Add azure-pipelines.yml to the root folder
3. Setup nuke project 

### Expected Behavior

 `ci` folder with azure-pipelines.yml is visible under _build project in VS

### Actual Behavior

Only `boot` and `config` folders are displayed

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
![2024-06-13-Parallels Desktop-Windows 11-003901](https://github.com/nuke-build/nuke/assets/5005566/acea8def-16a1-43d9-8811-d25931707517)
