### ISSUE TITLE
Support for NuGetKeyVaultSignTool

### ISSUE THREAD

**Issue by Julien-Marpault** [nuke-build/nuke#1395]
### Description

Azure Sign Tool doesn't allow to sign Nuget Packages. We need to use [NuGetKeyVaultSignTool](https://github.com/onovotny/NuGetKeyVaultSignTool) for that. It could be useful to support it

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
Feel free to create a pull-request. I will close the issue as per [contribution guidelines](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-an-issue). For more information, see the part about [when creating a pull-request](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-a-pull-request).
