### ISSUE TITLE
5x the dialog box "Build project could not compile" when opening my solution

### ISSUE THREAD

**Issue by jeroenlandheer** [nuke-build/nuke#1402]
### Usage Information

VS2022 Nuke build extension

### Description

This is about the Visual Studio extension. When opening up the solution I'm getting 5 times the dialog box "Nuke Support" with the message "Build project could not compile".... which makes this extension quite unusable. 

The build project compiles just fine, but not every project in the task runner is a build project. (There are multiple projects in the task runner each having things like Gulp files, build cmds or other stuff.) Besides this, showing a dialog box is really annoying, this error message should be in an output window instead. 

### Reproduction Steps

Create a solution with a simple nuke build file, install the Visual Studio extension and add a project with a different task runner in it.

### Expected Behavior

No error messages, the extension should not try to build projects that aren't nuke build projects.

### Actual Behavior

Multiple pop-up dialog boxes which blocks the rest of the UI in Visual Studio.

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
I doubt that the extension is compiling a non-build projects – it will execute `build --help` – but please send in a repro.
