### ISSUE TITLE
dotnet run does not support /property MSBuild parameters

### ISSUE THREAD

**Issue by jwfx** [nuke-build/nuke#1403]
### Usage Information

NUKE 8.0.0 / SDK 8.0.303 / net8.0 / win-x64

### Description

Adding MSBuild properties to DotNetTasks.DotNetRun() calls currently produces `/property` parameters, which is not supported, it should be `--property`.

`dotnet run doesn't respect arguments like /property:property=value, which are respected by dotnet build.`
Source: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-run#description

### Reproduction Steps

```
DotNetTasks.DotNetRun(y => y
    .SetApplicationArguments("--someparameter")
    .SetProjectFile(RootDirectory / "test" / "test.csproj" )
    .AddProperty("VersionPrefix", "9.0.0"));
```

### Expected Behavior

`14:22:44 [INF] > "C:\Program Files\dotnet\dotnet.exe" run --project D:\test\test\test.csproj --property:VersionPrefix=9.0.0 -- --someparameter`

### Actual Behavior

`14:22:44 [INF] > "C:\Program Files\dotnet\dotnet.exe" run --project D:\test\test\test.csproj /property:VersionPrefix=9.0.0 -- --someparameter`

### Could you help with a pull-request?

No

**Comment by jwfx** [comment]
What am I missing?

**Comment by jwfx** [comment]
@matkoch
Could you please elaborate what the problem with this bug report is?

I did contribute to NUKE before, so I can't really figure out what my mistake was this time around.
Maybe this is a bigger issue than I thought it would be and you prefer a PR for this? Is there a workaround I'm not seeing or is this actually working as expected?

Thanks

**Comment by matkoch** [comment]
The text below went missing


Feel free to create a pull-request. I will close the issue as per [contribution guidelines](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-an-issue). For more information, see the part about [when creating a pull-request](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#when-creating-a-pull-request).
