### ISSUE TITLE
Dependencies are not skipped when the dependent is skipped

### ISSUE THREAD

**Issue by dennisdoomen** [nuke-build/nuke#1414]
### Usage Information

Nuke 8.0.0 / .NET 8.0.108 / Windows 11

### Description

When I mark a target with `OnlyWhenDynamic` or `OnlyWhenStatic` and the condition is not met, the target is skipped. But its dependencies are still executed, even if the target is the only one that uses it. 

### Reproduction Steps

  Target Restore => _ => _
      .Executes(() =>
      {
      });

  Target Compile => _ => _
      .OnlyWhenStatic(() => IsServerBuild)
      .DependsOn(Restore)
      .Executes(() =>
      {
      });

### Expected Behavior

When you run this locally, both the `Compile` and `Restore` steps should be skipped.

### Actual Behavior

```
NUKE Execution Engine version 8.0.0 (Windows,.NETCoreApp,Version=v6.0)
​
​
╬════════════
║ Restore
╬═══
​
​
═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Restore            Succeeded     < 1sec
Compile            Skipped                // OnlyWhen: IsServerBuild
───────────────────────────────────────
Total                            < 1sec
═══════════════════════════════════════
​
Build succeeded on 8-9-2024 09:34:57. ＼（＾ᴗ＾）／
```

### Regression?

Yes, but I don't remember exactly in which version. Even in 6.3.0 it doesn't work as expected.

Also, `.WhenSkipped(DependencyBehavior.Skip)` doesn't make a difference.

### Known Workarounds

Apply `OnlyWhenDynamic` on _all_ targets

### Could you help with a pull-request?

Yes

**Comment by IT-VBFK** [comment]
I am using 8.1.0, but this issue doesn't seem to be fixed?

A target (which is skipped) which depends on exactly one target runs this one target.

<img width="861" alt="image" src="https://github.com/user-attachments/assets/9277c55d-495c-4cf7-bd5d-8e500fba126e">

**Comment by ITaluone** [comment]
I also seeing this:

With the reproduction steps from this ticket and NUKE 8.1.1 I get following:

```csharp
Target Restore => _ => _
        .Executes(() =>
        {
            Information($"Should not execute... {nameof(Restore)}");
        });

    Target Compile => _ => _
        .OnlyWhenStatic(() => IsServerBuild)
        .DependsOn(Restore)
        .Executes(() =>
        {
            Information($"Should not execute... {nameof(Compile)}");
        });

```

![image](https://github.com/user-attachments/assets/e1926fa1-7e95-47ab-8fca-661bebc01b80)

**Comment by ITaluone** [comment]
With 8.1.2 this is fixed ~for `OnlyWhenStatic`. `OnlyWhenDynamic` still runs the dependencies?~ As the documentation states, this is the desired behavior :)

Thanks @matkoch 🎉
