### ISSUE TITLE
Spec has odd assertion, seems incorrect

### ISSUE THREAD

**Issue by LordMike** [nuke-build/nuke#143]
Great project - looking at it for builds. 

I was reading one of the specs, and saw that this odd assertion is in place: https://github.com/nuke-build/nuke/blob/7c2ecbeb3cf674c6448ecc8f6b50d08b8d955215/build/specifications/DocFx.json#L85-L91.

It doesn't seem like this is correct (it's quite possible I just don't know what any of this means, and skipped the RTFM :P).

**Comment by arodus** [comment]
Hi @LordMike, the assertion looks odd but is there for a reason:
Themes are always folders and the parameter is optional, so the assertion ensures that the build fails direcly in Nuke (but only if a value is passed and it's not the path to a valid folder) and not in in the tool with a, perhaps, strange error message.

After checking the docs again I noticed that the assertion was indeed correct for the intented use case but the `Theme` parameter also accepts a list of themes and also a zip file. I will create a follow up issue to update the specification accordingly. 

Thanks for making us aware of that.
