### ISSUE TITLE
Unable to download the plugin from Nuke.build website

### ISSUE THREAD

**Issue by vova-lantsov-dev** [nuke-build/nuke#1440]
### Usage Information

Nuke.build website

### Description

/download/rider endpoint fails with error HTTP 500 (Visual Studio and ReSharper endpoints fail as well)

### Reproduction Steps

Go to https://nuke.build and press "JetBrains Rider (download)"

### Expected Behavior

Should start downloading

### Actual Behavior

Fails with HTTP code 500

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
try again

**Comment by tiltPaul** [comment]
Its still broken for me
