### ISSUE TITLE
Provide ability to use custom logger sinks

### ISSUE THREAD

**Issue by ElijahReva** [nuke-build/nuke#145]
Hello!

I'm trying to figure out how to use Serilog as the logger. Is there any way to do this globally in the current release?

**Comment by arodus** [comment]
Currently there is no extension point to select a different output sink but we can definitly do this. But we first have to think about how to select the logger in the build and how to combine it with e.g. the Teamcity Api.

**Comment by matkoch** [comment]
In order to get gain experience and some more feedback, I've created an extension point (https://github.com/nuke-build/nuke/compare/75c9a88aca8b...5b3a3bdb232a). @arodus you alright with that?

**Comment by arodus** [comment]
The property should be public.

**Comment by matkoch** [comment]
Why?

**Comment by arodus** [comment]
nvm 🙈

**Comment by ElijahReva** [comment]
Why it's internal?

**Comment by matkoch** [comment]
It's internal protected. You can override it.

**Comment by ElijahReva** [comment]
Thanks!
