### ISSUE TITLE
SetProcessArgumentConfigurator is missing from ToolSettings

### ISSUE THREAD

**Issue by cz-dev-ge** [nuke-build/nuke#1464]
### Usage Information

9.0.1 / 9.0.100 / 9.0 / Windows 11

### Description

Since the update of `Nuke.Common` to 9.0.1 the method `SetProcessArgumentConfigurator` of `ToolSettings` if gone. I could not find and mentions of breaking changes but I found that the code has been removed.

PS: The example code [in the docs](https://nuke.build/docs/common/cli-tools/#custom-arguments) still contains that code.

How do I migrate? Best regards,
Georg

### Reproduction Steps

```cs
DotNetTasks.DotNetBuild( settings => settings
  .SetProcessArgumentConfigurator(
    argument => argument
      .Add( "/d:login={0}", Secrets.AccessToken, secret: true )
      .Add( $"-getProperty:{propertyName}" ) );
```

### Expected Behavior

I expect it to be there or a hint in the release notes or a migration guide.

### Actual Behavior

Missing.

### Regression?

Yes

### Known Workarounds

I guess this but I am not sure as the methods have no documentation:

```cs
.AddProcessRedactedSecrets( Secrets.AccessToken )
.AddProcessAdditionalArguments(
  $"/d:login={Secrets.AccessToken}",
  $"-getProperty:{propertyName}" ) );
```

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
That's the correct new method.
