### ISSUE TITLE
Add option to disable automatic .NET SDK installation when requested SDK is missing

### ISSUE THREAD

**Issue by jwfx** [nuke-build/nuke#1469]
### Description

Right now when a global.json with an undesired SDK version is committed to a NUKE enabled repository. This SDK is automatically installed and used on the CI server. Both NUKE and also the actual application compilation is then done with that SDK version.

Right now, as far as I can tell, there is no official way to opt out of this behavior.

We would like to have more deterministic control over which SDK versions are used, by only installing the green-lit ones on the CI machines.

If would be helpful if this behavior was configurable.

### Usage Example

Proposal: https://github.com/jwfx/nuke/commit/2970ffbcc662b9609d23261732b600d4a91e9be3

One could opt out of this behavior by simple disabling it via parameters.json:

```
{
  "$schema": "build.schema.json",
  "DisableDotNetInstall": true
}
```

I could turn this into a PR.

### Alternative

Manually editing the NUKE build scripts and manually merging in future official changes, which is quite tedious.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
it's very unclear why you would commit an undesired SDK version in the first place

**Comment by matkoch** [comment]
I can already state that I'm not willing to modify the bootstrapper scripts in such an excessive way as the default

**Comment by jwfx** [comment]
> it's very unclear why you would commit an undesired SDK version in the first place

It's basically the human factor. There are always people who want the latest and grated on the day it is dropped, without contemplating possible side effects.

> I can already state that I'm not willing to modify the bootstrapper scripts in such an excessive way as the default

Any other official way to opt out of this behavior would be perfectly fine, this was just an idea after all.

As a general rule of thumb, whenever something is happening automatically, especially if it is installing something, there should be a way to disable that.

NUKE itself is not actually the problem. It is perfectly acceptable for NUKE to use the locally installed SDK to run itself. The problem arises in calls to MSBuild or dotnet.exe from NUKE, which then also use the locally installed SDK version instead of failing as they should.

I haven't researched yet how exactly MSBuild is picking up that local SDK in the NUKE temp folder, probably env vars or something?
