### ISSUE TITLE
Ability to navigate up in the hierarchy with AbsolutePath, other features

### ISSUE THREAD

**Issue by LordMike** [nuke-build/nuke#147]
Hey,

I was working with paths, and was lacking these features on AbsolutePath:

* Fetch parent directory (f.ex. `.Parent`)
* Ability to get all parents (f.ex. `IEnumerable<AbsolutePath> .Parents()`
* Various string operations, lacking `.Parent`, I looked for `.Contains` -- Althought I imagine it would be bad to have Contains on AbsolutePath, so maybe scratch this one

**Comment by matkoch** [comment]
The `Parent` property is now implemented. But I'm against `Parents` as we already have `Descendents` and `DescendentsAndSelf`. Would that be enough?

**Comment by matkoch** [comment]
Also I suggest to rename `AbsolutePath` to `Path` with the intent to use it more widely (not for vNext, but the next). I'd vote for duplicating all static methods from `System.Path`. Any opinions?

**Comment by LordMike** [comment]
`Descendants` goes down the tree, while `Parents` would go up the tree, right?

Having the name clash with `Path` would probably .... work.. Since nuke scripts are usually one file and you generate most of them so you'd be able to do a mapping of `Path` to Nuke's `Path`. ... right?

**Comment by matkoch** [comment]
It is a general purpose method that receives a delegate, so you could write path.Descendents(x => x.Parent), and it would walk up the chain.

Basically we need to ensure that most stuff from System.IO is available by some other class from our own Nuke.IO.

**Comment by LordMike** [comment]
That, and any extensions that the user may have on the static `Path` class (C# 8.0) will not be present in Nuke's version of `Path`.

**Comment by markusamshove** [comment]
I'm not sure if renaming AbsolutePath to Path wouldn't create more confusion than just leaving it as it is

**Comment by matkoch** [comment]
Current plan is to use another name like `NPath` or `Path2`. In our own solution `Path` lead to too many resolution issues (mostly due to `File`, `DirectoryInfo` and so on).

**Comment by matkoch** [comment]
@MarkusAmshove the general goal is to have something _shorter_ than `AbsolutePath` ... to me it doesn't feel very convenient.
