### ISSUE TITLE
Generally set `LogErrorAsStandard` for GitTasks

### ISSUE THREAD

**Issue by cz-dev-ge** [nuke-build/nuke#1470]
### Description

Git logs to stderr by default. I think that much is known. I saw that there is this code in `ToolTasks.Logger.cs`:

```cs
var errorAsStandard = toolType.HasCustomAttribute<LogErrorAsStandard>();
```

Since we cannot set `GitTasks.GitLogger` in Nuke 9 it might be a good idea to set this attribute from the beginning.

Best regards,
Georg

### Usage Example

What I did before Nuke 9:

```cs
GitTasks.GitLogger = (_, m) => Log.Information( "{M}", m );
```

### Alternative

What I have to do now on every call of `GitTasks.Git`:

```cs
GitTasks.Git( "<some git command>", logger: (_, m) => Log.Information( "{M}", m ) )
```

### Could you help with a pull-request?

No

**Comment by czdietrich** [comment]
Yep, once more a breaking change without easy work around. :/

**Comment by matkoch** [comment]
One more issue that doesn't follow the contribution guidelines.

![2024-11-28-Arc-nukeCONTRIBUTING md at develop · nuke-buildnuke-006076](https://github.com/user-attachments/assets/86a974f6-92f9-4d03-b7ae-c0e3939c072c)

**Comment by AlexejLiebenthal** [comment]
@czdietrich also let me highlight this for you:

> Could you help with a pull-request?
> No

It's a completely natural right for an OSS project maintainer to close issues without response, especially when help was ruled out from the beginning, and contribution guidelines weren't followed. Sarcasm and frustration are the wrong answer. If you want this project to match your expected quality/API design, then maybe match it in different terms too.

**Comment by czdietrich** [comment]
I agree with you that it is his right to close issues without response, but still I think doing so is helping no one. Referring to the guidelines was the better reaction in my opinion and made the point clear.

**Comment by cz-dev-ge** [comment]
Yeah, fine by me. Might be a tool wrapper request but still connected to a breaking change. Must have overlooked that part of the guideline.

Part of the issue are missing breaking changes notes in the release notes. Due to that I have to gather some information and opinion from the maintainer and understand the situation before I think about opening a pull request.

I am happy to help if I can. I'll try to make a better next issue.

**Comment by matkoch** [comment]
@czdietrich, from the contribution guidelines:
> Refrain from debating the governance or state of the project

@georg-eckert-zeiss, from the FAQ:
> If you can no longer find an API, proceed as follows:
> - Check the [changelog](https://github.com/nuke-build/nuke/blob/develop/CHANGELOG.md)
> - Try to fuzzy search in your IDE
> - Reach out to the community on [Slack](https://nuke.build/slack) or [Discord](https://nuke.build/discord)
>
> Please remember that this is an open-source project.

Guys, I don't enjoy having to quote myself repeatedly. Take some time to get more familiar with the project––it’ll help you understand why I’m not cool with these kinds of provocations.
