### ISSUE TITLE
Add artifacts-path options for dotnet commands

### ISSUE THREAD

**Issue by SigtryggurO** [nuke-build/nuke#1476]
### Description

dotnet 8 added a artifacts-path option for multiple commands, eg. dotnet `clean`, `test`, `build`, 
`pack` and `publish` that are missing in nuke.

### Usage Example

```csharp
DotNetTasks.DotNetBuild(s => s.SetArtifactsPath("artifacts/");
```

### Alternative

In Nuke 8.14 it's:
```csharp
DotNetTasks.DotNet("build --artifacts-path artifacts/");
```
Nuke 9.01 added better way to add new options but I couldn't use that version due too other issues.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
feel free to file a pr
