### ISSUE TITLE
Add documentation on how to generate the specs

### ISSUE THREAD

**Issue by LordMike** [nuke-build/nuke#148]
I wanted to add a spec for Pnpm (a faster version of npm), so I initially just copied Npm.json and set out to find the generator. I did not succeed.

For now, I've copied the generated code and renamed all methods / classes appropriately, and that works - but ideally it should be generated :).

Is pnpm of interest to Nuke in general? (should I do a PR with pnpm.json?)

**Comment by matkoch** [comment]
Given it has 4k stars on GitHub, I think it’s quite reasonable to have it included. A PR would surely be very welcome. However, I suggest to have a quick chat on either Gitter or Slack. We do know that documentation misses a few things, and it’s on our list. But it will take some time to get to that.

**Comment by matkoch** [comment]
Ah sorry, now I understand :)

You just invoke `nuke generate` to execute the [target](https://github.com/nuke-build/nuke/blob/develop/build/Build.CodeGeneration.cs#L31).

Could you please also update your PR for dotnet? (If not I will do it as soon as 0.9.0 is going to ship)

**Comment by matkoch** [comment]
Infrastructure will change fundamentally. So this will be obsolete anyways.

**Comment by dperez3** [comment]
So what is the current way to generate code? The latest version of `CodeGenerator` has an API that's different from all the documentation I can find.

Where do I get the json schema for json spec files?

**Comment by matkoch** [comment]
Schema is in the examples, and code gets generated on compile.
