### ISSUE TITLE
Allow extending Host

### ISSUE THREAD

**Issue by shlomiassaf** [nuke-build/nuke#1480]
### Description

Currently, extending `Host` is possiable however, customizing the output theme/template is virtually impossible.

https://github.com/nuke-build/nuke/blob/7e09c3cb21c849d9eabf186aafaf65ecc139add0/source/Nuke.Build/Host.cs#L30-L32

The console output `Theme` and `OutputTemplate` is fixed to the logger's default or, internal implementation for a specfic host if such provided (eg `AzurePipeline`)

Is it possible change the modifiers to `protected internal` similar to the method in `Host`?

 internal virtual IHostTheme Theme => Logging.DefaultTheme; 

```
    protected internal virtual IHostTheme Theme => Logging.DefaultTheme;

    protected internal virtual string OutputTemplate => Logging.TimestampOutputTemplate;

    protected internal void WriteLogo() 
```

Thnaks

### Usage Example

We want to implement various host's.
For example, a remote console where we will set the Host theme as the remote's theme.

### Alternative

No alternative

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
why do you need to extend the output theme?

**Comment by shlomiassaf** [comment]
I've mentioned above, for example, a remote console host.
Where we send the console logs over the wire.

Another one will be a scenario where Nuke runs inside a docker build which a parent Nuke executed.
Same thing here, we want to send the console to the top-level nuke.

It's already implemented.
Controlling the log's is easy.
The hard part is the console, which is written to directely by nuke.

I'm already sending the console remotely but I can't control the theme.
For example, in a docker build, that console will not have XTERM terminal, so it will "use" System colors for the console, which are not transfarable to a remote console

**Comment by shlomiassaf** [comment]
Just wondering.
The theme's are based on serilog.
Their implementations (`AnsiConsoleHostTheme`/`SystemConsoleHostTheme`) is also public.

What are the concerns of exposing this API to derived classes?

**Comment by matkoch** [comment]
the motivation is to make people contribute to the project instead of improving just within their orgs.

what you described about docker is already possible, afaiu:
- https://github.com/nuke-build/nuke/commit/7b84eb74a4456e71c3f40892d9e75ce531ad6552
- https://github.com/nuke-build/nuke/commit/a50f84b8b450f1fb0a709822bd6647f23d5a60e4

**Comment by shlomiassaf** [comment]
We will contribute once it's possible and based on the scope you guys willing to accept.

The example you gave is known and it's not what I described.

The policy of this project is that code should be limited just to force people to contribute?

We're not trying to hide anything and the functionality does not exist.

There are other things done, for example a dockerfile configuration generator.

I think you should reconsider the agenda.

There are a lot of different setups, scenarios and features.

This project can not accommodate them all. 
It's better to allow customization let people go wild. 

If something is good or popular you can add it afterwards.

**Comment by matkoch** [comment]
I think you're putting words in my mouth...

**Comment by shlomiassaf** [comment]
> I think you're putting words in my mouth...

Apologies.
I'm asking not stating.

That's the explanation you gave for keeping it internal.

The limitation is unfortunate.
I wish it was otherwise, for a build orchestrator customization is a must.

**Comment by matkoch** [comment]
`IHostTheme` generally has a very limited use-case, i.e., better output in CI/CD tools. If you had seen as many internal builds as me, you'd understand why I'm trying to make people contribute those parts. That doesn't mean it's the project-wide "agenda".

Your initial issue doesn't give much information about the ultimate goal. I suggest forking the repository, going wild, and then coming back to discuss further design/integration.

**Comment by shlomiassaf** [comment]
I believe that you will see with time that trying to bring it all to this project will do more harm then good.
That's quite the opposite of the best practice.

You've built an impressive project, and your entitled to choose the path forward.

I don't see it covering all scenarios, it's virtually impossible.
I don't think it should as it will not be maintainable.

Since it's a build tool, it should allow extensibility in all aspects, as builds have many shapes and forms.

I understand there's no chance to change your decision, but just for the record
I'm not asking for a feature, i'm asking for an extension point that does not require logical development.
I would understand your logical argument if it was a feature, but since it's just exposing something that is mostly exposed already, it's simply doesn't make sense - to me.

You should focus on extensibility and let the community rock'n'roll.

Anyway, thank you for your time.

**Comment by matkoch** [comment]
I pointed out the reasoning, I offered to discuss it further once there are more details / a draft about your remote console host. What I read in your text is a lot of "you should", "opposite of best practices", and such and such. Respectfully, this is the wrong way to make an issue. From what I gathered, you don't seem to know about the project for very long. Don't make the mistake of underestimating things, and maybe also check out the guidelines once more, because I'm very clear about my openness for folks to [take ownership of certain subsystems](https://github.com/nuke-build/nuke/blob/develop/CONTRIBUTING.md#sustainability-contributions).
