### ISSUE TITLE
DockerTasks.DockerRun places options after image name which is wrong.

### ISSUE THREAD

**Issue by Danielku15** [nuke-build/nuke#1487]
### Usage Information

9.0.3

### Description

The Docker run command dictates that the options are placed before the image name followed by the command and command args:
> docker container run [OPTIONS] IMAGE [COMMAND] [ARG...]
https://docs.docker.com/reference/cli/docker/container/run/

But Using DockerTasks.DockerRun places the options after the image name leading to errors. 

### Reproduction Steps

```cs
DockerTasks.DockerRun(c => c
	.SetImage("ubuntu:latest")
	.SetRm(true)
	.SetCommand("uname")
	.SetArgs("-a")
);
```

### Expected Behavior

Options need to be placed before the image name:
```
11:46:31 [INF] > "C:\Program Files\Docker\Docker\resources\bin\docker.exe" run --rm ubuntu:latest uname -a
```

### Actual Behavior

Options are placed after the image name leading to an error. 

```
11:46:31 [INF] > "C:\Program Files\Docker\Docker\resources\bin\docker.exe" run ubuntu:latest --rm uname -a
11:46:32 [DBG] docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--rm": executable file not found in $PATH: unknown.
```

### Known Workarounds

Use `ProcessTasks` and call docker directly. 

### Could you help with a pull-request?

No. Seems this logic is somehow deeply buried in the generated code for the docker tooling. I'm not sure where I'd need to start fixing things. I think it could be solved by setting the `Position` on some arguments.

**Comment by Danielku15** [comment]
I'd expect this breaks the functionality in https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/Docker/DockerTargetDefinitionExtensions.cs#L105 but tests might be green because it seems the image name is not passed to docker run in this code.

**Comment by IT-VBFK** [comment]
A workaround for me is that the last one is `SetImage`

In your example just swap `SetImage`  and `SetRm`

**Comment by matkoch** [comment]
Anyone of you would like to take over maintaining `Docker.json` ?

**Comment by Danielku15** [comment]
@matkoch I cannot take fully over such a responsibility, but if you have any concrete needs around code generation I could look into helping you out. I might need some initial guidance though. I couldn't find deeper docs on how the tool generation is currently organized.

**Comment by klemmchr** [comment]
> @matkoch I cannot take fully over such a responsibility, but if you have any concrete needs around code generation I could look into helping you out. I might need some initial guidance though. I couldn't find deeper docs on how the tool generation is currently organized.

Tool generation is done using json configuration files located at [source/Nuke.Common/Tools](https://github.com/nuke-build/nuke/tree/develop/source/Nuke.Common/Tools). The schema is linked at the top where most of the options are documented. The schema is not 100 % correct and some options are obsolete or unused but you can get an idea on how to configure tools by browsing through existing tools.
