### ISSUE TITLE
Tools dynamic install/download package.

### ISSUE THREAD

**Issue by ricaun** [nuke-build/nuke#1488]
### Description

Hello 

When I started messing the Tools I thought that nuke gonna download the tool if necessary, but that does not happen at least in nuke version `8.*`.

I was experimenting to forcing downloading the tools on the fly without the need to add `<PackageDownload Include="NuGetKeyVaultSignTool" Version="[3.2.3]" />` in the nuke project.

Using `DotNetTasks.DotNetToolInstall` is possible to install the package in a temporary folder and use the `.exe` in as the path for the tool.

Here is a full sample using nuke version `8.*`, should work in version `9.*` with some minor changes.

```c#
private static void DownloadNuGetKeyVaultSignTool()
{
    try
    {
        _ = NuGetKeyVaultSignToolTasks.NuGetKeyVaultSignToolPath;
    }
    catch (Exception)
    {
        var toolFolder = GetToolInstallationPath();
        var packageId = NuGetKeyVaultSignToolTasks.NuGetKeyVaultSignToolPackageId;

        if (Globbing.GlobFiles(toolFolder, $"{packageId}.exe").FirstOrDefault() is AbsolutePath packageToolPathExists)
        {
            Environment.SetEnvironmentVariable(packageId.ToUpper() + "_EXE", packageToolPathExists);
        }

        DotNetTasks.DotNetToolInstall(x => x
            .SetPackageName(packageId)
            .SetToolInstallationPath(toolFolder)
        );

        if (Globbing.GlobFiles(toolFolder, $"{packageId}.exe").FirstOrDefault() is AbsolutePath packageToolPath)
        {
            Environment.SetEnvironmentVariable(packageId.ToUpper() + "_EXE", packageToolPath);
        }
    }

    _ = NuGetKeyVaultSignToolTasks.NuGetKeyVaultSignToolPath;
}
```

I only tested with `NuGetKeyVaultSignTool` and `AzureSignTool`, but I believe will work with any tool that require the `PackageDownload `.

Something like that would be a great addiction, maybe download by default if needed or an utility class/method.

Let's discuss.

### Could you help with a pull-request?

Yes

**Comment by matkoch** [comment]
Something like that is already implemented. See `RequiresAttribute` for the build class, and `Requires<T>` on target definitions. It's restoring to the global nuget cache though.

**Comment by ricaun** [comment]
Interesting using `NuGetPackageRequirement` attribute.
https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Build/Execution/ToolRequirementService.cs

Maybe that works...

**Comment by ricaun** [comment]
> Something like that is already implemented. See `RequiresAttribute` for the build class, and `Requires<T>` on target definitions. It's restoring to the global nuget cache though.

After adding `Requires` works for the require tool, but the other tools stop working for some reason.
```C#
 Target AzureSignTool => _ => _
     .TriggeredBy(Clean)
     .Before(Compile)
     .Requires<AzureSignToolTasks>()
     .Executes(() =>
     {
         Serilog.Log.Information(AzureSignToolTasks.AzureSignToolPath);
     });
```

**Comment by matkoch** [comment]
this is a _one or the other_ decision. `NuGetPackageResolver` uses bare XML parsing (instead of MSBuild) infrastructure. Hence it will only see packages added to `.nuke/temp/nuget.csproj`. One of the reasons why this is not documented.

**Comment by ricaun** [comment]
> this is a _one or the other_ decision. `NuGetPackageResolver` uses bare XML parsing (instead of MSBuild) infrastructure. Hence it will only see packages added to `.nuke/temp/nuget.csproj`. One of the reasons why this is not documented.

In my case I need to add the other tools like this:

```C#
 Target AzureSignTool => _ => _
     .TriggeredBy(Clean)
     .Before(Compile)
     .Requires<AzureSignToolTasks>()
     .Requires<GitVersionTasks>()
     .Requires<NuGetTasks>()
     .Executes(() =>
     {
         Serilog.Log.Information(AzureSignToolTasks.AzureSignToolPath);
     });
```

Yes I noticed the file `nuget.csproj` is created, but in my case I don't think `Requires` gonna work. Only because the others tools need to be require as well.

Install only if the tool will be used would be better to prevent problems.

Using `DotNetTasks.DotNetToolInstall` is the way.
```C#
DotNetTasks.DotNetToolInstall(x => x
    .SetPackageName(packageId)
    .SetToolInstallationPath(toolFolder)
);
```

**Comment by matkoch** [comment]
i'm not sure what you're talking about... tools will only be restored if either the build requires them (globally) or a target (locally).

**Comment by ricaun** [comment]
> i'm not sure what you're talking about... tools will only be restored if either the build requires them (globally) or a target (locally).

I kinda want to use a tool on the fly, without have the configuration in the project.

Run `AzureSignToolTasks.AzureSignTool` and the tool downloads if not installed.

**Comment by matkoch** [comment]
i'm very much against promoting that idea because it would require `SetVersion` on each invocation to be fully deterministic, plus, download times would contribute to target execution times

**Comment by ricaun** [comment]
> i'm very much against promoting that idea because it would require `SetVersion` on each invocation to be fully deterministic, plus, download times would contribute to target execution times

Yes, you are right, gonna make some tests with `Requires`. That's the intended way.

Thanks, appreciate the help!
