### ISSUE TITLE
Installing Nuke on zsh in MacOS

### ISSUE THREAD

**Issue by tiagodenoronha** [nuke-build/nuke#149]
Good afternoon,

I tried installing nuke on zsh within the VSCode terminal, it came back as installed, but I didn't manage to get it working...

![image](https://user-images.githubusercontent.com/27889458/45882278-944b0c80-bda5-11e8-8094-14524ab98870.png)

Was it something I did wrong on my end?
Thanks!

**Comment by matkoch** [comment]
This is a zsh issue. You need to adapt your `.zshrc` configuration. I've got `export PATH=$HOME/.dotnet/tools:$PATH` at the beginning.

**Comment by tiagodenoronha** [comment]
Thanks! Able to run nuke now but it's giving me an error with not finding the nuget packages, want me to message you on twitter or something with this instead of opening a new issue?

**Comment by matkoch** [comment]
Sure, you should be able to message me via @matkoch87, or join our slack workspace / gitter channel :)
