### ISSUE TITLE
Cannot install resharper extension

### ISSUE THREAD

**Issue by pwm1234-sri** [nuke-build/nuke#1497]
### Usage Information

Nuke 9.0.3/dotnet 9.0.101/Windows 11

### Description

I have Resharper 2024.3.20241113.1046 (update available: 2024.3.2) installed in Visual Studio Version 17.12.3 and have downloaded the nuke resharper extension nupkg file ReSharper.Nuke.Community.2024.3.0.nupkg

### Reproduction Steps

I have downloaded the nuke resharper extension nupkg file ``ReSharper.Nuke.Community.2024.3.0.nupkg``. I followed the instructions for configuring the resharper extension manager so the directory containing this nupkg file is the only available extension source that is checked. I do not have this problem with a .nupkg file that I downloaded from plugins.jetbrains.com, so I believe the problem is that the resharper extension manager does not recognize ReSharper.Nuke.Community.2024.3.0.nupkg as a supported plugin. 

### Expected Behavior

That ReSharper.Nuke.Community.2024.3.0.nupkg shows up as an extension to install.

### Actual Behavior

ReSharper.Nuke.Community.2024.3.0.nupkg is not listed as an extension to install.

### Regression?

I don't know how to try a previous extension. 

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
2024.3.1

**Comment by pwm1234-sri** [comment]
Thanks for the update. The resharper extension provides me with only "Run without dependencies" (and it does not seem to do anything). The Debug and Debug without dependencies actions are missing.

![image](https://github.com/user-attachments/assets/98abe484-4f13-479b-b06c-db1461442fc0)
