### ISSUE TITLE
Wrong .NET Core SDK is downloaded

### ISSUE THREAD

**Issue by arodus** [nuke-build/nuke#155]
Format of the json changed, we should use https://github.com/dotnet/core/blob/new-json/release-notes/releases-index.json instead.
https://github.com/dotnet/announcements/issues/87

**Comment by matkoch** [comment]
## Description

The format of the `release.json` file has been changed (https://github.com/dotnet/announcements/issues/87), which we used to resolve the _latest version_ for .NET Core SDK. This results in the behavior that a possibly wrong/old version of the SDK could be downloaded. According to the bootstrapping templates (https://github.com/nuke-build/nuke/blob/0.11.1/source/Nuke.GlobalTool/templates/build.netcore.ps1#L37-L61), there are two requirements for the problem to appear:

1. There is no `global.json`
2. There is no local installation of the SDK

Given these points, it's very likely that the issue appears on CI build servers.

## Temporary workaround

We're not sure yet how we're going to solve this issue. Trying to work things out with the dotnet team. Meanwhile you can either create a `global.json` file, as we do (https://github.com/nuke-build/nuke/blob/develop/global.json), or follow the current approach of using a static default version (https://github.com/nuke-build/nuke/compare/feature/fix-dotnet-version).
