### ISSUE TITLE
Is running without the global tool a supported scenario?

### ISSUE THREAD

**Issue by ljani** [nuke-build/nuke#161]
I just discovered this project, I like the very core of this system. However, I'm not a big fan of the global tool `Nuke.GlobalTool`. Thus I'm asking is using `Nuke.Core` directly in a project a supported scenario? It works now, but will it work in the future? I'm asking, because the website only talks about the global tool.

To clarify, I have a `MyProject.Build.csproj` project, which contains the following references:

```xml
<ItemGroup>
    <PackageReference Include="Nuke.Core" Version="0.2.10" />
    <PackageReference Include="Nuke.Docker" Version="0.2.0" />
</ItemGroup>
```

Then I'm just defining the entrypoint as shown in the [getting started guide](https://nuke.build/getting-started.html) and it all works when I do the following:

```sh
git clone my-project
cd my-project/MyProject.Build
dotnet run
```

I especially like the way there's no need to install any additional tools and my build is already running after it compiles.

I haven't investigated what the global tool provides over this setup, I only found out it added a lot of cruft to my project. :) Have you considered having [a per-project tool](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility#consuming-per-project-tools) as an alternative way to invoke `nuke` (ie. `dotnet nuke ...`), if there's anything I'm going to miss with the way I'm (ab)using Nuke? In other words, a per-project tool is a tool installed via `DotNetCliToolReference`.

Thank you for your work!

**Comment by arodus** [comment]
Hi ljani,
at first make sure to not use `Nuke.Core` but `Nuke.Common`. The `Nuke.Core` package is deprecated.

There is no need to install the global tool besides for the initial setup.
The setup creates a build script for bash and PowerShell which just can be executed on any machine even if the dotnet SDK is not installed.
The build script ensures that the correct dotnet SDK is installed and downloads it if it wasn't found. Afterwards it also just executes `dotnet run`.

It's also possible to install the global tool in a custom directory. So, you can "install" it invoke the setup and just delete it when you are finished.

Personally, I'm not a big fan of the per-project-tools. You have to execute the tool from within the project directory which doesn't scales well in big solutions. What's the advantage of using it as a per-project-tool?

**Comment by ljani** [comment]
> The Nuke.Core package is deprecated.

Ah, thanks for the info! Maybe add a mention of deprecation to [the nuget package](https://www.nuget.org/packages/Nuke.Core/)?

> The build script ensures that the correct dotnet SDK is installed and downloads it if it wasn't found.  Afterwards it also just executes dotnet run.

This sounds very promising! I can rely on dotnet being installed, because we're a dotnet shop after all and thus I'd like to minimize anything unnecessary. `dotnet run` has a clear intent that everything is in the `.cs` files.

> What's the advantage when using it as a per-project-tool?

I edited my original question a little to clarify this. I do prefer running `dotnet run` to a per-project tool, but I was just asking, if there's anything I'm missing, because I'm not using the global tool or the additional scripts. As you mentioned, these only add the bootstrapping functionality, so I think I'm not missing anything and thus there's no point having a per-project tool. I love how `dotnet run` covers everything!

As a side note, you are probably aware of the templates for bootstrapping a project in dotnet, right?

**Comment by matkoch** [comment]
Just a few additional notes:

- You've been creating the build project by yourself, including adding the reference to `Nuke.Core`, right? Afaik, there is no mention of this package anywhere, and it's also not part of our template generated by the global tool.
- Using the bootstrapping scripts (ps1/sh) along with the global tool currently allows executing the build from any directory below the root directory, which is kind of convenient I guess. Also at some point we will integrate parameter completion into the global tool, which would allow tabbing to complete terms like `-tar` to `-target` and so on. However, it's not a requirement for sure.

**Comment by ljani** [comment]
> You've been creating the build project by yourself, including adding the reference to Nuke.Core, right? 

Yes, it was my mistake. I did start by exploring Nuget and found the package. I thought Core contained runner and Common had some stuff shared between the runner and other packages. I did wonder why `Nuke.Core` did not reference `Nuke.Common`, heh.

> Using the bootstrapping scripts (ps1/sh) along with the global tool currently allows executing the build from any directory below the root directory, which is kind of convenient I guess. Also at some point we will integrate parameter completion into the global tool, which would allow tabbing to complete terms like -tar to -target and so on.

Sure, I agree that this is convenient and I'm all for providing additional tooling for better experience. But my use cases tend to be simple and thus I'm aiming for a simple solution. Similarly I'm using `npm` over `yarn` in many projects, because `npm` gets the job done and there is no need for the features provided by `yarn`.

> However, it's not a requirement for sure.

Please keep it this way! 👍
