### ISSUE TITLE
Cannot execute gitversion on MACOS

### ISSUE THREAD

**Issue by HotdogWang** [nuke-build/nuke#163]
Hi,

I just init nuke build on my Project, and try to using gitversion to add build number for my lib.
Then I got below two issues.

1. I manually add `path '~/.dotnet/tools'` to my environment path, then every time I run nuke build will get environment path warning.

2. As I know, MacOS needs to depend  mono to run gitversion.
But when I run nuke build in terminal will got error.
```
Process 'mono' exited with code 1. Verify the invocation.
> /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /Users/beck.wang/.nuget/packages/gitversion.commandline/3.6.5/tools/GitVersion.exe
```
The strange thing is run below command is OK.
```
/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /Users/beck.wang/.nuget/packages/gitversion.commandline/3.6.5/tools/GitVersion.exe
```
![2018-11-02 6 39 38](https://user-images.githubusercontent.com/12172172/47910860-12cfb980-decf-11e8-9869-18a479512703.png)

Please help to look.
Thanks.

**Comment by arodus** [comment]
You have to add the following line to your build.sh
https://github.com/nuke-build/nuke/blob/develop/build.sh?l23#L33

Also make sure the global tool path exists and is readable by Nuke.

**Comment by arodus** [comment]
Regarding the `inaccessible path...` warning. Afaik using `~` isn't supported. Try using `$HOME/.dotnet/tools`.

**Comment by HotdogWang** [comment]
Hi Arodus, 
Thanks for your reply.

For `inaccessible path..` I already check my environment path is 
`export PATH=$HOME/.dotnet/tools:$PATH` why it will display `~` QQ

For mono issue, it doesn't work for me after add that line.
I still look for solution and try. 😀

**Comment by arodus** [comment]
> For inaccessible path.. I already check my environment path is
export PATH=$HOME/.dotnet/tools:$PATH why it will display ~ QQ

See #165

> For mono issue, it doesn't work for me after add that line.

Could you please share the output of `which mono`
and `ls -ld $(dirname $(which mono))/../lib/mono`

**Comment by matkoch** [comment]
@HotdogWang 

This warning is shown because neither `$var` nor `~` is expanded when calling `Environment.ExpandEnvironmentVariables`. I've created #165.

As for the mono/gitversion issue. https://github.com/nuke-build/nuke/blob/develop/build.sh?l23#L33 isn't going to help here. It is used for compilation of projects targeting `netxx`. Are you sure that there is a git repository initialized?

**Comment by HotdogWang** [comment]
@matkoch 
Sorry for late to reply.
Are you mean that is my project already init with git?
This is answer is sure!

I add the line into build.sh and echo the path.
![image](https://user-images.githubusercontent.com/12172172/48186746-f242ac00-e373-11e8-97ab-6513c2a329c5.png)

Then I also make sure I have mono file in that path.
But I still got the same issue.
Seems path doesn't be override, right?
![image](https://user-images.githubusercontent.com/12172172/48186891-51a0bc00-e374-11e8-9a8f-35fdbd6e0ced.png)

**Comment by matkoch** [comment]
Could you please paste the output of `/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /Users/beck.wang/.nuget/packages/gitversion.commandline/3.6.5/tools/GitVersion.exe`

**Comment by HotdogWang** [comment]
Here is the out put I manually run 
`/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /Users/beck.wang/.nuget/packages/gitversion.commandline/3.6.5/tools/GitVersion.exe`

<img width="1059" alt="screen shot 2018-11-09 at 10 38 59 am" src="https://user-images.githubusercontent.com/12172172/48240092-734d8200-e40c-11e8-9ebb-e208bb5b9a34.png">

**Comment by arodus** [comment]
It seems like the problem lies within gitversion. I think it has a problem with the current state of your repository. Could you try running it again in a clean repository?
