### ISSUE TITLE
Bug in Arguments.cs

### ISSUE THREAD

**Issue by hayhay27** [nuke-build/nuke#170]
Secret's value falls in customValue argument:
https://github.com/nuke-build/nuke/blob/6787fedf3abd411ed1f98b18174ebd7fb465b34a/source/Nuke.Common/Tooling/Arguments.cs#L45

Signature:
https://github.com/nuke-build/nuke/blob/6787fedf3abd411ed1f98b18174ebd7fb465b34a/source/Nuke.Common/Tooling/Arguments.cs#L48-L53

**Comment by matkoch** [comment]
That's a nasty bug, thanks for reporting. How did you notice?

**Comment by hayhay27** [comment]
Just extending ToolSettings for SonarQube tool I looked under hood

**Comment by matkoch** [comment]
Just to make sure, do you know that we use code generation to add support for CLI tools?

**Comment by hayhay27** [comment]
Yes, I know. From dotnext video. But forgot. Sometimes, it's not so bad)
