### ISSUE TITLE
Overriding Configuration at runtime?

### ISSUE THREAD

**Issue by LordMike** [nuke-build/nuke#171]
Hey, is it possible to override the `Configuration` at runtime?

We want to decide between `Release` and `Debug`, depending on if the CI is building a Tagged commit. We're using `GitVersion` to do the assembly versioning, and it already has logic to add pre-release versions if we're doing untagged builds - now we'd like the Configuration to match this logic :)

**Comment by matkoch** [comment]
For a few versions, `Configuration` is no longer provided from the `NukeBuild` base class. So you can just implement it the way you want it. Does that answer the question?

**Comment by LordMike** [comment]
I'm simply out of date? :O

**Comment by LordMike** [comment]
https://nuke.build/getting-started.html#predefined-properties is out of date then.
