### ISSUE TITLE
Solution Attribute updates

### ISSUE THREAD

**Issue by LordMike** [nuke-build/nuke#172]
Hey,

Following an update to 0.11.x, I'm told the Solution Attribute will no longer find the solution file given a .nuke file. Is there a way to get the `Solution` instance, in a base class?

So what we have, is a base class for all our Nuke builds, which has the Solution on it. This Base does not know about the actual solution file for a project. I also cannot, because it's an attribute, get the Solution file in a constructor and then pass it to the attribute.

I suppose I could override the Solution in the base class, so I can attribute it with the known solution file at that point, but it seems odd :P.

A very short example here -- the two classes are also in seperate assemblies.

```csharp
public class OurBase : NukeBuild
{
    [Solution] public readonly Solution Solution;
}

public class SomeConcreteBuildProject : OurBase
{
    ... use Solution
}
```

**Comment by matkoch** [comment]
Currently it still resolves from the .nuke file, and I think we’re going to keep it this way. Just need to remove the Obsolete attribute.

**Comment by matkoch** [comment]
By the way, you can pass the solution file also from the command line. Parameter name is the same as the field being attributed. Just check `nuke —help`.
