### ISSUE TITLE
build.ps1, Ctrl+C closes window

### ISSUE THREAD

**Issue by LordMike** [nuke-build/nuke#173]
It seems the Nuke build.ps1 closes the Powershell window when canceled (Ctrl+C).

For example:

* In a new PS window, running a command and cancelling **does not** close the window
* In a new PS window, running `.\build.ps1` and cancelling **does** close the window

This is minorly inconvenient, as I will iterate on builds quickly a number of times, meaning I'd run the build script, do a change, cancel the build, re-do the build etc.. But the cancelling step means I have to reopen my PS window :P

**Comment by matkoch** [comment]
I currently don’t have any time to investigate this. It’s probably to do with the trap declaration in build.ps1, which should ensure that the script is exited with non-zero whenever something bad happens. I don’t remember the details, but you’re welcome to raise a PR.

FYI, the global tool can also invoke the build.
