### ISSUE TITLE
Update Glob version

### ISSUE THREAD

**Issue by Bacon-Pancake** [nuke-build/nuke#177]
Glob 0.3.2 contains a bug where the full path is being used for pattern matching.

This causes unexpected behaviour when the root path contains part of that pattern.

Example:
`GlobFiles(@"c:\src\foo", "src/**/*.cs");`
Absolute : `c:\src\foo\bar\example.cs`

Expected behaviour: should not match
Actual behaviour: does match

See [https://github.com/kthompson/glob/commit/6b5e09907ec51abfb6332cac9e763d978f23f417#diff-d2b12e2da004eedc848270948268b7c4](https://github.com/kthompson/glob/commit/6b5e09907ec51abfb6332cac9e763d978f23f417#diff-d2b12e2da004eedc848270948268b7c4)

**Comment by RaringCoder** [comment]
There are other issues caused by this version too, such as not honouring the zero or more directory pattern `**`, or the comma-delimited literals `{Tests,Specs}`.
