### ISSUE TITLE
the --Help parameter throws an assertion exception

### ISSUE THREAD

**Issue by robsonj** [nuke-build/nuke#183]
If I do not have a .nuke file and supply only the help parameter (--help), I do not receive any help, instead I get the following stack trace...

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Nuke.Common.NukeBuild' threw an exception. ---> System.Exception: Assertion failed: Could not locate '.nuke' file while walking up from working directory 'C:\Source\coredev\applications\SharedLibraries'.
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.NotNull[T](T obj, String text)
   at Nuke.Common.NukeBuild.GetRootDirectory()
   at Nuke.Common.NukeBuild..cctor()
   --- End of inner exception stack trace ---
```

**Comment by robsonj** [comment]
Was this issue fixed in 0.12.2? it still appears to be an issue, at least when running as a global tool

**Comment by matkoch** [comment]
True, but just saying: the only thing we can improve here is the error message. Telling that no .nuke file was found, and —root should probably be passed.

**Comment by robsonj** [comment]
That would be better than the assert tbf. Currently someone needs to know how to use Nuke in order to get help on how to use Nuke.
