### ISSUE TITLE
What's the purpose of the `.tmp` directory?

### ISSUE THREAD

**Issue by LordMike** [nuke-build/nuke#184]
I've noticed `.tmp` is created whenever Nuke is run - and it contains some Nuke related stuff in addition to some targets and more.

- Should this file be checked in? 
- Deleted? 
- Ignored? 
- Should we ignore .tmp entirely? 
- Can its location be customized?

**Comment by matkoch** [comment]
The content of the `.tmp` directory is not intended to be checked in. The assumption is that `.gitignore` and similar files have an entry for `*.tmp` already. The location is currently not customizable, is there a specific need for that?

**Comment by LordMike** [comment]
No specific need. I was wandering what to do with it.

I've added `.tmp/` to our ignores.
