### ISSUE TITLE
NuGetPath error: Assertion failed: !IncludesDependencies

### ISSUE THREAD

**Issue by lt-gerjan** [nuke-build/nuke#185]
It seems Nuke cannot find my nuget.exe. when using `NuGetTasks.NuGetPack` I am getting:

```
System.Exception: 'Assertion failed: !IncludesDependencies([path]\build\nuke\packages.config) || includeDependencies'
```

So I try to debug it and the problem is the property `NuGetTasks.NuGetPath;` 

In the code I see that it checks for a environment variable or else tries to download it (?).  See:
https://github.com/nuke-build/nuke/blob/b9a08b5ddf2262e5455fb1617880e467256618e8/source/Nuke.Common/Tools/NuGet/NuGet.Generated.cs#L27

My attempt to workaround this issue by doing:

```Csharp

Environment.SetEnvironmentVariable("NUGET_EXE", @"D:\tools\NuGet.exe");
--or
EnvironmentInfo.SetVariable("NUGET_EXE", @"D:\tools\NuGet.exe");

```

Somehow it will not pick this up, can I set the tool explicitly? I just want to point it to the right location, but I do not want to permanently set the ENV variable

**Comment by matkoch** [comment]
Are you using the legacy format during setup? If yes, why?

**Comment by lt-gerjan** [comment]
What is legacy format? .NET framework? I want to use the NuGet tool to do some custom packing stuff

**Comment by matkoch** [comment]
Sorry, I meant MSBuild bootstrapping (in contrast to .NET Core). See here https://nuke.build/docs/getting-started/setup.html

**Comment by lt-gerjan** [comment]
I have a large repository with mixed projects (.NET Core and .NET framework). I am not sure what I selected during setup, does it matter? Can I check what I selected?

**Comment by matkoch** [comment]
For this issue it does matter, yes. Please check the note at the end of the linked article. To answer the question about setting the tool path, they can be changed ad-hoc via `SetToolPath`. In general, I think you should add `NuGet.CommandLine` as a package reference. With SDK based project, you will probably see that message.

**Comment by lt-gerjan** [comment]
Okay, I migrated to .NET Core and it seems to fix it 👍

**Comment by lt-gerjan** [comment]
Hm, now I have a lot more other issues, for example `GlobFiles` does not return anything anymore

**Comment by matkoch** [comment]
I think I will change two things:

- Change setup to not ask about .NET Core /  MSBuild, because most folks get this the wrong way. But provide a `--legacy` switch, which will allow to opt-in.
- Remove that assertion all along.

Regarding your other questions, please create a new issue or swing by at our slack channel!
