### ISSUE TITLE
Create zip file 

### ISSUE THREAD

**Issue by LucaGabi** [nuke-build/nuke#187]
Hi, 

   Great project! How can I create a zip file or archive in one of the tasks ?

Thanks.

**Comment by GeorgDangl** [comment]
You can take a look at this:
https://github.com/Dangl-IT/Dangl.AVACloudClientGenerator/blob/develop/build/Build.cs#L124-L137

Essentially, I just use the framework classes to do this:

    System.IO.Compression.ZipFile.CreateFromDirectory(outputPath, outputPath.ToString().TrimEnd('/').TrimEnd('\\') + ".zip");
