### ISSUE TITLE
Execute external tool

### ISSUE THREAD

**Issue by LucaGabi** [nuke-build/nuke#190]
Hi,

   Is there a way to execute external commands/tools? Should one do it with Proccess class ? 

Thanks.

**Comment by lt-gerjan** [comment]
Please see

http://www.nuke.build/docs/authoring-builds/cli-tools.html
Check `[PathExecutable]` or `[PackageExecutable]`

Or to do it manually:

http://www.nuke.build/api/Nuke.Common/Nuke.Common.Tooling.ProcessTasks.html
