### ISSUE TITLE
Paket and GitVersion

### ISSUE THREAD

**Issue by Liminiens** [nuke-build/nuke#192]
It looks like a change https://github.com/nuke-build/nuke/commit/b7b76c6c8d7304e9921ba6b42c8fd44b300d2b01#diff-6d97f850f2742445eea7c48c99291580L29 broke GitVersion resolving when using Paket. Before it also looked up for the package at `<sln>/packages/GitVersion../GitVersion.exe` via `ToolPathResolver.GetPackageExecutable` at https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tooling/PaketPackageResolver.cs#L19.

Now it only searches via `NuGetPackageResolver` at https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/GitVersion/GitVersionTasks.cs#L45.

**Comment by Liminiens** [comment]
@matkoch should I open a pr where I am aiming to fix this with [Paket API](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PublicAPI.fs) ? :)

**Comment by matkoch** [comment]
PR is welcome. I'm currently thinking of another method `ToolPathResolver.TryGetPackageExecutable`, similar to other methods in `NuGetPackageResolver.TryXxx`, but no exact thoughts here (and no time). I'd prefer not to do a partial fix in `GitVersionTasks`. For your own code, you can use `SetToolPath` meanwhile.

**Comment by matkoch** [comment]
@Liminiens 	sorry for the late response. This should be solved with https://github.com/nuke-build/common/commit/a84642f6ce86852e7389fe5a3e1b9f8e107e413e#diff-6d97f850f2742445eea7c48c99291580
