### ISSUE TITLE
Warning on having Build configuration for build.csproj

### ISSUE THREAD

**Issue by Liminiens** [nuke-build/nuke#201]
Now Nuke expects that there is no `Build` configuration for the build project in `.sln` file, so it won't try to build itself and hang on copying. It would be good to have a warning if such configuration exists for the `.build.csproj`.

**Comment by Liminiens** [comment]
Related api: https://github.com/Microsoft/msbuild/blob/master/src/Build/Construction/Solution/SolutionFile.cs

**Comment by matkoch** [comment]
Any thoughts if this should be done independently from `SolutionAttribute`? For instance, we could spin off a background thread, that collects all `*.sln` files (warn if too many), and check available configurations. Otherwise, we rely on the fact that the `SolutionAttribute` is being used.

**Comment by Liminiens** [comment]
Yes, I think that we can use the path from `SolutionAttribute` and add warning somewhere here after [InjectionService.InjectValues](https://github.com/nuke-build/nuke/blob/b431ce6d121f0d40c8ab882e97577974c664b5d7/source/Nuke.Common/Execution/BuildExecutor.cs#L49). Otherwise search from the root for all `.sln` files and take first with build project in it. But I don't know how slow `sln` parsing is, yet.

**Comment by Liminiens** [comment]
@matkoch should it be done just as warning now, without any changes to `SolutionAttribute` and friends?

**Comment by matkoch** [comment]
My preferred approach would be to look for all solution files, parse them, and check build configurations. Probably using `Assembly.GetExecutingAssembly` or something. Solution parsing is available in another PR, which is in turn just blocked because tests are still running netfx instead of netcore.

**Comment by Liminiens** [comment]
so what needs to be done to fix tests? :)
