### ISSUE TITLE
Less opinionated IDE settings

### ISSUE THREAD

**Issue by jnm2** [nuke-build/nuke#210]
Working with IDE defaults would be a selling point for Nuke from my perspective. I want the build project to look and feel like a normal C# project, fitting in with the rest of the repository.

This is the current default .editorconfig:

```ini
[*.cs]
dotnet_style_qualification_for_field = false:warning
dotnet_style_qualification_for_property = false:warning
dotnet_style_qualification_for_method = false:warning
dotnet_style_qualification_for_event = false:warning
dotnet_style_require_accessibility_modifiers = never:warning

csharp_style_expression_bodied_properties = true:warning
csharp_style_expression_bodied_indexers = true:warning
csharp_style_expression_bodied_accessors = true:warning
```

`dotnet_style_require_accessibility_modifiers` doesn't match the existing projects and root editorconfig in my repo. `csharp_style_expression_bodied_accessors` happens to align with my preferences, but the `:warning` is too opinionated for me.

Now, what if none of these, including `csharp_style_expression_bodied_indexers`, were even specified? That way:

- If the user hasn't put any thought into it, they'll get IDE defaults and match the rest of the projects in their repo (a great thing).
- If the user has put thought into it and set a setting to a conflicting value like `csharp_style_expression_bodied_properties = false`, they will probably want to keep the build project in line with that.

The reason why I value keeping the style consistent is that what's generally good for any C# project is exactly what I expect to be good for the build project. I'm turning to Nuke because I need something that easily scales in complexity, unlike a ten-line script. Because of this, I want to follow practices such as code style that work at scale.

Maybe the setup tool could ask the user whether they want to match the style of the other projects or add the overriding files to make the build project look and feel more scripty than the rest of the projects?

**Comment by matkoch** [comment]
https://nuke.build/docs/getting-started/setup.html#note-2

**Comment by jnm2** [comment]
> For maximum readability, NUKE prefers certain code formatting settings. For example, these include to omit accessibility modifiers and use expression-bodied properties. In case the build project should look like any other project, the two files .editorconfig and .dotsettings may simply be removed.

Fair enough. The demand isn't high, so I can continue deleting the files after setting up.
