### ISSUE TITLE
Read obj/project.assets.json instead of parsing ProjectReference elements

### ISSUE THREAD

**Issue by jnm2** [nuke-build/nuke#211]
This could bring greater flexibility with things like putting versions in Directory.Build.props with `<PackageReference Update="`, etc.

**Comment by matkoch** [comment]
I guess this is going to be a wont-fix, as the current approach also supports to resolve packages from un-restored projects. Are there downsides?

**Comment by jnm2** [comment]
Yes, but let's wait until there's a more specific need, such as https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-packages-and-versions#how-to-enable-this-feature.

Is there any harm in autorestoring if no `project.assets.json` exists?
