### ISSUE TITLE
Short form for parameters

### ISSUE THREAD

**Issue by jnm2** [nuke-build/nuke#216]
It would be nice to be able to specify a second short form for each parameter, such as `-c` and `--configuration`. Defaulting a short form when the first letter is unique might even make sense, possibly?

**Comment by lt-gerjan** [comment]
I had the same request on Slack, so 👍

**Comment by matkoch** [comment]
How would you deal with a situation when the first character _was_ unique, but became ambiguous?

**Comment by lt-gerjan** [comment]
That ambiguity came because a developer added a parameter property with the same first letter right?

I think I would generate/log a warning. You might throw a hard exception (which crashes Nuke or prevent it from starting, if thats possible) but that seems a bit too harsh

**Comment by jnm2** [comment]
Yes; any time the developer adds or changes parameters, it's up to the them to know and test the scenarios they care about. What's the worst-case scenario? Having to edit Build.cs an extra time?

**Comment by matkoch** [comment]
The issue I’m having is that currently there is no warning or error issued, if a parameter is not bound to a field/property. For instance, you could pass `—foo bar` without actually having a member `foo`. I’m not sure if I’m ready to change this behavior at this point.

**Comment by jnm2** [comment]
Can we separate that part out and enable you to opt into a short form on a case-by-case basis?
