### ISSUE TITLE
Windows Explorer interferes with EnsureCleanDirectory

### ISSUE THREAD

**Issue by ItEndsWithTens** [nuke-build/nuke#217]
As per my comment on [this issue](https://github.com/ItEndsWithTens/Arbatel/issues/1), I'm migrating this info from my own project.

## Expected
A Windows Explorer window, displaying the content of a directory that gets passed as the argument to EnsureCleanDirectory during a build, has no impact on the cleaning of said directory.

## Actual
That Explorer window causes the directory in question to be deleted but not recreated.

## Environment
Windows 10, version 1809
Nuke 0.15.0
Visual Studio 2017, version 15.9.5
PowerShell 5.1.17763.134

I first encountered this in a .NET Framework project, but I can successfully reproduce the behavior with a fresh .NET Core console app created from Visual Studio, after initializing with `nuke :setup`. It happens whether I run the PowerShell build script or execute the build from within Visual Studio.

## Steps
1. In any project using Nuke, set a breakpoint on a line of code that calls EnsureCleanDirectory. Begin debugging.
2. Once the debugger hits that breakpoint, open Windows Explorer and navigate to the directory that's about to be cleaned. Leave the window open during the next step.
3. Back in the debugger, step over the EnsureCleanDirectory call. Explorer should refresh, and at the same time bump you up one level, showing that the directory that was cleaned has disappeared.

Repeating those steps but leaving Explorer one level up from the directory to be cleaned, or displaying any other folder, lets the process work as expected. The issue also appears when simply running a build script, outside a debugger, but this demonstrates that the call to EnsureCleanDirectory is where things go wrong.

## Remarks
Looking at the other issues here, #127 seems to be related (maybe identical, but I thought a new issue would be preferable over reopening an old one; correct me if I'm wrong). According to that issue, EnsureCleanDirectory calls Directory.Delete, which in turn calls Windows' native [RemoveDirectory](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-removedirectorya) function. To quote its documentation:
>The RemoveDirectory function marks a directory for deletion on close. Therefore, the directory is not removed until the last handle to the directory is closed.

With an Explorer window viewing the directory, I take it there's still an open handle, and I'd venture a guess that the call to recreate the directory happens before Windows can close that handle and delete the folder.

I am unfortunately not terribly experienced with regard to native Windows APIs, or their interaction with C#, so I couldn't personally offer any suggestions for a fix. Currently I work around it by [calling EnsureExistingDirectory](https://github.com/ItEndsWithTens/Arbatel/blob/39e6cc6a5154565e3e96c14b221c8ce43638ebb6/build/Build.cs#L241), and that does the trick, as strange as it may look.

**Comment by matkoch** [comment]
I assume this should fix it, would you agree?

https://github.com/nuke-build/common/commit/f556158cd88e5c973735563bddd7b4163bb16d02

**Comment by ItEndsWithTens** [comment]
I'm back to be annoying again! Hopefully this comment won't reopen the issue (I can never remember how Github handles comments on closed items), since I just want to add some information.

I've been using 0.16.0 for a bit now, and I thought it was doing the trick, but while it solved the immediate issue I was having here, I've come to realize today that it's ultimately just kicked the can down the road a bit: having subdirectories of EnsureCleanDirectory's target folder open in Windows Explorer will cause similar problems, since they get deleted too. They don't get recreated, but I assume that subdirectories are deleted first and higher levels afterwards, the problem becoming the fact that the deletion of a given subdirectory isn't guaranteed to have finished before Nuke attempts to remove the next level up.

As an example, if I have bin/Debug/netstandard2.0 open in Windows Explorer, and I call EnsureCleanDirectory(bin) in a target, running that target will delete only netstandard2.0 and produce a "directory is not empty" message the first time. A second attempt will delete Debug and give "access denied". A third run will complete successfully.

The reason I say I hope this doesn't reopen the issue is only that it seems like a proverbial barrel of monkeys to fix:
- [This StackOverflow question](https://stackoverflow.com/questions/36384368/how-to-synchronously-and-consistently-delete-a-folder-on-ntfs-with-c-sharp) discusses the problem, but I don't know if I'd say any of the answers are simple or completely effective.
- I also found [an MSDN forum thread](https://social.msdn.microsoft.com/Forums/vstudio/en-US/a2fcc569-1835-471f-b731-3fe9c6bcd2d9/systemiodirectorydeletestring-path-bool-recursive-doesnt-seem-to-be-blocking-on-windows-7?forum=csharpgeneral) touching on the same thing, and as comforting as it is to see someone else experience the same slowly dawning horror I've been through, it links to [some very dispiriting documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.delete?view=netframework-4.7.2#System_IO_Directory_Delete_System_String_) that says, in part,
> In some cases, if you have the specified directory open in File Explorer, the Delete method may not be able to delete it.

Considering their shrugging off of the issue with "in some cases" and "may not", and the apparent complexity of the proposed solutions, I think what you did for 0.16.0 is reasonably effective, and I'm grateful for your effort! Hopefully this extra detail will be of some use to anyone who either has some inkling of a more reliable solution, or is just searching for some sort of workaround for their own project.
