### ISSUE TITLE
(Relative)Path property for PathExecutableAttribute

### ISSUE THREAD

**Issue by lt-gerjan** [nuke-build/nuke#218]
Like: `[PathExecutable(RelativePath = "Tools/tool.exe")]`

RelativePath is relative to `RootDirectory`
Maybe in the future you can add `AbsolutePath`

The following is not possible, sadly:
`[PathExecutable(Path = RootDirectory /  "Tools" / "CorFlags")]`

**Comment by matkoch** [comment]
Added as `LocalExecutableAttribute`.

**Comment by lt-gerjan** [comment]
https://github.com/nuke-build/common/commit/cc13e8283117dd3332d51c46d0dc28390447f789

Thank you
