### ISSUE TITLE
Add custom message to OnlyWhenX

### ISSUE THREAD

**Issue by lt-gerjan** [nuke-build/nuke#219]
Current API is: `ITargetDefinition OnlyWhen(params Func<Boolean>[] conditions);`

I propose: `ITargetDefinition OnlyWhen(params Func<Boolean>[] conditions, string message);`

So I can give a custom message about the requirement, that will be shown in the log/output

**Comment by matkoch** [comment]
Open question for me is, where to put those messages in output. In summary? How should it look?

**Comment by matkoch** [comment]
ping

**Comment by lt-gerjan** [comment]
Yes i think in the summary

**Comment by matkoch** [comment]
> How should it look?

**Comment by lt-gerjan** [comment]
To be honest, I do not use this feature ;) It was just a thought when I was exploring it via Intellisense. You can close this if you want

**Comment by ElijahReva** [comment]
@matkoch I'm using next approach to solve this right now. 
```
        protected Target CheckHelm => _ => _
            .OnlyWhenStatic(() => !CanPushHelm)
            .Executes(() => { Logger.Warn("Push Helm was skiped due to missing Registry URI"); });
```

IMO, ideally, we could change Func to expression and print automatically the whole expression with no need to explicit skip reason(like fluent-assertions do). Output could be probably logged with some special color before final status grid. Or maybe Something like this would be enough.
%'[{targetName}] [SKIPPED] {reason}
