### ISSUE TITLE
Add CopyDirectory / CopyFiles

### ISSUE THREAD

**Issue by lt-gerjan** [nuke-build/nuke#222]
In `FileSystemTasks` there is a `CopyDirectoryRecursively`, but I am missing a `CopyDirectory` or `CopyFiles` (same functionality). I want to copy all the files within a directory, not the children or anything

Personally I would make recursive a parameter, so:
`CopyDirectory(String source, String target, FileExistsPolicy policy = FileExistsPolicy.Fail, bool recursive = true)`

**Comment by matkoch** [comment]
What about `FileSystemTasks.CopyDirectoryRecursively` ?

**Comment by matkoch** [comment]
https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/IO/FileSystemTasks.cs#L224-L231

**Comment by lt-gerjan** [comment]
See my openings post. I do not see how I can "turn off" the recursiveness?

**Comment by matkoch** [comment]
Sorry, was only speed reading first. `FileSystemTasks.CopyDirectoryRecursively` has an `excludeDirectory` delegate, you can use that to exclude any child directory.

**Comment by lt-gerjan** [comment]
Yes, I saw that, but I think this is a nice API addition

**Comment by matkoch** [comment]
We can leave this issue open for vote, but I personally think it's too specialized.

**Comment by matkoch** [comment]
Another option is `files.ForEach(x => CopyFileToDirectory(...))`
