### ISSUE TITLE
Convert NukeBuild.Verbosity to MSBuildVerbosity 

### ISSUE THREAD

**Issue by lt-gerjan** [nuke-build/nuke#223]
```Csharp
    public MSBuildVerbosity MSBuildVerbosity
    {
      get
      {
        switch(NukeBuild.Verbosity)
        {
          case Verbosity.Verbose:
            return MSBuildVerbosity.Detailed; // or Diagnostic
          case Verbosity.Normal:
            return MSBuildVerbosity.Normal;
          case Verbosity.Minimal:
            return MSBuildVerbosity.Minimal;
          case Verbosity.Quiet:
            return MSBuildVerbosity.Quiet;
        }
        return MSBuildVerbosity.Minimal; // default
      }
    }
```

It would be nice that MSBuildSettings by default would pick this up

**Comment by lt-gerjan** [comment]
Be aware that `MSBuildVerbosity.Normal` is already very very detailed, probably this should convert to `Minimal`

**Comment by matkoch** [comment]
We considered that some time ago already, but not as a public discussion. The issue is, that this would be a _very_ opinionated approach. Even if you do want to have it, it's likely that it doesn't match your expectations. What I _would_ consider is an opt-in way. Say we can apply an attribute `AutoApplyToolVerbosity` on `Build`, which is then checked for existence in the `XxxSettings` classes, and if applied, will set verbosities by default. Contrary to your code snippet, I would still leave the properties settable.

**Comment by lt-gerjan** [comment]
Opt-in would be fine my me. Strictly tying the two together does not seem a good idea to me. You need/want to be able to override one of them.

Personally I have an option to override the MSBuild verbosity, because sometime you only want to have very detailed MSBuild log, and let Nuke Verbositoy the default.

My code snippet: 

```csharp

    [Parameter("Set the verbosity of MSBuild explicitly", Name = "msbuildverbosity")]
    public readonly MSBuildVerbosity MSBuildVerbosityParameter = null;

    public MSBuildVerbosity MSBuildVerbosity
    {
      get
      {
        if (MSBuildVerbosityParameter != null)
        {
          return MSBuildVerbosityParameter;
        }

        switch (Verbosity)
        {
          case Verbosity.Verbose:
            return MSBuildVerbosity.Detailed; // or Diagnostic
          case Verbosity.Normal:
            return MSBuildVerbosity.Minimal;
          // return Nuke.Common.Tools.MSBuild.MSBuildVerbosity.Normal; // Normal is way too detailed
          case Verbosity.Minimal:
            return MSBuildVerbosity.Quiet;
          case Verbosity.Quiet:
            return MSBuildVerbosity.Quiet;
        }
        return MSBuildVerbosity.Minimal; // default
      }
    }
```
