### ISSUE TITLE
Add first class support for building pipelines (including parallel targets)

### ISSUE THREAD

**Issue by lt-gerjan** [nuke-build/nuke#224]
As an extension to https://github.com/nuke-build/nuke/issues/162

Currently I am using TeamCity with multiple agents to run targets in parallel but I would be nice that Nuke has first class support for this.
I call it "Pipelines" because thats the term most systems use.

First draft proposal:

Property syntax:
```csharp
    Pipeline CI => _ => _
      .Description("Default pipeline for CI")
      .AddTarget(Clean)
      .AddParallelTargets(CompileCore, CompileFramework)    
      .AddParallelTargets(TestCore, TestFramework)    
      .AddTarget(Publish)    
```

```
       +---->Compile Core+-------->Test Core+--------+
       |                                             |
Clean+->                                             +->Publish
       |                                             |
       +---->Compile Framework+--->Test Framework+---+

```

**Comment by lt-gerjan** [comment]
One question is: what to do with the dependencies of the targets, because that can create all kinds of conflicts

Personally I like to be explicit (readability and predictability), so maybe we can say that pipelines do not run the dependencies of single targets. You need to compose a correct pipeline yourself.

**Comment by GerjanOnline** [comment]
When I think more about this feature: if we agree not to run the dependencies of the single targets, I think its more an _alternative_ way of declaring dependencies _and_ to give an option to run it in parallel.

## Declaring via `.DependsOn`

```
Target Clean => _ => _
  .Executes(...)

Target Restore => _ => _
  .Executes(...)
  .DependsOn(Clean)

Target CompileCore => _ => _
  .Executes(...)
  .DependsOn(Restore)

Target CompileFramework => _ => _
  .Executes(...)
  .DependsOn(Restore)
```

## Declaring via `Pipeline` (draft)

```
Pipeline LocalBuild => _ => _
  .AddTargets(Install)
  .AddTargets(Clean)
  .AddTargets(Restore)
  .AddTargets(CompileCore, CompileFramework).Parallel(degree: 2)

Pipeline TeamCityBuild => _ => _
  // for example: clean is not needed
  .AddTargets(Restore)
  .AddTargets(CompileCore, CompileFramework).Parallel(degree: 4)
```

**Comment by lt-gerjan** [comment]
When I think more about this feature: if we agree not to run the dependencies of the single targets, **I think its more an _alternative_ way of declaring dependencies _and_ to give an option to run it in parallel.**

## Declaring via .DependsOn

```csharp
Target Clean => _ => _
  .Executes(...)

Target Restore => _ => _
  .Executes(...)
  .DependsOn(Clean)

Target CompileCore => _ => _
  .Executes(...)
  .DependsOn(Restore)

Target CompileFramework => _ => _
  .Executes(...)
  .DependsOn(Restore)
```

Now if you want to know the order of targets, you can scan the source code and figure it out in your head, or use the `--plan` switch. 
I think this can be a cognitive overhead issue.

## Declaring via Pipeline (alternative draft syntax)

```csharp
Pipeline LocalBuild => _ => _
  .Run(Install)
  .Run(Clean)
  .Run(Restore)
  .Parallel.Run(CompileCore, CompileFramework) // syntax b

Pipeline TeamCityBuild => _ => _
  // for example: clean is not needed
  .Run(Restore)
  .Run(CompileCore, CompileFramework).InParallel(degree: 4) // syntax c
```

As you can see, it is very readable and explicit. You can "compose" multiple pipelines, with full control.

Maybe it is hard to see the benefit with such a trivial example. But when you have lots of targets with dependencies and different runners, you might see the benefit

**Comment by lt-gerjan** [comment]
I was hoping we could use MSBuild for the parallelism part, but it seems it does not support it OOTB. In only supports parallelism _inside_ targets

https://stackoverflow.com/questions/997047/how-to-run-tasks-in-parallel-in-msbuild

**Comment by mifopen** [comment]
The lack of just sequential targets execution mechanism is a showstopper for me. Even without parallelism, it would be awesome to have this feature.

**Comment by matkoch** [comment]
@mifopen how is it a showstopper? Targets are executed sequentially.

**Comment by matkoch** [comment]
I strongly believe this feature isn’t going to happen. There is only a small advantage of being able to declare dependencies in one place. The cognitive load to understand a dependency graph could also easily be solved with proper tooling (displaying the resulting graph live). Also the pipeline approach implies that for multiple pipeline declarations, you would need to repeat dependency logic. Last but not least, exposing a single feature in multiple ways is usually a bad idea from my experience.

That being said, I will think about making `NukeBuild.ExecutableTargets` public, in which case you should be able to implement such a feature yourself.

**Comment by matkoch** [comment]
Here's a little draft from what you'll be able to do from next release on. It's non-invasive and you need to add it to your build projects. Customize as needed. Maybe you can give some feedback later, and we may re-evaluate.

```
public class Pipeline
{
    public static Pipeline Create()
    {
        return new Pipeline();
    }

    internal List<Target> Targets { get; } = new List<Target>();

    public Pipeline AddTarget(Target target)
    {
        Targets.Add(target);
        return this;
    }
}

public class SupportPipelinesAttribute : Attribute, IPreLogoBuildExtension
{
    public void Execute(NukeBuild build, IReadOnlyCollection<ExecutableTarget> executableTargets)
    {
        var pipelines = build.GetType().GetProperties(ReflectionService.All)
            .Where(x => x.PropertyType == typeof(Pipeline))
            .Select(x => x.GetValue(obj: build)).Cast<Pipeline>();

        foreach (var pipeline in pipelines)
        {
            var targets = pipeline.Targets.Select(x => executableTargets.Single(y => y.Factory == x)).ToList();
            for (var i = 0; i < targets.Count - 1; i++)
                targets[i + 1].ExecutionDependencies.Add(targets[i]);
        }
    }
}
```

**Comment by lt-gerjan** [comment]
Making some API's public is nice, so we can built something on top of it! Thanks for that. If I have something useful, I will post a code snippet here
