### ISSUE TITLE
Handle ^C with AssuredAfterFailure 

### ISSUE THREAD

**Issue by ljani** [nuke-build/nuke#225]
As mentioned in #119, `^C` ([`Console.CancelKeyPress`](https://docs.microsoft.com/en-us/dotnet/api/system.console.cancelkeypress?view=netcore-2.2)) is not currently handled to trigger targets with `AssuredAfterFailure `. If a build has cleanup steps, we should at least attempt to gracefully shut down and clean up after the build.

**Comment by matkoch** [comment]
Please check prerelease

**Comment by matkoch** [comment]
Please pay attention, it's `0.16.0-alpha0027` (not 28 nor 29) - I've squashed some commits, so the version number is off :/
