### ISSUE TITLE
Private/internal and public targets

### ISSUE THREAD

**Issue by lt-gerjan** [nuke-build/nuke#226]
From Slack:

Idea/question: would it make sense to have "internal targets" and "public targets"?

For example: my Compile target consists of 3 parts: patching assemblyInfo's, compile projects, and execute corflags if needed (32bit thingy). Now Im in doubt to create 3 targets or just one Compile target. The advantage of creating separate targets are:
- easier to spot errors (in what step)
- will appear in build summary (how long did it take)
- can execute it via command line for debugging/dev/testing
- it feels nice to use targets for "units of work"

The disadvantage is:
- Its not a "public api", it should not appear in the target list by default (`--help`)

We might use the `public` and `private` modifiers for this.

Other possible changes:
- `--help` will not show private targets by default. Maybe an extra switch can be added to also show private/internal targets
- Maybe the build summary can indent private targets 

Last point might infer these are "sub targets"

**Comment by matkoch** [comment]
What is the disadvantage? What should not appear?
