### ISSUE TITLE
EnsurceCleanDirectory continues before directory exists

### ISSUE THREAD

**Issue by joostmeijles** [nuke-build/nuke#227]
`EnsurceCleanDirectory()` continues before directory exists.

It should instead wait till the directory exists, e.g:
```
EnsureCleanDirectory("./data/mssql");
SpinWait.SpinUntil(() => System.IO.Directory.Exists("./data/mssql"));
```

**Comment by matkoch** [comment]
Is the fix working reliably?

**Comment by joostmeijles** [comment]
Nope... `EnsureCleanDirectory` sometimes does not re-create the deleted directory.

Therefore the proposed solution will hang.

**Comment by matkoch** [comment]
Unfortunately, it's always hard to diagnose filesystem issues. Especially when it's on another remote machine :) Do you have any suggestions?

**Comment by ItEndsWithTens** [comment]
> Nope... `EnsureCleanDirectory` sometimes does not re-create the deleted directory.

I'm sorry to butt in with stupid questions, but what version of Nuke are you using and are you running it in Windows? I described a problem in issue #217 that sounds just like yours, but there's been a fix included in Nuke 0.16.0 that seems to have addressed it, for the most part.

**Comment by matkoch** [comment]
@joostmeijles

**Comment by joostmeijles** [comment]
Looks indeed the same as issue #217 .
