### ISSUE TITLE
DotNetPack: The 'licenseUrl' element will be deprecated

### ISSUE THREAD

**Issue by mifopen** [nuke-build/nuke#235]
I get
```C:\Program Files\dotnet\sdk\2.2.102\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(202,5): warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.```
when I use `.SetPackageLicenseUrl(licenseUrl)`

**Comment by matkoch** [comment]
Yes, me too. That's unrelated to this project.

**Comment by mifopen** [comment]
Great. And what project it is related to?

**Comment by matkoch** [comment]
Your own and NuGet I guess
