### ISSUE TITLE
File In Use Error at External Files

### ISSUE THREAD

**Issue by DannySotzny** [nuke-build/nuke#239]
affected version: 0.17.1

I get an error that the file I want to replace is currently in use. After that the file has exactly the desired content.

I created a project with "dotnet new sln", called "nuke : setup" and extended the project file with the "Item Group" as described in the documentation. 

Then I created a "Build.cs.ext" and inserted the following content, similar to the documentation:

    https://git01.local/snippets/21/raw
    
    GITVERSION
    
    SOURCE=https://api.nuget.org/v3/index.json

But I get the following error:

    E:\tmp\nuke2\build\Build.cs.ext : Build error : The process cannot access the file 'E:\tmp\nuke2\build\Build.cs' because it is being used by another process. [E:\tmp\nuke2\build\_build.csproj]

But there is no program open that has the Build.cs or Build.cs.ext open and Sysinternals handle tells me that the file is not open.

When I empty the file and call build I get the error message, but also the message that the file has been changed!

    E:\tmp\nuke2\build\Build.cs.ext : Build warning : External file has been updated. [E:\tmp\nuke2\build\_build.csproj]

**Comment by matkoch** [comment]
Can you provide a repro for the error case? The build task integration is a bit of a mess, but I have plans to update it asap.

The build warning is only for information. Would be better if it's only shown when the file content changed though.

**Comment by DannySotzny** [comment]
> Can you provide a repro for the error case? The build task integration is a bit of a mess, but I have plans to update it asap.

yes, you find it here: https://github.com/DannySotzny/nuke-issue-239

> 
> The build warning is only for information. Would be better if it's only shown when the file content changed though.

and it's okay that way. There one knows that what was done.

**Comment by matkoch** [comment]
Could not reproduce after removing duplicated item group includes.
