### ISSUE TITLE
AddTeamCityLogger causes error: Assertion failed: TeamCity.Instance != null

### ISSUE THREAD

**Issue by lt-gerjan** [nuke-build/nuke#241]
When I run my build locally, `AddTeamCityLogger` causes an error:

```csharp
var settings = DefaultMSBuildSettings
  .AddTeamCityLogger() // Error
  .SetProperty("Platform", "Any CPU")
  .SetProperty("MvcBuildViews", "true") // For WebApplications
  .SetProjectFile(slnFile);
```

Output:
`Assertion failed: TeamCity.Instance != null`

I can work around this, by checking if `TeamCity.Instance` is not null, but this seems a bug

**Comment by matkoch** [comment]
I wouldn't consider this a bug, the method communicates _add teamcity logger_, which it does. The easiest thing would be to call `When(TeamCity.Instance != null, x => x...)` or wrap another method `TryAddTeamCityLogger`.

**Comment by RobSmyth** [comment]
An alternative approach, that removes the need for null guards, would be to use the null pattern. That is, have TeamCity.Instance return a null type (not null) if not running under a build server. That is a type with methods that do nothing.

So ... if a local build it does nothing (good). If a build system build it does build system stuff. No null guards.
