### ISSUE TITLE
'Could not find a part of the path ...' on default Clean Target

### ISSUE THREAD

**Issue by hayhay27** [nuke-build/nuke#243]
Checked on Nuke 0.17.1 and 0.17.4
In bootstrapped Build.cs Clean target doesn't work correctly. Some issue in method DeleteDirectory: `SourceDirectory.GlobDirectories("**/bin", "**/obj").ForEach(DeleteDirectory);`

> PS C:\Users\Masha\source\repos\WebApplication1> nuke Clean --verbosity Verbose
> NUKE Global Tool version 0.17.4 (Windows,.NETStandard,Version=v2.0)
> Windows PowerShell 5.1.17763.316
> Microsoft (R) .NET Core SDK version 2.1.504
> Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Restore completed in 51,02 ms for C:\Users\Masha\source\repos\WebApplication1\build\_build.csproj.
>   _build -> C:\Users\Masha\source\repos\WebApplication1\build\bin\Debug\_build.dll
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:00.82
> NUKE Execution Engine version 0.17.4 (Windows,.NETStandard,Version=v2.0)
> 
> 
> 
> ╬══════════
> ║ Clean
> ╬══
> 
> Deleting directory 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin'...
> Deleting file 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin\Debug\netcoreapp2.1\WebApplication2.deps.json'...
> Deleting file 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin\Debug\netcoreapp2.1\WebApplication2.dll'...
> Deleting file 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin\Debug\netcoreapp2.1\WebApplication2.pdb'...
> Deleting file 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin\Debug\netcoreapp2.1\WebApplication2.runtimeconfig.dev.json'...
> Deleting file 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin\Debug\netcoreapp2.1\WebApplication2.runtimeconfig.json'...
> Deleting directory 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin\Debug\netcoreapp2.1'...
> Deleting directory 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin\Debug'...
> Deleting directory 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin'...
> Could not find a part of the path 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin'.
> 
> Repeating warnings and errors:
> Could not find a part of the path 'C:\Users\Masha\source\repos\WebApplication1\src\WebApplication2\bin'.
> 
> =======================================
> Target             Status      Duration
> ---------------------------------------
> Clean              Failed          0:00
> ---------------------------------------
> Total                              0:00
> =======================================
> 
> Build failed on 03.03.2019 18:26:59.

**Comment by kooshanabedian** [comment]
Same here. I was just going to login and open an issue, then I saw this.

**Comment by matkoch** [comment]
I can't do anything else than assuming this is a local issue on your workstations. As you see from the log output, it traverses up the directories and deletes one by one.

If you find an issue in the code itself, I'd be happy to know:

https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/IO/FileSystemTasks.cs#L82-L100

**Comment by kooshanabedian** [comment]
Actually Nuke.Common version 0.16 used to work. Going to 0.17.4, this one is a beauty. Just saying...

**Comment by matkoch** [comment]
Changeset is here: https://github.com/nuke-build/common/compare/0.16.0...0.17.4

Looks for _Files changed_ and then for `FileSystemTasks.cs`.

I can't really do anything if I can't reproduce the issue.

**Comment by kooshanabedian** [comment]
Is there any options to give a more elaborate verbose output? So we can track the delete instruction cycling over directories. It reproduces the same error on even empty bin and obj directories. Therefore, I don't think it is related to nested deleting etc.

```
Deleting directory 'D:\****\SecurityPortal\src\IdentityClients\bin'...
Solution D:\****\SecurityPortal.sln has an active build configuration for D:\****\SecurityPortal\build\_build.csproj.
Could not find a part of the path 'D:\****\SecurityPortal\src\IdentityClients\bin'.

Repeating warnings and errors:
Assertion failed: Could not complete checking build configurations within 500 milliseconds.
Solution D:\****\SecurityPortal\SecurityPortal.sln has an active build configuration for D:\****\SecurityPortal\build\_build.csproj.
Could not find a part of the path 'D:\****\SecurityPortal\src\IdentityClients\bin'.

```

**Comment by matkoch** [comment]
Just copy the implementation from `FileSystemTasks` and add the information you need.

**Comment by hayhay27** [comment]
I make some investagations. I was wrong. Exception was thrown in method MoveNext on enumerable result of GlobDirectories after first deletion. Problem with globbing.

`Glob.Directories(SourceDirectory, "**/bin").ForEach(DeleteDirectory)` - this code gives same result.

Look at Glob now.

----

My host:

> Windows 10 Pro
> Version 1809 (OS Build 17763.316)

Maybe you can't reproduce issue because you on *nix.

Here is stacktrace:
```
   at System.IO.Win32FileSystemEnumerableIterator`1.HandleError(Int32 errorCode, String path)
   at System.IO.Win32FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.Win32FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler)
   at System.IO.Win32FileSystem.EnumerateFileSystemInfos(String fullPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetDirectories()
   at GlobExpressions.PathTraverser.TraverseOptions.GetDirectories(DirectoryInfo root)
   at GlobExpressions.PathTraverser.Traverse(DirectoryInfo root, Segment[] segments, Int32 segmentIndex, TraverseOptions options)
   at GlobExpressions.PathTraverser.Traverse(DirectoryInfo root, Segment[] segments, Int32 segmentIndex, TraverseOptions options)
   at System.Linq.Enumerable.<SelectManyIterator>d__167`3.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__167`3.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__32`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Build.<get_Clean>b__10_1() in C:\Users\Masha\source\repos\cnt\build\Build.cs:line 46
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
```

**Comment by matkoch** [comment]
Try to add `ToList` to it... it's probably because the collection was modified. I'll think about making our wrapper methods calling `ToList` implicitly.

**Comment by matkoch** [comment]
Done 👆

**Comment by hayhay27** [comment]
IEnumerable more flexible. Maybe add ToList in bootstrapped Build.cs?
