### ISSUE TITLE
NRE on Requires

### ISSUE THREAD

**Issue by hayhay27** [nuke-build/nuke#244]
Hi.
Next configuration

```
class Build : NukeBuild
{
    public static int Main () => Execute<Build>(x => x.Test);

    // without [Parameter]
    readonly string TestVar = "123";
    Target Test => _ => _.Requires(() => TestVar);
}
```

fails with NRE somewhere and no stacktrace, no debug in nuke code. Very hardly to investigate with a lot of targets.
I'm very frustrated. I think 0.11 closer to production than 0.17. 

> NUKE Execution Engine version 0.17.4 (Windows,.NETStandard,Version=v2.0)
> 
> Object reference not set to an instance of an object.
> 
> Repeating warnings and errors:
> Object reference not set to an instance of an object.
> 
> =======================================
> Target             Status      Duration
> ---------------------------------------
> Test               NotRun          0:00
> ---------------------------------------
> Total                              0:00
> =======================================
> 
> Build failed on 2019-03-04 15:23:45.

**Comment by matkoch** [comment]
> I'm very frustrated. I think 0.11 closer to production than 0.17.

I hope you realize that this is very frustrating for me as well, given the amount of time I've put into this project, and given the numerous features that have been implemented since 0.11 release.

**Comment by hayhay27** [comment]
Didn't mean to upset you. Sorry. I think this is the best project for build automation with c#. So I open issues to make it better.

I'm not talking about new features. Only about broken behavior of base functionality and the lack of the ability to debug normally.

**Comment by matkoch** [comment]
_I'm very grateful for every reported issue, and I'm looking at it the same way you do. Yet I think it's important to remember how demotivating OSS can be sometimes. But all good as long as we can find an agreement :)_

It's fixed in 0.17.6, and regarding debugging, there is an open issue #237

**Comment by matkoch** [comment]
The fix is basically a better error message.

**Comment by GeorgDangl** [comment]
I would also like to thank you for the work you put in, @matkoch! Just today, I saw someone impressed by how easy Nuke is to use who was new to it:)

**Comment by matkoch** [comment]
🤗
