### ISSUE TITLE
Build Project with NuGet Packages from Private Repositories

### ISSUE THREAD

**Issue by DannySotzny** [nuke-build/nuke#245]
## Problem
In the Build Project, a nuget package from a repository other than nuget.org is used. You can apply `dotnet restore` to the build project, but when starting nuke you still get the error message that the package was not available.

## Solution
Use a nuget.config to configure dotnet - what could be more obvious than to have these generated with nuget.

Currently there is no way to create a `NuGet.Config` with the program `dotnet`. For the restore of `dotnet` you can now use the parameter "-s" to define the sources. Unfortunately you can't use this parameter if the :nuke: build project uses a nuget package from a repository other than nuget.org.  
The work-arrount now is to create a NuGet.Config in the project folder. For this you could install nuget which uses mono. With `nuget add source -Name MyNuget -Source https://.....` you add the new source.

According to the documentation (https://docs.microsoft.com/en-US/nuget/tools/cli-ref-sources) the NuGet.Config is created in `~/.nuget/NuGet/NuGet.Config`. In my experiments it was created under `~/.config/NuGet/NuGet.Config` - but there it does not find `dotnet`. You might think that specifying the config file to Nuget would correct the problem. Here nuget acknowledges the attempt with an error message that the folder does not exist - so you have to create it first.
A workaround would look like this: `mkdir -p /root/.nuget/NuGet && cp /root/.config/NuGet/NuGet.Config /root/.nuget/NuGet/NuGet.Config`.

Alternatively you could put a NuGet.Config in the project directory - but for automation and delivery via Docker this is sometimes not possible.

**Comment by matkoch** [comment]
Discussed privately. The issue is on Mono/dotnet side.
