### ISSUE TITLE
How to traverse solution folders and subfolders for specific projects?

### ISSUE THREAD

**Issue by kooshanabedian** [nuke-build/nuke#246]
I have a solution with dozens of projects in a hierarchy of subfolders. My projects consist of both dotnet core projects and good old WCF projects. I have figured out, reading documents, that I can use `Solution.GetProject("My Project Name")` to retrieve specific projects to form different target sets which would be handled by separate DotNetTasks and MsBuild pipelines accordingly. All is set and perfectly working.

Recently, after my project grew in size, I have split some of my previous projects across separate layers, which resulted in projects with the same names placed within distinct subfolders. e.g:

src -> Api -> Common
src -> Business -> Common

This new setting obviously messed up with `Solution.GetProject("ProjectName")` Particularly, since I need to narrow down my deploy pipeline to the Api projects and not other layer counterparts. 
According to the [Docs](https://www.nuke.build/docs/authoring-builds/solutions-and-projects.html), I supposedly would use `Solution.SolutionFolders` to navigate through solution subfolders to pinpoint the project that I want. But there is two problem, or I have not really figured it out how to do it right.

1. `Solution.SolutionFolders` works greats for the first level subfolders, i.e. it grabs my 'src' and 'tests' subfolders. But when I use linq to get 'src' folder, I get an instance of the `SolutionFolder` in the next step not an IEnumerable of possible next level subfolders.

2. Even if there was a recurring `SolutionFolders` all the way down, I don't know how does it help to extract my desired project by somehow applying a `.GetProject("My Project Name")` like function.

I doubt this is an issue, it is just that I'm a newbie to this build pipeline and couldn't find any reference on how to address such situation.
Thanks.

P.S. I know that I should have name my projects something like:
src -> Api -> Api.Common
src -> Business -> Business.Common

Actually I have done it before. But since folder hierarchy extends for 3 or 4 levels, I found this naming convention superfluous. I stopped naming the actual files and use the directives inside the csproj file instead:
```
    <AssemblyName>Company.System.Subsystem.Layer.Package</AssemblyName>
    <RootNamespace>Company.System.Subsystem.Layer.Package</RootNamespace>
```

**Comment by matkoch** [comment]
In your case, it's probably the best to do something like `solution.AllProjects.Where(x => x.SolutionFolder.Name == "anything")`. The `SolutionFolder` class is currently only intended for managing solution folder items.

_Btw, except for bug reports, we require people to star the project_ 😄
