### ISSUE TITLE
Better document for CoverletTasks

### ISSUE THREAD

**Issue by ghost** [nuke-build/nuke#247]
I'm writing a test task using CoverletTasks for code coverage:

```
  Target Test => _ => _
      .DependsOn(Compile)
      .Executes(() =>
      {
        var testSetting = new DotNetTestSettings()
              .SetProjectFile(Solution)
              .SetConfiguration(Configuration)
              .SetLogger("trx")
              .SetResultsDirectory(TestResultDirectory)
              .SetNoBuild(true);

        CoverletTasks.Coverlet(s => s
              .SetTargetSettings(testSetting)
              .SetAssembly(@"D:\Workspace\Code\~SourceCode\.Net\TheAlgorithmDesignManual\tests\TheAlgorithmDesignManual.Tests\bin\Debug\netcoreapp3.0\TheAlgorithmDesignManual.Tests.dll")
              .SetOutput(TestCoverageDirectory / "coverage.cobertura.xml")
              .SetExclude("[*.Tests]*")
              .SetFormat(CoverletOutputFormat.cobertura));

        ReportGeneratorTasks.ReportGenerator(s => s
              .SetTargetDirectory(TestReportDirectory)
              .SetReports(TestCoverageDirectory / "coverage.cobertura.xml"));
      });
```

Coverlet console has already installed globaly. But when I run the test, it say that : 
`Assertion failed: Could not find package 'coverlet.console' via 'D:\Workspace\Code\~SourceCode\.Net\TheAlgorithmDesignManual\build\_build.csproj'.`

After clone nuke-build/common and take a look at file Coverlet.Generated.cs , I notice this:
```
public static string CoverletPath =>
            ToolPathResolver.TryGetEnvironmentExecutable("COVERLET_EXE") ??
            ToolPathResolver.GetPackageExecutable("coverlet.console", "coverlet.console.dll");
```
So I try to set an environtment variable COVERLET_EXE pointing to my coverlet.exe and it work. I think this should be documented to not make people confused.

About the GetPackageExecutable method, after reading source code I'm still not sure what it does so please correct me if I'm wrong. My guess is It try to find package "coverlet.console" in .csproj file of build project and try to get the executable file "coverlet.console.dll" to run coverlet. But coverlet.console is a dotnet tool installed via `dotnet tool install` not `dotnet add package` so I don't know if we can add it to .csproj file or not, in addition, executable file of coverlet.console is "coverlet.exe". I have checked other coverage tool task like DotCoverTasks, its "JetBrains.dotCover.CommandLineTools" is a package thus can be added to .csproj and the code can find executable file if people don't know about DOTCOVER_EXE variable. But how about CoverletTasks, does the Coverlet.json for code generate have wrong values or I am missing some thing to make it work?

**Comment by matkoch** [comment]
The assertion message already tells you that the expected package `coverlet.console` is not added to the build project file.

**Comment by matkoch** [comment]
_Please mind our contribution guidelines. I.e., put a star for the project_ 😉

**Comment by matkoch** [comment]
http://www.nuke.build/docs/authoring-builds/cli-tools.html contains the information about packages required to be added.

**Comment by matkoch** [comment]
The fact that coverlet is a global tool is irrelevant. Package references are added to ensure consistent versions across different machines.

**Comment by mario-d-s** [comment]
@matkoch I'm currently grinding my teeth on this one :confused:
It makes total sense to have all tools available as dependencies (for portability and repeatability) **but** in this instance @Fubuchi seems to be right: you **can't** add a reference to a dotnet CLI global tool! So in fact it is completely relevant.

Using `PackageReference` you get:

>  error NU1212: Invalid project-package combination for coverlet.console 1.5.1. DotnetToolReference project style can only contain references of the DotnetTool type 

Using `DotNetCliToolReference` it restores, but when running Nuke it still says:

> Assertion failed: Could not find package 'coverlet.console' via '[redacted]/build/_build.csproj'.

**Comment by matkoch** [comment]
I think you can still add it manually as below:

```
<PackageReference Include="coverlet.console" Version="1.5.1">
  <ExcludeAssets>all</ExcludeAssets>
</PackageReference>
```

**Comment by matkoch** [comment]
Verified also:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5005566/57533606-7800dd80-733e-11e9-9197-9947659211b5.png">

**Comment by ghost** [comment]
@matkoch The case of Coverlet is a bit different because it is not provided as a package but as a tool. I guess nuke treats all coverage tool like they are package and this cause the problem.

Before using Coverlet, I use OpenCover which has a package on nuget: https://www.nuget.org/packages/OpenCover/ and everything work fine after I add it to build project with `dotnet add` command, but it doesn't meet my need so I try Coverlet and face this problem. Manual add `PackageReference` like you said make it work but it is a bit tricky to know and try so as my original question, this case should be documented in nuke's guide.

**Comment by matkoch** [comment]
Instead of fixing the documentation, I would prefer something like https://github.com/nuke-build/nuke/issues/274.
