### ISSUE TITLE
Process color output

### ISSUE THREAD

**Issue by LordMike** [nuke-build/nuke#249]
Hey,

I just tried upgrading from `0.12` to `0.17.6`, and we lost the coloring of output from `DotNetTasks.DotNetBuild`. Was this intentional?

Mike.

**Comment by matkoch** [comment]
Yes intentional. This is required to make parallel targets possible.

How important is colorization? Yes, it would be cool if it still had colors, but how bad is it without them?

**Comment by LordMike** [comment]
Hmm, we use the colors to quickly identify warnings and errors from Dotnet Build (and friends).

Parallelization is a problem because of synchronous access to Console output?

**Comment by matkoch** [comment]
your are using DotNetTasks?

**Comment by LordMike** [comment]
Yup.

**Comment by matkoch** [comment]
Warnings and errors should continue to be colorized according to this: https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/Tools/DotNet/DotNetTasks.cs#L33

**Comment by LordMike** [comment]
I've set up a small project with Nuke, and I can reproduce the no colors output. I've noticed there are different ways of interpreting what colored output is.

In the image below, we see colors in three places (more if build errors are present):

* Dotnet build stuff, e.g. "build succeeded"
* Build errors and warnings
* Nuke summary of errors and warnings (this was colored in 0.12.0)

Am I right in speculating that the console output has gone from being hooking up `stdout->stdout` to being `stdout -> Nuke -> stdout` (to support parallel builds) .. ? If so, to support this again, the console color has to be read from the original process in order to recreate it on Nukes output -- which seems like a larger task :|

![image](https://user-images.githubusercontent.com/1027111/54228214-f3dad700-4501-11e9-9689-f375d4795e49.png)

The same build script but with `0.12.0` (I had to remove some attributes on my NukeBuild type).

![image](https://user-images.githubusercontent.com/1027111/54228352-4b794280-4502-11e9-8b28-d6e3555e71c5.png)

**Comment by matkoch** [comment]
You're executing from PowerShell? Can you try cmd instead?

**Comment by LordMike** [comment]
![image](https://user-images.githubusercontent.com/1027111/54229147-f2121300-4503-11e9-8449-060436c1facb.png)

Note: I'm still running Powershell, just in CMD. The result is the same - the `0.12.0` produces colors while the `0.17.6` does not.

Note 2: Running the build as `dotnet run` still does not produce colors.

**Comment by matkoch** [comment]
Should be fixed ^^^

**Comment by LordMike** [comment]
I'll try out whatever you have when `0.17.7` is ready.

I've found [this](https://github.com/dotnet/cli/issues/9250) which suggests that `/clp:ForceConsoleColor` can be set on `dotnet build`. I've tried that in my own wrapper that runs `Process.Start` and found that I indeed do get the ANSI color codes with that.

Other than that - It doesn't seem possible (in a particularly friendly / cross-platform way) to read the output colors on a process spawned by `Process`.. So parsing specific programs' output like you do is probably the only way.

![image](https://user-images.githubusercontent.com/1027111/54230801-787c2400-4507-11e9-8e0f-bd1d201935fa.png)

**Comment by matkoch** [comment]
It's the only cross-platform way at least. On Windows there exist nasty Win32 APIs to make it work, but this is really not a priority.

**Comment by LordMike** [comment]
At least not with the code examples I found. That was a rabbit hole of native interop shit.

**Comment by mvestergaard** [comment]
I've been playing around with nuke this evening, considering replacing cake with it, but I encountered the same thing as shown in the screenshots above with `0.17.7`.

The build summary from nuke etc. has colors, but warnings/errors from msbuild do not.
Is that intentional, as you put it in your first reply?

While not hugely important, colors really help when building solutions of 300+ projects.

**Comment by LordMike** [comment]
I think the only option is to force ANSI colors from various tools. For Msbuild this is possible using `/clp:ForceConsoleColor` which [sets this](https://github.com/Microsoft/msbuild/blob/e70a3159d64f9ed6ec3b60253ef863fa883a99b1/src/Build/Logging/ConsoleLogger.cs#L142-L146) in ConsoleLogger of Msbuild - thereby ensuring that any setting of colors will result in ANSI codes coming out.

This is specific to each tool, but should otherwise be universally supported (Windows 10 prompts, all Linux prompts ever, ..).

Nuke may have to inform whatever console its in, that it supports ANSI color codes, f.ex. using [SetConsoleMode](https://docs.microsoft.com/en-us/windows/console/setconsolemode) in Windows.

**Comment by mvestergaard** [comment]
I don't believe powershell itself supports ANSI though, so unless using something like ConEmu, it'll just appear even more screwed up

**Comment by matkoch** [comment]
@mvestergaard for MSBuild there is no `CustomLogger` defined. You can [set it manually](https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/Tools/MSBuild/MSBuild.Generated.cs#L32) and take the `DotNetTasks.CustomLogger` as an [example](https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/Tools/DotNet/DotNetTasks.cs#L33). Then probably also do a PR :)

**Comment by LordMike** [comment]
@mvestergaard https://stackoverflow.com/a/51681675/1246988

In it, if you pipe any output in PS through `Out-Host`, it will interpret ANSI codes. The other methods should also work.

**Comment by matkoch** [comment]
Would be better to follow up here: https://github.com/nuke-build/nuke/issues/256

As this issue is already solved properly. At least how I consider it at the moment.
