### ISSUE TITLE
Coveralls Integration broken

### ISSUE THREAD

**Issue by coder2000** [nuke-build/nuke#255]
Adding coveralls as a package raises an error that it is not supported.

![coveralls2](https://user-images.githubusercontent.com/27944/54254046-3d3a1f00-4520-11e9-9780-cbb81384670d.PNG)

Setting `<ExcludeAssets>` to true fixes the not supported issue, however, Nuke is unable to find the tool:

![failed](https://user-images.githubusercontent.com/27944/54254099-69ee3680-4520-11e9-8f6d-ed8f1d1c17d8.PNG)

Looks like it is looking in the wrong folder as the tool is in the `tools/` folder.

**Comment by matkoch** [comment]
Note it's `exe` and not `dll`. It's fixed in develop already. Release coming soon.
