### ISSUE TITLE
Code cleanup tooling

### ISSUE THREAD

**Issue by jussimattila** [nuke-build/nuke#258]
I'm digging Nuke more and more, it's a great tool!

What would it take to add support for [ReSharper's automatic code cleanup command line tool](https://www.jetbrains.com/help/resharper/CleanupCode.html)? I would consider contributing it myself if the learning curve is not too steep.

**Comment by matkoch** [comment]
You didn't dig deep enough :) As per the [contributing guidelines](https://github.com/nuke-build/nuke/blob/master/CONTRIBUTING.md), we don't accept issues regarding unsupported tools.

**Comment by matkoch** [comment]
Here are examples how CLTs are implemented: https://github.com/nuke-build/common/tree/develop/build/specifications

I suggest you to join the Slack workspace.

**Comment by jussimattila** [comment]
Oh my, I'm breaking rules left and right. Apologies! On my way to Slack...
