### ISSUE TITLE
List of requested CLTs

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#259]
All the following tools are kept for contributions. Please add a comment to make an additional request (or better directly provide a PR):

- WiX by @jnm2
- ReSharper Cleanup by @jussimattila
- Nerdbank.GitVersioning by @juchom
- Yarn by @joskoanicic

**Comment by jussimattila** [comment]
FYI, I'm happy to have a look at adding ReSharper Cleanup, but only after I'm back from my (long overdue) vacation. I will be more or less off the grid for 1,5 weeks and resume work then.
