### ISSUE TITLE
Ignore/Skip invalid solution files.

### ISSUE THREAD

**Issue by wischi-chr** [nuke-build/nuke#261]
I recently started using nuke on most of my projects and I really love it.

A few minutes ago I found a problem regarding (very) old sln files (I don't control this particular file it's from a third party lib). If I run nuke (even with empty target) it fails with `obj != null` assertion.

I digged a bit deeper and cloned nuke.common (0.17.7) and found out that the exception happens in `Nuke.Common.ProjectModel.SolutionSerializer.GetPrimitiveProjects` while parsing section `ProjectConfigurationPlatforms`.

The old solution, I don't control and don't need for the build, doesn't have that section (it was named `ProjectConfiguration` back then)

```
Microsoft Visual Studio Solution File, Format Version 8.00
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "zmbv", "zmbv.vcproj", "{619CF3F9-C373-4BD5-93DA-025F5E16F8FA}"
	ProjectSection(ProjectDependencies) = postProject
	EndProjectSection
EndProject
Global
	GlobalSection(SolutionConfiguration) = preSolution
		Debug = Debug
		Release = Release
	EndGlobalSection
	GlobalSection(ProjectConfiguration) = postSolution
		{619CF3F9-C373-4BD5-93DA-025F5E16F8FA}.Debug.ActiveCfg = Debug|Win32
		{619CF3F9-C373-4BD5-93DA-025F5E16F8FA}.Debug.Build.0 = Debug|Win32
		{619CF3F9-C373-4BD5-93DA-025F5E16F8FA}.Release.ActiveCfg = Release|Win32
		{619CF3F9-C373-4BD5-93DA-025F5E16F8FA}.Release.Build.0 = Release|Win32
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
	EndGlobalSection
	GlobalSection(ExtensibilityAddIns) = postSolution
	EndGlobalSection
EndGlobal
```

I understand that supporting such old sln files will not happen 😃 but I think it's shouldn't prevent nuke from running.

**A few ideas:**
1. Skip invalid (unable to parse) solution files (and maybe spit out a warning)
2. Allow the user to ignore specific solutions

**Workaround:**
At the moment I renamed the solution file to `*.sln.bak` but that's not a pretty good solution IMHO

Pls let me know what you think. If you think option one is a good idea I could implement that and create a PR - not sure if I'm comfortable enough with the code base to implement option two.

**Comment by matkoch** [comment]
Why skip or ignore if the serializer could just parse it correctly?

**Comment by matkoch** [comment]
Please star the project :)

**Comment by wischi-chr** [comment]
> Why skip or ignore if the serializer could just parse it correctly?

True.

Didn't know you would be ok with supporting such old solution files :-)
Second: Even if the file is parsed correctly a malformed/invalid solution would still result in a cryptic error message (`obj != null`) and prevent the build script from running.

My suggestion: I update the serializer to support old solutions. Files that can't be parsed (because they are not visual studio solutions) will be skipped and a sensible warning will be logged.

> Please star the project :)

Done 😸

**Comment by matkoch** [comment]
If a solution is malformed, we should probably throw an appropriate error message - right.

I’m totally okay supporting this. I just don’t have time doing it myself :)

**Comment by matkoch** [comment]
#234 might be slightly related.

**Comment by wischi-chr** [comment]
>  I just don’t have time doing it myself :)

No problem. I hope I find the time this week to prepare a PR

**Comment by alphaleonis** [comment]
I just encountered this problem myself, due to the `[CheckBuildProjectConfigurations]` on the build class, and an old solution file being in a subfolder somewhere in the source directories.  Took the liberty to remedy the problem and submit a PR.
