### ISSUE TITLE
Support for Nerdbank.GitVersioning

### ISSUE THREAD

**Issue by juchom** [nuke-build/nuke#262]
For my personal needs, I need to use Nerdbank.GitVersioning: https://github.com/AArnott/Nerdbank.GitVersioning

Woud you be interested in a PR for it? If yes, could you please point to some documentation?

Thanks

**Comment by matkoch** [comment]
Sure, it's not finished yet, but you can find a lot of information here already: http://www.nuke.build/docs/writing-addons/code-generation.html

**Comment by matkoch** [comment]
Moving to #259. If you have further questions either post them there or in our Slack workspace.

**Comment by matkoch** [comment]
And please also consider giving the project a star :)
