### ISSUE TITLE
Improve TeamServices/AzureDevOps interface

### ISSUE THREAD

**Issue by RLittlesII** [nuke-build/nuke#264]
I recently upgraded from 0.14.1 => 0.18.0 after upgrading my TFBuild commands broke.

Seems in the time since last upgrade color has been added to other loggers, and it broke the output to console (which is how you run TFBuild commands in Azure DevOps).

```
##[error]Unable to process command '[96;1m##vso[artifact.upload containerfolder=Artifacts;artifactname=Artifacts;]C:\agent\_work\9\s\artifacts[0m' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
```

**Comment by matkoch** [comment]
As privately discussed, this is - judging from the framework - a user error. However, the `TeamServices` class should be extended and also renamed.

**Comment by matkoch** [comment]
@RLittlesII 	assigned alright?

**Comment by RLittlesII** [comment]
@matkoch Yes.  I'll have a WIP PR this week.

**Comment by alphaleonis** [comment]
The output definitely looks a bit funky. Attaching a picture displaying how it appears for us on an on premise TFS server.
![image](https://user-images.githubusercontent.com/5114354/57622287-8db81200-758d-11e9-9310-312e2e29a6f6.png)

**Comment by Skyqula** [comment]
I can confirm @alphaleonis image. `[96;1m` and `[0m` are added to nuke's writes. Note that there is a hidden character in there as well.

**Comment by MarchingCube** [comment]
Any chance of resolving this anytime? My team switched to use Azure DevOps and we have the same broken output in the console.

**Comment by matkoch** [comment]
I'm not really sure how this should be "solved". Azure devops is not really consistent with how it handles the output. The following is from the same build. First image while it's running, second when it has finished.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/5005566/62429089-6d21d300-b70a-11e9-8183-49bbd3b4e4bf.png">
<img width="859" alt="image" src="https://user-images.githubusercontent.com/5005566/62429090-701cc380-b70a-11e9-9dd7-f2b0ffd77024.png">

**Comment by RLittlesII** [comment]
I'll pull some raw logs and see if I can't glean something from them.  Hopefully, we can find a pattern and solve the problem.

**Comment by matkoch** [comment]
I'm not an AzureDevOps expert, but maybe someone could file an issue for them and reference it here. @MarchingCube @Skyqula @alphaleonis

**Comment by Skyqula** [comment]
I looked trough the source again and inside the [AnsiColorOutputSink](https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/OutputSinks/AnsiColorOutputSink.cs) I found the characters that are causing this issue. They are the ansi color coding.

So I turned to google and found [this issue](https://developercommunity.visualstudio.com/content/problem/440605/write-host-foreground-color-with-powershell-task-i.html) where a user asked how to color code output, to which the response is to use the [logging commands](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md).

I also found [another issue](https://developercommunity.visualstudio.com/content/problem/614084/ansi-terminal-color-issues.html) stating that DevOps now seems to have partial ansi color support. The answer there seems to suggest that the latest version should have full support.

So to me it seems there are 2 ways to fix this issue.
1. Wait it out and recommend users to update to the latest version of DevOps. This means no TFS support.
2. Change the [AzureDevOpsSink](https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/BuildServers/AzureDevOpsOutputSink.cs) to use the official [logging commands](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md). Which should then support TFS as well. (looking at [AzureDevOpsSink](https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/BuildServers/AzureDevOpsOutputSink.cs), warning and error already seem to bypass the ansi colors and [AzureDevOps](https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/BuildServers/AzureDevOps.cs) already seems to use some [logging commands](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md)).

**Comment by matkoch** [comment]
<img width="251" alt="image" src="https://user-images.githubusercontent.com/5005566/62983032-4b250080-be2e-11e9-88bf-1b75ae48641e.png">
<img width="459" alt="image" src="https://user-images.githubusercontent.com/5005566/62983043-5546ff00-be2e-11e9-8def-732d5c194309.png">
