### ISSUE TITLE
GitVersion doesn't work with MSBuild

### ISSUE THREAD

**Issue by EMostafaAli** [nuke-build/nuke#267]
I am trying to compile .NET4.6 framework project, so while setting up the project, I chose MSBuild (rather than Core CLI). I can see from the powershell that assembly version is set to 0.1.0

`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\msbuild.exe" C:\Users\abdelale\source\repos\Simusharp.AutoBuilder\Simusharp.AutoBuilder.sln /maxcpucount:8 /nodeReuse:True /p:Configuration=Debug /p:AssemblyVersion=0.1.0 /p:FileVersion=0.1.0 /p:InformationalVersion=0.1.0-MSbuild.1+2.Branch.MSbuild.Sha.7828ec21e7db4ccaecfa8c8e167fbec9c6f4d4c0 /target:Rebuild`

However, checking file properties shows 1.0.0 (the same version from AssemblyInfo file).

I tested another project that targets .NET core and it works without issues.

**Comment by matkoch** [comment]
Passing versions, i.e. file version, assembly version, informational version, only works with SDK based projects. There is nothing we can do about it.

**Comment by EMostafaAli** [comment]
How about this?
https://stackoverflow.com/questions/8446693/specify-assembly-version-number-as-a-command-line-argument-in-msbuild

http://www.lionhack.com/2014/02/13/msbuild-override-assembly-version/
