### ISSUE TITLE
Parameter help text should include additional information

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#27]
The help text for parameters should provide additional standardized information. For instance:

- Possible values if type is an enum
- Default values
- Separator character

**Comment by VolkmarR** [comment]
I've build a small test script for this issue: 

    public enum BoolWithDefault { Default, True, False }

    [Parameter()]
    readonly int IntParam;
    [Parameter()]
    readonly BoolWithDefault EnumParam = BoolWithDefault.Default;
    [Parameter(Separator = "#")]
    readonly string[] StringArrayParam = new string[0];

    Target Compile => _ => _
        .Executes(() =>
        {
            Console.WriteLine("Parameter Values");
            Console.WriteLine($"- IntParam: {IntParam}");
            Console.WriteLine($"- EnumParam: {EnumParam}");
            Console.WriteLine($"- StringArrayParam: {string.Join(" / ", StringArrayParam)}");
        });

The current Help output for these parameters is

    --enum-param         <no description>
    --int-param          <no description>
    --string-array-param   <no description>

A more helpful output could look like this

    --enum-param         The Enum values are 'Default', 'True', 'False'. The Default is 'Default'.
    --int-param          The Default is 0.
    --string-array-param   Array with '#' as separator. The Default is Empty.

I can investigate this issue further and probably solve it.

**Comment by AlexMountainBN** [comment]
Why is the PR still open? I would give it a try if there are still issues open on this topic.
