### ISSUE TITLE
Allow hyphens in target names

### ISSUE THREAD

**Issue by lshearer** [nuke-build/nuke#270]
#### Motivation
As noted [in the documentation](https://nuke.build/docs/authoring-builds/parameter-declaration.html), resolution of parameter names is very forgiving, allowing both Pascal and lisp-cased forms. However, the forgiveness is not carried over to target name resolution, as it does not resolve target names with a hyphenated, lisp-cased form. 

Allowing hyphens in target names would improve consistency between target and parameter usage, making multi-word targets more user-friendly and predictable, particularly for users accustomed to tools with lisp-cased commands (e.g., [yarn](https://yarnpkg.com/en/docs/cli/upgrade-interactive)) and parameters.

#### Current version of NUKE
0.18.0

#### Expected behavior
Any of these commands would match a target named `PublishDocs`:
```
./build.sh publish-docs
./build.sh PublishDocs
./build.sh publishDocs
```

#### Actual behavior
Either of these commands would match a target named `PublishDocs`:
```
./build.sh PublishDocs
./build.sh publishDocs
```
This will fail:
```
./build.sh publish-docs
```

#### Solution
This would be easy to allow by simple stripping dashes from target names when searching for a match [here](https://github.com/nuke-build/common/blob/8dc207e1eadf67ef92a7f30b85f55d3524cfa9e4/source/Nuke.Common/Execution/ExecutionPlanner.cs#L101), in the same way it is being done for parameters [here](https://github.com/nuke-build/common/blob/8dc207e1eadf67ef92a7f30b85f55d3524cfa9e4/source/Nuke.Common/Execution/ParameterService.cs#L207).

**Comment by matkoch** [comment]
Would you be interested in creating a PR ?

**Comment by lshearer** [comment]
Sure! I just wanted to float it as an issue first to make sure it seemed valuable.

**Comment by matkoch** [comment]
Definitely. The global tool probably also needs an update.
