### ISSUE TITLE
How to setup debugging with nuke

### ISSUE THREAD

**Issue by MoshiMoshi0** [nuke-build/nuke#271]
I have problems trying to figure out how to setup debugging of the project/solution that nuke is compiling.

Currently I do this:
```csharp
protected override void OnBuildFinished()
{
    if (string.Compare(InvokedTargets.Last().Name, "Run", true) != 0)
        return;

    // start process using Process.Start
}

...

Target Run => _ => _
    .DependsOn(Compile);
```

But this does not look like a proper solution. Since VS does not support debugging of child processes this solution requires a plugin or by using some EnvDTE [magic](https://stackoverflow.com/questions/11811856/attach-debugger-in-c-sharp-to-another-process/11811881).

I wonder if there is a better way to do this, or if this is even in the scope of nuke?

**Comment by matkoch** [comment]
I’m not sure what you’re trying to do. Debugging a process that was started via `Process.Start`? This would be way out of scope.

**Comment by MoshiMoshi0** [comment]
I'm trying make a setup so that you can run nuke build in visual studio and it will compile the solution and also start debugging it.

But thinking about it, its more of a feature in the visualstudio plugin and not nuke itself.

**Comment by matkoch** [comment]
Isn’t that what F5 does?

**Comment by MoshiMoshi0** [comment]
Well yes, but if I set the startup project to be the nuke build project it will only compile and not debug. If I set the startup project to my project it will debug but not do then compile automation stuff I need.

Or you are supposed to run the compile target manually from the Task Runner before you run your project?

Wouldn't it be better if you could just set the startup project to be nuke and by pressing F5 it would run for example the compile target and the start debugging?

**Comment by matkoch** [comment]
It's not a good idea to use nuke as a replacement for F5/startup project functionality. I feel that whatever you need to do should better be implemented with MSBuild/pre-build steps.
