### ISSUE TITLE
Nuke --help screenshot on the website is out of date and misleading

### ISSUE THREAD

**Issue by mlaily** [nuke-build/nuke#272]
Hello!

I'm starting to play with Nuke, and I noticed the screenshot of the `nuke --help` console output in the docs is out of date. (http://www.nuke.build/docs/running-builds/fundamentals.html)

It shows a `--graph` command, but apparently it's now `--plan` instead.

It's not a very big deal, but it made me wonder for a while why it didn't work, so it would probably be better if it was updated.

In case it helps, the out of date file is here:
https://github.com/nuke-build/web/blob/fd48c4913b45dabbeee0e1d42749e6c877a55e75/source/images/help.png
(I'd rather not do a screenshot myself because I'm not on macOS so it would look out of place with the other screenshots)

Thanks for a promising alternative to Cake. Cheers!

**Comment by matkoch** [comment]
fixed
