### ISSUE TITLE
Tags/categories for targets

### ISSUE THREAD

**Issue by robvanuden** [nuke-build/nuke#273]
As discussed in Slack, my idea was to make it possible to assign tags/categories to targets. Then it would be possible to skip targets by category, e.g.  "Test". 
For example `nuke --skip-category Test` would skip all test targets.

See https://nukebuildnet.slack.com/archives/C9Q99MFU0/p1556186659022100 for the discussion.

The key of the discussion was:
- It doesn't follow the current dependency model
- Shell completion is difficult

This issue is mainly for reference.

**Comment by matkoch** [comment]
Can be implemented with [trigger dependencies](http://www.nuke.build/docs/authoring-builds/fundamentals.html#trigger-dependencies).

**Comment by matkoch** [comment]
Triggers may not always be the solution. Here is a specific example with unit and integration tests:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/5005566/57248689-45f03280-7043-11e9-90f5-c6b79e7058ed.png">
