### ISSUE TITLE
add support compile arguments /p:CoreRT=true 

### ISSUE THREAD

**Issue by drearyrainDeng** [nuke-build/nuke#276]
add SetArguments function to support pass more param to compile.  it is more flexible to do something like [#132](https://github.com/nuke-build/nuke/issues/132)

**Comment by matkoch** [comment]
I’m not sure what this should mean.

**Comment by drearyrainDeng** [comment]
sorry ! i mean that if i want to get a native package by nuke (compile with corert),how should i do.  thank advance

**Comment by matkoch** [comment]
have you read this? http://www.nuke.build/docs/authoring-builds/cli-tools.html
