### ISSUE TITLE
build  nuke fail with vs2019 on win10

### ISSUE THREAD

**Issue by drearyrainDeng** [nuke-build/nuke#277]
i want to build local nuke package,but fail because path is wrong.  after installed vs2019  ,correct path is "C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Current\Microsoft.Common.props" 
![image](https://user-images.githubusercontent.com/35326823/57913099-73986f80-78be-11e9-8dd9-c2afb06487df.png)

**Comment by matkoch** [comment]
We recently discussed this on  [slack](https://nukebuildnet.slack.com/archives/C9Q99MFU0/p1557435857057600). I think it's a problem with msbuild. You can try changing the sdk version with a global.json file.
