### ISSUE TITLE
Issue with altissan pipeline

### ISSUE THREAD

**Issue by EMostafaAli** [nuke-build/nuke#278]
I create a build project using the nuke wizard. The project has two simple tasks: Restore and Compile (.NET core) project. It works great on my local machine. However, when I tried to run it using Altissan pipeline, it gives an error related to GitVersion.

```
NUKE Execution Engine version 0.19.2 (Linux,.NETStandard,Version=v2.0)
> /usr/bin/git rev-parse --abbrev-ref HEAD
> /usr/bin/dotnet /root/.nuget/packages/gitversion.commandline.dotnetcore/4.0.1-beta1-49/tools/GitVersion.dll
Process 'dotnet' exited with code 1.
   > /usr/bin/dotnet /root/.nuget/packages/gitversion.commandline.dotnetcore/4.0.1-beta1-49/tools/GitVersion.dll
   @ /opt/atlassian/pipelines/agent/build
StackTrace:
   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.<>c.<GetValue>b__4_0()
```

**Comment by matkoch** [comment]
Are you talking about Atlassian? Do you have a `gitversion.yml` file?

**Comment by EMostafaAli** [comment]
Oops, sorry. Yes, it is Atlassian.
I do have the yml file and I believe the error is Nuke looks for gitversion in user folder. When I run locally I see the following line.
`"C:\Program Files\dotnet\dotnet.exe" C:\Users\maali\.nuget\packages\gitversion.commandline.dotnetcore\4.0.1-beta1-49\tools\GitVersion.dll`

**Comment by matkoch** [comment]
Which executable should it use? From where?

**Comment by EMostafaAli** [comment]
dotnet.exe is installed in the vm and it works fine. I guess the question will be can we change the GitVersion.dll location to be located in the project folder.

**Comment by matkoch** [comment]
Sorry, I meant `GitVersion.dll`, but I doubt it's in the project folder

**Comment by matkoch** [comment]
You can also start nuke with `--verbosity verbose`.. that could maybe give more output.

**Comment by EMostafaAli** [comment]
I believe GitVersion nuget package install it in users folder as indicated above. When I  searched the project folder I couldn't locate it.

**Comment by EMostafaAli** [comment]
I created a sample project that show the error.
The [master branch](https://bitbucket.org/Emostafaali/nukegitsample/commits/branch/master) contains the initial project created by Nuke wizard. The [build result](https://bitbucket.org/Emostafaali/nukegitsample/addon/pipelines/home#!/results/1) shows an issue with GitVersion dll (before restore task).

In [B1 branch](https://bitbucket.org/Emostafaali/nukegitsample/commits/branch/b1), I set GiTVersion_EXE variable to a copy of GitVersion.dll inside project folder (that I copied manually), [still didn't work](https://bitbucket.org/Emostafaali/nukegitsample/addon/pipelines/home#!/results/2).

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/issues/278#issuecomment-493924477

**Comment by EMostafaAli** [comment]
I tried it locally but i didn't see any difference in the output. Please see screenshot below.
![image](https://user-images.githubusercontent.com/11354102/58053584-311ca000-7b15-11e9-8976-4a1b7e2b5bc5.png)

**Comment by matkoch** [comment]
build passes?

**Comment by matkoch** [comment]
Doesn't make much sense to pass `--verbosity verbose` locally,  if it works there.

**Comment by EMostafaAli** [comment]
For master branch, https://bitbucket.org/Emostafaali/nukegitsample/addon/pipelines/home#!/results/4
For b1 branch, https://bitbucket.org/Emostafaali/nukegitsample/addon/pipelines/home#!/results/3

**Comment by matkoch** [comment]
This is an issue with GitVersion and probably your container configuration.
