### ISSUE TITLE
TeamService.BuildNumber incorrectly using long

### ISSUE THREAD

**Issue by Skyqula** [nuke-build/nuke#279]
From the [AzureDevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) documentation:

> Build.BuildNumber => The **name** of the completed build. You can specify the build number format that generates this value in the pipeline options.

When a build number uses a custom format there is no guarantee that this variable will actually be a number. IE: When I use a the following build number format: `$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)`, I would expect a version along the lines of: "2019.5.20.1". With the current implementation this results in the following error: "##[error]Resolving parameter 'BUILD_BUILDNUMBER' failed."

I looked in the TeamServices class and found:
`public long BuildNumber => Variable<long>("BUILD_BUILDNUMBER");`

When I manually call `Variable<String>("BUILD_BUILDNUMBER")`, I get: "2019.5.20.5" and the build succeeds.

I therefor suggest fixing this by changing the BuildNumber to:
`public string BuildNumber => Variable<string>("BUILD_BUILDNUMBER");`

**Comment by robvanuden** [comment]
Note that the `UpdateBuildNumber` method already accepts a string as build number.
So yes, I agree.

https://github.com/nuke-build/common/blob/d8016926edd92a524b796ceeb1e1b32ee53364b1/source/Nuke.Common/BuildServers/TeamServices.cs#L84

**Comment by matkoch** [comment]
PR?

**Comment by RLittlesII** [comment]
@matkoch I can PR a fix for this in a few hours.
