### ISSUE TITLE
Microsoft.Build packages

### ISSUE THREAD

**Issue by VagyokC4** [nuke-build/nuke#280]
Using the Project.GetMSBuildProject() returns an error when/if the project is using Microsoft.Build.CentralPackageVersions to centralize the package versions.

```
<Project Sdk="Microsoft.NET.Sdk"> 
  
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.1" />

  <PropertyGroup>
    <ProjectType>NuGet</ProjectType>
    <TargetFramework>netstandard20</TargetFramework>
  </PropertyGroup>

</Project>
```

On projects without this < Sdk /> line, everything works as expected.  Is there a "work-around" we can employ until this officially gets fixed?

**Comment by matkoch** [comment]
`GetMSBuildProject` is just a wrapper around the `Microsoft.Build` nuget package. So this is not really the right place to ask this. I don't think we can do anything about it. Correct me if I'm wrong.

**Comment by VagyokC4** [comment]
Well @matkoch, since Visual Studio, Rider, dotnet-cli all can parse the project correctly when the CentralPackageVersions sdk is present...  and apparently Nuke cannot...  

Maybe you can look into see why it's not parsing correctly, especially since other tools have no problems parsing the .csproj file.  Is your Microsoft.Build / wrapper out of date?

**Comment by arodus** [comment]
Yep the Microsoft.Build package is @15.9.20 latest version is 16.0.461. But updating the versions isn't that simple since netstandard isn't supported anymore.
