### ISSUE TITLE
Missing NuGet.exe on Linux

### ISSUE THREAD

**Issue by eylvisaker** [nuke-build/nuke#281]
I have a build script that works great on Windows, but when I run it on Linux I get the following error:
```
Assertion failed: Could not find 'nuget.exe' inside '/home/erik/.nuget/packages/nuget.commandline/4.9.4'.
```
The target in my build.cs file is simple:
```
Target Restore => _ => _
        .After(Clean)
        .Executes(() =>
        {
            NuGetRestore(s => s);
        });
```

This happened right after the build script downloaded and installed the dotnet core sdk.

I can see two possible causes for this error message:
* The exe file is actually in /home/erik/.nuget/packages/nuget.commandline/4.9.4/tools
* The actual filename is 'NuGet.exe' and since this is a case sensitive filesystem, it can't find 'nuget.exeth

Not sure which is the relevant issue, or if both are. Any suggestions on how to fix or work around this issue?

**Comment by macsux** [comment]
Just heads up, nuget.exe doesn't run under core runtime. It can only run with limited functions under mono when on Linux. https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools

**Comment by matkoch** [comment]
it’s probably just the casing issue...

**Comment by eylvisaker** [comment]
Is there another way to restore packages in Nuke aside from NuGetRestore?

**Comment by macsux** [comment]
Should be able to do it via DotNetTasks.DotNetRestore
