### ISSUE TITLE
Try to run wrong target through msbuild

### ISSUE THREAD

**Issue by martonx** [nuke-build/nuke#282]
Hi,

I would like to run nuke from an msbuild target. In this case nuke try to run bad target. Here you are the details:

Check this msbuild example:

<Project DefaultTargets="ListAllTasks" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <Target Name="TestOne">
    <Exec Command="powershell nuke TestTwo" />
  </Target>
  <DeploymentTask Include="TestOne" />
</Project>

In my Build.cs there is only one target, what is TestTwo. When I run this Deployment like this:

msbuild.exe Test.msbuild -t:TestOne

I got this error:

Solution C:\...\Build.sln has an active build configuration for C:\...\Build.csproj.
  Target with name 'TestOne' is not available.
     at Nuke.Common.ControlFlow.Fail(String text)
     at Nuke.Common.Execution.ExecutionPlanner.GetExecutableTarget(String targetName, IReadOnlyCollection`1 executableT
  argets)
     at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Nuke.Common.Execution.ExecutionPlanner.GetExecutionPlan(IReadOnlyCollection`1 executableTargets, IReadOnlyColle
  ction`1 invokedTargetNames)
     at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1 defaultTargetExpression)

So it is strange Nuke should have run TestTwo, even from msbuild I ran TestOne, what is under itself run "powershell nuke TestTwo"

I found a solution when I add -target to PowerShell exec section, but I found this is a bug from side of nuke.

So <Exec Command="powershell nuke -target TestTwo" /> is working, <Exec Command="powershell nuke TestTwo" /> is finding TestOne, which is not existing in my Build.cs

**Comment by matkoch** [comment]
I don't really understand. You only have a target `TestOne` but execute it with `TestTwo`, so it's obvious there is no matching entry. I also see no reason to invoke the build from msbuild?

**Comment by martonx** [comment]
"I also see no reason to invoke the build from msbuild?" because of compatibility reasons, now I have to run it from msbuild.

```
<Target Name="TestOne">
     <Exec Command="powershell nuke TestTwo" />
 </Target>
```

So nuke should run TestTwo, even if I run it through msbuild with target TestOne.

**Comment by matkoch** [comment]
Sorry, but it’s still unclear. It is irrelevant from where you call nuke, whether it’s msbuild, batch or powershell. If you call it with a non-existent target, you’ll get an exception.

**Comment by matkoch** [comment]
We can't detect with which target msbuild was invoked. So this is a wrong assumption about how nuke works.
