### ISSUE TITLE
Upgrade Microsoft.Build package from 15.9.20 to latest version 16.0.461

### ISSUE THREAD

**Issue by VagyokC4** [nuke-build/nuke#283]
Can we get Microsoft.Build package updated to the latest release (v16.0.461) from the current (v15.9.20) so that projects that use the Microsoft.Build.CentralPackageVersions will work inside Nuke correctly?

[Microsoft.Build.Exceptions.InvalidProjectFileException](https://github.com/nuke-build/nuke/issues/280)

**Comment by matkoch** [comment]
Why a new issue?

**Comment by VagyokC4** [comment]
@matkoch You closed the other thinking there was nothing you could do.

**Comment by matkoch** [comment]
As @arodus mentioned, we can't update them. It's an issue with the `Microsoft.Build` packages.

**Comment by VagyokC4** [comment]
@matkoch So does that mean this project dies, as the rest of the dotNet world keeps marching forward towards dotNet5?  Or will this project keep moving into the future with the rest of the dot net world?

**Comment by matkoch** [comment]
I reopened the other issue, and the question isn't about whether we want to move forward or not. It's simply not possible to reference the package, as it targets netcoreapp2.1 and our library is netstandard. You're welcome to open an issue with the microsoft/msbuild repository.

**Comment by VagyokC4** [comment]
@matkoch So I have both netstandard2 and netcore2 projects which both use the Microsoft.Build.CentralPackageVersions and both project types load / run without issues.  Assuming MS is using it's latest Microsoft.Build package, is there really a problem?

**Comment by matkoch** [comment]
We are talking about the package reference in `Nuke.Common`. I.e., not your individuell project target frameworks.
