### ISSUE TITLE
Web project does not compile

### ISSUE THREAD

**Issue by mlaily** [nuke-build/nuke#285]
Hi,

I wanted to submit a PR for a dead link in the documentation, but I cannot build https://github.com/nuke-build/web

Things I did and problems I encountered before giving up:
- The first thing I did was execute build.ps1 - Unfortunately a global.json exists with a pinned .net core version I don't have, so it triggered the download and installation of the corresponding .net core sdk.
- I ran build.ps1 again, but I had a compilation error, so I tried to open the solution instead (with VS2019) - I couldn't because apparently I still didn't have the proper SDK, so I just removed global.json and had the solution load. (My .net core SDK version is 2.2.300, it it's important)
- The project Build.csproj does not build out of the box, with the following error:
```
Build.cs(57,29): error CS1061: 'PathConstruction.AbsolutePath' does not contain a definition for 'GlobDirectories' and no accessible extension method 'GlobDirectories' accepting a first argument of type 'PathConstruction.AbsolutePath' could be found (are you missing a using directive or an assembly reference?) [C:\git\nuke-web\build\_build.csproj]
```
I updated the `Nuke.Common` nuget package to the latest version available (0.20.1) and it fixed the error.
- I ran build.ps1 again, and it failed because `source\api` did not exist. This directory is created in the `Clean` target, which is skipped by default.
- I set the `DownloadPackages` target `WhenSkipped` behaviour to `DependencyBehavior.Execute` to force the `Clean` target to always execute so that the required directories are always created.
- I ran `build.ps1` again, and it failed because
```
Method 'get_CustomLogger' in type 'Nuke.DocFX.DocFXBuildSettings' from assembly 'Nuke.DocFX, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```
- I updated all the nuget packages to their latest available versions and it fixed the previous error.
- I ran `build.ps1` again, and it failed because `docfx.json does not exist!`.
- After some googling I found out I'm supposed to have this file generated by running `docfx.exe init -q` so I did that. It created a whole lot of things in a `docfx_project` subfolder.
- Not sure if it would be enough I tried copying the generated `docfx.json` file in the root folder of the repository and tried to run build.ps1 again.
- If finally succeeded, and I got a `Serving "C:\git\nuke-web\_site" on http://localhost:8080`. Unfortunately something is still wrong because the only file in the served directory is `manifest.json`

At this point I gave up and created this issue.

I'm not sure if I did something wrong, but in my opinion, cloning the repo and running build.ps1 should be enough to generate the doc. In the meantime, I will just submit a blind PR to fix my initial problem (dead link in the doc).

I'm happy to answer any question you may have :)

**Comment by matkoch** [comment]
Should be fixed now.
