### ISSUE TITLE
Support for anonymous targets and multiple target files

### ISSUE THREAD

**Issue by stevenlauwers22** [nuke-build/nuke#286]
Hi,

I'm in the process of migrating a build script from cake to nuke, however I seem to have run into an unsupported scenario.

I always try to make my build file as easy and readable as possible by only having some main targets that delegate all work to a bunch of child tasks. Example:

```C#
class Build : NukeBuild
{
    public static int Main() => Execute<Build>(x => x.CI);

    [Parameter]
    readonly Configuration Configuration = Configuration.Release;

    [Solution]
    readonly Solution Solution;
    
    Target CI => _ => _
        .DependsOn(x => x.Executes(() => Tasks.CompileSolution()))
        .DependsOn(x => x.Executes(() => Tasks.RunTests()))
        .DependsOn(x => x.Executes(() => Tasks.PackageWebApi()))
        .DependsOn(x => x.Executes(() => Tasks.PackageWebsite()));

    Target Publish => _ => _
        .DependsOn(x => x.Executes(() => Tasks.PublishWebApi()))
        .DependsOn(x => x.Executes(() => Tasks.PublishWebsite()));
}
```
Running this build script is giving me the following error:

```C#
System.InvalidOperationException: 'Sequence contains no matching element'
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Nuke.Common.Execution.ExecutableTargetFactory.<>c__DisplayClass0_1`1.<<CreateAll>g__GetDependencies|1>d.MoveNext()
   at NuGet.Packaging.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
   at Nuke.Common.Execution.ExecutableTargetFactory.CreateAll[T](T build, Expression`1 defaultTargetExpression)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1 defaultTargetExpression)
   at Build.Main() in F:\Steven\Werk\Digitize\Projects\Digitize.Admin\Digitize.Admin.Build\Build.cs:line 10
```
Apparently the ExecutableTargetFactory expects all Targets to be defined in the Build class, otherwise it won't find them. 

It would be really nice if targets could be defined in other classes than the nuke build file.
Also it would be nice to have some kind of anonymous target, below the CompileSolution is just an Action method wrapped in a Target delegate.
```C#
.DependsOn(x => x.Executes(() => Tasks.CompileSolution()))
```

**Comment by matkoch** [comment]
This is not how you use the framework. I suggest first reading the docs: http://www.nuke.build/docs/authoring-builds/fundamentals.html

**Comment by stevenlauwers22** [comment]
I have read the docs :).
This is more a feature request than an issue.

**Comment by matkoch** [comment]
Then this is a won't fix. I see no real value in this. You already can split the build class. Either by making it partial, or delegating to other static classes.

https://github.com/nuke-build/web/blob/master/build/Build.cs#L78
https://github.com/nuke-build/web/blob/master/build/CustomTocWriter.cs

or

https://github.com/nuke-build/common/blob/develop/build/Build.cs#L35
https://github.com/nuke-build/common/blob/develop/build/Build.CodeGeneration.cs#L15

**Comment by stevenlauwers22** [comment]
OK @matkoch, using partial classes is a reasonable solution.
Thanks for your feedback!
