### ISSUE TITLE
MSBuild properties with semicolon

### ISSUE THREAD

**Issue by Alxandr** [nuke-build/nuke#288]
`dotnet build` blows up if you provide a property with semicolon as such: `/property:NoWarn="CS1234;CS5678"`.

```
$ dotnet build /property:NoWarn="CS1234;CS5678"
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1006: Property is not valid.
Switch: CS5678

For switch syntax, type "MSBuild -help"
```

Currently, I do this in my nuke file: `"NU5105;CS7035".Replace(";", "%3B")`. There might be other solutions, but encoding should probably be handled by Nuke itself regardless.

**Comment by matkoch** [comment]
```
DotNetBuild(s => s
    .SetNoWarns(1234, 1234));
```

**Comment by Alxandr** [comment]
Then how about setting the property `AdditionalNoWarn` (that our build scripts use) to that?

**Comment by matkoch** [comment]
#326
