### ISSUE TITLE
DotNetTasks.DotNetNuGetPush Allow NonZeroExitCode?

### ISSUE THREAD

**Issue by VagyokC4** [nuke-build/nuke#289]
I'm currently using the following command to push up nuget packages
```
DotNetTasks.DotNetNuGetPush(s => s
	.SetSource(teamProject)
	.SetApiKey(apiKey)
	.SetTargetPath(nupkgFile)
	.SetLogOutput(true)
	.SetDisableBuffering(true)
	.SetForceEnglishOutput(true)
);
```
The problem occurs when the package already exists in the destination, and I get the following error:
```
##[error]error: Response status code does not indicate success: 409 (Conflict - The feed already contains...
```
I do not want to fail the build if the package already exists during from the push. 

How can I achieve this?

**Comment by matkoch** [comment]
http://www.nuke.build/docs/authoring-builds/fundamentals.html#failure-behavior
