### ISSUE TITLE
Add GitLink feature to nuget packages

### ISSUE THREAD

**Issue by vabka** [nuke-build/nuke#290]
https://github.com/GitTools/GitLink
It is impossible to read decompiled code
example: (Process2.cs)
```cs
    [return: TupleElementNames(new string[] {"Settings", "Result", "Output"})]
    public static IReadOnlyCollection<ValueTuple<TSettings, TResult, IReadOnlyCollection<Output>>> Invoke<TSettings, TResult>(
      this CombinatorialConfigure<TSettings> configurator,
      [TupleElementNames(new string[] {"Result", "Output"})] Func<TSettings, ValueTuple<TResult, IReadOnlyCollection<Output>>> executor,
      Action<OutputType, string> logger,
      int degreeOfParallelism,
      bool completeOnFailure)
      where TSettings : ToolSettings, new()
    {
      return (IReadOnlyCollection<ValueTuple<TSettings, TResult, IReadOnlyCollection<Output>>>) ConfigureExtensions.Invoke<TSettings, ValueTuple<TSettings, ValueTuple<TResult, IReadOnlyCollection<Output>>>>(configurator, (Func<TSettings, ValueTuple<TSettings, ValueTuple<TResult, IReadOnlyCollection<Output>>>>) (x => new ValueTuple<TSettings, ValueTuple<TResult, IReadOnlyCollection<Output>>>(x, executor(x))), (Func<ValueTuple<TSettings, ValueTuple<TResult, IReadOnlyCollection<Output>>>, IReadOnlyCollection<Output>>) (x => x.Item2.Item2), logger, degreeOfParallelism, completeOnFailure).Select<ValueTuple<TSettings, ValueTuple<TResult, IReadOnlyCollection<Output>>>, ValueTuple<TSettings, TResult, IReadOnlyCollection<Output>>>((Func<ValueTuple<TSettings, ValueTuple<TResult, IReadOnlyCollection<Output>>>, ValueTuple<TSettings, TResult, IReadOnlyCollection<Output>>>) (x => new ValueTuple<TSettings, TResult, IReadOnlyCollection<Output>>(x.Item1, x.Item2.Item1, x.Item2.Item2))).ToList<ValueTuple<TSettings, TResult, IReadOnlyCollection<Output>>>();
    }
```

**Comment by matkoch** [comment]
so?

**Comment by arodus** [comment]
@vabka we already provide nuget symbol packages for all our libraries. So normally there should be no need for your IDE to decompile the lib. 
You may have to add the nuget symbol server url to your symbol sources see https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/  for references.

The only advantage of gitlink over symbol packages is that you don't have to specify symbol server, but since we are using the officially nuget feed, which is a pretty default one, I can't see an urge to add gitlink right now. 
Or are there any other benefits i missed?

**Comment by vabka** [comment]
Maybe, i am blind, but i cant see "download symbols" button in nuget. Also, i had tried to navigate into methods - decompiles on-fly. I think, this is a bug (or missed feature) on Rider for Mac OS. I will check this later
![image](https://user-images.githubusercontent.com/17644379/60523286-e4c3a300-9d03-11e9-95c3-ef24f37e9575.png)

**Comment by vabka** [comment]
On windows - all the same, and in VS too

**Comment by arodus** [comment]
You are right, the symbols are actually missing seems we missed something when switching to the new `snupkg` format. We are going to fix the issue and either publish the symbols for the current package or releasing a new version with symbols. 

Other than that there is currently no plan on adding GitLink as long as it has the same features as the nuget built-in solution. 

PS:  Did you manage to find any package on Nuget.org where the download link to the symbols package  is actually there?

**Comment by matkoch** [comment]
Should be fixed with 0.21.1.

**Comment by vabka** [comment]
I cant find any package with "download symbols" link

**Comment by matkoch** [comment]
![image](https://user-images.githubusercontent.com/5005566/61625973-51cfb600-ac7c-11e9-97c0-c9ab340c6765.png)
