### ISSUE TITLE
Didn't find ability to list targets by default 

### ISSUE THREAD

**Issue by alexanium-dev** [nuke-build/nuke#291]
I'm porting build script from Cake and can't find API for listing all targets if no target specified (`runOrList` in FAKE) or for accessing targets list (`Tasks` property in Cake). Second is better because I want to apply different colours for names and descriptions.

The closest match I could find is `NukeBuild.ExecutableTargets` but it is internal

**Comment by matkoch** [comment]
If you remove the default target, i.e. no lambda in `Main`, then a list of targets is printed when the build is invoked with no target.
