### ISSUE TITLE
Calling ParseProject breaks NuGetTasks for .NET Framework projects

### ISSUE THREAD

**Issue by totollygeek** [nuke-build/nuke#292]
If you use `ProjectModelTasks.ParseProject` somewhere in a Target, this will populate the environment variable `MSBUILD_EXE_PATH` with path do `MSBuild.dll` in dotnet/sdk folder. 

When you call `NuGetRestore`, for example, afterwards, on a project that is NOT .NET sdk, you will get an error that `NuGetResolver.dll` could not be loaded. 
The problem occurs, because this will tell `nuget.exe` to work with `MSBuild`, which is not compatible.

**Comment by arodus** [comment]
https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/ProjectModel/ProjectModelTasks.cs#L42-L44

That's the relevant code, probably reverting the variable afterwards is enough.
