### ISSUE TITLE
Jenkins class uses a false (?) environment variable to determine branch name

### ISSUE THREAD

**Issue by markusamshove** [nuke-build/nuke#293]
Currently the implementation of Jenkins uses [GIT_BRANCH](https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/BuildServers/Jenkins.cs#L54) to determine the branch name.

I'm not sure if there is a plugin in Jenkins where this works.
In our setup, the environment variable would be `BRANCH_NAME` as described [here](https://jenkins.io/doc/book/pipeline/multibranch/#additional-environment-variables)

**Comment by arodus** [comment]
> I'm not sure if there is a plugin in Jenkins where this works.

The comment in the code says `[...] ﻿(all the Git* properties require git plugin).` ;) 

The `BRANCH_NAME` variable is a feature specific to multibranch pipelines and is afaik not populated in other pipeline types. 
Contrary to the `GIT_BRANCH` variable which is introduced by the [Git Plugin](https://wiki.jenkins.io/display/JENKINS/Git+Plugin#GitPlugin-AdvancedFeatures) (scroll down to environment variables) and should be populated in all pipeline types.

**Comment by markusamshove** [comment]
`GIT_BRANCH` wasn't populated in our builds, leading to errors in the Nuke build :-)

We're also using `BRANCH_NAME` in all our pipeline libraries.

Couldn't we try both environment variables in when asking Jenkins for the branch name?

**Comment by matkoch** [comment]
We can add another property for access, but I’m against implementing fallback logic in the original Jenkins class. There will be an abstraction some day, where we can make things a bit smarter.

**Comment by arodus** [comment]
As matkoch said we can add another property and add that one after https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/Git/GitRepositoryAttribute.cs#L43.
No need for a a fallback in the Jenkins class, essentially the vars return different things.
