### ISSUE TITLE
Cannot install sonarscanner nuget package in a nuke build project

### ISSUE THREAD

**Issue by Rick-van-Dam** [nuke-build/nuke#294]
I have issues getting sonarscanner to work with NUKE build. Seems this is a bug in NUKE: https://github.com/SonarSource/sonar-scanner-msbuild/issues/761

NUKE wants me to install `dotnet-sonarscanner` but you cant since its a DotNet tool package:
```
c:\Git\Website\build\_build.csproj : error NU1202: Package dotnet-sonarscanner 4.6.2 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package dotnet-sonarscanner 4.6.2 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any

c:\Git\Website\build\_build.csproj : error NU1212: Invalid project-package combination for dotnet-sonarscanner 4.6.2. DotnetToolReference project style can only contain references of the DotnetTool type 
```

 Instead I think it should be a package like `SonarAnalyzer.CSharp`

**Comment by matkoch** [comment]
That’s correct. You need to exclude assets. See https://github.com/nuke-build/nuke/issues/274

**Comment by Rick-van-Dam** [comment]
This fixes it!
