### ISSUE TITLE
ControlFlow.Fail should throw its own exception

### ISSUE THREAD

**Issue by totollygeek** [nuke-build/nuke#296]
As a general rule of [Framework design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types), you should not throw base types of exceptions like `System.Exception`. This prevents better exception handling by consuming code.

I suggest that `ControlFlow.Fail` should be changed to use its own type of exception and also introduce another generic method. Something like that:
```
public static void Fail<TException>()
      where TException : Exception, new() 
 {
     throw new TException();
 }
```
which can be used to specify what type of exception you want to throw. This second one is not a must, more like nice to have.

**Comment by matkoch** [comment]
I'm indifferent whether this is needed or not. _Fail_ generally means there is no way to recover to a valid state, and only cleanup code should be executed.

**Comment by jgn-epp** [comment]
I'd like to take a crack at this one 🙂
