### ISSUE TITLE
setup.ps1 is broken

### ISSUE THREAD

**Issue by evil-shrike** [nuke-build/nuke#3]
I followed the bootstrap procedure from the site.
```
powershell -Command iwr https://nuke.build/powershell -OutFile setup.ps1
powershell -ExecutionPolicy ByPass -File ./setup.ps1
```
But this is all I got - console output:
0.1.277

Looked into setup.ps1 to found:

```
[CmdletBinding()]
Param()

$LatestVersion = $(Invoke-WebRequest https://api-v2v3search-0.nuget.org/query?q=packageid:Nuke.Common | ConvertFrom-Json
).data.version
Write-Host $LatestVersion

exit
```

**Comment by matkoch** [comment]
@evil-shrike sorry, that happened accidental. It belonged to another branch. Should be fixed now. Could you check?

**Comment by evil-shrike** [comment]
Now it's ok, thanks.

But there's another issue.
run `powershell ./setup.ps1`, it fails with error:
Unable to determine root directory (containing .git or .svn folder)
At D:\Work\R-n-D\XFW3\Sources\Foundation\Repo-netcore\Build\nuke\setup.ps1:49 char:30

After that setup.ps1 disappears.

**Comment by matkoch** [comment]
We are currently assuming that you're executing the script in a repository that already is version-controlled (with GIT or SVN). Thus it looks for a `.git` or `.svn` folder. Could you check that?

The setup script is automatically deleted at the beginning of itself. If you need it for further investigation, then first download it, and out-comment the deletion from [here](https://github.com/nuke-build/nuke/blob/master/bootstrapping/setup.ps1#L4). I agree that we need better error messages for this.

**Comment by evil-shrike** [comment]
I have no .git or .svn at all in that project, it uses TFS. Anyway it's strange to delete the script in case of an error.

**Comment by matkoch** [comment]
Will TFS leave a similar folder in the root directory?

**Comment by evil-shrike** [comment]
No. No honestly it's unclear why a build tool should care about VCS. It could search for a sln and ask for path to it.

**Comment by matkoch** [comment]
It is to find the root, and from there search 2-levels downwards for solution files (based on that, you'll be asked). This is actually only used during setup, and nowhere else. I will update the setup scripts to be able to pass the root directory via argument.

**Comment by matkoch** [comment]
@evil-shrike I've made a couple of changes:

- Scripts are only deleted if successful
- Root directory is _attempted_ to be determined by finding _.git_ or _.svn_ upwards, otherwise it falls back to the _current directory_
- Website contains [troubleshooting](http://www.nuke.build/getting-started.html#troubleshooting) part

Let me know if you think we can improve anything else )

**Comment by evil-shrike** [comment]
cool, build project was generated successfully.

but it failed to run via build.ps1:
```
Package "Nuke.MSBuildLocator.0.1.228" is already installed.
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 06.09.2017 15:53:24.
Project "D:\Work\...\Repo-netcore\Src\build\.build.csproj" on node 1 (default targets).
D:\Work\...\Repo-netcore\Src\build\.build.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
```

`build\.build.csproj` is the generated build project w/o any modification. 
If I run `dotnet build` with it then it's built w/o any error.

**Comment by matkoch** [comment]
I saw this issue reported quite often recently (outside of Nuke). Could you check which version of .NET Core you've installed? For better troubleshooting I can also suggest you to join our [Gitter room](https://gitter.im/nuke-build/nuke).

Actually, the `dotnet` based builds are in work, but not yet ready.

**Comment by matkoch** [comment]
Might be related to https://github.com/dotnet/cli/issues/6827.

**Comment by evil-shrike** [comment]
> .NET Core 

sdk 2.0 rtm + VS 2017.3

>Actually, the dotnet based builds are in work, but not yet ready

Ok, I see.

**Comment by matkoch** [comment]
You could add `/v:diag` to [this call](https://github.com/nuke-build/nuke/blob/master/bootstrapping/build.ps1#L43) and list the output here. But maybe in another issue then )
