### ISSUE TITLE
Add dotnet msbuild support

### ISSUE THREAD

**Issue by RLittlesII** [nuke-build/nuke#301]
I have some builds that need `dotnet msbuild` to integrate with [MSBuild.Sdk.Extras](https://www.nuget.org/packages/MSBuild.Sdk.Extras/)

https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-msbuild.md

**Comment by andrewlock** [comment]
Hi @matkoch, I've just found a need for `dotnet msbuild` too - was there a reason the associated PR for this fix was never merged?  I'm assuming it shouldn't be too hard to add - would you be happy to take a PR?

**Comment by matkoch** [comment]
@andrewlock i don't remember. I think we discussed it on slack, which is now lost (because of the free plan). I'll check again..

**Comment by RLittlesII** [comment]
I don't remember either at this point.  This was so long ago.  I can clean up the PR if need be.
