### ISSUE TITLE
Setup documentation - Users NuGet packages folder

### ISSUE THREAD

**Issue by RobSmyth** [nuke-build/nuke#305]
Hi,

The setup described at https://nuke.build/docs/getting-started/setup.html assumes that a user has NuGet installed and has loaded some global package (to the user's .nuget/packages folder). It fails with an exception if this folder does not exist.

We found that as we use VS to load NuGet packages to a project folder many developers did not have the requires users packages folder. The fix was to ask NuGet to install a sample package when not in a project folder.

It would be great if the setup was updated.

**Comment by matkoch** [comment]
What part exactly assumes that a global package folder exists?

**Comment by RobSmyth** [comment]
Hi,

The line "nuke :setup" fails with an error message that the user's packages folder does not exist.

The fix is to download NuGet.exe and from a separate folder install any NuGet package (say NUnit). This creates the user's packages folder and then all is fine.

So, if the user has not used NuGet before, to install user global packages, it fails.

**Comment by matkoch** [comment]
Do you get a stacktrace?

**Comment by matkoch** [comment]
@RobSmyth 	?
