### ISSUE TITLE
Request: add tool attribute for absolut paths and custom resolvers

### ISSUE THREAD

**Issue by penenkel** [nuke-build/nuke#306]
AFAIK there are three tool resolution attributes at the moment:

- PathExecutable: retrieves tool-path from environment variable or path variable (via which).
- LocalExecutable: resolves tools relative to the repository-root
- PackageExecutable: resolves from nuget package

From my point of view there should also be one that allows specifying an absolute path. (I know this wouldn't all that robust with regard to portability, but sometimes this would be expedient. ATM I work around this by defining an environment variable in the constructor.)

An other idea would be an attribute that allows specifying a custom resolution function for more complex path calculations.

**Comment by matkoch** [comment]
I’d rather not add another attribute, but i will think if we can make the `LocalExecutableAttribute` to also work with rooted paths.

**Comment by matkoch** [comment]
PS: feature requests require adding a star :)
