### ISSUE TITLE
Guidance on code generation

### ISSUE THREAD

**Issue by mlaily** [nuke-build/nuke#308]
Hi,

I'm trying to create a tool to wrap the InnoSetup compiler command line.

My tool now almost works, but I ran into a few issues and I would appreciate some guidance:
- Is there some centralized documentation about how to write a new tool? I could not find any. For now I cloned your template repository and incrementally managed my way around by testing various things.
- InnoSetup has some flags with a strange syntax, like /O+ or /O-, to enable or disable the flag. What would be the best way to map them to a boolean property? For now I implemented a `customValue` property where I return `+` or `-` based on the boolean value.
- Another InnoSetup quirk is the way some key value arguments can be set multiple times, like `/DAppVersion="1.12.0.1282" /DBuildConfig="Debug"` to override preprocessor defines. What would be the best way to map this into Nuke? For now I map them on a `Dictionary<string, string>` with `"format": "{value}"` and `"itemFormat": "/D{key}={value}"`, but apparently Nuke explicitly disallows this, and wants exactly one extra character in the `itemFormat` beside the key and value. I did some testing where I removed the `ControlFlow.Assert(listSeparator.Length == 1, "listSeparator.Length == 1")` and it seems to work well...

I did not test it yet, but the `/D` arguments' values are optional. (sometimes, only the key would be set) I'm not sure it's a case handled by Nuke. What do you think?

For reference, my current json is here: https://github.com/mlaily/nuke-innosetup/blob/master/src/Nuke.InnoSetup/InnoSetup.json, and the InnoSetup compiler help page output is here: https://github.com/mlaily/nuke-innosetup/blob/master/src/Nuke.InnoSetup/InnoSetup.ref.000.txt

This issues is getting big, but I have a last question: when I manage to have something cleaner, how/where should I publish this tool? (Should it be a PR into Nuke.Common? a separate repo but managed by the Nuke community? A separate repo? Can I use the reserved Nuke prefix on nuget or should I use another?)

Thanks.

**Comment by matkoch** [comment]
Hi @mlaily,

thanks for approaching with a PR :) I'm a bit short on time right now, but I will leave some notes on the bullet point set. Let me know if it helps.

- A bit of documentation is [here](http://www.nuke.build/docs/writing-addons/code-generation.html), but probably you know that already.
- PR would go directly into nuke/common.
- for the `/O+` and `/O-` you probably need to set `customValue` to `true` for this property ([example](https://github.com/nuke-build/common/blob/c8389968de801553fc2be8e8206b7366bbc6e936/build/specifications/MSBuild.json#L46-L51)). that will leave you with a compile error that you can fix by adding a partial file and implementing the missing method manually.
- Just define `"format": "/D{key}={value}"` and remove `itemFormat`. that should work!

**Comment by matkoch** [comment]
And about _sometimes value, sometimes not_... not sure if we support that, but could be. Just try adding another property - different name obviously - but with the same format. Type should be `List<string>` in that case.

**Comment by matkoch** [comment]
PS: sorry for your other issue being unanswered. I haven't had any time taking care of the website recently. Will try to follow up asap.

**Comment by mlaily** [comment]
Thanks for your quick answer :)

I will try your suggestions and see how it goes.

And no worries about my other issue. I wanted to document my experience somewhere useful, but it's not something very urgent, so I did not expect an answer immediately...

**Comment by mlaily** [comment]
> Just define "format": "/D{key}={value}" and remove itemFormat. that should work!

It does not work for at least one reason: the `{key}` format pattern is not replaced by the key. :/

The only "correct" solution I see is keeping the `itemFormat` and modifying `Arguments.cs` to remove the assertion causing the failure. Disallowing the key-value separator would not be automatic when `Length > 1`.

> And about sometimes value, sometimes not... not sure if we support that, but could be. Just try adding another property - different name obviously - but with the same format. Type should be List<string> in that case.

Unfortunately this is not enough, because the `itemFormat` is not used when the `type` is a `List<>`.
I also tried to play with the `separator` property, but it's a `char`, not a `string`, so I can't cheat and set it to " /D".

I can probably manage to do these changes and create a PR, but it seems like these are a bit risky and far reaching, so I wonder whether I'm trying to do something that I'm not supposed to.

What do you think?

**Comment by matkoch** [comment]
can you please give me a few invocation examples?

**Comment by mlaily** [comment]
Sure!

We use this one:
`iscc /O+ /OC:\git\MyProject\setup\bin   /FMyProject-1.13.0.1282    /DAppVersion=1.13.0.1282   /DBuildConfig=Release    C:\git\MyProject\setup\MyProject.iss`

There are other examples on the official iscc documentation:
http://www.jrsoftware.org/ishelp/index.php?topic=compilercmdline
`iscc /Qp /O"My Output" /F"MyProgram-1.0" /Sbyparam=$p "c:\isetup\samples\my script.iss"`

**Comment by matkoch** [comment]
I was wrong about the dictionary part. It should be `format:"/D{value}"` and `itemFormat:"{key}={value}"`. There should be no exception then.

**Comment by mlaily** [comment]
Thanks, it works :)

Some examples in the documentation for cases like that would be welcome!

**Comment by matkoch** [comment]
This example is linked: https://github.com/nuke-build/common/blob/develop/build/specifications/DotNet.json#L698-L699

To me it seems that exactly the case.

**Comment by matkoch** [comment]
Any questions left?

**Comment by mlaily** [comment]
> This example is linked: https://github.com/nuke-build/common/blob/develop/build/specifications/DotNet.json#L698-L699
>To me it seems that exactly the case.

Mmh ok. I was under the impression it would only output the `format` value once, then the `itemFormat` as many times as there are pairs.

Some examples with the resulting output would still be welcome. :)

And I think that's all, thanks again!

**Comment by matkoch** [comment]
> Some examples with the resulting output would still be welcome. :)

I prefer helping on demand :)
