### ISSUE TITLE
Add support for Yarn

### ISSUE THREAD

**Issue by joskoanicic** [nuke-build/nuke#309]
It would be great if yarn was supported as npm. 

I think someone mentioned in other issues that they implemented the tools for Yarn. Maybe they could send a PR?

**Comment by matkoch** [comment]
You can also send a PR

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/issues/259
https://github.com/nuke-build/nuke/blob/master/CONTRIBUTING.md

**Comment by joskoanicic** [comment]
I will try to find time to write an extension and send a PR. 
It would be helpful if there is a way to get a crash course or read what I need to know about the architecture before getting started. Or should I just get into the code and analyse how npm support works?

**Comment by matkoch** [comment]
Help is available here: http://www.nuke.build/docs/writing-addons/code-generation.html

If you need any help, it's best to ask in Slack.
