### ISSUE TITLE
Issue finding Package Executable when using Microsoft.Build.CentralPackageVersions

### ISSUE THREAD

**Issue by david-driscoll** [nuke-build/nuke#312]
I've run into a strange issue upgrading to `0.22.2` from `0.21.2` which I can't trace down the change in the code that would have caused this to popup.  Note this currently works on `0.21.2` without any errors or problems.

I have created a repository that demonstrates this issue here:
https://github.com/david-driscoll/nuke-gitversion

I'm getting the following error while the build starts up, and then `GitVersion` is null.`
```
Assertion failed: packageDirectory != null
StackTrace:
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.<GetValue>b__8_0()
```

This error prevents the code from ever finding the verison of `GitVersion`.

Basically what's happening is `Microsoft.Build.CentralPackageVersions` centralizes all the package versions into a common `.props` file. `Packages.props` for example.  And then the project files only have `<PacakgeReference Include="GitVersion.CommandLine.DotNetCore" />` without the version metadata.  

Also this will fail to work with existing code (which is technically for a `PackageReference`.
```
    <PackageReference Include="Nuke.Common" Version="0.22.0" />
    <PackageReference Include="GitVersion.CommandLine.DotNetCore">
      <Version>5.0.1</Version>
    </PackageReference>
```

My best guess is that there is a change of `resolveDependencies` when calling `NuGetPackageResolver.GetLocalInstalledPackage`.  The latest version adds the `version` parameter, and removes `resolveDependencies: false`.
https://github.com/nuke-build/common/compare/0.21.2...0.22.0#diff-bd10216e86fee8efa01d32dc4cfb478d
![image](https://user-images.githubusercontent.com/1269157/65277698-80d99b00-daf8-11e9-8d02-9c9d80f58504.png)

Where the default value is true here:
https://github.com/nuke-build/common/compare/0.21.2...0.22.0#diff-ff1356e2ed38bc7bc09f93075cb7c46dL42-L58
![image](https://user-images.githubusercontent.com/1269157/65277762-9cdd3c80-daf8-11e9-85fc-c496764408c4.png)

I do have a workaround which ideally I'd like to avoid if possible, and that's to use `PackageDownload` instead of `PackageReference` for these items.

cc @RLittlesII

**Comment by matkoch** [comment]
@david-driscoll thanks for the detailed report. Frankly, the `packages.props` approach was never actually supported. What happened before was that always the latest version would have get picked. There was another change to [support multiple versions of the same tool](https://github.com/nuke-build/common/commit/f364f5bddd1a9b466f0981df29a82fbf043f7619), which is also directly contradictory to your use case. The `NuGetPackageResolver` was always a very naive approach that only does a few Xpath queries. Supporting your use case would require to get the MSBuild engine involved, which is kind of a scary move, to be honest. In my opinion, a `packages.props` doesn't seem to provide much value in the context of a build project. It likely references much different packages than the actual production code, and diverging versions seem unlikely to be an issue. What are your thoughts?

**Comment by matkoch** [comment]
Btw, why do you see `PackageDownload` as a workaround to avoid? It's actually the best thing that could happen to nuke, because it avoids putting `PrivateAssets=All` all around.

**Comment by david-driscoll** [comment]
Mainly around tooling like `dotnet-outdated`, `nukeeper`, etc don't know it exists so it's harder to know when you have outdated dependencies.

Would you consider using `*.deps.json` as a secondary source for version information?  I'd be willing to get a PR out for that if it's something you might take. (Otherwise no point 😄)

Basically we could just look for a `bin/*/**.deps` file relative to the project file, if the file is found we can find the specific version from the `targets` or `libraries` entries in that file.

**Comment by matkoch** [comment]
I was actually considering that at some point, but also don’t remember why it was discarded. I guess it was conflicting with the “global tool” sharing approach, but afaics this is no longer an issue. So PR is welcome.  Not sure where it would fit in `NuGetPackageResolver`.
