### ISSUE TITLE
NuGetRestore throws Assertion failed: packageDirectory != null

### ISSUE THREAD

**Issue by danielmpetrov** [nuke-build/nuke#313]
Hi,

I have a relatively simple .NET Framework Solution that I'm trying to convert from Cake to Nuke.

It contains 1 ASP.NET MVC project, 1 ASP.NET Web API project, and a few class libraries, everything targetting .NET Framework 4.5.2 if that makes a difference.

All the projects use `packages.config` to restore NuGet packages.

I've been reading the `cake.build` file and translating it to C# with Nuke, and it works _great_, but I cannot make the following Cake line to work in Nuke.

```csharp
NuGetRestore("./folder/Solution.sln");
```
I thought the Nuke equivalent would be

```csharp
NuGetTasks.NuGetRestore(settings => settings.SetTargetPath(Solution));
```

but whatever configuration and arguments I tried setting to `NuGetTasks.NuGetRestore()`, I always end up with the following exception

```powershell
Assertion failed: packageDirectory != null
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.NuGet.NuGetTasks.NuGetRestore(NuGetRestoreSettings toolSettings)
   at Build.<>c.<get_Restore>b__9_1() in C:\Folder\SomeProject\build\Build.cs:line 33
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

I tried setting the `TargetPath`, `ConfigFile`, `PackagesDirectory`, `SolutionDirectory`, all the same.

Since every other line in a ~100 lines `cake.build` file translated so well, I must be missing something here, and I don't know where to look.

I could not find any examples in the docs, online, or in the NukeBuild.Common source code of how to use the `NuGetRestore()` method.

Thank you.

**Comment by pkudrel** [comment]
Hi,

I can't help you with `NuGetRestore()`, but I can tell you how I deal with the restore task. I use the standalone version of `Nuget`.

```
    Target Restore => _ => _
        .DependsOn(Clean)
        .Executes(() =>
        {
            using (var process = ProcessTasks.StartProcess(
                NugetPath,
                $"restore  {Solution.Path}",
                SourceDir))
            {
                process.AssertWaitForExit();
                ControlFlow.AssertWarn(process.ExitCode == 0,
                    "Nuget restore exited with some errors.");
            }
        });

```

**Comment by matkoch** [comment]
Please try 0.21.0

**Comment by matkoch** [comment]
And I assume you're having a similar issue as #312. Otherwise, I need a repro.

**Comment by danielmpetrov** [comment]
@matkoch Thanks for the help.

The problem was I did not install the `NuGet.CommandLine` package in the `_build` project.

Downgrading to `Nuke.Common 0.21.2` displayed a proper message like so

```powershell
Assertion failed: Could not find package 'NuGet.CommandLine' [...]
```

After that the build works even with `Nuke.Common 0.22.0`

**Comment by matkoch** [comment]
The previous assertion message is already back in place.

**Comment by danielmpetrov** [comment]
@pkudrel Thanks for the input.

For my purpose, to simply restore solution packages, the following line works

```csharp
NuGetTasks.NuGetRestore(settings => settings.SetTargetPath(Solution));
```

My mistake was not installing the `NuGet.CommandLine` package, and Nuke was not outputting a proper message.

**Comment by matkoch** [comment]
@danielmpetrov btw, the relevant docs are here: https://nuke.build/docs/authoring-builds/cli-tools.html

**Comment by danielmpetrov** [comment]
@matkoch ah yes, thank you. I had seen that page before creating the issue, I even read the blue note on top, but my brain didn't register. The error message really threw me off.
