### ISSUE TITLE
dotNetCoverage not working with TeamCity bundled version of dotCover

### ISSUE THREAD

**Issue by donandren** [nuke-build/nuke#319]
dotNetCoverage import is not working when bundled version of dotCover in TeamCity is incompatible with referenced version of dotCover in build.
for example in my scenario: TC bundled version of dotCover is `2017.2.2`, build project use version `2019.2.2`

example code:
``` C#
TeamCity.Instance.ImportData(TeamCityImportType.dotNetCoverage, 
"report.dcvr", TeamCityImportTool.dotcover, verbose: true);

```

in order to fix it i needed to manually force TeamCity use same version from build script like:

``` C#
//force teamcity use dotCover from the nuke referenced version
TeamCity.Instance.Write("dotNetCoverage", 
d => d.AddKeyValue("dotcover_home", DotCoverTools.DotCoverPath));

TeamCity.Instance.ImportData(TeamCityImportType.dotNetCoverage, 
"report.dcvr", TeamCityImportTool.dotcover, verbose: true);
```

this way everything is working fine.

But it would be nice Nuke have something baked to force use dotCover version from the build script :)

**Comment by matkoch** [comment]
What error do you get otherwise?

I think this is a good situation for the `PostProcess` extension. I'm just not sure yet, if we should set it right away, or just print out a warning, and suggest the user to add a special attribute `TeamCityAutoChangeDotCoverPath` to the build class.

**Comment by akunchev** [comment]
that's the first error in teamcity, it's logged after the build is finished:
> [21:57:37][Merge dotCover reports] Started dotCover: E:\TeamCity\BuildAgent2\tools\JetBrains.dotCover.CommandLineTools.bundled\dotCover.exe merge E:\TeamCity\BuildAgent2\temp\buildTmp\dotcover1256239472018797868.xml
> [21:57:37]
> [Merge dotCover reports] Output: JetBrains dotCover Console Runner 2017.2.2. Build 109.0.20171006.131113
> Copyright (c) 2009-2019 JetBrains s.r.o. All rights reserved.
> [JetBrains dotCover] Snapshot merging started [10/5/2019 11:57:37 AM]
> [JetBrains dotCover] Source snapshots number: 1
> [21:57:37][Merge dotCover reports] [JetBrains dotCover] Failed to merge snapshots. Unknown version of section 0: version=8, available=2, 3, 4, 5, 6, 7. Unknown version of section 0: version=8, available=2, 3, 4, 5, 6, 7
> [21:57:37]
> [Merge dotCover reports] 
> [21:57:37][Merge dotCover reports] dotCover exited with code: -2
> [21:57:37][Merge dotCover reports] dotCover returned non-zero exit code.

in Cake can be set right away - https://github.com/cake-build/cake/blob/a0f142af2dfbf18eecc240789529da428cb0d82a/src/Cake.Common/Build/TeamCity/TeamCityProvider.cs#L235-L257

**Comment by matkoch** [comment]
Actually, I meant `PreProcess` extension point. I will add this for the next version. Thanks for pointing out!

**Comment by matkoch** [comment]
@donandren / @akunchev I thought about it. I think I'm against setting anything automatically, because it would become impossible to change the behavior to anything else which we don't consider correct. Stating things clear is a better solution in my opinion. However, I still look at this as a common pitfall. What would you think about warning the user in `TeamCity.ImportData`, when `DOTCOVER_HOME` ends with `bundled` ? We could then suggest to set it manually to `DotCoverTasks.DotCoverPath`. We could still use a special attribute, or advice to add the statement `TeamCity.Instance.SetParameter("DOTCOVER_HOME", ...)`.

**Comment by matkoch** [comment]
Attribute as follow. I'm open to different naming suggestions, but I think it should start with `DotCover`. Maybe you could confirm that it works.

```
[PublicAPI]
[AttributeUsage(AttributeTargets.Class)]
public class DotCoverSetPathOnTeamCityAttribute : Attribute, IOnAfterLogo
{
    public void OnAfterLogo(NukeBuild build, IReadOnlyCollection<ExecutableTarget> executableTargets, IReadOnlyCollection<ExecutableTarget> executionPlan)
    {
        TeamCity.Instance?.SetConfigurationParameter("DOTCOVER_HOME", DotCoverTasks.DotCoverPath);
    }
}
```

The new assertion in `TeamCity.ImportData` would look like this:

```
ControlFlow.AssertWarn(
    tool == TeamCityImportTool.dotcover &&
    ConfigurationProperties["DOTCOVER_HOME"].EndsWithOrdinalIgnoreCase("bundled"),
    new[]
    {
        "Configuration parameter 'DOTCOVER_HOME' is set to the bundled version.",
        $"Add the '{nameof(DotCoverSetPathOnTeamCityAttribute)}' to automatically set " +
        $"it to '{nameof(DotCoverTasks)}.{DotCoverTasks.DotCoverPath}'."
    }.JoinNewLine());
```

**Comment by donandren** [comment]
` TeamCity.Instance?.SetConfigurationParameter("DOTCOVER_HOME", DotCoverTasks.DotCoverPath);`
is not working properly :(

proper initialization should be 
```
TeamCity.Instance?.Write("dotNetCoverage", 
d => d.AddKeyValue("dotcover_home", DotCoverTools.DotCoverPath));
```

btw DotCover might be a private case for all test coverage tools, all other can have potentially same issues:
https://www.jetbrains.com/help/teamcity/manually-configuring-reporting-coverage.html

**Comment by matkoch** [comment]
Yes, it should be `TEAMCITY_DOTCOVER_HOME`.

I see the issue about other tools, but we currently only support dotCover. Open for PRs though.

**Comment by donandren** [comment]
`TeamCity.Instance?.SetConfigurationParameter("TEAMCITY_DOTCOVER_HOME", DotCoverTasks.DotCoverPath);` is also not  working properly
