### ISSUE TITLE
Question: building multiple repositories w/ nuke

### ISSUE THREAD

**Issue by SalahEddin** [nuke-build/nuke#321]
My setup uses multiple repositories to build my tool, I have the following folder structure:
|- Engine
---|- Engine.sln
|- Config
---|- Config.sln
|- Runtime
---|- Runtime.sln

Should I place nuke in my Engine repo, or a new build repo?

**Comment by SalahEddin** [comment]
The docs mention
```
Firstly, builds are invokable from any directory beneath the root directory. More specifically, the global tool will search for the .nuke marker file upwards the current directory and then search for build.ps1 or build.sh from there.
```
that means my `.nuke` will have to be at the root, right?

**Comment by matkoch** [comment]
Usually the `.nuke` file should be next to the repository root, i.e., `.git` or `.svn`. If you want to build solutions from multiple repositories, I suggest to have an umbrella repository, that automatically clones/updates all its children.

**Comment by SalahEddin** [comment]
Thanks, do you mean using git submodules by umbrella repo? ?

**Comment by matkoch** [comment]
Not necessarily. I can’t properly answer your question without knowing your project. Many times it’s a bad decision to split up projects into multiple repositories as you do.
