### ISSUE TITLE
DotNetPack::SetDescription - comma breaks the build

### ISSUE THREAD

**Issue by danielmpetrov** [nuke-build/nuke#325]
Setting a NuGet package description that contains a comma breaks the nuke build.

```csharp
.SetDescription("Castle Core, including DynamicProxy, Logging Abstractions and DictionaryAdapter")
```

```bash
MSBUILD : error MSB1006: Property is not valid.
Switch:  including DynamicProxy
```

Same issue is described here - https://github.com/Microsoft/msbuild/issues/2999, a solution is to escape commas with `%2c`. The following line works as intended.

```csharp
.SetDescription("Castle Core%2c including DynamicProxy%2c Logging Abstractions and DictionaryAdapter")
```

Maybe this is something Nuke should handle for us.

Other relevant docs:
- https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters

**Comment by GeorgDangl** [comment]
I’ve got something that I use for this in the Nuke.GitHub package: https://github.com/GeorgDangl/Nuke.GitHub/blob/develop/src/Nuke.GitHub/ChangeLogExtensions.cs#L26

**Comment by matkoch** [comment]
#326

**Comment by matkoch** [comment]
@danielmpetrov I know everyone has their own preferences, but for my taste I think the description should rather be set in the project file.

**Comment by danielmpetrov** [comment]
@matkoch That's true. I'm still not used to the new csproj format honestly. :sweat_smile:
