### ISSUE TITLE
Nuke.Common _Build Generate Target - changes files incorrect when using a fork.

### ISSUE THREAD

**Issue by rlove** [nuke-build/nuke#327]
The goal was able to build the Nuke so I can assist in an awesome project.

### Steps to reproduce

1. Fork Repository
2. Clone Locally
3. Run `./build.ps1 Generate`

### Expected Results

No changes in `source/Nuke.CodeGeneration/schema.json` 
No changes in `source/Nuke.Common/Tools/**.cs`

### Actual Results
Changes in `source/Nuke.CodeGeneration/schema.json` 
```
  "id": "https://raw.githubusercontent.com/nuke-build/common/master/source/Nuke.CodeGeneration/schema.json",
  "id": "https://raw.githubusercontent.com/rlove/common/master/source/Nuke.CodeGeneration/schema.json",

```
Example changes in `source/Nuke.Common/Tools/**.cs`
```
// Generated from https://github.com/nuke-build/common/blob/master/build/specifications/CloudFoundry.json
// Generated from https://github.com/rlove/common/blob/master/build/specifications/CloudFoundry.json

```

**Comment by matkoch** [comment]
#326
