### ISSUE TITLE
Solution has an active build configuration for _build.csproj

### ISSUE THREAD

**Issue by JoshClose** [nuke-build/nuke#328]
I can't for the life of me figure out how to get this error message to go away. I setup a new build and running nuke gives me this error. I went to the properties of the solution and unchecked `Build` for all configuration and platforms for project `_build` and it's still happening. I don't know what to do from here.

I created a branch with these changes in it for you to look at. 

https://github.com/JoshClose/CsvHelper/tree/nuke-build-error

I'm sure I'm missing something simple, but am a little confused why it doesn't work from the initial setup.

**Comment by matkoch** [comment]
I suppose you’ve added the build project manually to your solution, which
results in a build configuration to be added by default. This should not be
the case, as it eventually results in the build project trying to build
itself, which in turn will result in MSbuild trying to overwrite the
assembly that’s currently in use.

**Comment by JoshClose** [comment]
I used `nuke :setup` to configure it. Here is a branch from before running setup.

https://github.com/JoshClose/CsvHelper/tree/nuke-build

I ran `nuke :setup` and then `nuke clean` gives me that error.

**Comment by JoshClose** [comment]
![image](https://user-images.githubusercontent.com/114971/67425855-79e1f480-f59e-11e9-9c29-9164bf1e0cdd.png)

**Comment by matkoch** [comment]
Okay, but that's a different error now, right? I suppose your solution file is "corrupt", meaning that some build configurations exist, where no matching project is present. We should handle that more gracefully. Marking as bug for now.

**Comment by matkoch** [comment]
Have you modified the branch already? I thought the `_build` project was in the solution file.

**Comment by JoshClose** [comment]
Before setup: https://github.com/JoshClose/CsvHelper/tree/nuke-build
After setup: https://github.com/JoshClose/CsvHelper/tree/nuke-build-error

**Comment by JoshClose** [comment]
This is what I was getting before, so I thought that error was a part of the message.

![image](https://user-images.githubusercontent.com/114971/67426422-ad714e80-f59f-11e9-98ae-f9156f7d048b.png)

**Comment by JoshClose** [comment]
I did rip out a bunch of Cake build stuff, so it doesn't surprise that the solution file may be corrupt.

**Comment by JoshClose** [comment]
I just created a brand new solution from scratch and I'm getting that same exception. It's like it doesn't like my folder structure or something.

**Comment by JoshClose** [comment]
The `unity` folder has a solution file in it. I moved the solution file to the root and the error still happens. If I delete the `unity.sln` file completely, it works. It's definitely possible the unity solution file is corrupt. I'll have to check into that.

**Comment by matkoch** [comment]
@JoshClose ah great, thanks for the notice. You can also remove the attribute, if you want. It's just there to catch a common problem, when people added the build project manually. I will check what we can do about the empty `unity.sln` file. Btw, what is it for anyway?

**Comment by JoshClose** [comment]
It was to build assets for CsvHelper so it could go into their store. I don't know why it's empty... It's been a long time since I've looked at it. The Unity store rejected it anyways because there wasn't enough documentation or something with it. After that, I haven't looked at it. People can just download the netstandard2.0 version and include it in their projects. It would be handy for them to be able to just include it from the store. I'll probably just delete it and revisit it later. I'm sure it's not compatible with the latest version of unity anyways.
