### ISSUE TITLE
Working self-contained executable via .NET Core 3.0

### ISSUE THREAD

**Issue by Xeinaemm** [nuke-build/nuke#330]
Hey,

Today I've tested that it's possible to create a self-contained executable of a nuke.
Params for _build.csproj
```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
```
Command:
```
.\_build.exe --target Compile --Solution Xeinaemm.Standard.sln --root
```

Trimming it's not possible because nuke use reflection so the initial build has 85MB rather than 75MB.
At this approach, I can put executable inside folder without any additional files and say the CI to run the process.

The question, it's compatible with the whole NUKE or not?

**Comment by matkoch** [comment]
Should be. Have you tried it?

**Comment by matkoch** [comment]
_And please give the project a star_ 🙂

**Comment by Xeinaemm** [comment]
From my point and my targets, yes. 
Keeping this simple, everything needed is inside a project?

I just wonder that under the hood NUKE doesn't have any external features that can break program ie. download files, linking, importing that coming from outside of the project.

I'm comparing this to Cake where automagically process can download files and break due to proxy restrictions, permissions, etc.

**Comment by matkoch** [comment]
> From my point and my targets, yes.
Keeping this simple, everything needed is inside a project?

The only outside thing you need is the  `.nuke` file or to pass `--root` to your invocation.

> I just wonder that under the hood NUKE doesn't have any external features that can break program ie. download files, linking, importing that coming from outside of the project.

It does, but not in conjunction with global tools.

> I'm comparing this to Cake where automagically process can download files and break due to proxy restrictions, permissions, etc.

I would argue that automatically downloading files is a very bad idea, since you're builds are not deterministical anymore.

**Comment by Xeinaemm** [comment]
I found a bug in this approach. When publishing an app with 
```
<PublishSingleFile>true</PublishSingleFile>
``` 
NukeBuild.BuildProjectDirectory broke on resolve path by returning null in these lines:

https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/Execution/BuildManager.cs#L54-L57

with stack trace: 
```
Assertion failed: left != null
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.IO.PathConstruction.AbsolutePath.op_Division(AbsolutePath left, String right)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

In single file, the runtime cannot find where the process resides so this line will not work:
https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/EnvironmentInfo.Others.cs#L26

The possible fix can be done by changing implementation to this:
```
get => Process.GetCurrentProcess().MainModule.FileName;
```

Ref:
https://github.com/dotnet/core-setup/issues/7491
https://github.com/dotnet/coreclr/issues/25623

**Comment by Xeinaemm** [comment]
I found all occurrences of this problem, prepare PR to check.
