### ISSUE TITLE
Fluent Migrator global tool not writing to console

### ISSUE THREAD

**Issue by DanScottNI** [nuke-build/nuke#331]
I'm using fluent migrator's global tool, installed on a path within my project (usually "/tools/FluentMigrator.DotNet.Cli". (policy reasons for this)

Because it doesn't always exist at build start, I'm just executing the runner through ProcessTasks.StartProcess. (relatively new to Nuke, so I'm not sure if this is the correct way to do this either)

However, I'm not getting any output to the console through Nuke. I can run the tool from Powershell, and I do get output.

My code looks like this:

`ProcessTasks.StartProcess(RootDirectory / "tools" / FluentMigratorToolPackage / "dotnet-fm.exe", $"migrate --connection=\"{builder}\" --processor SqlServer2016 --assembly \"{path.FirstOrDefault()}\"",
               logOutput: true,
               logInvocation: true);`

I've not changed any of the default log levels or anything.  Mostly because I don't know how!

What am I doing wrong?

**Comment by matkoch** [comment]
What do you by _doesn't alwats exist at build start_ ?

**Comment by DanScottNI** [comment]
I do an install of the global tool using the tool path argument. The tools directory isn't in git so the build actually installs it if it doesn't exist.

**Comment by matkoch** [comment]
Why aren’t you adding it as dependency for the build project?

**Comment by DanScottNI** [comment]
Is that possible if it's a nuget tool package? 

My work machine has an applocker policy applied to it so that most things outside of program files or the visual studio project directory cannot be run.

**Comment by matkoch** [comment]
Tool packages can be referenced in the same way. Either as packagereference
with excludeassets attribute, or as packagedownload item.

You can also use the LocalExecutableAttribute. Should work with absolute
paths too. Please note that StartProcess does exactly what it says -
starting the process. If you want to wait for it to exit, call
AssertZeroExitCode or something like that.

**Comment by DanScottNI** [comment]
Would that help with whatever is suppressing the tool's output?

Good tip about the zero exit code assertion, thanks!

**Comment by matkoch** [comment]
As I said, it’s probably not waiting for output.

**Comment by DanScottNI** [comment]
Apologies, I must have missed that. 

Thanks for your help. I'll test it out later but I'm confident that you're right - it is definitely not waiting for the result.

Would also explain why my failed builds on Jenkins are sometimes locking up.

**Comment by matkoch** [comment]
For other questions I recommend to join our slack workspace. And please also add a star for the project :)
