### ISSUE TITLE
Manage many solutions at once

### ISSUE THREAD

**Issue by Xeinaemm** [nuke-build/nuke#332]
I have 50+ systems to manage so creating for each build project is cumbersome for common targets (clean, restore, build, pack, create IIS farm, reconfigure environment, update packages, apply actual runtimeBindings for legacy web projects). 

NUKE should have the option that by default enable ```--root``` and turns into "searching" mode for a solution to execute on them by filling ```--solution``` or without then will target all solutions inside nested folders that will find.

In more advanced mode when will find inside folder a ```.nuke``` will execute the default target of build project or any that we will specify by the flag and omit other build projects if not find this target (this same as bootstrapper ```build.ps1``` with params but for a specific solution with specific requirements).

In my approach, I'm thinking about self-contained apps and global tools that are not rooted to build projects and can work independently.

**Comment by matkoch** [comment]
Hi @Xeinaemm, I do understand the general issue about managing many solutions, but on some parts what you've said, I don't follow. The `.nuke` file doesn't execute something, and is also not responsible for a default target. In general, it only marks the repository root – usually next to `.svn` or `.git` directories.

I guess it would make more sense to have a discussion or Slack or via voice call.

On another note, I'm not sure yet about the single file approach. This is really limited, as no tools will be packed with it. So you can only really use _compiled_ functionality, as `FileSystemTasks` and alike, but no `XunitTasks` or similar.

**Comment by Xeinaemm** [comment]
> The .nuke file doesn't execute something, and is also not responsible for a default target. In general, it only marks the repository root – usually next to .svn or .git directories.

Correct, and going forward you can suppose that inside folder is build project and deal with that to extend functionality. The question is, it's possible to invoke NUKE by another NUKE or somehow find compiled targets to invoke?

Another thing is that when I looked inside the implementation of default paths(working, root, temp etc.), DirectoryBuild, ToolPathResolver in depths, they strictly follow the flow of build projects so it's possible to mark collection of markers and their paths by globbing.

> This is really limited, as no tools will be packed with it. So you can only really use compiled functionality, as FileSystemTasks and alike, but no XunitTasks or similar.

You're right. I think it's possible to move the place of build project outside of the solution and by searching in-depth for markers do these same things as before. 
In this approach, I see three ways. 

1. Searching for all .sln without additional nuke projects inside folder or markers.
2. Searching for markers and nuke projects
3. Both 

Somehow you're defined standard paths that searching above directory for the marker. By adding an extra flag that reverses searching no one will be confused that at this moment NUKE working in a different mode.

**Comment by matkoch** [comment]
I think it would be better to discuss this on Slack.

**Comment by matkoch** [comment]
I will close this issue for now but will await your contact!
