### ISSUE TITLE
namespace 'Nuke' could not be found

### ISSUE THREAD

**Issue by FinHorsley** [nuke-build/nuke#333]
Just getting started with Nuke, but when i open the build project in VS4Mac/VSCode the Nuke namespaces cannot be found 

```
The type or namespace name 'Nuke' could not be found 
(are you missing a using directive or an assembly reference?) (CS0246) [NukeBuildTest]
```

If i run `./build.sh` the build restores and executes correctly. Also if i make changes to build.cs, for example adding `Console.Writeline("Hello world")` to one of the targets, these changes are reflected in the build output

<p align="center">
<img src="https://user-images.githubusercontent.com/10697741/68117971-b692e180-fef6-11e9-827d-b41f3a462231.png" width="500"/>
</p>

### Environment
- `dotnet --version`
3.0.100
- `dotnet tool list -g`
nuke.globaltool      0.23.3       nuke
- `<PackageReference Include="Nuke.Common" Version="0.23.3" />`

https://nukebuildnet.slack.com/archives/C9Q99MFU0/p1572865713164600

Here is the repro project 
[NukeBuildTest.zip](https://github.com/nuke-build/nuke/files/3803841/NukeBuildTest.zip)

**Comment by david-driscoll** [comment]
ensure your `TargetFramework` is `netcoreapp3.0`

**Comment by FinHorsley** [comment]
@david-driscoll just checked, everything targetting `netcoreapp3.0` `<TargetFramework>netcoreapp3.0</TargetFramework>`

**Comment by matkoch** [comment]
The attached zip content is completely broken. You have a `Program.cs` and there is no reference to `Nuke.Common`.

**Comment by FinHorsley** [comment]
All the Nuke build code is in the `build` folder, the `build.csproj` has the references to `Nuke.Common`. Executing `./build.sh` successfully runs the nuke build process

![image](https://user-images.githubusercontent.com/10697741/68162372-c7237600-ff4f-11e9-9522-9c204e86ba58.png)

**Comment by matkoch** [comment]
You're editing the `Build.cs` file in context of `NukeBuildTest.csproj`, which is the wrong project file. However, `_build.csproj` is not added to the solution.

**Comment by matkoch** [comment]
In other words: there must be no `csproj` file in any parent path of the build project. SDK-based projects include all descendent C# files automatically.

**Comment by FinHorsley** [comment]
Ah, ok 🙂 

I'm now lost as to what I did wrong during installation. I followed the following steps
1) `dotnet tool install Nuke.GlobalTool --global`
2) `dotnet new console -n NukeBuildTest`
3) `cd NukeBuildTest/`
4) `nuke :setup`
5)  used the defaults for all configuration options

This created a separate `build/` folder, which is what you see above (including the _build.csproj, etc.)

**Comment by matkoch** [comment]
Youre _fault_ is to have a project file in the root directory of your repository, next to the solution file. This issue is not specific to nuke, and you would have issues with _any_ other additional csharp project file.

**Comment by matkoch** [comment]
I suppose you've only tested things in a dummy project, but no real solution – to my knowledge – will have a `csproj` file be located below another `csproj` file.

**Comment by FinHorsley** [comment]
Thanks, think i see what you mean 🙂 

so the project outline should look like the following...
```
|- src
   NukeBuild.sln
   |- NukeBuild
       |- Program.cs
       |- NukeBuild.csproj
   |- build
       |- build.cs
       |- build.csproj 
```

#### Updated - see comment below
(For anyone else having the same problem in the future)
```
NukeBuild.sln
|- build
   |- build.cs
   |- build.csproj 
|- src
   |- NukeBuild
      |- Program.cs
      |- NukeBuild.csproj
```

**Comment by matkoch** [comment]
I'd rather suggest to have the solution file, `build`, and `src` on the same level.

@CalebRollins please also star the project if this was of matter for you.
