### ISSUE TITLE
MSBuildToolPathResolver fails to find MSBuild installed in a non-default location.

### ISSUE THREAD

**Issue by alphaleonis** [nuke-build/nuke#334]
We have some computers where Visual Studio (2017) is installed in a location other than the default.  In this instance it is installed on the `E:\` drive. In this case, MSBuildTasks commands do not work, because the tool path resolver has the program files folder hard-coded.

Suggest perhaps using VSWhere to locate MSBuild instead, which seems to be the recommended way from Microsoft?

**Comment by matkoch** [comment]
Using `VSWhereTasks` would require the `vswhere` package to be added to the build project. To me this would be kind of a messed up situation, where adding a package magically resolves paths differently. Therefore I'm voting for having to use `SetToolPath` and `VSWhereTasks` manually in case someone installs the product in a non-default path.

**Comment by alphaleonis** [comment]
In that case, how about using the official MSBuildLocator package from MSBuild?  Since there are official implementations that locate MSBuild, wouldn't we be better of using those than trying to re-invent the wheel in Nuke? (Also would have to update the resolution in Nuke every time a new VS-version (including previews) are released)?

**Comment by matkoch** [comment]
how is it different to vswhere?

**Comment by alphaleonis** [comment]
Nuke.Common already has dependencies to other Microsoft.Build.XXX NuGet packages, what would be the problem of having a dependency also on Microsoft.Build.Locator to properly locate the available versions?

**Comment by matkoch** [comment]
If it resolved fine for older versions and different editions too, I’m okay
with it. Can you make a PR?

**Comment by alphaleonis** [comment]
Unfortunately it turns out that Microsoft.Build.Locator will not work for this purpose as I originally had assumed. Mainly because of the problem described microsoft/MSBuildLocator#61 which they will not "fix".  

I still think we need to provide a better way to locate MSBuild instances out of the box though, because of the great hassle of actually finding them.  (MSBuild instances can be found within .NET Core SDK as well , so we should be able to select one of those as well as preview versions of VS etc.)

It does however seem like we have to write the code ourselves. I'll look into writing a more complete approach to solving this problem, and submit a PR if I find one.
