### ISSUE TITLE
TeamCity integration

### ISSUE THREAD

**Issue by vchirikov** [nuke-build/nuke#335]
* You should add possibility to change Kotlin DSL version. Not all customers use latests TeamCity. Workaround:
```C#
public class TeamCity2018Attribute : TeamCityAttribute
{
    public TeamCity2018Attribute(TeamCityAgentPlatform platform) : base(platform) { }
    protected override IEnumerable<string> GetHeader() => base.GetHeader().Select(x => x.Replace("2019.1", "2018.2"));
}
```
* Do we have the option for add \ change generation of dsl config? Because in develop branch only that I found is a fully commented file with `TeamCityConfigurationGenerator` and `BEGIN USER FUNCTIONS` marker that shouldn't works, right?

**Comment by matkoch** [comment]
First of all, please star the project.

Putting another kotlin version in the header should probably be configurable via property on `TeamCityAttribute`. You're free to create a PR, or I will see later.

The commented file `TeamCityConfigurationGenerator` is a leftover. Currently, there's no way to modify the generated script other than the `AutoGenerate = false` opt-out.

**Comment by vchirikov** [comment]
https://github.com/nuke-build/common/blob/377325c7498a8b1cd9a2881fa7f447a333a70de7/source/Nuke.Common/CI/TeamCity/Configuration/TeamCityConfiguration.cs#L18

So you should change this line too.

**Comment by vchirikov** [comment]
Weird work with community, I point out confusing messages, missing information in documents and a hard-coded version in the implementation, but you just mark as a question and close it. So how I can track this changes? Your tool isn't bad, but really isn't production ready.
p.s. not only tc integration and docs, also too flexible api for same things (for example I see 3 different methods to set some properties in csproj, etc)), csproj parsing errors out of the box ( PackageReference Microsoft.build ) etc etc.

**Comment by matkoch** [comment]
> Weird work with community

Funny, I had the same thought when you started that issue with _you should_. Sorry, but I really have no fun interacting with someone in that manner repeatedly. I wish you all the best finding a build tool that is production-ready.
