### ISSUE TITLE
NuGetPackageResolver bug

### ISSUE THREAD

**Issue by vchirikov** [nuke-build/nuke#336]
If intermediate path isn't standard, nuke throw exception.
Here I have gotten `NullReferenceException` for example.
https://github.com/nuke-build/common/blob/develop/source/Nuke.Common/Execution/BuildManager.cs#L57
Main problem that author like static classes with static properties that, so I can't use nuke with nonstandard output paths. (I use project structure from Microsoft) and can't make workaround.

**Comment by matkoch** [comment]
I’m sorry you can’t change your project structure. I can’t change any of that implementation, unfortunately.

**Comment by vchirikov** [comment]
So your code just will throw NRE, rather read property from Directory.Build.props / csproj. Good job.
