### ISSUE TITLE
GitVersion Framework

### ISSUE THREAD

**Issue by netclectic** [nuke-build/nuke#338]
- Targeting a mix of .Net Core 2.2 / 3 / 3.1 and .Net Standard 2
- Nuke Global Tool 0.23.3
- NUKE Execution Engine version 0.24.0-alpha.138
- GitVersion Global Tool 5.1.2

I get the following error with my build...

> Assertion failed: Package executable 'tools' [GitVersion.Tool|GitVersion.CommandLine] requires a framework

How do I go about setting a framework for GitVersion?

**Comment by matkoch** [comment]
Can you please provide a repro?

**Comment by netclectic** [comment]
Putting together a repro I noticed the new build project was using a 'PackageDownload' for 'GitVersion.Tool' whereas I was using a regular package reference for GitVersion.CommandLine. 

Changing my build project to be the same has resolved the issue.

Thanks!
