### ISSUE TITLE
Cannot run nuke application after dotnet publish

### ISSUE THREAD

**Issue by johanclasson** [nuke-build/nuke#339]
## Background

While using nuke for running deploys I would like to package the nuke console application while building, and run that console application at a later time (when appropriate) to make the deployment. I think It would be nice to not have to compile stuff in the deployment stage in my process.

But when I attempt to run the published application, I get a strange error:

```
Assertion failed: left != null
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.IO.PathConstruction.AbsolutePath.op_Division(AbsolutePath left, String right)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

The issue is easily repeatable.

```
PS C:\dev\nuke-issue> dotnet new solution
PS C:\dev\nuke-issue> nuke :setup
Could not find root directory. Falling back to working directory.
How should the build project be named?
¬  _build
Where should the build project be located?
¬  ./build
Which NUKE version should be used?
¬  0.23.3 (latest release)
Which solution should be the default?
¬  nuke-issue.sln
Do you need help getting started with a basic build?
¬  Yes, get me started!
Restore, compile, pack using ...
¬  dotnet CLI
Source files are located in ...
¬  ./source
Move packages to ...
¬  ./output
Where do test projects go?
¬  ./tests
Do you use git?
¬  No, something else
PS C:\dev\nuke-issue> dotnet publish .\build\_build.csproj -o c:\temp\build
PS C:\dev\nuke-issue> c:\temp\build\_build.exe
```

Perhaps I am missing something here? Perhaps Nuke is not designed for this scenario?

## Possible workaround 1

I have boiled it down to that when the BuildManager.Execute runs, it tries to execute the following line (57):

```csharp
ToolPathResolver.NuGetAssetsConfigFile = NukeBuild.BuildProjectDirectory / "obj" / "project.assets.json";
```

But the `NukeBuild.BuildProjectDirectory` is null since there is no .csproj-file to be found.

A as workaround to run a published nuke console application, I can create a dummy .csproj-file.

```
PS C:\dev\nuke-issue> ni c:\temp\build\x.csproj
PS C:\dev\nuke-issue> c:\temp\build\_build.exe
```

## Possible workaround 2

Package the source code for the nuke deploy project during the build step, and use build.ps1 to build and run it when deploying.

**Comment by matkoch** [comment]
Can you please check if it's fixed?

**Comment by johanclasson** [comment]
Yes! Publish works now!
