### ISSUE TITLE
AzurePipelines PublishTestResults joins with comma and space

### ISSUE THREAD

**Issue by johanclasson** [nuke-build/nuke#341]
Just before 0.23.0, the `resultFiles` parameter of PublishTestResults became joined by comma and space (`, `) instead of just comma (`,`).

https://github.com/nuke-build/nuke/blob/5c807b099e9ba7be2c561247e0808314cc10a7e0/source/Nuke.Common/CI/AzurePipelines/AzurePipelines.cs#L170

For me, running a build on a Windows2019 hosted agent failed when it tried to do:
```
##[warning]Failed to publish test results: The filename, directory name, or volume label syntax is incorrect : 'C:\agents\2.160.0\bin\ D:\a\1\s\test-results\Proj2.Specs.trx'
##[debug]Processed: ##vso[results.publish type=VSTest;resultFiles=D:\a\1\s\test-results\Proj1.Specs.trx, D:\a\1\s\test-results\Proj2.Specs.trx;runTitle='Specs results']
```

## Workaround

```csharp
var filesString = string.Join(',', files);
AzurePipelines.Instance?.PublishTestResults(title, type, new []{ filesString });
```

**Comment by matkoch** [comment]
Thanks for your contribution! 😄🎉

I fixed both issues on develop.
