### ISSUE TITLE
MSBuildTasks.MSBuild fails on Teamcity

### ISSUE THREAD

**Issue by robsonj** [nuke-build/nuke#343]
In Nuke.Common 0.23.x, the teamcity properties were changed in the nuke infrastructure to have a dot notation instead of underscore, so teamcity property names which are used by nuke.common went from...

TEAMCITY_DOTNET_MSBUILD_EXTENSIONS4_0

to 

teamcity.dotnet.msbuild.extensions4.0

This is a good change, the names now reflect what you see in teamcity, however...

The property above in particular is used within nuke.common to locate the msbuild exe. it needs to be updated from TEAMCITY_DOTNET_MSBUILD_EXTENSIONS4_0 to teamcity.dotnet.msbuild.extensions4.0 as outlined in PR #57 on nuke.common...

https://github.com/nuke-build/common/pull/57

This is a blocking bug to anyone using nuke on teamcity in conjunction with the MSBuildTasks.MSBuild() method.

**Comment by robsonj** [comment]
Closed?

**Comment by matkoch** [comment]
v0.24.0

**Comment by robsonj** [comment]
Ok, the change is so minor, no way it can be merged to 0.23.x so we can upgrade from 0.22.x ?

**Comment by robsonj** [comment]
I don't see anything in 0.24.0 that covers this. this is using msbuild.exe, not dotnet msbuild

**Comment by matkoch** [comment]
Take a second look

**Comment by robsonj** [comment]
Ok, the change is so minor, no way it can be merged to 0.23.x so we can upgrade from 0.22.x ?

**Comment by matkoch** [comment]
Please wait for the next release.

**Comment by robsonj** [comment]
Is there an ETA on 0.24.0 please? trying to decide if we need to fork

**Comment by matkoch** [comment]
No
