### ISSUE TITLE
TeamCity env variables parser error

### ISSUE THREAD

**Issue by MichaelSL** [nuke-build/nuke#346]
### Description
Build is failing on Team City when trying to parse env variables. I believe this is because I have several `=` in the variable

### Steps to reproduce
I have several variables with `=` in the name in TC:

```

dep.BuildBootstrapper.env.=:: = ::\
dep.BuildBootstrapper.env.=C: = C:\BuildAgent\bin
dep.BuildBootstrapper.env.=ExitCode = 00000000
```

### Relevant log output

```
[15:11:10]
[Step 1/2] An item with the same key has already been added. Key: dep.BuildBootstrapper.env.
[15:11:10]
[Step 1/2]    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
[15:11:10]
[Step 1/2]    at Nuke.Common.CI.TeamCity.TeamCity.ParseDictionary(String file)
[15:11:10]
[Step 1/2]    at Nuke.Common.CI.TeamCity.TeamCity.<.ctor>b__14_1()
[15:11:10]
[Step 1/2]    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
[15:11:10]
[Step 1/2]    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
[15:11:10]
[Step 1/2]    at System.Lazy`1.CreateValue()
[15:11:10]
[Step 1/2]    at System.Lazy`1.get_Value()
[15:11:10]
[Step 1/2]    at Nuke.Common.CI.TeamCity.TeamCity.get_ConfigurationProperties()
[15:11:10]
[Step 1/2]    at Nuke.Common.CI.TeamCity.TeamCity.get_BranchName()
[15:11:10]
[Step 1/2]    at Nuke.Common.Git.GitRepositoryAttribute.GetBranch()
[15:11:10]
[Step 1/2]    at Nuke.Common.Git.GitRepositoryAttribute.GetValue(MemberInfo member, Object instance)
[15:11:10]
[Step 1/2]    at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
[15:11:10]
[Step 1/2]    at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
[15:11:10]
[Step 1/2]    at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

### How to fix?
The easy workaround for me might be just changing `var index = line.IndexOf(value: '=');` to `LastIndexOf` in `TeamCity` class. However this approach might break builds with variables with `=` in variable value. It will not have such devastating effect as duplicate keys, but could still cause some issues.

**Comment by matkoch** [comment]
I don't really understand why you would use the equals sign inside environment variable keys?!

**Comment by MichaelSL** [comment]
Unfortunately I don't control TeamCity server configuration. This params are set on a root project level for all build agents.

Do you think it is safe to use last value found in config when reading TC params? Like overwrite the value if the key is already present in dictionary?

**Comment by matkoch** [comment]
Sorry, but there's no way we can fix this. The pattern is `[key]=[value]`. There are no spaces or anything else that we could rely on. And again, I'd rather expect an additional `=` in `value` than in `key`.

**Comment by MichaelSL** [comment]
According to this (maybe outdated) article, in general, Windows ENV variable names shouldn't contain equal sign: https://docs.microsoft.com/en-us/windows/win32/procthread/environment-variables?redirectedfrom=MSDN

From the other hand, Linux systems threat first equals sign as a variable name separator.

[Similar issue](https://github.com/moby/moby/issues/26178) was fixed in Moby repo complying with Linux approach.

So far we could just ignore duplicate variables with warning. In most cases this will be the Windows `cmd.exe` variables. Another way around it, which would be more specific to TC, is to check if the parsed key already in the dictionary and skip one equal sign.

<blockquote><div><strong><a href="https://docs.microsoft.com/en-us/windows/win32/procthread/environment-variables">Environment Variables - Win32 apps</a></strong></div><div>Every process has an environment block that contains a set of environment variables and their values. There are two types of environment variables: user environment variables (set for each user) and system environment variables (set for everyone).</div></blockquote>

**Comment by MichaelSL** [comment]
As this variables are used by specific Windows process (cmd.exe) we may just exclude them from the env variables list. I'll work on PR for this.

**Comment by MichaelSL** [comment]
@matkoch so we can use the same regex that TC uses for splitting the params instead of current split by `=`.

Change:
`var index = line.IndexOf(value: '=');`
to
```
var regex = new Regex(@"[^\.]=", RegexOptions.Compiled);
...
var index = regex.Match(line).Index + 1;
```

If you agree with the approach, I will submit a PR.

I checked on my broken build agent vars: works as expected.

**Comment by matkoch** [comment]
I would expect another `StringExtensions` method called `SplitRegex`, to make it more general. Otherwise, yes I'm fine.

**Comment by ghost** [comment]
Based on feedback from @matkoch I implemented the PR since we are also now hitting this issue. Would love to get this sorted as it's blocking us currently.

**Comment by ghost** [comment]
Can confirm that after updating to 0.24.1 this issue is now fixed! Thanks for pushing out the hotfix release quickly @matkoch.

**Comment by MichaelSL** [comment]
Thank you for fixing this one @archonandrewhunt  I just came back and I will update our pipelines on Monday.

**Comment by MichaelSL** [comment]
Verified on our pipeline. Let's close it!
