### ISSUE TITLE
Cannot set TestCaseFilter with the operators != or ~

### ISSUE THREAD

**Issue by johanclasson** [nuke-build/nuke#349]
### Description

Since the test case filter is set through supplying a dictionary of `testCaseFilterKey` and `testCaseFilterValue`-properties, and that the operator is fixed to `=`, I cannot use the other operators `!=` and `~`. This makes it hard to use filters such as for example `Category!=Integration`.

Since I have lots of in-memory tests and only a few integration-tests I think it is easier to use a filter which removes all integration tests instead of including all in-memory tests, since the former options saves me from specifying a category for all these tests in code.

### Proposed solution

Replace the TestCaseFilters below:

https://github.com/nuke-build/nuke/blob/5c807b099e9ba7be2c561247e0808314cc10a7e0/build/specifications/VSTest.json#L76-L83

With something similar to:

```json
{
  "name": "TestCaseFilter",
  "type": "string",
  "format": "/TestCaseFilter:{value}",
  "help": "Run tests that match the given expression.<para/>The <c>/TestCaseFilter</c> command line option cannot be used with the <c>/Tests</c> command line option.<para/>For information about creating and using expressions, see <a href=\"https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md\">TestCase filter</a>."
},
```

Note that I removed the item format description from the `help`-property.

I would have been nice if one could have had both the old dictionary- and the string-approach side by side. But this might lead to confusion since it is not allowed to supply `/TestCaseFilter` twice.

On the other hand, the string-approach is similar to what is used by the DotNetTest filter option.

### Possible Workaround

```csharp
var args = new VSTestSettings()
    ...
    .GetArguments().RenderForOutput();
VSTest(args + " /TestCaseFilter:Category!=Integration");
```

**Comment by matkoch** [comment]
I’ll change it to `List<string>`. Btw, there us also `SetArgumentConfigurator`.
