### ISSUE TITLE
Prettify configuration name in TeamCity

### ISSUE THREAD

**Issue by razenpok** [nuke-build/nuke#351]
### Description

It would be cool if I could have "Cook Asset Bundles" as a TeamCity configuration name instead of "CookAssetBundles" for `Target CookAssetBundles`

![image](https://user-images.githubusercontent.com/8434406/69572772-e43ee800-0fd5-11ea-8c34-6004fc186b29.png)

**Comment by matkoch** [comment]
You can achieve that by inheriting from the TeamCity attribute and overriding the method to create build types.
