### ISSUE TITLE
Type of GitVersionSettings.UpdateAssemblyInfoFileName is incorrectly defined as Nullable<bool> while string is expected

### ISSUE THREAD

**Issue by pslotvinski** [nuke-build/nuke#355]
### Description
Here is how GitVersion defines the _"/updateassemblyinfofilename"_ command line option:
```
>dotnet gitversion /?
GitVersion 5.1.2+Branch.master.Sha.4eb164e8b5ddc27b736a11fd9979c7760c7a2b0f
. . .
 # AssemblyInfo updating
    /updateassemblyinfo
                    Will recursively search for all 'AssemblyInfo.cs' files in the git repo and update them
    /updateassemblyinfofilename
                    Specify name of AssemblyInfo file. Can also /updateAssemblyInfo GlobalAssemblyInfo.cs as a shorthand
```
### Steps to reproduce
[GitVersion.Generated.cs](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/GitVersion/GitVersion.Generated.cs) defines the corresponding property as follows:
```
/// <summary>
///   Specify name of AssemblyInfo file.
/// </summary>
public virtual bool? UpdateAssemblyInfoFileName { get; internal set; }
```
This makes _UpdateAssemblyInfoFileName_ property (and corresponding _SetUpdateAssemblyInfoFileName_ extension method) not usable when it is needed to specify single AssemblyInfo.cs file to be updated (which is quite common practice - having single _SharedAssemblyInfo.cs_ linked to every project in solution).

**Comment by matkoch** [comment]
PR please
