### ISSUE TITLE
Pack Step doesn't use correct GitVersion

### ISSUE THREAD

**Issue by jameswoodley** [nuke-build/nuke#362]
### Description
When using the DotNetPack inbuilt function the property is output with a version, but the Nuget package created has a differing version

### Steps to reproduce

```
Target Pack => _ => _
        .DependsOn(Compile)
        .Produces(ArtifactsDirectory / "*.nupkg")
        .Executes(() =>
        {
            DotNetPack(s => s
                .SetProject(Solution)
                .SetVersion(GitVersion.NuGetVersionV2)
                .SetOutputDirectory(ArtifactsDirectory));
        });
```

Produces:
![image](https://user-images.githubusercontent.com/52610563/70987376-a9e9d780-20b7-11ea-9406-b68f2cf5e21e.png)

As you can see, Version should be 0.1.3, but is 1.0.0

**Comment by jameswoodley** [comment]
So heads up, adding the "PackageVersion" property seems to have resolved it:

```
Target Pack => _ => _
        .DependsOn(Compile)
        .Executes(() =>
        {
            DotNetPack(s => s
                .SetProject(Solution)
                .SetConfiguration(Configuration)
                .EnableNoBuild()
                .EnableNoRestore()
                .SetVersion(GitVersion.NuGetVersionV2)
                .SetProperty("PackageVersion", GitVersion.NuGetVersionV2)
                .SetOutputDirectory(ArtifactsDirectory / "nuget"));
        });
```

I wonder if we should add a `.SetPackageVersion()` method?

**Comment by matkoch** [comment]
Regarding your first post, this is a user-code issue. `DotNetPack` only allows you to manipulate the actual arguments for invocation. Nothing more. As a side-note, the same invocation is used in our own builds, and it works.

Regarding `PackageVersion`, you're welcome to create a PR.

**Comment by jameswoodley** [comment]
Apologies, when you say it only allows you to manipulate the actual arguments for invocation, what do you mean by this? I was, perhaps naively, under the impression that if I set the version using `SetVersion` it would give me that version in my output package?

**Comment by matkoch** [comment]
Constructing an invocation has no guarantee that it is actually meaningful or will work. The idea is only to provide a fluent way to construct the invocation with all known arguments according to http://www.nuke.build/docs/authoring-builds/cli-tools.html

<blockquote><img src="../../favicons/favicon.ico" width="48" align="right"><div><strong><a href="http://www.nuke.build/docs/authoring-builds/cli-tools.html">CLI Tools | NUKE</a></strong></div></blockquote>
