### ISSUE TITLE
Set RootDirectory as default ProjectPath in Unity task

### ISSUE THREAD

**Issue by razenpok** [nuke-build/nuke#363]
### Description

When no `-projectPath` is supplied, Unity builds last opened/built project. This is an expected behavior and works fine for a single project, but it can catch people off-guard with multi-project CI setups (like it was in my case). I'm not sure if this is an idiomatic way for this library, but I think defaulting `ProjectPath` to `RootDirectory` can help newcomers avoid this pitfall.

```csharp
Unity(_ => _
    // SetProjectPath is needed, and it will most likely be the RootDirectory
    .SetProjectPath(RootDirectory)
    .EnableBatchMode()
    .EnableQuit());
```

**Comment by matkoch** [comment]
We decided a while ago that there are no implicit default settings for command line tool invocations. However, I’m open for showing a hint or add code inspections.

Is there a particular error output from Unity? Are you using ReSharper or Rider? Under what circumstances is setting a different directory expected?

**Comment by razenpok** [comment]
>Is there a particular error output from Unity?

No error. Nuke starts correctly in an initial directory and invokes Unity, and then Unity starts doing its stuff in a different directory. I can provide a sample of logs if it can help.

>Are you using ReSharper or Rider?

Rider.

>Under what circumstances is setting a different directory expected?

I'm using TeamCity, and the build pipeline worked fine until I've created a second Unity project. This project uses a different VCS Root, so TC naturally checkouts its working copy to a different directory. After the checkout, Unity is invoked and the rest is described above.

Still, similar behavior can be achieved via manually opening a Unity project and then trying to build some other project from Unity CLI without providing `projectPath`. I think `projectPath` is mandatory more often than not, so it won't hurt hinting every time it is being missing in a configuration.

**Comment by razenpok** [comment]
>Under what circumstances is setting a different directory expected?

More about that: Unity defines a project as a folder which has this structure

```
Some Unity Project
|-Assets
|-ProjectSettings
```

Where `Assets` and `ProjectSettings` are directories.

Directory other than `RootDirectory` is expected when you have some non-"Unity project in a root of a repo" scenario. For example, having multiple Unity projects in a single repo, or if structure of a repo looks like this:

```
My Awesome Game
|-Server
|--(server-side code)
|-Client // <- Client is not a root of a repo
|--Assets
|--ProjectSettings
```

**Comment by matkoch** [comment]
No error? What about exit code?

**Comment by razenpok** [comment]
Exit code 0. Really, this is not an exceptional behavior, Unity just builds a different project from one that I expected it to.
