### ISSUE TITLE
Nuke logo is offensive to me

### ISSUE THREAD

**Issue by totollygeek** [nuke-build/nuke#364]
The logo looks offensive and asking me why is also offensive! 😏

**Comment by GeorgDangl** [comment]
No offense intended, but why is it offensive? 😊

**Comment by totollygeek** [comment]
It is my human right to not answer offensive questions and since I identify myself as a person, that does not give answers, you are offending me even more by asking me any questions at all 😁

**Comment by maxkatz6** [comment]
Perfect label for issues like that 😁
