### ISSUE TITLE
GitRepositoryAttribute and GitVersionAttribute fail the build if they produce an error

### ISSUE THREAD

**Issue by Thealexbarney** [nuke-build/nuke#366]
Since bac69547, if an error occurs in GitRepositoryAttribute or GitVersionAttribute, the entire build fails. Before that the fields were left as null.

Previously the build script could detect something like the lack a `.git` directory by checking if GitRepository/GitVersion fields were null and react accordingly. Since that change, you can't have class-wide GitRepository and GitVersion instances without initializing them in a Target.

**Comment by matkoch** [comment]
See #345
