### ISSUE TITLE
Allow to specify TeamCity authentication method

### ISSUE THREAD

**Issue by robertmircea** [nuke-build/nuke#368]
### Description

When generating Teamcity Kotlin project, allow to specify which type of authentication to use for connecting to VCS repository. I use private repositories via ssh or https and most of the time, the authentication mechanism must be specified in `.teamcity/settings.kts` project.

Something like this should be generated for ssh key authentication:

```
    authMethod = uploadedKey {
        userName = "teamcity.dev.system"
        uploadedKey = "id_rsa"
    }
```
although there are 5 mechanisms available in Teamcity for git server authentication:

- Anonymous
- Password
- CustomPrivateKey
- DefaultPrivateKey 
- UploadedKey

Example:
```
object VcsRoot : GitVcsRoot({
    name = "....."
    url = "ssh://git@scm.x.com/project.git"
    branch = "refs/heads/master"
    pollInterval = 60
    branchSpec = """
        +:refs/heads/*
    """.trimIndent()
    authMethod = uploadedKey {
        userName = "teamcity.dev.system"
        uploadedKey = "id_rsa"
    }
})
```

**Comment by matkoch** [comment]
You can change this from the TeamCity UI, which will then create a patch file.

**Comment by matkoch** [comment]
Please vote for https://youtrack.jetbrains.com/issue/TW-63918

<blockquote><div>YouTrack</div><div><strong><a href="https://youtrack.jetbrains.com/issue/TW-63918">teamcity.build.branch parameter is missing when using DslContext.settingsRoot : TW-63918</a></strong></div><div>I've tried to replace a custom (yet duplicated) VcsRoot definition in "settings.kts" by using "DslContext.settingsRoot". This mostly works, but the "teamcity.build.branch" parameter is not set. Here…</div></blockquote>
