### ISSUE TITLE
Add method to Jenkins class to get custom environment variable by "name" parameter

### ISSUE THREAD

**Issue by krolol** [nuke-build/nuke#370]
It is will very useful to get not only standard Jenkins environment variables

**Comment by krolol** [comment]
@matkoch, if you approve this feature, I can prepare a pull request

**Comment by arodus** [comment]
Why creating a dedicated function and not just using `EnvironmentInfo.Variable` or similar? 
http://www.nuke.build/api/Nuke.Common/Nuke.Common.EnvironmentInfo.html#Nuke_Common_EnvironmentInfo_Variable__1_System_String_

<blockquote><img src="../../favicons/favicon.ico" width="48" align="right"><div><strong><a href="http://www.nuke.build/api/Nuke.Common/Nuke.Common.EnvironmentInfo.html#Nuke_Common_EnvironmentInfo_Variable__1_System_String">Class EnvironmentInfo
   | NUKE</a></strong></div></blockquote>
