### ISSUE TITLE
Output from processes doesn't handle non standard characters (UTF-8)

### ISSUE THREAD

**Issue by DemoBytom** [nuke-build/nuke#371]
### Description

Running GIT commands (and most likely any that are run through `Process.Start(startInfo);`) on Windows doesn't handle non standard characters in the output.
For example returns `Micha┼é` instead `Michał` 

Tested using cloned Nuke repository

### Steps to reproduce

1. Create dummy commit in repository with author set to `Michał` and email set to `email@email.com`
![image](https://user-images.githubusercontent.com/17877724/71769744-37854e00-2f25-11ea-9bfb-7a568b98eae6.png)
2. Run code below:
   ```csharp
    private Target UpdateContributors => _ => _
         .Executes(() =>
         {
             var repositoryDirectories = new[] { RootDirectory / ".git" }
                 .Concat(ExternalRepositoriesDirectory.GlobDirectories("*/.git"));
            var contributors = repositoryDirectories
                .SelectMany(x => Git(@"log --pretty=""%an|%ae%n%cn|%ce""", workingDirectory: x, logOutput: false))
                .Select(x => x.Text)
                .Distinct().ToList()
                .Select(x => x.Split('|'))
                .ForEachLazy(x => Assert(x.Length == 2, "x.Length == 2"))
                .Select(x => new { Name = x[0], Email = x[1] })
                 .Where(o => o.Email.Equals("email@email.com"))
                 .Select(o => o.Name)
                 .ToArray();

             var contributorsStr = string.Join(';', contributors);
             Logger.Info(contributorsStr);
         });
   ```
3. Outup is corrupted:
![image](https://user-images.githubusercontent.com/17877724/71769950-54bb1c00-2f27-11ea-80b6-3eafc6a33d7a.png)

### Proposed fix
Changing `ProcessTasks.StartProcessInternal()` to include `StandardErrorEncoding` and `StandardOutputEncoding ` set to `Encoding.UTF8` seems to fix the issue:

```
var startInfo = new ProcessStartInfo
{
    FileName = toolPath,
    Arguments = arguments ?? string.Empty,
    WorkingDirectory = workingDirectory ?? EnvironmentInfo.WorkingDirectory,
    RedirectStandardOutput = true,
    RedirectStandardError = true,
    UseShellExecute = false,
    StandardErrorEncoding = Encoding.UTF8,
    StandardOutputEncoding = Encoding.UTF8
};
```

Reruning the test after change returns correct string:
![image](https://user-images.githubusercontent.com/17877724/71769933-2c332200-2f27-11ea-8742-3f666cd15957.png)

Tested on latest stable version (0.23.0) and latest develop (SHA 1a3d536cd7d7521687a6b2649232d635e2414623)

**Comment by matkoch** [comment]
Done. Thanks for raising this.

**Comment by matkoch** [comment]
Seems this is not as easy. Setting the encoding breaks output on TeamCity and AppVeyor for me. So I will revert the change for now.

**Comment by matkoch** [comment]
https://help.appveyor.com/discussions/problems/25861-encoding

<blockquote><div><strong><a href="https://help.appveyor.com/discussions/problems/25861-encoding">Encoding / Problems / Discussion Area - AppVeyor Support</a></strong></div></blockquote>
