### ISSUE TITLE
Support of parameters with underscores

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#379]
### Description

A member `PackagesApiKey` attributed with `[Parameter]` should also take environment variables in the format `PACKAGES_API_KEY` into account.

#### Example

```csharp
[Parameter] string PackagesApiKey;
```

When specifying this the following should be possible:

* Environment Variables
  * `PACKAGES_API_KEY=abc` 
  * `PACKAGESAPIKEY=abc` 
  * `packagesapikey=abc`
  * `PackagesApiKey=abc`
* Command-Line-Args
  * `--packages-api-key abc`
  * `-PackagesApiKey abc`

**Comment by matkoch** [comment]
Direct match still has precendence.
