### ISSUE TITLE
Allow multiple VerbosityMappingAttribute on class level

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#380]
### Description

Currently, it's not possible to add multiple `VerbosityMappingAttribute` on a class.

### Steps to reproduce

Add multiple `VerbosityMappingAttribute` on the `Build` class.

```csharp
[VerbosityMapping(typeof(ReportGeneratorVerbosity),
    Quiet = nameof(ReportGeneratorVerbosity.Off),
    Minimal = nameof(ReportGeneratorVerbosity.Warning),
    Normal = nameof(ReportGeneratorVerbosity.Info),
    Verbose = nameof(ReportGeneratorVerbosity.Verbose))]
[VerbosityMapping(typeof(NuGetVerbosity),
    Quiet = nameof(NuGetVerbosity.Quiet),
    Minimal = nameof(NuGetVerbosity.Normal),
    Normal = nameof(NuGetVerbosity.Normal),
    Verbose = nameof(NuGetVerbosity.Detailed))]
class Build : NukeBuild
{
}
```

### Relevant log output

```ext
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0579	Duplicate 'VerbosityMapping' attribute	_build	C:\build\Build.cs	38	Active
```

**Comment by matkoch** [comment]
This is by design. You can create derived attributes and add them to the build class. I did that so that the build definition is not overcrowded with logging mappings.

**Comment by matkoch** [comment]
Okay, the docs don't reflect that. I rather change the attribute usage instead of documentation. You win 👏
