### ISSUE TITLE
Tool warning is treated as build problem and causes build to fail

### ISSUE THREAD

**Issue by MichaelSL** [nuke-build/nuke#382]
### Description

After updating nukebuild from `0.23.4` to `0.23.6` our Docker build started to fail.
It happens because Docker throws a warning when using `docker login` with a password from command line. It was reported as a warning before but didn't cause build to fail.

### Steps to reproduce

0. Use Nuke `0.23.6`.
1. Create a Team City build configuration
2. Create a build Target which calls Docker.
```
DockerTasks.DockerLogin(conf => conf
                .SetServer("https://your-server.org/")
                .SetUsername(DockerLogin)
                .SetPassword(DockerPassword));
```
3. Run build configuration.

### Relevant log output

Relevant part of Team City build log.
```
[Step 1/3] NUKE Execution Engine version 0.23.6 (Linux,.NETStandard,Version=v2.0)
[13:54:57]
[Step 1/3] LoginToNuget
[13:54:58]
[LoginToNuget] > /usr/bin/docker login --password [hidden] --username [redacted] [redacted]
[13:54:58]
[LoginToNuget] Login Succeeded
[13:55:00]
[Step 1/3] WARNING! Using --password via the CLI is insecure. Use --password-stdin.
[13:55:00]
[Step 1/3] WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
[13:55:00]
[Step 1/3] Configure a credential helper to remove this warning. See
[13:55:00]
[Step 1/3] https://docs.docker.com/engine/reference/commandline/login/#credentials-store
[13:54:58]
[Step 1/3] "description" attribute must be a non-empty value for "buildProblem" service message
```

### Workaround

Use `DisableLogOutput` on `DockerLogin` command:

```
DockerTasks.DockerLogin(conf => conf
                .SetServer("https://your-server.org/")
                .SetUsername(DockerLogin)
                .SetPassword(DockerPassword)
                .DisableLogOutput());
```

**Comment by matkoch** [comment]
I worked on better CI system integration for warning and error messages. The current implementation is going to remain. The real issue here is that Docker writes warnings on the error stream, so I will close this issue. However, I would accept a PR that implements a custom Docker logger (search for `DotNetTasks.CustomLogger`), that could fix the issue.
