### ISSUE TITLE
TeamCity build configuration branch filter

### ISSUE THREAD

**Issue by razenpok** [nuke-build/nuke#386]
### Description

TeamCity build configurations have [branch filters](https://teamcity.jetbrains.com/app/dsl-documentation/jetbrains.build-server.configs.kotlin.v2019_2/-vcs-settings/branch-filter.html) (not to confuse with vcs trigger branch filters) which are not exposed via Nuke. These filters make TeamCity UI hide irrelevant branches in build configuration overview page which is a nice UX improvement.

![image](https://user-images.githubusercontent.com/8434406/73439797-42cf6c00-4361-11ea-8f82-c66b9b402adc.png)

**Comment by matkoch** [comment]
VcsRoots are not specified by NUKE starting with 0.24

**Comment by razenpok** [comment]
What was the reason for ditching VcsRoots?

**Comment by razenpok** [comment]
And btw, this branch filter is not for a concrete VcsRoot, it is applied to a whole configuration.

**Comment by matkoch** [comment]
VcsRoots have so many options that it makes no sense to repeat logic inside the C# implementation. They can be reused from where they were originally defined.

**Comment by razenpok** [comment]
Uh, I'm not that familiar with Nuke. What do you mean by "They can be reused from where they were originally defined."?

**Comment by matkoch** [comment]
You define VcsRoots in the TeamCity UI. Not in the C# build implementation.

**Comment by razenpok** [comment]
Ok, got it. The thing is, the options I'm talking about are _per-configuration_, i.e. I'm still required to go through each build configuration and set this branch filter individually. VcsRoots are not involved in this process.

**Comment by matkoch** [comment]
In that case, you can simply change the settings from the UI.

**Comment by razenpok** [comment]
Yep, we do that already. It's just weird that Nuke has `cleanCheckout` and `showDependenciesChanges` from `VcsSettings` and not `branchFilter`.
