### ISSUE TITLE
Use .EnableNoFetch() in GitVersionAttribute for SSH repositories

### ISSUE THREAD

**Issue by razenpok** [nuke-build/nuke#388]
### Description

As far as I can see, [GitVersion doesn't support SSH](https://github.com/GitTools/GitVersion/issues/38#issuecomment-415711401) because [LibGit2Sharp doesn't have a publicly available version which supports it](https://github.com/libgit2/libgit2sharp/issues/1422). Given that by default GitVersion does a fetch on invocation, using `GitVersionAttribute` in conjunction with SSH repo will always fail. Simply using `.EnableNoFetch()` for SSH repositories would mitigate this issue while retaining the default behavior for HTTPS.

### Alternatives

Just using `.EnableNoFetch()` implicitly for SSH repositories might be confusing for users since there's no indication of such a change in default behavior. To improve UX in this situation we can:
- log a warning with a mention of /nofetch usage for SSH to notify a user about this change
- add a `NoFetch` property to the attribute if a user would want to override this behavior

A completely alternative implementation would be using `.EnableNoFetch()` both for SSH and HTTPS. Since builds are usually run on up-to-date repositories on build agents/slaves/etc, there is no need to fetch from a remote. Logging a warning, in this case, would or would not be useful (idk).

Regarding the current state of Nuke, there are a couple of workarounds:
- Switch to HTTPS
- Copy-paste Nuke's `GitVersionAttribute` and append `.EnableNoFetch()` to `GitVersion` ` (I am currently using this solution)

**Comment by matkoch** [comment]
I'm adding the property.

**Comment by razenpok** [comment]
Thanks! What do you think about adding a warning if an attribute is used in an SSH repo when `NoFetch` is not set?

**Comment by razenpok** [comment]
Ping
