### ISSUE TITLE
TeamCityOutputSink Ansi color choice

### ISSUE THREAD

**Issue by razenpok** [nuke-build/nuke#393]
### Description

What's the reasoning behind [TeamCityOutputSink](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/CI/TeamCity/TeamCityOutputSink.cs)'s Ansi color choice?

- Warning, Error and Success all use reasonable colors and look good
- Trace uses White color (37m). TeamCity's background is also white
- Information uses Cyan color (36m) which is better than white but still much harder to read than black on white background

### Alternatives

- Black (30m) for Information
- Blue (34m) or Magenta (35m) for Trace, though Cyan (36m) is also fine I guess

Here are available color codes (30-37, 40-47, 90-97, 100-107).
![image](https://user-images.githubusercontent.com/8434406/73723788-f5754500-473a-11ea-979b-e85c75204540.png)

**Comment by matkoch** [comment]
Now made it dark gray. If that's still not enough, please report back.
