### ISSUE TITLE
Missing tools from PackageDownload when publishing as global tool

### ISSUE THREAD

**Issue by yang-xiaodong** [nuke-build/nuke#394]
### Description

GitVersion does not work when packaged as dotnet tools for sharing in a team.
The error message is ` Could not find package 'GitVersion.Tool', or 'GitVersion.CommandLine'`

### Steps to reproduce

1. The tools project named  **MyCommand.csproj**

```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PackAsTool>True</PackAsTool>
    <IsPackable>True</IsPackable>
    <ToolCommandName>mycommand</ToolCommandName>
    <PackageOutputPath>./../artefacts</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nuke.Common" Version="0.24.0" />
    <PackageDownload Include="GitVersion.Tool" Version="[5.1.1]" />
  </ItemGroup>
```

2.  **Build.cs** code under the MyCommand.csproj
```cs
class Build : NukeBuild
{
    public static int Main() => Execute<Build>(x => x.ShowVersion);

    [GitVersion] GitVersion GitVersion;

    Target ShowVersion => _ => _
        .Executes(() =>
        {
            Logger.Success("Current Version: " + GitVersion.SemVer);
        });
}

```

3.  Pack the dotnet tools project  MyCommand.csproj  and push to nuget server

```sh
> dotnet pack MyCommand.csproj 
> dotnet nuget push -s http://192.168.xxx.xxx/v3/index.json ..\artefacts\MyCommand.1.0.0.nupkg
```

4、Install as the dotnet tool and execute to show the version

```sh
> dotnet tool install -g --add-source http://192.168.xxx.xxx/v3/index.json MyCommand
> mycommand showversion
```

Then the error will be raised

### Relevant log output

```
NUKE Execution Engine version 0.24.0 (Windows,.NETCoreApp,Version=v3.0)

Assertion failed: Could not find package 'GitVersion.Tool', or 'GitVersion.CommandLine' using:
 - Embedded packages directory at ''
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageDirectory(String[] packageIds, String version)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.GetToolPath()
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.get_ToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
   at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

**Comment by matkoch** [comment]
Could you please star the project?

**Comment by yang-xiaodong** [comment]
> Could you please star the project?

Yes, it works in visual studio

**Comment by yang-xiaodong** [comment]
Sure,   :)
By the way , it  works in visual studio

**Comment by yang-xiaodong** [comment]
If needed, I can help write a blog and publicity in China .net community website. I have about 2000+ followers of .net fans

**Comment by matkoch** [comment]
@yang-xiaodong sure, always welcome :)

what do you mean, what works in Visual Studio?

**Comment by yang-xiaodong** [comment]
Source code in visual studio, click nuke icon and debug can print the version, no error!

**Comment by matkoch** [comment]
Yes. That works different than after installing as global tool.

**Comment by matkoch** [comment]
For now I suggest to switch to `PackageReference` with `ExcludeAssets=all`. That should work, afaik.

**Comment by yang-xiaodong** [comment]
@matkoch Thanks for your answer, I tried the suggested way you pointed, it doesn't seem to work for me, am I missing something?

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PackAsTool>True</PackAsTool>
    <IsPackable>True</IsPackable>
    <ToolCommandName>mycommand</ToolCommandName>
    <PackageOutputPath>./../artefacts</PackageOutputPath>
    <Version>1.0.4</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nuke.Common" Version="0.24.0" />

<!--<PackageDownload Include="GitVersion.Tool" Version="[5.1.1]" />-->
    <PackageReference Include="GitVersion.Tool" Version="5.1.1">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>    
  </ItemGroup>
</Project>
```

**Comment by cmenzi** [comment]
Maybe some information on this:

- https://github.com/NuGet/Home/issues/9132#issuecomment-581740452

When you're using `<ExcludeAssets>all</ExcludeAssets>` the references don't get packed into nuget.

I've nearly managed it though `.props` file.  See here: https://github.com/nuke-build/nuke/issues/396

Another option regarding this: https://github.com/NuGet/Home/issues/9132#issuecomment-581740452 is not using `<Project Sdk="Microsoft.NET.Sdk">.

Suggestion from nuget team is to use https://github.com/microsoft/MSBuildSdks 




<blockquote><img src="https://repository-images.githubusercontent.com/119565463/88fe1580-7d66-11e9-95b7-57208b3c811d" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/microsoft/MSBuildSdks">microsoft/MSBuildSdks</a></strong></div><div>MSBuild project SDKs. Contribute to microsoft/MSBuildSdks development by creating an account on GitHub.</div></blockquote>

**Comment by krankenbro** [comment]
I had the same problem. The found workaround is to add constructor
```csharp
public Build()
{
        ToolPathResolver.ExecutingAssemblyDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
}
```
