### ISSUE TITLE
Don't warn about active build configuration if it's not part of the solution one wants to build

### ISSUE THREAD

**Issue by marcpiechura** [nuke-build/nuke#395]
### Description
Would be cool if nuke would only log the warning if the build project is part of the .sln that is defined in the .nuke file, or check if the .sln, it is part of, contains any other projects and only if that's the case, log the warning. 
The reason is that we can't change anything in the build project without Visual Studio complaining that it wants to create a .sln, which is a bit annoying ;-) So in our case, we created a .sln file only for the build project and therefore it doesn't build itself. 
 
### Alternatives
Just remove the `CheckBuildProjectConfigurations` attribute :)

**Comment by matkoch** [comment]
Mh... why don't you add the build project to your usual solution?

And even in the dedicated solution file, you could remove the build project from the build configurations.

**Comment by marcpiechura** [comment]
Sorry, you're right. Removing only the build configuration fixes the issue, didn't know that's possible hence why I thought a different solution file would fix the problem ;-)
