### ISSUE TITLE
Pipeline caching task for azure pipelines

### ISSUE THREAD

**Issue by wischi-chr** [nuke-build/nuke#398]
Up until now I called nuke with a powershell task in an azure pipeline and I'm trying to switch to autogenerated yaml pipeline files (saw the talk at rubicon and didn't know about that feature before).

Is it possible to make use of the azure pipeline mechanism to cache nuget packages? I've a hand full of tasks and each tasks taskes about a minute to start (from the start of the script until the logo is shown) IMO one minute is fine for installing dotnet core 3.1, restoring nugets for nuke, etc. but if this overhead is per Target it adds up quickly.

Alternatively NonEntryTargets could be expressed as steps inside the yaml, this would also solve the fact that artifacts are not published for NonEntryTargets .

**Comment by matkoch** [comment]
You can also use the pre-installed SDK.

**Comment by wischi-chr** [comment]
According to the [logs of the most recent nuke azure build](https://dev.azure.com/nuke-build/db5bcee5-db3e-430e-980b-96372b5b7941/_apis/build/builds/718/logs/28) Installing .net core took about 15 seconds, but restoring the nuget packages took over a minute.
