### ISSUE TITLE
AbsolutePath symbol missing

### ISSUE THREAD

**Issue by gsscoder** [nuke-build/nuke#403]
I don't know if this is a bug or something linked to my environment. This the error when I try to execute `build.sh`:
```sh
Build.cs(33,5): error CS0246: The type or namespace name 'AbsolutePath' could not be found (are you missing a using directive or an assembly reference?) [/Users/coder/Dropbox/Hacking/DotNetCore/nuketest/src/NukeTest.Build/NukeTest.Build.csproj]
Build.cs(34,5): error CS0246: The type or namespace name 'AbsolutePath' could not be found (are you missing a using directive or an assembly reference?) [/Users/coder/Dropbox/Hacking/DotNetCore/nuketest/src/NukeTest.Build/NukeTest.Build.csproj]
```
I've added the build project using `nuke :setup` command. The solution is very simple (created only to evaluate this great tool).
![Nuke test solution VSCode Screenshot](https://user-images.githubusercontent.com/1194228/74430668-a5466300-4e5d-11ea-99c3-334954ebf0e8.png)

This is the output of `dotnet --info` on my **mac OS Catalina**:
```sh
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

And that's the one of `system_profiler SPHardwareDataType` command:
```sh
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro9,2
      Processor Name: Dual-Core Intel Core i5
      Processor Speed: 2,5 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 3 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      Boot ROM Version: 230.0.0.0.0
      SMC Version (system): 2.2f44
      Serial Number (system): C1MKPPTMDTY3
      Hardware UUID: 1EB71DD5-ECCB-5663-8C03-73BDBDA3D224
      Sudden Motion Sensor:
          State: Enabled
```

Thank you.
Best regards,
Giacomo S. S.

**Comment by matkoch** [comment]
I just tested the setup procedure calling `nuke` twice (first execution is a setup, second will build it). Everything works as expected. Could you point me to a repro?

**Comment by matkoch** [comment]
Since the default build doesn't include any usage of `AbsolutePath` I suspect you've added that manually. This type is contained in the `Nuke.Common.IO` namespace, so you need a `using` directive for that. Not sure if that's obvious to you, but this is just a console application. So everything works as in any other C# project.

**Comment by gsscoder** [comment]
Thanks for replying **so fast**, @matkoch. I shared a zip with the solution: https://www.dropbox.com/s/c16obaw2cvnxqx1/nuketest.zip?dl=0.

I confirm you I've **not modified anything** after `nuke :setup`.

If you need anything else, please let me know.


<blockquote><img src="https://www.dropbox.com/static/images/spectrum-icons/generated/content/content-zip-large.png" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/s/c16obaw2cvnxqx1/nuketest.zip?dl=0">nuketest.zip</a></strong></div><div>Shared with Dropbox</div></blockquote>

**Comment by matkoch** [comment]
Yes, it’s the template that’s out-of-date. But it’s still just a missing using directive.

**Comment by gsscoder** [comment]
OK, thank you for support.
