### ISSUE TITLE
Add Octopus.DotNet.Cli package as tool executable

### ISSUE THREAD

**Issue by tunger** [nuke-build/nuke#414]
### Description
Octopus Deploy has a dotnet core tool published as [nuget package](https://www.nuget.org/packages/Octopus.DotNet.Cli/7.1.0). At present there is only OctopusTools listed as `packageId` for Octopus.
https://github.com/nuke-build/nuke/blob/develop/build/specifications/Octopus.json#L12

I tried adding the change myself by adding:
`
  "packageId": "OctopusTools|Octopus.DotNet.Cli",
  "packageExecutable": "Octo.exe|dotnet-octo.dll",
`

However, the Octopus.DotNet.Cli package contains binaries for two frameworks (separate folders netcoreapp2.1 & netcoreapp3.1). `ToolPathResolver` expects a `framework` parameter in this case. 
https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tooling/ToolPathResolver.cs#L62
However, this parameter can't be specified in the code generation json schema.

Therefore I wanted to reach out to you.

### Possible solutions
1. Add that one can add framework specification in code generation json schema. However, this might interfere with lookup when there are .NET Framework and .NET Core packages mixed?
2. Allow an array "packages" in code generation json schema consisting of (id, executable, framework). Code generation would pipe multiple `ToolPathResolver.GetPackageExecutable` calls.

**Comment by matkoch** [comment]
Please create a PR similar to [this commit](https://github.com/nuke-build/nuke/commit/7effe95745e7917f01d1db795fc09e194e08e3da). I will close the issue as it's not essential for the library. Awaiting the PR.
