### ISSUE TITLE
Control name of generated yml file for Azure DevOps Pipeline

### ISSUE THREAD

**Issue by BoSorensen** [nuke-build/nuke#416]
### Description

The default name when generating a pipeline YAML file for Azure DevOps is azure-pipelines.yml. But that is the default name for pipelines, so it would be great if it could be modified to something like azure-pipelines.nuke.yml instead.

### Alternatives

I don't really see any alternative.

**Comment by matkoch** [comment]
What's wrong about the default name?

**Comment by BoSorensen** [comment]
I would like for the default yml file of a pipeline to use the generated Nuke yml file as a template. That requires another name, such as 'azure-pipelines.nuke.yml'.
This inspiration comes from [this commit](https://github.com/RocketSurgeonsGuild/Nuke/blob/2576bf0c970f4cd2eeb3531e48b337635b06255f/src/Nuke/AzurePipelinesStepsAttribute.cs) where a similar approach is used.
