### ISSUE TITLE
Support for nuget install

### ISSUE THREAD

**Issue by matt-richardson** [nuke-build/nuke#417]
### Description

We're spiking out converting some of our builds from cake to nuke (and loving it!), and one thing we've found missing in nuke is support for nuget install.

I'd like to propose adding support for nuget install. As far as I can tell, this will just require adding the details from [the docs](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-install) to the [nuget.json](https://github.com/nuke-build/nuke/blob/master/build/specifications/NuGet.json) specification.

### Alternatives

We've currently got a local manually written implementation of the nuget install, based on how the nuget restore works... It's... a lot more code than i'd like to keep around :)

Another approach might be to use a `Tool`, which is probably very much simpler than my first attempt.

### Proposal

I'm happy to contribute a PR (I've actually got something already written locally), but wanted to check in first to see if this is something you'd be interested in accepting. Also wanted to check if adding to the `nuget.json` was the correct approach and to get some advice on the best way to test it.

**Comment by matkoch** [comment]
@matt-richardson thanks for the kind words. PRs are very welcome. As you've probably seen this is just about adding a new `task` in the specification file. My wish would be to transform the help texts with care and mind situations with formatting. I.e. you should use `<ul>` and `<li>` for `DependencyVersion` for instance, `<c>` for code, `<em>` for emphasized text.

**Comment by matkoch** [comment]
Testing works either:
- by adding the modified json to your local build project. Recompile, and generated code should be there.
- or by working directly in our solution, execute `nuke regenerate-tool`

**Comment by matkoch** [comment]
Out of curiosity, what do you mean by _local manually written implementation_ ? Could you share it?

**Comment by matt-richardson** [comment]
> Out of curiosity, what do you mean by _local manually written implementation_ ? Could you share it?

It was a case of reverse engineering our NugetRestore and friends worked, and then tweaking to work for the `nuget install` case we needed.

I've dropped into a gist - https://gist.github.com/matt-richardson/b4dfc84a0d3e1377194d62554d243e7a

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/matt-richardson/b4dfc84a0d3e1377194d62554d243e7a">Handwritten task class for nuke to support nuget install</a></strong></div><div>Handwritten task class for nuke to support nuget install - CustomNugetTasks.cs</div></blockquote>
