### ISSUE TITLE
NpmTasks.Npm() outputs warnings as errors

### ISSUE THREAD

**Issue by kvnhck** [nuke-build/nuke#421]
### Steps to reproduce

Add a NpmTasks.Npm() call

```
NpmTasks.Npm("install", Directory);
```

### Log output

Warnings are marked as errors. This results in broken builds on CI systems like TeamCity.

**Comment by ThinkingBIGRon** [comment]
@kvnhck - I have a pull request in to correct this - https://github.com/nuke-build/nuke/pull/419
