### ISSUE TITLE
Please update Glob v1.1.5 to remove debug logging

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#422]
Could you please update `Glob` dependency to version 1.1.5 to remove the debug or hard coded console.writeline logging.

https://github.com/kthompson/glob/releases/tag/1.1.5
https://github.com/kthompson/glob/commit/711b3293e9923cfcd26c8ab34565573bf1181e05,

Thx

**Comment by matkoch** [comment]
Please create a pr
