### ISSUE TITLE
Support for new dotnet nuget commands

### ISSUE THREAD

**Issue by BoSorensen** [nuke-build/nuke#425]
### Description
The 3.1.200-preview version of the DotNet SDK will have extended support for manipulating NuGet sources and it would be nice to have support for those in Nuke. [The original issue was reported here](https://github.com/NuGet/Home/issues/4126).

The help for the improved **dotnet nuget** command looks like this:

> Usage: dotnet nuget [options] [command]
> 
> Options:
>   -h|--help  Show help information
>   --version  Show version information
> 
> Commands:
>   add      Add a NuGet source.
>   delete   Deletes a package from the server.
>   disable  Disable a NuGet source.
>   enable   Enable a NuGet source.
>   list     List configured NuGet sources.
>   locals   Clears or lists local NuGet resources such as http requests cache, packages folder, plugin operations cache  or machine-wide global packages folder.
>   push     Pushes a package to the server and publishes it.
>   remove   Remove a NuGet source.
>   update   Update a NuGet source.
> 

### Alternatives
Use the NuGet.exe executable or manipulate the nuget.config file directly.

**Comment by matkoch** [comment]
Please create a PR.

**Comment by BoSorensen** [comment]
After reading the documentation some more there is another workaround.
Start by defining the dotnet executable like this:
```
[PathExecutable("dotnet")]
readonly Tool DotnetExecutable;
```

In a target do the following:
```
    Target SetupNuget => _ => _
        .Executes(() =>
        {
            DotnetExecutable($"nuget add source {FeedSource} --name Core --configfile {NugetConfig} --username someuser --password somepass --store-password-in-clear-text");
        });
```
Note that this requires FeedSource and NugetConfig variables to be defined.

**Comment by matkoch** [comment]
There's also the workaround of providing a PR :)
