### ISSUE TITLE
Can not activate the 'NUKE Support' VS code

### ISSUE THREAD

**Issue by ghost** [nuke-build/nuke#426]
### Description
Error:
Cannot activate the 'NUKE Support' extension because it depends on an unknown 'ms-vscode.csharp' extension .

The C# extension changed their package name from ms-vscode.chsarp to ms-dotnettools.csharp (you can find it in the change-log of version 1.21.13).

### Steps to reproduce
Installed latest extensions on a clean vs-code.

Also, i have tried to change the ".vsixmanifest" in the Nuke extension and reload/reinstall the packages (but no success), I might miss something with this local fix.
```
<Property Id="Microsoft.VisualStudio.Code.ExtensionDependencies" Value="ms-dotnettools.csharp" />
```

**Comment by matkoch** [comment]
Care for a PR and fav'ing the project?

**Comment by ghost** [comment]
Sure, I can do that. I am just not hundred percent about how to solve it :)

**Comment by matkoch** [comment]
Just updating the reference, no? Actually, a PR already exists. But you could help verifying that it works. I don't use vscode.

https://github.com/nuke-build/vscode/pull/2/files

<blockquote><img src="https://avatars3.githubusercontent.com/u/611219?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/vscode/pull/2">Update the C# extension publisher name by JoeRobich · Pull Request #2 · nuke-build/vscode</a></strong></div><div>Hi,
I work on the C# extension for VS Code. We see that this extension has a dependency on our C# extension. We wanted to inform you of our intent to change the account we publish the extension und...</div></blockquote>

**Comment by ghost** [comment]
I approved that the PR on the vs code repository is solving the issue.
You can mark this as solved.
