### ISSUE TITLE
Add option to run a Tool with elevated privileges

### ISSUE THREAD

**Issue by totollygeek** [nuke-build/nuke#428]
### Description
I might want to run a CLI tool as administrator. An example for that is to install or use [Chocolatey](https://chocolatey.org/). 
This can be easily achieved if we add a flag in the `Tool` delegate and then if set to `true` to add a `Verb` in the `ProcessStartInfo` to start the process with elevation.

If you like the idea, I will go on and prepare a PR for adding it.

### Alternatives
Not sure if there is an alternative at the moment. Maybe it is, but I can't figure it out.

**Comment by matkoch** [comment]
Like the idea. You can go on.

**Comment by matkoch** [comment]
@totollygeek close this?

**Comment by totollygeek** [comment]
> 
> 
> @totollygeek close this?

Not yet, please. Give me a little bit of time to try to figure out a way to do it. If not, I will close it in a few days.

**Comment by totollygeek** [comment]
Can't seem to find a solution that fits at the moment. Closing issue until enlightenment comes and I figure out something genius 😏
