### ISSUE TITLE
Ability to generate steps and not jobs in AzurePipelines

### ISSUE THREAD

**Issue by BoSorensen** [nuke-build/nuke#431]
### Description
I have defined a simple build pipeline with just two targets. The main target Restore depends on another target. I have configured the AzurePipelines like this:
```
[AzurePipelines(
    AzurePipelinesImage.UbuntuLatest,
    InvokedTargets = new[] { nameof(Restore) })]
```
Then i generate the azure-pipelines.yml file like this `nuke --configure-build-server --host AzurePipelines`. The end result is a pipeline with two jobs, where each job is run on its own Agent.

I would like to specify that the two targets should be defined as steps and not jobs, the documentation does not seem to offer any information on how to do this.
The reason for doing this, is that the targets work together, so having jobs on different Agents won't work.

EDIT:
Some more context from https://developercommunity.visualstudio.com/content/problem/671622/pass-setup-from-one-job-to-another-in-azure-devops.html, which explains that this is specific to **Microsoft-hosted agents** that is used, quote:

> Microsoft-hosted agents, we see that each time we run a pipeline, we get a fresh virtual machine. The virtual machine is discarded after one use. That is to say, each time we get a fresh hosted agent to run a single job.

### Alternatives
Manually creating a pipeline file and calling each target using `build.cmd`.

**Comment by matkoch** [comment]
Just put every other target in `NonEntryTargets`.
