### ISSUE TITLE
The Azure Pipeline System.AccessToken secret is not available to scripts

### ISSUE THREAD

**Issue by BoSorensen** [nuke-build/nuke#432]
### Description
When trying to use the predefined variable AccessToken i get an empty variable. This is due to System.AccessToken not being accessible to scripts in Azure Pipelines. See https://daveaglick.com/posts/pushing-packages-from-azure-pipelines-to-azure-artifacts-using-cake for a good explanation of the issue.

However i see no way of generating a yml file where the env: keyword along with System.AccessToken is specified like this:
```
   env:
     SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

**Comment by erkinkas** [comment]
Have you tried to select the tick box?

![image](https://user-images.githubusercontent.com/13992901/76333939-48b65680-62ea-11ea-92cd-165ea74e0c9d.png)

**Comment by BoSorensen** [comment]
I don't have that box anywhere, i think it was for a previous design of Azure DevOps.
The only way to enable System.AccessToken in a script is to add the `env:` block i think.

The option used to be a part of Pipeline settings, see for example https://stackoverflow.com/questions/50741682/vsts-where-has-allow-scripts-to-access-oauth-token-gone. Currently in Azure DevOps pipeline these settings look like this:
https://dontcodetired.com/blog/image.axd?picture=image_117.png

**Comment by BoSorensen** [comment]
Would modifying Nuke.Common.CI.AzurePipelines.AzurePipelinesAttribute to support a boolean EnableAccessToken be acceptable ? I'm thinking this is only relevant for AzurePipelines and since a single job is generated, it would be fine to enable this through the AzurePipelines configuration.
