### ISSUE TITLE
The Produces keyword does not generate PublishBuildArtifacts task for Azure Pipeline when target is added to the NonEntryTargets group

### ISSUE THREAD

**Issue by BoSorensen** [nuke-build/nuke#434]
### Description
Adding a target that uses the Produces keyword to the NonEntryTargets group causes the PublishBuildArtifacts task to not be output in the generated yml file.

### Steps to reproduce
Start with a AzurePipelines definition with a Target named Pack that calls the DotNetPack command like this:
```
[AzurePipelines(
    AzurePipelinesImage.UbuntuLatest,
    NonEntryTargets = new[] { nameof(Pack) },
    InvokedTargets = new[] { nameof(Publish) })]

...
    Target Pack => _ => _
        .Produces(ArtifactsDirectory / "*.nupkg")
        .Executes(() =>
        {
            DotNetPack(_ => _
...
```

When the Pack target is added to the NonEntryTargets group, then no PublishBuildArtifacts task is added to the generated yml file. Adding the Pack target to the InvokedTargets group instead causes the PublishBuildArtifacts task to be generated in the yml file.

It is not an option to put the target in the InvokedTargets group as i'm trying to invoke all targets in a single build.cmd line to avoid multiple jobs (see issue #431).

UPDATE:
It seems that placing the Produces keyword on the target that do belong to the InvokedTargets group creates the task in the generated yml file. In my case placing it on the Publish target works, although i would rather have the Produces keyword on the target that actually produces the artifact.

**Comment by matkoch** [comment]
We have a solution, just checking on making it more abstract for all CI environments.
