### ISSUE TITLE
More control over DisplayName for AzurePipelines job

### ISSUE THREAD

**Issue by BoSorensen** [nuke-build/nuke#436]
### Description
Currently the Job name and DisplayName for an AzurePipelines job are identical. It would be nice to have different values set for the two. Perhaps Description could be used as input for DisplayName as it does not seem to be used for anything.

To be backwards compatible, the DisplayName could still work as it is today if Description has not been set for the target.

### Alternatives
Not really.

**Comment by ThinkingBIGRon** [comment]
I see value in this too - in other build environments like TeamCity.

**Comment by matkoch** [comment]
You can create your own derived attribute and set the display name.
