### ISSUE TITLE
Nuke doesn't support DebugType for DotNetPublish and DotNetBuild

### ISSUE THREAD

**Issue by falamarzijahromi** [nuke-build/nuke#439]
### Description

In many cases for builds and publishes, it's required to have the build results without .pdb files. With dotnet core CLI it's possible to achieve this by entering dotnet publish /p:DebugType=None

### Alternatives

Setting property group condition for different configurations in the project file.

`
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
  <DebugType>None</DebugType>
  <DebugSymbols>false</DebugSymbols>
</PropertyGroup>
`

Or Setting a post build action for deleting .pdb files after publish or build by putting its Action delegate in the .Execute().

**Comment by matkoch** [comment]
Please create a PR.
