### ISSUE TITLE
Add Commit to GitRepository

### ISSUE THREAD

**Issue by lars-nielsen** [nuke-build/nuke#441]
### Description
Nuke.Common.Git.GitRepository interacts with the local repository and parses the HEAD file.

All that is needed is reading the contents of .git\refs\heads\XXXX and exposing it in a Commit property on the GitRepository type

Edit.
In the event that the HEAD is detached the id will be located in HEAD file 

### Alternatives
Use GitVersion - But this approach seems overkill as this is information already is available

**Comment by matkoch** [comment]
Could you provide a PR ?

**Comment by lars-nielsen** [comment]
@matkoch 

Yep, i'm finishing up right now. Can you confirm that there is no way to get the current commit from teamcity.

**Comment by matkoch** [comment]
@lars-nielsen I'm not sure what you mean? The commit sha?

**Comment by lars-nielsen** [comment]
@matkoch 

Yep, if we are doing a CI build we might as well inject it as is done with branch 
(GitRepositoryAttribute.GetBranch)

Search for **Build.SourceVersion** @ https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml 

So im looking for something equivalent.

**Comment by matkoch** [comment]
@lars-nielsen TeamCity provides it via `BuildVcsNumber`

**Comment by matkoch** [comment]
FYI, I've also added `Tags` as a property. Thanks for your PR.
