### ISSUE TITLE
GetPackageExecutable gets slower by big local package cache

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#443]
### Description

`PackageExecutable` or any other tool like GitVersion resolved by from NuGet packages, execution gets slower and slower. 

### Steps to reproduce

1. Having a huge package cache
1. dotTrace
1. Run `build.ps1`

On a build server it's not a big issue, but locally it becomes cumbersome. Not sure if we can try first directly guess the path and doing detailed resolving as a fallback.

### Relevant log output

![image](https://user-images.githubusercontent.com/1763806/76857176-33df4300-6855-11ea-8c26-c28a9f112953.png)

**Comment by tunger** [comment]
Ah, that's the reason why my builds were getting slower locally. I can confirm the issue.

**Comment by mortengjesing** [comment]
https://github.com/nuke-build/nuke/pull/408 should fix it

**Comment by matkoch** [comment]
For now we I'm taking a different approach of just filtering packages by ID. If this is not enough, feel free to reopen or comment again.
