### ISSUE TITLE
EnvironmentInfo.Framework is incorrect

### ISSUE THREAD

**Issue by macsux** [nuke-build/nuke#444]
### Description
EnvironmentInfo.Framework is reporting version that nuke assembly was compiled against, instead, it should be reporting the current framework. Since .NET Core 3.0, this can be retrieved via System.Environment.Version. 

### Steps to reproduce

1. Compile build against netcoreapp3.1
2. Start the app, it's reporting as netcoreapp3.0

This issue prevents usage of packages that require 3.1 such as the latest version of GitVersion.Tool

**Comment by matkoch** [comment]
How does this prevent from using packages for 3.1 ?
