### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by krankenbro** [nuke-build/nuke#449]
### Description
It would be nice to provide ability to return custom exit codes. For example, in some case my global tool returns code 123 and then it would be easy to get this in jenkins pipeline script(def code = bat script: mytool SomeTarget, returnStatus: true) for next processing.
To do this now i found an ugly workaround:
![image](https://user-images.githubusercontent.com/42555001/77400443-d77ba680-6db3-11ea-8587-f6ff2a1cb538.png)

**Comment by matkoch** [comment]
`SetExitCode(..)` or `ExitCode = ..` ?

**Comment by krankenbro** [comment]
@matkoch  for example:
![image](https://user-images.githubusercontent.com/42555001/77509309-2a696280-6e75-11ea-8902-f922ccdddba5.png)
in real app i want to handle 409 from nuget(nuget already exists), 422 from github(github release already exists) and so on

**Comment by matkoch** [comment]
The question was if it should be a method or property. But I think I’ll go
with `EnvironmentInfo.ExitCode`, as that is also settable from outside the
build class.

**Comment by maartenba** [comment]
@matkoch is `EnvironmentInfo.ExitCode` still the desired way of doing this? I might give it a try.

Also, should it be taken into account when the build throws an exception? In other words, if you set `EnvironmentInfo.ExitCode = 0`, should an exception during build respect that `0` or still return `-1`?

**Comment by matkoch** [comment]
I think I wanna go with `NukeBuild.ExitCode`. `EnvironmentInfo` is also used in other places, like the global tool, but we wouldn't use `ExitCode` there.

One thing to consider is how it should work with the calculated property `NukeBuild.IsSuccessful`...

**Comment by maartenba** [comment]
Leaning towards making it `NukeBuild.OverrideExitCode`, and always returning this as the exit code when set? So that when you set it, you opt in to manually controlling the exit code?

**Comment by maartenba** [comment]
PR incoming in the next days 👍
