### ISSUE TITLE
Website is out-of-date

### ISSUE THREAD

**Issue by MindWrapper** [nuke-build/nuke#45]
minimal build file link on getting started page leads to 404
https://raw.githubusercontent.com/nuke-build/nuke/master/bootstrapping/Build.cs

**Comment by matkoch** [comment]
A couple of other things:

- Remove troubleshootings (don't think it's worth; exceptions will tell what's wrong)
- Explain `=> _ => _`
- Fix parameters (nodeps)
- Add more references
- Change gitter to slack

**Comment by matkoch** [comment]
cc @arodus
