### ISSUE TITLE
Single node execution on CI environments

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#450]
### Description
Sometimes it's not necessary to run targets on different agents. In that case, we just want to execute all related targets (dependencies and triggers), to be executed with the top-level invoked target:

```
// Current state ---> nuke Restore Compile Test --skip
[TeamCity(TeamCityAgentPlatform.Unix,
    VcsTriggeredTargets = new[]{ nameof(Test) },
    NonEntryTargets = new[]{nameof(Restore), nameof(Compile)})]
```

### Suggestions
```
// alternative 1
[TeamCity(TeamCityAgentPlatform.Unix,
    RunSingleTarget = new[]{ nameof(Test) },
    VcsTriggeredTargets = new[]{nameof(Test)})]

// alternative 2
[TeamCity(TeamCityAgentPlatform.Unix,
    VcsTriggeredTargets = new[]{ nameof(Test) },
    SingleNodeMode = true)] // or SingleInvocationMode
```

Currently preferring alternative two, as it causes less confusion if `NonEntryTargets` is also applied.

**Comment by ThinkingBIGRon** [comment]
As mentioned on Twitch, my team is interested in this feature - I am happy to take it on for a PR.

**Comment by matkoch** [comment]
@ThinkingBIGRon any progress?

**Comment by ThinkingBIGRon** [comment]
I should be able to complete this over next few days.

**Comment by ThinkingBIGRon** [comment]
I have a version of this to test - will try it on a few projects tomorrow then submit the PR.
