### ISSUE TITLE
Simplify Platform (AnyCPU, x64, etc) handling

### ISSUE THREAD

**Issue by paolofulgoni** [nuke-build/nuke#452]
### Description

There are a lot of "helpers" to handle the Configuration:

* the `Nuke.Common.Configuration` class
* `.SetConfiguration(...)` methods in `MSBuild`, `NuGetPack` etc.
* a predefined `Configuration` property in the build template

But unfortunately there isn't the same to handle the Platform.

### Alternatives

Use the `Nuke.Common.Tools.MSBuild.MSBuildTargetPlatform` class

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/commit/c653e06c4f4399475ca550e0507470325ee169c1

**Comment by paolofulgoni** [comment]
@matkoch to be honest I didn't expect that code change... but it makes sense! 

Anyway, there is still inequality between Configuration and Platform...
What about adding a Platform class to the template?

**Comment by matkoch** [comment]
This is supposed to be a template to write your own Platform type. I think
platform is much less used than Configuration. I also moved Configuration,
since many want to extend it.
