### ISSUE TITLE
VSCode extension error: command 'nuke.runTarget' not found

### ISSUE THREAD

**Issue by paolofulgoni** [nuke-build/nuke#454]
### Steps to reproduce

1. open the build project folder in VS Code
2. press F1 and run the `Nuke: Run target` action
3. error: "command 'nuke.runTarget' not found"

![image](https://user-images.githubusercontent.com/5703017/78114408-8433d480-7401-11ea-88e7-9e08253c399e.png)

![image](https://user-images.githubusercontent.com/5703017/78114140-1687a880-7401-11ea-8284-e02f0c0e4bd4.png)

I'm using the VSCode extension v0.2.2

**Comment by ghost** [comment]
It will be easier to help if the screen shot would show if you are opened on the correct sln.
I susspect the vs code is not opened on the _build.csproj correctly.

**Comment by ghost** [comment]
Another option would be to go in the vs code settings->Nuke and change the path.

**Comment by paolofulgoni** [comment]
@ohgrad in my case, the build project is not part of any solution.
I've just opened the folder containing the build project (right click on the folder - open with code)
I can build/debug the project, so I think it's opened the right way.

**Comment by paolofulgoni** [comment]
I've just tried to change the **Nuke: Build project pattern** setting from `*build/*build*.csproj` to `*build*.csproj`, but nothing changed.

**Comment by ghost** [comment]
did you try to re-run the OmniSharp after changing the path ? or "reload window" ?

**Comment by paolofulgoni** [comment]
> did you try to re-run the OmniSharp after changing the path ? or "reload window" ?

I restarted VS code

**Comment by ghost** [comment]
Im sorry but i cant reproduce it.
can you send the OmniSharp log after finishing to load the project?

**Comment by paolofulgoni** [comment]
Sure! Here it is:

```
Starting OmniSharp server at 01/04/2020, 1:56:21 pm
    Target: c:\git\vis-ftvision\build

OmniSharp server started.
    Path: C:\Users\PFulgoni\.vscode\extensions\ms-dotnettools.csharp-1.21.16\.omnisharp\1.34.15\OmniSharp.exe
    PID: 5252

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Professional 2017 15.9.28307.960 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
            2: Visual Studio Professional 2019 16.5.29926.136 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
            3: StandAlone 16.4 - "C:\Users\PFulgoni\.vscode\extensions\ms-dotnettools.csharp-1.21.16\.omnisharp\1.34.15\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2019 16.5.29926.136 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\git\vis-ftvision\build'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\git\vis-ftvision\build'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\git\vis-ftvision\build\_build.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\git\vis-ftvision\build'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\git\vis-ftvision\build\_build.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\git\vis-ftvision\build' on host 20696.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\git\vis-ftvision\build\_build.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\git\vis-ftvision\build\_build.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: _build
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\git\vis-ftvision\build\_build.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\git\vis-ftvision\build\_build.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\git\vis-ftvision\build\_build.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\git\vis-ftvision\build\_build.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\git\vis-ftvision\build\_build.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: _build
```

**Comment by ghost** [comment]
so if your project root is "vis-ftvision" (also the .nuke file should be there) then the default path in the nuke extention settings should work just fine.
try to make a clean dummy project and do a new nuke setup on it and see if the extention reproduce this problem for you.

**Comment by paolofulgoni** [comment]
OK, I'll try to make an ad-hoc public repo to reproduce the issue and then link it here

**Comment by paolofulgoni** [comment]
Here it is: https://github.com/paolofulgoni/nuke-issue-454
Hopefully you can now reproduce the issue

<blockquote><img src="https://avatars3.githubusercontent.com/u/5703017?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/paolofulgoni/nuke-issue-454">paolofulgoni/nuke-issue-454</a></strong></div><div>Contribute to paolofulgoni/nuke-issue-454 development by creating an account on GitHub.</div></blockquote>

**Comment by matkoch** [comment]
Everything runs fine for me

**Comment by paolofulgoni** [comment]
I found it depends on how you open the project on VS Code.

If I open the root folder of the project, i.e. the `nuke-issue-454`, then everything works fine.

If I open the `build` subfolder on VS Code, then I get the _"command 'nuke.runTarget' not found"_ error.

Even changing this Nuke extension settings doesn't solve the problem:
`"nuke.buildProjectPattern": "*build*.csproj"`

I guess that the latter way of opening the project is not the standard or preferred one.

**Comment by paolofulgoni** [comment]
As @arodus  said here https://github.com/nuke-build/nuke/issues/471#issuecomment-612233469 the VS Code extension looks for a `.nuke` file, that's why it doesn't work if you open just the build project folder as workspace.

So I'm closing this issue given that by design you must open the root folder
