### ISSUE TITLE
Add a .nuke folder

### ISSUE THREAD

**Issue by bitbonk** [nuke-build/nuke#455]
### Description

I just started playing with nuke and I noticed that once I build and run `_build.csproj`, some files are beeing generated inside a `.tmp` folder (e.g. `build-attempt.log`, `shell-completion.yml`). If I understand it correctly, the whole `.tmp` folder can completely added to `.gitignore`. Nothing in there ever needs to be added to source control.

Additionally there is the `.nuke` file which AFAIK actually _should_ be added to source control. 

I suggest that you

1. put all those generated "helper files" (e.g. log files or files that only support nukes infrastructure) into a dedicated folder that is specific to nuke,
2.  call that folder `.nuke` and
3.  add means to nuke that can add a dedicated  `.gitignore` file inside that `.nuke` folder that ignores all generated, nuke-specific files that never should be added to source control.  Optionally nuke could even extend the content of the `.gitignore` on a pay-as-you-go basis, i.e. add new lines there when new files are generated.

This is what I think would be the benefit:

1. Users don't have to maintain (i.e. think about) what to add to the `.gitignore` of the project since nuke will do it for them.
2. Users will understand where those generated files come from because they do not reside in a generic folder named `.tmp`.
3. Nuke has complete freedom what to do in that folder because it belongs to nuke only. The `.tmp` folder is also used by other things.

### Alternatives

Leave it the way it currently is.

**Comment by ThinkingBIGRon** [comment]
I support this - opens up some flexibility around other features in the future.

**Comment by paolofulgoni** [comment]
This looks a very good idea to me.

However, I personally don't like having multiple `.gitignore` files.
What about adding a new `.gitignore` template for Nuke?
For example, Gradle has one: https://github.com/github/gitignore/blob/master/Gradle.gitignore
And Cake has its own in this other repo: https://github.com/toptal/gitignore/blob/master/templates/Cake.gitignore

<blockquote><img src="https://avatars3.githubusercontent.com/u/9919?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/github/gitignore">github/gitignore</a></strong></div><div>A collection of useful .gitignore templates. Contribute to github/gitignore development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/4004158?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/toptal/gitignore">toptal/gitignore</a></strong></div><div>The largest collection of useful .gitignore templates - toptal/gitignore</div></blockquote>

**Comment by bitbonk** [comment]
The advantage of a separate `.gitignore` is that it just works. Users would not have to think about it at all (other than committing it).

If there is no separate `.gitignore` that is autogenerated by nuke, users will have to hunt for and then add the right settings themsefles. Also you‘d probably want to get the nuke stuff into the templates of of the various IDEs. (e.g. [Visual Studio](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) and [Rider](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore)). 

I always find the process of manually collecting and merging all the right .gitignore setting a bit of a PITA.

**Comment by paolofulgoni** [comment]
I agree, but on the other hand having a single `.gitignore` has one advantage too, that's *simplicity*. In fact, a single list of ignore pattern is easier to understand. Also the `.gitignore` in the root folder is well known and visibile, while a second `.gitignore` in a subfolder is somehow hidden and unexpected.

Moreover, tools like [gitignore.io](https://gitignore.io) make the creation of the `.gitignore` quite simple...

It's a tradeoff, as usual. 🙂

**Comment by RemyDuijkeren** [comment]
On the first commit after adding NUKE, the folder will pop-up to be committed. This is normally the time developers will review what needs to be in `.gitignore`. I think the convention is that folders starting with a dot (.) are usually user-specific folders, like: .git, .vs, .vscode, .tmp, .cr, etc. I think a lot of developers will assume this, and therefor automatically set the .nuke or .tmp folder in the root `.gitignore'.

I also didn't expected (didn't know) that `.gitignore` could be in subfolders. I assume a lot of developers don't know this. Agreeing with @paolofulgoni on this.

**My alternative 1**
Remove `.nuke` file. I really don't understand why it is needed if you only have one solution file, like most projects have. Can't NUKE work this out automatically?

Rename the folder _.tmp_ to _.nuke_ to inform that this are nuke internal helper artifacts, but with the assumption it can be **fully** ignored for Git). 

Downside of naming it _.nuke_ is that developers will still going to look into the documentation to know if it is save to ignore the .nuke folder. Leaving the name as is, _.tmp_, will make it perfectly clear it is a temporary folder and that it should be ignored.

**Comment by matkoch** [comment]
It works VCS agnostic. So some kind of marker is necessary. Also these are
only negative examples, for Rider for instance, content of the `.idea`
folder _is_ commited to source control.
