### ISSUE TITLE
Allow abbreviation of target

### ISSUE THREAD

**Issue by VolkmarR** [nuke-build/nuke#458]
### Description

When starting Nuke from the command line, it is required to specify the full name of the target. If would be nice, if I could specify only the start of the target, as long it identifies one unique target.

#### Example

The available targets are: clean, restore, compile.
| command line | executes target |
|---|---|
| nuke r | nuke restore |
| nuke c | invalid target, because not unique |
| nuke cl | nuke clean |
| nuke co | nuke compile |

### Alternative 

An alternative could be to allow specifying abbreviations for targets using attributes.

**Comment by matkoch** [comment]
There is shell completion exactly for that matter.

**Comment by VolkmarR** [comment]
The benefit of adding this to nuke itself would be, that it would be working in any shell. But registering  the shell completion is certainly an alternative. In any case, I could make a PR, if you see it beneficial to add this feature.

**Comment by matkoch** [comment]
Sorry, but I don’t think it’s worth it.
