### ISSUE TITLE
Warn when GitVersion is used with SSH endpoint

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#459]
When GitVersion is used with an SSH endpoint, we could warn about that and suggest to set `NoFetch = true`. For that to work, `GitRepository` must carry information whether it was parsed from SSH or HTTPS endpoint.

Originally suggested in #388

https://github.com/nuke-build/nuke/blob/b837ba757ec9aa56ada619f7b3602cd95bc529f9/source/Nuke.Common/Tools/GitVersion/GitVersionAttribute.cs#L31-L55

**Comment by vankos** [comment]
Hi!
Will be correct to assume that if  value in protocol group from   
https://github.com/nuke-build/nuke/blob/6fc950f130d1346e0770065dee7fa8631d6135ac/source/Nuke.Common/Git/GitRepository.cs#L62-L66
return "ssh://" or it's empty than this is SSH endpoint ?
