### ISSUE TITLE
Legacy format for build project does not work

### ISSUE THREAD

**Issue by MindWrapper** [nuke-build/nuke#46]
Repro:
1. Creates simple Console application targeting 4.5 framework
2. When generating chose "L" (legacy format) when generating build.csproj
3. run .\build.cmd 
and you'll get a bunch of:
Build.cs(3,7): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?) [D:\temp\NukeTest\build\.build.csproj]

I guess project generator messed up something with references.
SDK  based format works nice.

**Comment by matkoch** [comment]
It’s a duplicate of #36. Just to be clear, even if your production project is not using the SDK based project files, you can still chose to make the build project SDK based.
