### ISSUE TITLE
Process should not be killed automatically upon time out

### ISSUE THREAD

**Issue by ghost** [nuke-build/nuke#460]
Why dont we let the user trigger "Kill" himself? is it a must to always shut down a process if it just exceeded the amount of time out?

```
Process2.cs
        public bool WaitForExit()
        {
            // TODO: we are assuming that this method is called directly after process creation
            // use _process.StartTime
            var hasExited = _process.WaitForExit(_timeout ?? -1);
            if (!hasExited)
                _process.Kill();
            return hasExited;
        }
```
Fixing this code block will allow better end user control on timed out process.
This is very useful for integration tests.

**Comment by mdealer** [comment]
In terms of discussion, this purely depends on the context. In terms of real world, nearly always we just want the process to go away. I guess it could be an optional parameter, but, honestly, it's no longer a real timeout but a wait. Perhaps the terminology could be improved.

To further expand the discussion, I'd always prefer the default to be how Jenkins roughly handles a timeout of a process: 
1. Send abort signal
2. wait a bit
3. Send kill signal
4. wait a bit
5. Terminate

Then provide options to tune it for the context, but the above works out of the box 99.99% of time and I am fine with direct termination even. Everything else is a wait, not a timeout of a running process, even though technically they imply each other under the hood.
