### ISSUE TITLE
build.ps1 - Unable to download the .NET Core because of TLS issues

### ISSUE THREAD

**Issue by ayfie-frank-gynnild** [nuke-build/nuke#462]
### Description
Tried to run the build.ps1 inside Docker for Windows, but unable to download the .NET Core from Microsoft due to SSL issues.

### Fix
Added this line:
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12  
````
before d/l in the `build.ps1` file.

### Steps to reproduce

Needs a context, like build.ps1 etc.

Dockerfile
```
# escape=`

FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS locatorbuilder

ENTRYPOINT powershell ./build.ps1
```
When running this Dockerfile, it fails with it can't download.

### Relevant log output

Running build.ps1 from inside Docker
```
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\
Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26
.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.201/dotnet-sdk-3.1.201-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.201/dotnet-sdk-3.1.201-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.201/dotnet-dev-win-x64.3.1.201.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.201/dotnet-dev-win-x64.3.1.201.zip
```

Starting the container interactively and testing download of the .NET file:
```
PS C:\app>  Invoke-WebRequest -Uri "https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.201/dotnet-sdk-3.1.201-win-x64.zip" -OutFile dotnet-sdk-3.1.201-win-x64.zip
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:2
+  Invoke-WebRequest -Uri "https://dotnetcli.azureedge.net/dotnet/Sdk/3 ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by matkoch** [comment]
Should that be done in any case?

**Comment by ayfie-frank-gynnild** [comment]
Good question. I think maybe a fallback strategy could work if the default security protocols fails.
But before doing anything, it would be good to know the exact root cause first, as we currently have a workaround.

# PowerShell
```
Write-Host "[Net.ServicePointManager]::SecurityProtocol: $([Net.ServicePointManager]::SecurityProtocol)"
Invoke-WebRequest -Uri "https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.201/dotnet-sdk-3.1.201-win-x64.zip" -OutFile dotnet-sdk-3.1.201-win-x64.zip
```

# Output
```
[Net.ServicePointManager]::SecurityProtocol: Tls13

Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive.
At C:\sync\ayfie\code\research\nuke-build\download_dotnet_core.ps1:7 char:1
+ Invoke-WebRequest -Uri "https://dotnetcli.azureedge.net/dotnet/Sdk/3. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by ghost** [comment]
> If your app targets .NET Framework 4.7 or later versions
> The following sections show how to verify you're not using a specific TLS or SSL version.
> 
> For HTTP networking
> ServicePointManager, using .NET Framework 4.7 and later versions, will use the default security protocol configured in the OS. To get the default OS choice, if possible, don't set a value for the ServicePointManager.SecurityProtocol property, which defaults to SecurityProtocolType.SystemDefault.
> 
> Because the SecurityProtocolType.SystemDefault setting causes the ServicePointManager to use the default security protocol configured by the operating system, your application may run differently based on the OS it's run on. For example, Windows 7 SP1 uses TLS 1.0 while Windows 8 and Windows 10 use TLS 1.2.
> 
> The remainder of this article is not relevant when targeting .NET Framework 4.7 or later versions for HTTP networking.
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

**As you can see from your docker file the Runtime Environment is 4.8.
Please look on the following changes:
From 4.6 the default security protocol changed to TLS.**

> The .NET Framework 4.6 adds TLS 1.1 and TLS 1.2 to the WCF SSL default protocol list. When both client and server machines have the .NET Framework 4.6 or later installed, TLS 1.2 is used for negotiation.TLS 1.2 does not support MD5 certificate authentication. As a result, if a customer uses an MD5 certificate, the WCF client will fail to connect to the WCF service.
>
> When using NetTcp with transport security and a credential type of certificate, the SSL 3 protocol is no longer a default protocol used for negotiating a secure connection. In most cases there should be no impact to existing apps as TLS 1.0 has always been included in the protocol list for NetTcp. All existing clients should be able to negotiate a connection using at least TLS1.0.
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.0-4.8

**So now that we know the core of the issue, I think a fallback system is good for legacy support.
Default should be the new TLS and a fallback to SSL if fails.
(Although TLS should be always working anyways)**



<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls">Transport Layer Security (TLS) best practices with the .NET Framework</a></strong></div><div>Describes best practices using Transport Layer Security (TLS) with the .NET Framework</div></blockquote>
<blockquote><div><strong><a href="https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.0-4.8">Runtime Changes for Migration from .NET Framework 4.0 to 4.8</a></strong></div></blockquote>

**Comment by ayfie-frank-gynnild** [comment]
Thanks for shedding more light on it @ohgrad, a fallback mechanism to TLS 1.2 - so that it behaves and works on more OS - seems to be a good approach. The rest of the versions are deprecated: https://www.ssl2buy.com/wiki/ssl-vs-tls


<blockquote><img src="https://www.ssl2buy.com/wiki/wp-content/uploads/2018/10/ssl2buy-ssl-certificate-security.jpg" width="48" align="right"><div><img src="https://www.ssl2buy.com/wiki/wp-content/themes/knowhow/images/favicon.ico" height="14"> SSL2BUY Wiki - Get Solution for SSL Certificate Queries</div><div><strong><a href="https://www.ssl2buy.com/wiki/ssl-vs-tls">SSL vs. TLS – What are differences?</a></strong></div><div>If you look at SSL vs TLS certificate, both perform the same task of encrypting data exchange. TLS was an update and secure version of SSL.</div></blockquote>

**Comment by maartenba** [comment]
Not sure if related, but https://github.com/dotnet/sdk/issues/11172
