### ISSUE TITLE
Dotnet installation began when global.json has not latest version

### ISSUE THREAD

**Issue by sm-g** [nuke-build/nuke#467]
global.json:

```
{
  "sdk": {
    "version": "3.1.101",
    "rollForward": "latestMajor"
  }
}
```

`dotnet --version`'s output (`3.1.201` in my case) used in build.ps1 to decide whether to download and install dotnet.exe. 

But 3.1.101 already installed (checking via `dotnet --info`:
```
.NET Core SDKs installed:
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
```

**Comment by matkoch** [comment]
Could you provide a repro?

**Comment by sm-g** [comment]
I cannot give code, it depends on installed SDKs on your machine. 
For repro you need to set `"version": "3.1.101",` to some other version (or update dotnet to the latest version)

**Comment by matkoch** [comment]
I'm sorry, but this works as expected on multiple CI agents. So I'm gonna need a repro on a CI server at least. Meanwhile closing. Feel free to add more information.
