### ISSUE TITLE
Improve how VS Code extension finds the Nuke build project

### ISSUE THREAD

**Issue by paolofulgoni** [nuke-build/nuke#471]
### Description

The VS Code extension finds the Nuke build project based on a glob pattern, stored in the `nuke.buildProjectPattern` setting. This works fine in most of the use cases.

Nevertheless there may be some cases in which you must change this setting, such as:
* you want to open the build project folder in VS Code, not the root folder
* your build project has a non-standard name

An alternative approach, not based on paths, could be:
* find all .csproj files in all folders recursively
* check which of them reference the `Nuke.Common` NuGet package

### Alternatives

Always use a standard name for the build project, open the root folder, and everything works fine.

**Comment by matkoch** [comment]
Why don't you just change the glob pattern?

**Comment by arodus** [comment]
I agree. 

> You want to open the build project folder in VS Code, not the root folder

The extension just gets enabled when the `.nuke` file is available in the workspace (https://github.com/nuke-build/vscode/blob/master/package.json#L143-L145).

To change that the extension would have to be enabled as soon as a csharp project is loaded which is quite some overhead, especially if you're doing a recursive search looking for the build project which may not exist at all.


<blockquote><img src="https://avatars1.githubusercontent.com/u/26774874?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/vscode">nuke-build/vscode</a></strong></div><div>VSCode extension. Contribute to nuke-build/vscode development by creating an account on GitHub.</div></blockquote>

**Comment by paolofulgoni** [comment]
I didn't know about the need of a `.nuke` file in the workspace. I understand it makes much sense.

So I'm closing this issue, thanks for the clarification
