### ISSUE TITLE
Brand new NUKE generation results in compiler warning `Solution MyApp.sln has an active build configuration for _build.csproj.` after openeing SLN in VS.

### ISSUE THREAD

**Issue by VictorioBerra** [nuke-build/nuke#474]
### Description

If you generate a nuke build using `nuke :setup` and then you open the SLN in VS. From that point on you will always receive the following error:

`Solution MyApp.sln has an active build configuration for MyApp\build\_build.csproj.`

### Steps to reproduce

1. `dotnet new sln --name NukeIssue`
2. `dotnet new mvc --name NukeIssue.Web`
3. `dotnet sln .\NukeIssue.sln add .\NukeIssue.Web\NukeIssue.Web.csproj`
4. `nuke :setup` (just take all the defaults)
5. Open the SLN, and then when it loads, click file -> save all
6. Back in the CLI, simply run `nuke` and you will see the error.

### Expected Result

Simply opening the SLN modified by `nuke :setup` should not result in a bright yellow warning that the user then has to google in confusion. In fact, simply googling the error leads you to this locked issue that is unhelpful https://github.com/nuke-build/nuke/issues/328

Additionally, this warning is displayed prominently in Azure DevOps, which is common for anyone using the CI features of nuke.

### Manual Workaround

Open the SLN, and delete all build configs related to the GUID for the build.csproj:

![image](https://user-images.githubusercontent.com/2934507/79130048-f2ff1f00-7d6b-11ea-8afa-926d0c693b1b.png)

**Comment by matkoch** [comment]
That's more or less impossible. Solution modifications are done manually, and we don't add build configurations for the newly created build project.

**Comment by VictorioBerra** [comment]
@matkoch That's fine. But I think maybe a mention of this on the docs, or even better if it could be auto detected by NUKE and the user could be informed of that problem and the fix would be very helpful.

Again this warning will probably pop up for a lot of people.

**Comment by matkoch** [comment]
I’m confused. We are actively checking that? That’s why there is the warning. Additionally, this usually only appears when you’re not properly proceeding with the setup. More or less user error to me.

**Comment by matkoch** [comment]
Btw, this is not a compiler warning.

**Comment by VictorioBerra** [comment]
> this usually only appears when you’re not properly proceeding with the setup.

Can you please advise given the steps I show above to reproduce, what should I have done different to avoid the error?

It seems to me that if I follow the default nuke :setup, and I open my SLN the build config will be added no matter what I do.

**Comment by VictorioBerra** [comment]
Most people are not in the habit of editing SLN files manually. So maybe the warning could point to a doc page with more helpful information?

**Comment by matkoch** [comment]
I simply can't reproduce the issue you're describing.

**Comment by matkoch** [comment]
Here's what the setup is changing: https://github.com/nuke-build/nuke/blob/develop/source/Nuke.GlobalTool/Program.Setup.cs#L402-L403

<blockquote><img src="https://avatars1.githubusercontent.com/u/26774874?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by VictorioBerra** [comment]
> I simply can't reproduce the issue you're describing.

That is really odd. I am on Microsoft Visual Studio Community 2019
Version 16.5.1

You?

Make sure when you open the sln you click file -> save all this will save the SLN that was modified by VS. And dont open the SLN until after you ran nuke setup.

**Comment by VictorioBerra** [comment]
> Here's what the setup is changing: https://github.com/nuke-build/nuke/blob/develop/source/Nuke.GlobalTool/Program.Setup.cs#L402-L403
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/26774874?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[nuke-build/nuke](https://github.com/nuke-build/nuke)**The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.

This is very helpful thank you. So whats the downside of having this active config anyway? What problems could it cause?

<blockquote><img src="https://avatars1.githubusercontent.com/u/26774874?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by matkoch** [comment]
I have the latest version and did everything as you described. If build configurations are added  for an unknown reason when saving a solution file, that would anyways be a bug outside of this project.

> So whats the downside of having this active config anyway? What problems could it cause?

What do you think would happen if you try to build the solution the build project is added to?
