### ISSUE TITLE
Wix Installer

### ISSUE THREAD

**Issue by Simusharp** [nuke-build/nuke#475]
### Description
Thanks for this great project. I wonder if you have any plan to add [Wix installer](www.wixtoolset.org).  I will be happy to provide a PR. However, I saw that Wix was mentioned in #259 Also, there was a PR for Wix in the old "common tool" repo. So, I guess my question, are you interested in adding Wix or not?

Thanks,

**Comment by matt-richardson** [comment]
Are you looking at adding support for something like [cakes support for WiXHeat](https://cakebuild.net/api/Cake.Common.Tools.WiX/WiXAliases/AF4E4C0F)? I could use definitely use something like that.

**Comment by Simusharp** [comment]
@matt-richardson, yes, I think it will be helpful. Let's wait for @matkoch 's opinion; maybe he still has the wix PR from old repo.

**Comment by matkoch** [comment]
The PR from @jonsth131 is still available at https://github.com/matkoch/common/pull/15

Adding support for WiX requires a bit of work for the code generation part, since multiple executables exist in the same package.
