### ISSUE TITLE
Ambiguous call in generated Build.cs using Visual Studio 2017

### ISSUE THREAD

**Issue by jozsefcsontos** [nuke-build/nuke#476]
### Description
I would like to build a .NET 4.6.2 specific app with Nuke 0.24.6 and Visual Studio 2017 (15.9.21), but got error messages after downgrading the TargetFramework to netcoreapp2.1 in _build.csproj.

### Relevant log output
1>Build.cs(42,18,42,32): error CS0121: The call is ambiguous between the following methods or properties: 'DotNetTestSettingsExtensions.SetProjectFile<T>(T, string)' and 'DotNetRunSettingsExtensions.SetProjectFile<T>(T, string)'
1>Build.cs(50,18,50,32): error CS0121: The call is ambiguous between the following methods or properties: 'DotNetTestSettingsExtensions.SetProjectFile<T>(T, string)' and 'DotNetRunSettingsExtensions.SetProjectFile<T>(T, string)'

Here is the related code part:
```
Target Restore => _ => _
        .Executes(() =>
        {
            DotNetRestore(s => s
                .SetProjectFile(Solution)); // This is broken
        });
    Target Compile => _ => _
        .DependsOn(Restore)
        .Executes(() =>
        {
            DotNetBuild(s => s
                .SetProjectFile(Solution) // This is broken
                .SetConfiguration(Configuration)
                .EnableNoRestore());
        });
```

**Comment by matkoch** [comment]
Seems to be a bug in VS2017.
