### ISSUE TITLE
Expose ExitCode from ProcessException

### ISSUE THREAD

**Issue by ghost** [nuke-build/nuke#477]
### Description
The ProcessException class should expose a property (ExitCode) with the exit code from the tool. Some tools return exit code other than 0 which is not considered an error. This will allow the opportunity to interrogate the exit code and act accordingly. An example is robocopy. An exit code <= 8 is not considered an error.

### Alternatives
Specify which return codes to consider an error (or not an error). You could add an argument that takes a predicate that is passed the exit code and returns a boolean.

**Comment by matkoch** [comment]
Tracked in #326
