### ISSUE TITLE
Update GitHub Actions to use checkout v2

### ISSUE THREAD

**Issue by mbaumanndev** [nuke-build/nuke#481]
I added Nuke to a project using GitHub Actions that used a handwritten yml.

In that script, I used  `actions/checkout@v2`, Nuke generate a script with `actions/checkout@v1`.

Is it possible to make the upgrade without editing the generated yml file ?

**Comment by matkoch** [comment]
Not sure what you mean?

**Comment by Bomret** [comment]
I think what @mbaumanndev is referring to might be that if you add the `GithubActionsAttribute` on your Build class to auto-generate a Github Actions yaml, that one uses a `actions/checkout@v1` instead of the newer `v2`. Might be a good candidate for up-for-grabs.

**Comment by matkoch** [comment]
@mbaumanndev what is the benefit of v2 ?

**Comment by mbaumanndev** [comment]
@matkoch v2 is faster, doesn't use the detached mode, can handle SSH and fixes some issues.
https://github.com/actions/checkout/releases

<blockquote><img src="https://avatars2.githubusercontent.com/u/44036562?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/actions/checkout">actions/checkout</a></strong></div><div>Action for checking out a repo. Contribute to actions/checkout development by creating an account on GitHub.</div></blockquote>

**Comment by matkoch** [comment]
v2 does a detached checkout

**Comment by mbaumanndev** [comment]
From the changelog :

> - Creates a local branch
>   - No longer detached HEAD when checking out a branch
>   - A local branch is created with the corresponding upstream branch set

**Comment by matkoch** [comment]
Yes I’ve read the changelog. Still the default is detached.
