### ISSUE TITLE
Cannot use EF6.exe nuget tool

### ISSUE THREAD

**Issue by sm-g** [nuke-build/nuke#484]
I add
```
[PackageExecutable("EntityFramework", "ef6.exe", Framework = "net45", Version = "6.4.0")]
readonly Tool EF6;
```
with
```
<PackageDownload Include="EntityFramework" Version="[6.4.0]" />
```
but `GetPackageExecutable` fails, because [packageExecutablePaths](https://github.com/nuke-build/nuke/blob/0cb1fa42e3b635560926b7380514ecc36a1b5e0e/source/Nuke.Common/Tooling/ToolPathResolver.cs#L61) contains 4 paths in case of this nuget package:

- tools\net45\any\ef6.exe
- tools\net45\win-x86\ef6.exe
- tools\net40\any\ef6.exe
- tools\net40\win-x86\ef6.exe

and so
```
return !directory.Name.EqualsOrdinalIgnoreCase("any")
                    ? directory.Name
                    : directory.Parent.NotNull().Name;
```
tries to add 2 `win-x86` keys into dictionary.

I also cannot use `LocalExecutable`, because in should contain path to nuget cache like:
`[LocalExecutable(@"%USERPROFILE%\.nuget\packages\entityframework\6.4.0\tools\net45\any\ef6.exe")]` and I cannot use non-const string in attribute to resolve that path.

Also I cannot call internal ctor of `new ToolExecutor(toolPath)`.

My workaround is: 
1) copypaste ToolExecutor.cs into my code
2) get path with code like:
```
using NuGet.Configuration;

// later
        var settings = Settings.LoadDefaultSettings(null);
        var nugetPackagesFolder = (AbsolutePath)SettingsUtility.GetGlobalPackagesFolder(settings);

        var toolPath = nugetPackagesFolder / "entityframework" / "6.4.0" / "tools" / "net45" / "any" / "ef6.exe";
        Assert(FileExists(toolPath), $"ef6.exe exists at {toolPath}");
        return _ef6 = new ToolExecutor(toolPath).Execute;
```

**Comment by sm-g** [comment]
@ohgrad you asked me to create this issue. Maybe you could add _a bit_ more info why it is closed?

**Comment by ghost** [comment]
Unfortunately I don't have all the information to answer your doubt.
