### ISSUE TITLE
Msbuild cound not be found when installed in non-default location

### ISSUE THREAD

**Issue by sm-g** [nuke-build/nuke#485]
1. Install VisualStudio not in Program Files
2. Use `Msbuild()` task in nuke script.

task failed with `Assertion failed: Could not find a suitable MSBuild instance.`, because MSBuildToolPathResolver [looks at SpecialFolders.ProgramFilesX86](https://github.com/nuke-build/nuke/blob/0cb1fa42e3b635560926b7380514ecc36a1b5e0e/source/Nuke.Common/Tools/MSBuild/MSBuildToolPathResolver.cs#L68)

**Comment by Ted-TW** [comment]
I ran into this issue as well, I was able to fix it by using `MSBuild(s => s.SetToolPath(Path / To / Msbuild).`

**Comment by sm-g** [comment]
@Ted-TW I know that this could help, in my case we check env variable "msbuild" before setting path, so developers with non standart path could set it on their machines.

I also could use vswhere task of nuke and build path manually for everybody.
