### ISSUE TITLE
GetPackageExecutable return wrong data for SonarQube

### ISSUE THREAD

**Issue by martin211** [nuke-build/nuke#488]
### Description

Install msbuild.sonarqube.runner.tool package and create a SonarQube step at build file.
Try to run it and you will see that nuke checks only two frameworks instead three.
The problem is [here](https://github.com/nuke-build/nuke/blob/13cbedec0855402a138ff9c5db28d9f05220af8b/source/Nuke.Common/Tooling/ToolPathResolver.cs#L45). Nuke returns executable paths only for first packageExecutables value. I think you should use SelectMany instead Select and Where instead FirstOrDefault 

### Steps to reproduce

1. Install Nuget package msbuild.sonarqube.runner.tool
2. Create a build step

```
Target SonarQue => _ => _
        .Executes(() =>
        {
            SonarScannerTasks.SonarScannerBegin(c => c
                .SetFramework("sonar-scanner-msbuild-4.8.0.12008-net46")
                .SetProjectKey("SonarProjectKey")
                .SetServer("SonarUrl")
                .SetLogin("SonarUser")
                .SetName("SonarProjectName")
                .SetWorkingDirectory(SourceDirectory));
        });
```
3. Execute target

You will get error that framework should be `sonar-scanner-msbuild-4.8.0.12008-netcoreapp2.0` or `sonar-scanner-msbuild-4.8.0.12008-netcoreapp3.0`.
Go to `c:\Users\User\.nuget\packages\msbuild.sonarqube.runner.tool\4.8.0\tools\` and you will see that it contain 3 frameworks.
Check the `GetPackageExecutable` method. packageExecutables has two elements (exe and dll), but it processed only one (dll) and do not return framework for exe

**Comment by matkoch** [comment]
Could you provide a repro?
