### ISSUE TITLE
Rider plugin: Build targets are not available outside of _build project

### ISSUE THREAD

**Issue by Marat-Gumerov** [nuke-build/nuke#489]
### Description
When I hit "Execute NUKE build" in Build.cs, or in any .cs file inside _build.csproj, where all targets declarated, I can see a list of targets and execute them.
But when I hit "Execute NUKE build" in any other project inside my solution, it says "There are no items to show in this menu".

I use Rider 2020.1.0 on Windows 10, my application is written using .NET Core SDK 2.1.804, _build.csproj uses target framework netcoreapp2.1.
My project structure looks like this:

> - build
>   - someDirectory
>     - SomeFile.cs
>   - _build.csproj
>   - Build.cs
>- src
>   - project.csproj
>   - Program.cs
>- solution.sln
>- build.ps1 
_build.csproj and project.csproj are added to solution.

All targets available in Build.cs, SomeFile.cs, but not available in Program.cs

**Comment by matkoch** [comment]
Could you provide a repro project?

**Comment by Marat-Gumerov** [comment]
This one reproduces problem on my pc:

https://github.com/Marat-Gumerov/nuke-bug-repro-489

<blockquote><img src="https://avatars1.githubusercontent.com/u/56924662?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Marat-Gumerov/nuke-bug-repro-489">Marat-Gumerov/nuke-bug-repro-489</a></strong></div><div>Contribute to Marat-Gumerov/nuke-bug-repro-489 development by creating an account on GitHub.</div></blockquote>

**Comment by Marat-Gumerov** [comment]
If I add `<PackageReference Include="Nuke.Common" Version="0.24.10" />` to nukebug.csproj - everything works

**Comment by Marat-Gumerov** [comment]
I debugged plugin using dnSpy, looks like problem is in this line of code:
https://github.com/nuke-build/resharper/blob/master/src/dotnet/ReSharper.Nuke/Extensions.cs#L92

<blockquote><img src="https://avatars1.githubusercontent.com/u/26774874?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/resharper">nuke-build/resharper</a></strong></div><div>Rider and ReSharper extension. Contribute to nuke-build/resharper development by creating an account on GitHub.</div></blockquote>

**Comment by Marat-Gumerov** [comment]
https://github.com/nuke-build/resharper/blob/master/src/dotnet/ReSharper.Nuke/Extensions.cs#L90 - here, targetDeclaredType does not contain assembly when I call from project without reference to Nuke.Common. And assembly is Nuke.Common when I call from Build.cs
I think that is the difference

<blockquote><img src="https://avatars1.githubusercontent.com/u/26774874?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/resharper">nuke-build/resharper</a></strong></div><div>Rider and ReSharper extension. Contribute to nuke-build/resharper development by creating an account on GitHub.</div></blockquote>

**Comment by matkoch** [comment]
@Marat-Gumerov thanks for investigating. I thought about something like that, but knowing where it is exactly helps a lot. I will take a look asap, but could take a while.

**Comment by matkoch** [comment]
I think I’ve fixed it. I will release a new version very shortly.
