### ISSUE TITLE
Issues while installing Resharper plugin

### ISSUE THREAD

**Issue by madhusameena** [nuke-build/nuke#493]
Getting installation errors while installing Resharper plugin 
please find the logs 
[InstallLog_2020-04-28T10-52-00.txt](https://github.com/nuke-build/nuke/files/4551008/InstallLog_2020-04-28T10-52-00.txt)
[Kafurap.txt](https://github.com/nuke-build/nuke/files/4551010/Kafurap.txt)

Also raised issue in R# - They asked me to raise here  
https://resharper-support.jetbrains.com/hc/en-us/requests/2628116?flash_digest=19e69bf4834160ede079bcb79ce5e463feb4c2ad

**Comment by madhusameena** [comment]
Could you please let me know - How to proceed further with this issue

**Comment by matkoch** [comment]
Released 2020.1.1
