### ISSUE TITLE
GetMSBuildProject() is failed for new csproj files

### ISSUE THREAD

**Issue by Alexcei88** [nuke-build/nuke#494]
### Description

[According documentation](https://nuke.build/docs/authoring-builds/solutions-and-projects.html),
we can get details information about project from solution using by

```
var commonProject = Solution.GetProject("SampleApp");
var msbuildProject = commonProject.GetMSBuildProject();
```` 

### Steps to reproduce
 
If I try to execute above code for project which has a new csproj format I catch the exception

```
Microsoft.Build.Exceptions.InvalidProjectFileException: "The imported project "C:\Program Files (x86)\MSBuild\2.0\Microsoft.Common.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\MSBuild\2.0\Microsoft.Common.props" is correct, and that the file exists on disk.  C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props"
```

If my project has an old csproj format I don't have any problem.

**Comment by matkoch** [comment]
What target framework is the project?

**Comment by Alexcei88** [comment]
The target framework is net48.

I am providing my csproj for example

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
    <AssemblyName>Example</AssemblyName>
  </PropertyGroup>
 
  <!-- the rest of the project file -->
 <ItemGroup>
   <PackageReference Include="Microsoft.Build" Version="16.5.0" />
 </ItemGroup>
</Project>
```

The nuke project is targeted on net48 as well.

**Comment by matkoch** [comment]
Please try to load the project with just `Microsoft.Build`. I suppose this is an issue with their packages.

**Comment by matkoch** [comment]
Also please star the project ;)

**Comment by Alexcei88** [comment]
Hi, Matkoch

I am trying to load the project which has a new csproj format like .

```
using Microsoft.Build.Evaluation;
using System;

namespace NewProject
{
    class Program
    {
        static void Main(string[] args)
        {
            var project = new Project(
                @"Example.csproj",
                null,
                null,
                new ProjectCollection());

            Console.ReadLine();
        }
    }
}

```

In order for it to load successfully, I installed two nuget packages

* Microsoft.Build.Utilities.Core(16.5.0)
* Microsoft.Build (16.4.0)

The project is loaded with no problem both from a project with old csproj format targeted to net48 platform and a project with new csproj format targeted to netcore31 platform .

But if I try to load the same project from nuke project targeted to net48, I always catch the expcetion.

**Comment by matkoch** [comment]
Okay, could you try to figure out the differences? There is really only a tiny wrapper around loading the project. The only additional thing is some stuff to preserve formatting.

**Comment by Alexcei88** [comment]
It's very interesting, Ok, I will try to figure out what is the diff.

**Comment by Alexcei88** [comment]
I found the reason why I catch the exception. The custom setup of 
_MSBUILD_EXE_PATH_ environment variable is caused the expection.

There is a `ParseProject` method [here](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/ProjectModel/ProjectModelTasks.cs).

You try to setup _MSBUILD_EXE_PATH_ environment variable using by custom resolve. 

```
 if (string.IsNullOrEmpty(msbuildPath))
                  Environment.SetEnvironmentVariable("MSBUILD_EXE_PATH", s_msbuildPathResolver.Value);
```

If I try to comment out these lines then everything is fine. The project is loaded successfully, I don't catch the exception. I have checked it that it works for any target platforms on Windows.

What do you think about it? Are you sure that we need to setup this environment variable?

**Comment by Alexcei88** [comment]
Additional information:

The resolver sets in my case the MSBUILD_EXE_PATH value=`C:\Program Files\dotnet\sdk\3.1.201\MSBuild.dll`. So, this path points to net core 3.1 sdk.

So, if I try to modify a target platform in the nuke project to
* _netcoreapp3.1_, I have no exception
* _net48_, I have exception.

It seems like the resolver does not take into account the target platform of the project itself(nuke project) and it causes to the error..

But maybe there is no reason to modify the value of this variable. Maybe it is a workaround of the old problem that was already fixed by microsoft(https://blog.rsuter.com/missing-sdk-when-using-the-microsoft-build-package-in-net-core/)

**Comment by matkoch** [comment]
Removing setting `MSBUILD_EXE_PATH` results in the following for me:

> The SDK 'Microsoft.NET.Sdk' specified could not be found.  /Users/matt/code/nuke/source/Nuke.GlobalTool/Nuke.GlobalTool.csproj

Do you also receive the error when targeting `net4x` with SDK-based project files?

**Comment by Alexcei88** [comment]
Hi Matkoch,
I am glad you back a write permission for us. :)

I checked again at my workstation, I don't catch any errors when I skip a setup of _MSBUILD_EXE_PATH_ environment variable.  
No matter, net4x or netcoreapp target of SDK-based project file.  I don't observe the above error.
I think,  maybe we can share our experiments in a separate branch.

**Comment by matkoch** [comment]
could you try https://www.nuget.org/packages/Nuke.Common/0.25.0-alpha0326

<blockquote><img src="https://api.nuget.org/v3-flatcontainer/nuke.common/0.25.0-alpha0326/icon" width="48" align="right"><div><strong><a href="https://www.nuget.org/packages/Nuke.Common/">Nuke.Common 0.25.0-alpha0326</a></strong></div><div>Cross-platform build automation system</div></blockquote>

**Comment by matkoch** [comment]
if that’s not helping, please support in https://github.com/microsoft/MSBuildLocator/issues/90

**Comment by Alexcei88** [comment]
I don't see the exception after updating nuget package. I have tried different target platforms for itself nuke project and for projects which I am loading, I don't catch any errors. It seems like your commit fully resolves problem for me on Windows OS.

**Comment by matkoch** [comment]
Unfortunately not completely, see the linked issue.
