### ISSUE TITLE
DotNetPackSettings fails on some properties with "," or multiple values

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#497]
When adding more than one Authors to a `DotNetPackSettings` via `SetAuthors()` then invocation fails.

1. Description with ","

    ```
    DotNetPack(_ => _
                .SetProject(Project)
                .SetPackageId("PackageId")
                .SetDescription("My Description with, a comma, fails."));
   ```

2. Multiple Authors

    ```
    DotNetPack(_ => _
                .SetProject(Project)
                .SetPackageId("PackageId")
                .SetAuthros("First Guy", Second Guy"));
   ```

I think those values must be escaped or quoted differently:

```
dotnet.exe pack Project.csproj --configuration Debug /property:Description=\"My Description with, a comma, would succeed.\"
```

```
dotnet.exe pack Project.csproj --configuration Debug /property:Authors=\"First Guy,Secord Guy\"
```

**Comment by matkoch** [comment]
I need more info regarding quoting, or i have to close this.

**Comment by matkoch** [comment]
As a side-note, authors sounds rather like something that should be done in a project file.

**Comment by cmenzi** [comment]
Will provide an example project. Sorry for that. 

The authors are extracted via Git Log summary in our case....And the Api has the method, so it should work. 😅

**Comment by cmenzi** [comment]
Here the repro: https://github.com/cmenzi/nuke-issue-497

<blockquote><img src="https://avatars0.githubusercontent.com/u/1763806?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/cmenzi/nuke-issue-497">cmenzi/nuke-issue-497</a></strong></div><div>Contribute to cmenzi/nuke-issue-497 development by creating an account on GitHub.</div></blockquote>

**Comment by cmenzi** [comment]
Same issue with multiple coverlet output formats: Added to repro aswell.

I think it's something that is always the case, when a comma `,` is in `/property:`, like `/property:a,b` is used.

* https://github.com/tonerdo/coverlet/blob/master/Documentation/MSBuildIntegration.md#coverlet-integration-with-msbuild
* https://github.com/Microsoft/msbuild/issues/2999#issuecomment-366078677


<blockquote><img src="https://avatars2.githubusercontent.com/u/7319262?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/tonerdo/coverlet">tonerdo/coverlet</a></strong></div><div>Cross platform code coverage for .NET. Contribute to tonerdo/coverlet development by creating an account on GitHub.</div></blockquote>

**Comment by cmenzi** [comment]
Additional info:

I think it must behave like this:

if a comma is in the string, then `\"a,b\"` must be passed, instead of `a,b`
if a comma and whitespaces are in the string then also `\"a b,c d\"` must be passed, instead of `"a b,c d"`

**Comment by matkoch** [comment]
I can't make any conditional logic there.

**Comment by cmenzi** [comment]
I guess the issues comes from `DoubleQuoteIfNeeded`, maybe we can change the behavoir there.

**Comment by cmenzi** [comment]
or we go with the way of msbuild and change every `,` to `%2c` during rendering

**Comment by cmenzi** [comment]
Just went a little bit deeper.

One option would be if we extend the [commonTaskProperties](https://github.com/nuke-build/nuke/blob/develop/build/specifications/DotNet.json#L750) with a new property `percentageEncodingCharacters: [','],`

Then we can use those elements in the rendering of those arguments.

What do you think?

**Comment by matkoch** [comment]
> or we go with the way of msbuild and change every `,` to `%2c` during rendering

I think this is the closest. But this is related to the code generation part, and I haven't looked at it for quite some time.

**Comment by matkoch** [comment]
I'll track this in #326. You can keep making notes here, but I will close this issue already.
