### ISSUE TITLE
Add option to rename GitHub Actions steps

### ISSUE THREAD

**Issue by patrickklaeren** [nuke-build/nuke#498]
### Description

It would be nice to have the same option of renaming steps, as you have with Azure Pipelines or TeamCity.

RE:

https://github.com/nuke-build/nuke/blob/72f4db1eca05eadf3770dc23372b7437d8390d99/source/Nuke.Common/CI/GitHubActions/Configuration/GitHubActionsRunStep.cs#L18-L34

Is there a particular design decision that I am unaware of that would keep you/us from being allowed to rename the "Name" of steps? As they are hardcoded in the above code from `GitHubActionsRunStep`.

I would love to contribute this, as I can imagine this is very low priority _if_ there is no particular reason as to why the name cannot be changed.

Love Nuke so far - I've migrated all work projects to use it.

**Comment by matkoch** [comment]
You mean this, right?
<img width="271" alt="image" src="https://user-images.githubusercontent.com/5005566/80828657-f147af00-8be5-11ea-9c61-461d39466c9c.png">

**Comment by matkoch** [comment]
Since there's only one run step, I'm not sure why this should be renamed?

**Comment by patrickklaeren** [comment]
Apologies, I had hoped we could generate separate steps, like the TeamCity or Devops configurations

**Comment by matkoch** [comment]
I don't think that is of benefit. Targets can be collapsed with the current implementation already.
