### ISSUE TITLE
Redirects to bootstrap scripts still exist on nuke.build

### ISSUE THREAD

**Issue by xtqqczze** [nuke-build/nuke#503]
### Description

The following redirects should not exist:
* `https://nuke.build/powershell` => `https://raw.githubusercontent.com/nuke-build/nuke/master/bootstrapping/setup.ps1`
* `https://nuke.build/bash` => `https://raw.githubusercontent.com/nuke-build/nuke/master/bootstrapping/setup.sh`

Instead, an response should be given indicating that bootstrap scripts are no longer supported.

See also: #128

### Steps to reproduce

```
curl -iL https://nuke.build/powershell -o install.ps1
```

### Relevant log output

```
HTTP/1.1 302 Found
Location: https://raw.githubusercontent.com/nuke-build/nuke/master/bootstrapping/setup.ps1
```

### Expected result

```
HTTP/1.1 410 Gone
```

**Comment by matkoch** [comment]
From where did you get the URLs?

**Comment by xtqqczze** [comment]
> 
> 
> From where did you get the URLs?

https://blog.dangl.me/archive/escalating-automation-the-nuclear-option/

<blockquote><img src="https://blog.dangl.me/favicon.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Dangl.Blog();</div><div><strong><a href="https://blog.dangl.me/archive/escalating-automation-the-nuclear-option/">Escalating Automation - The Nuclear Option - Dangl.Blog();</a></strong></div><div>For all but the tiniest of projects, there's a need to automate tasks. Build, Test or Publish - these should be easily reproducible jobs and require no complicated procedures. Here's a look at what I found to be a great way of automating your workflow.</div></blockquote>
