### ISSUE TITLE
Potential error resolving tool executables on case-sensitive filesystems

### ISSUE THREAD

**Issue by roshek** [nuke-build/nuke#509]
### Description

I've ran into a strange problem with Nuke resolving the executable path for dotnet tools. The specific error happened with finding the GitVersion tool executable, but I suspect this could happen with other tools as well.

The gist of it is: different versions of GitVersion have different casings for the executable (eg. 5.1.3 has GitVersion.dll but 5.2.0 has gitversion.dll) and this seems to cause problems when trying to find the executable in case-sensitive filesystems.

I haven't had time yet to actually test this manually on different filesystems (using the steps outlined below), but I use Nuke in docker based CI pipelines (with Drone CI) on Linux, where I observed the error when updating GitVersion from 5.1.1 (GitVersion.dll) to 5.3.3 (gitversion.dll).

If the casing is actually the issue, I suspect it is due to:

- GitVersionTask [specifies](https://github.com/nuke-build/nuke/blob/78f931f5c453f9ffbce69a67e25b7128e80b2fc9/source/Nuke.Common/Tools/GitVersion/GitVersionTasks.cs#L31) PascalCase GitVersion.dll (and exe) as executable
- ToolPathResolver uses [Directory.GetFiles(String, String, SearchOptions)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=netcore-3.1#System_IO_Directory_GetFiles_System_String_System_String_System_IO_SearchOption_) which seems to match filenames case-sensitively (on case-sensitive filesystems)

Again, I could not 100% confirm that this is the case yet, but if you need me to I can look into it this weekend or even whip up a PR (I think using [Directory.Getfiles(String, String, EnumerationOptions)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=netcore-3.1#System_IO_Directory_GetFiles_System_String_System_String_System_IO_EnumerationOptions_)  with case-insensitive search could solve it).

Thanks for the help!

### Steps to reproduce

1. Create new Nuke build project
2. Reference GitVersion.Tool 5.1.1 package
3. Add a build task that uses the GitVersion tool
4. Run it on Windows (NTFS) and Linux (ext4)
5. Observe correct behavior
6. Update GitVersion.Tool reference to 5.2.0
7. Run it on Windows and Linux
8. Observe error only on Linux

I used dotnet core sdk 3.1.300 and runtime 3.1.4. The project is targeting netcoreapp3.1.

### Relevant log output

```
NUKE Execution Engine version 0.24.11 (Linux,.NETCoreApp,Version=v2.1)

Assertion failed: Could not find 'GitVersion.dll', or 'GitVersion.exe' inside '/root/.nuget/packages/gitversion.tool/5.2.0'.
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.Assert(Boolean condition, String text)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.GetToolPath()
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.get_ToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.Execution.InjectionUtility.InjectValuesInternal[T](T instance, IEnumerable`1 tuples)
   at Nuke.Common.Execution.InjectionUtility.InjectValues[T](T instance, Func`2 filter)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)

Repeating warnings and errors:
Assertion failed: Could not find 'GitVersion.dll', or 'GitVersion.exe' inside '/root/.nuget/packages/gitversion.tool/5.2.0'.
```

**Comment by iwillspeak** [comment]
I created a PR (#506) to work around this for GitVersion, but a solution that changes the behavior of the ToolPathResolver would be nice.

**Comment by roshek** [comment]
Thanks, I'll try fixing ToolPathResolver and create a PR on the weekend.

**Comment by iwillspeak** [comment]
Apologies if I stole your thunder there. I'd already made the change before seeing your comment.

**Comment by roshek** [comment]
> 
> 
> Apologies if I stole your thunder there. I'd already made the change before seeing your comment.

No problem at all, thanks for your time :+1:
