### ISSUE TITLE
Allow to hide Targets when skipped

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#513]
### Description

Currently, when a target is skipped it's displayed in the list of executed targets. I have created a NuGet based on Nuke which takes several environment specific conditions into account and executes the necessary targets.

For example: I detect, if it's a python based repository and only execute common targets and python related targets. But for dotnet based repository, I execute dotnet targets, ...

All those targets are marked as "Unlisted" and intended to be executed indirectly.

There are two main targets (not unlisted) `Build` and `Deploy` which calls all other targets. 

It would be nice if we can specify also a condition if the target should be displayed in the execution plan.

Something like: `.OnlyWhenStatic(() => Project.Ecosystem.Supports(Ecosystem.Dotnet), hide: true)`

Means, if this condition is met, then we don't display it in the execution plan.

What do you think? Is it worth to create a PR on this? Or do you have any other ideas how to achieve that?

**Comment by matkoch** [comment]
I'm not a fan of introducing additional parameter to the fluent API. But you can check if https://ithrowexceptions.com/2020/06/05/reusable-build-components-with-interface-default-implementations.html works for you.
