### ISSUE TITLE
.target files cannot be loaded due wrong MSBuild

### ISSUE THREAD

**Issue by MeikelLP** [nuke-build/nuke#520]
## Description

Similar to #357 I have issues getting properties out of a project. The root cause of this is that projects cannot be loaded due to wrong msbuilds being used.

### Steps to reproduce

I have (45) projects in my solution (some legacy company thingy) containing **.NET Framework** (net472 some WebForms applications) **and .NET Core** projects (netstandard2.1 + netcoreapp3.1) and I obviously need to build some projects with the VS BuildTools MSBuild.exe and others with the .NET Core version.

Sadly when I try to do some `Solution.AllProjects.First().GetProperty<string>("OutputDirectory")` I get an exception:

```
The imported project "C:\Program Files\dotnet\sdk\3.1.300\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found.
```

because it's trying to use the .NET Core msbuild but should use the VS MSBuild for this project.

I tried 
* setting the `MSBUILD_EXE_PATH` env variable to the VS MSBuild
* overriding the `Microsoft.Build` package like suggested in #357
* using the Microsoft.Build API myself (failed due to empty MSBuild variables which I could not set myself because they are "reserved" ...)

and all of these failed.

Can anyone help? Is this my fault? Is it an issue for MSBuild or is it actually Nuke?

**Comment by matkoch** [comment]
Closing as obsolete. In case this still happens, please try to load a project by yourself, and if that works, please create another issue.
