### ISSUE TITLE
buid.csproj not using NuGet.config file of solution

### ISSUE THREAD

**Issue by madhu-sameena** [nuke-build/nuke#522]
I have NuGet.config for a solution 
And I have nuke build proj associated with the solution
I am using some packages which are available, If we use Nuget.Config of the solution.

From VS If open Manage Nuget packages - It is able to install the specific package - But  from ps1 not able to restore the pacakges

Any workaround ?

**Comment by madhu-sameena** [comment]
It is using only global level Nuget.Config - Please let me know, If I miss something.

**Comment by matkoch** [comment]
The build project is not built in the context of the solution. But if the `NuGet.config` is in a parent directory of the project, it should be picked up. Anyways, this is a .NET infrastructure issue.
