### ISSUE TITLE
TLS1.2 now only supported for downloading from dist.nuget.org

### ISSUE THREAD

**Issue by jajvisser** [nuke-build/nuke#524]
Today we ran into a issue with downloading nuget.exe from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe.

 ### Description
It looks like Microsoft changed the TLS settings to only allow TLS1.2 from now on. This causes a issue with the build.ps1.

### Steps to reproduce

1. Clear the .tmp directory
2. Run build.ps1

### Solution
Code change that will fix this issue:

Replace
```
(New-Object System.Net.WebClient).DownloadFile($NuGetUrl, $env:NUGET_EXE)
```
with
```
try {
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
    (New-Object System.Net.WebClient).DownloadFile($NuGetUrl, $env:NUGET_EXE)
} catch {
    Write-Host "Failed to download nuget.exe $($_)"  -fore red
}
```

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/issues/462
