### ISSUE TITLE
Headers in non -utf8 aware consoles

### ISSUE THREAD

**Issue by j-dc** [nuke-build/nuke#527]
# Description
Not all consoles have the correct outputencoding to show fancy headers..

NUKE Execution Engine version 0.24.11 (Windows,.NETCoreApp,Version=v2.1)

### Steps to reproduce
Use case 1) Run Nuke build from the visual studio plugin (task runner explorer)
Use case 2) Using the package manager console (which is basically a powershell console)  and execute the command 'nuke'.

This will output this header:

```
ÛÛÛ»ÿÿÿÛÛ»ÛÛ»ÿÿÿÛÛ»ÛÛ»ÿÿÛÛ»ÛÛÛÛÛÛÛ»
ÛÛÛÛ»ÿÿÛÛºÛÛºÿÿÿÛÛºÛÛºÿÛÛÉ¼ÛÛÉÍÍÍÍ¼
ÛÛÉÛÛ»ÿÛÛºÛÛºÿÿÿÛÛºÛÛÛÛÛÉ¼ÿÛÛÛÛÛ»  
ÛÛºÈÛÛ»ÛÛºÛÛºÿÿÿÛÛºÛÛÉÍÛÛ»ÿÛÛÉÍÍ¼  
ÛÛºÿÈÛÛÛÛºÈÛÛÛÛÛÛÉ¼ÛÛºÿÿÛÛ»ÛÛÛÛÛÛÛ»
ÈÍ¼ÿÿÈÍÍÍ¼ÿÈÍÍÍÍÍ¼ÿÈÍ¼ÿÿÈÍ¼ÈÍÍÍÍÍÍ¼
```

###Posible solution
This could be checked by reading this variable:
```
> Write-Host $OutputEncoding
System.Text.ASCIIEncoding
```
And if needed, altered with this code: 

```
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```
After executing the above code, nuke will print this header: 
```
███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
```
Best practice:  remember what $OutputEncoding was before, and restore it..

Also read this:  https://stackoverflow.com/questions/49476326/displaying-unicode-in-powershell#49481797

**Comment by Rubbiroid** [comment]
Similar issues with e.g. Germal locale, where ÜÖÄ character are displayed wrongly..
