### ISSUE TITLE
Add support for accessing Azure Pipeline secret variables

### ISSUE THREAD

**Issue by mattbrailsford** [nuke-build/nuke#531]
### Description
Using NUKE with the built in AzurePipelines feature is really nice, but I can't find a way to access secret variables defined against the pipeline

As per the docs here https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables the way you need to access secret variables is to map them to an environment variable defined on a task

    steps:
    - powershell: |
        Write-Host "Secret: $env:MY_MAPPED_ENV_VAR"
      env:
        MY_MAPPED_ENV_VAR: $(mySecret) 

I believe the only way to achieve this at the moment would be to disable auto generating the pipelines.yml file and modify it to include the `env` option

**Comment by matkoch** [comment]
Is the powershell part really necessary? For instance like here with GHA:


https://github.com/nuke-build/nuke/blob/1eb5b671a2b20abcb0b7ff5ea624096a7100562e/.github/workflows/continuous.yml#L31

**Comment by mattbrailsford** [comment]
@matkoch no, sorry I was just giving an example of something then using the passed in env variable.

**Comment by matkoch** [comment]
When secrets are defined in Azure Pipelines, how are they referenced then in the `env` block?

**Comment by mattbrailsford** [comment]
Just using the `$(mySecret)` syntax I believe. It’s like accessing any other variable but it knows to give the secret value.

**Comment by vip32** [comment]
this would be nice though:
![image](https://user-images.githubusercontent.com/164303/97054838-e3b42600-1585-11eb-82e2-db1ef8f5887e.png)

**Comment by matkoch** [comment]
@vip32 it's already fixed
