### ISSUE TITLE
Add support for accessing Azure Pipeline variable groups

### ISSUE THREAD

**Issue by mattbrailsford** [nuke-build/nuke#532]
### Description
When using the Azure Pipelines feature it would be nice if there was a way we could define variable groups to include in the generated pipelines.yml file https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group

Maybe this could become an option on the AzurePipelinesAttribute

    [AzurePipelines(AzurePipelinesImage.Vs2017Win2016,
        InvokedTargets = new[] { nameof(Push) },
        VariableGroups = new[]{ "my-group" })]
    class Build : NukeBuild
    ...

**Comment by mattbrailsford** [comment]
Linked to #531 it would also be good if this could support secret variable access, but I think if this and #531 are fixed, these should "just work"

**Comment by mattbrailsford** [comment]
Relates to PR #516

**Comment by matkoch** [comment]
Could you provide an example of the current YAML that you get, and mark the lines that need to be added? Then I could probably add this myself.

**Comment by mattbrailsford** [comment]
@matkoch sure thing, so the generated output looks along these lines

    stages:
      - stage: vs2017_win2016
        displayName: 'vs2017-win2016'
        dependsOn: [  ]
        pool:
          vmImage: 'vs2017-win2016'
        jobs:
          - job: Push
            displayName: 'Push'
            dependsOn: [  ]
            steps:
              - task: CmdLine@2
                inputs:
                  script: './build.cmd Push --skip'
    ...

Which I'd like to have a variables section declared at the top like

    variables:
      - group: "my-group1"
      - group: "my-group2"
    
    stages:
      - stage: vs2017_win2016
        displayName: 'vs2017-win2016'
        dependsOn: [  ]
        pool:
          vmImage: 'vs2017-win2016'
        jobs:
          - job: Push
            displayName: 'Push'
            dependsOn: [  ]
            steps:
              - task: CmdLine@2
                inputs:
                  script: './build.cmd Push --skip'
    ...

The variables defined within that group should then be available via the `$(myvar)` syntax so I guess there might be a need to have these variables be passed in some how? I'd guess by the env option on a task

    - task: CmdLine@2
      inputs:
         script: './build.cmd Push --skip'
       env:
         MY_VAR: $(myvar)

**Comment by matkoch** [comment]
Could you please review https://github.com/nuke-build/nuke/commit/4b6fc77284f43d99ade876a73d72de13fefda13e

**Comment by mattbrailsford** [comment]
@matkoch oh wow, that was quick. I’ll give it a test tomorrow but the solution looks great 👍🏻

**Comment by matkoch** [comment]
@mattbrailsford it's mainly the YAML I'd like you to take a look at.. only then I will create a prerelease

**Comment by mattbrailsford** [comment]
@matkoch the example yaml in your unit tests look spot on to me. 

The Microsoft examples show the env variables as all uppercase but I don’t think that’s important. I will verify this tomorrow though.

**Comment by mattbrailsford** [comment]
Ok, so double checking this morning and there is an issue.

In your output you have

    variables:
    - variable-group-1

but it should be

    variables:
    - group: 'variable-group-1'

I have double checked and in Azure Pipelines all env variables are automatically upper cased https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#access-variables-through-the-environment

> The name is upper-cased, and the . is replaced with the _. This is automatically inserted into the process environment. 

I don't think this means you have to upper case you env declarations, just that when you access the variable from the environment, it will now be upper cased. I'm not sure how the variables are resolved as properties, but it may be here https://github.com/nuke-build/nuke/commit/4b6fc77284f43d99ade876a73d72de13fefda13e#diff-1205fbc866426b1a5e452c13919fa085R188 so I'm wondering if this resolution should be upper cased? I couldn't find in the docs if trying to resolve an env variable in non-uppercased way would be a problem or not. I'd suspect on windows no, but not sure on linux.
