### ISSUE TITLE
Can't run NUKE CodeGenerationTask in GitHubAction

### ISSUE THREAD

**Issue by mattbrailsford** [nuke-build/nuke#533]
### Description
I'm trying to create a wrapper library for a 3rd party tool which the source code can be found here https://github.com/mattbrailsford/Nuke.UmbPack 

Essentially this is a simple library with a dependency on `Nuke.Common` with a spec file defined for the specific tool. I then have a code generation task hooked up in the projects prof file so that the generated wrapper is created. This setup works fine locally.

I'm now trying to deploy it as a nuget package and have created a NUKE build config to build it, however I'm hitting an issue in the build step with it failing at the point of running the code generator. 

### Relevant log output

    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018: The "CodeGenerationTask" task failed unexpectedly. [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018: System.Exception: Assertion failed: repository.Branch != null [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.Common.ControlFlow.Fail(String text) in /bitrise/src/source/Nuke.Common/ControlFlow.cs:line 48 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.Common.Tools.GitHub.GitHubTasks.GetGitHubDownloadUrl(GitRepository repository, String file, String branch) in /bitrise/src/source/Nuke.Common/Tools/GitHub/GitHubTasks.cs:line 137 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.<>c__DisplayClass20_0.<ExecuteInner>g__GetSourceFile|4(Tool tool) in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 53 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.CodeGeneration.CodeGenerator.GenerateCode(String specificationFile, Func`2 outputFileProvider, Func`2 namespaceProvider, Func`2 sourceFileProvider) in /bitrise/src/source/Nuke.CodeGeneration/CodeGenerator.cs:line 44 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.<>c__DisplayClass20_0.<ExecuteInner>b__6(String x) in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 57 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /bitrise/src/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 16 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.ExecuteInner() in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 59 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018: The "CodeGenerationTask" task failed unexpectedly. [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018: System.Exception: Assertion failed: repository.Branch != null [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.Common.ControlFlow.Fail(String text) in /bitrise/src/source/Nuke.Common/ControlFlow.cs:line 48 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.Common.Tools.GitHub.GitHubTasks.GetGitHubDownloadUrl(GitRepository repository, String file, String branch) in /bitrise/src/source/Nuke.Common/Tools/GitHub/GitHubTasks.cs:line 137 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.<>c__DisplayClass20_0.<ExecuteInner>g__GetSourceFile|4(Tool tool) in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 53 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.CodeGeneration.CodeGenerator.GenerateCode(String specificationFile, Func`2 outputFileProvider, Func`2 namespaceProvider, Func`2 sourceFileProvider) in /bitrise/src/source/Nuke.CodeGeneration/CodeGenerator.cs:line 44 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.<>c__DisplayClass20_0.<ExecuteInner>b__6(String x) in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 57 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /bitrise/src/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 16 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    C:\Users\runneradmin\.nuget\packages\nuke.common\0.24.11\build\netcore\Nuke.MSBuildTasks.targets(42,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.ExecuteInner() in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 59 [D:\a\Nuke.UmbPack\Nuke.UmbPack\src\Nuke.UmbPack\Nuke.UmbPack.csproj]
    Process 'dotnet.exe' exited with code 1.

**Comment by mattbrailsford** [comment]
I'm guessing this might be something to do with me building only on a tag push resulting in the repository.Branch to be null for some reason?

**Comment by mattbrailsford** [comment]
Hmm, by the looks of this line https://github.com/nuke-build/nuke/blob/78f931f5c453f9ffbce69a67e25b7128e80b2fc9/source/Nuke.Common/Git/GitRepository.cs#L38 I am guessing the GitRepository doesn't get a branch name if the branch is a tag as it will be `ref/tags/(?<branch>.*)`

Would it make sense to convert this line to

    var branchMatch = Regex.Match(head, "^ref: refs/(?<branchType>head|tag)s/(?<branch>.*)");

You could then also use the `branchType` capture group to allow detecting whether the branch is a `head` or a `tag`

**Comment by mattbrailsford** [comment]
Hmm, saying that, I've just tried deploying from the main branch and that failed with the same error too so for some reason, in the github action it's not picking up a branch name?

**Comment by matkoch** [comment]
Should be fixed now.

**Comment by mattbrailsford** [comment]
I can confirm this is now working 👍
