### ISSUE TITLE
Support detecting tag name

### ISSUE THREAD

**Issue by mattbrailsford** [nuke-build/nuke#534]
### Description
Identified in #533 I believe the GitRepository currently only supports identifying head branches, but not tags. It would be good if we could identify tags so that these could be checked as part of a Requires statement

    .Requires(() => GitRepository.Branch.StartsWith("v"))

From what I can tell, the issue lies here

https://github.com/nuke-build/nuke/blob/78f931f5c453f9ffbce69a67e25b7128e80b2fc9/source/Nuke.Common/Git/GitRepository.cs#L38

If we want to extend this to also detect tags, this regex could be updated to something like

    var branchMatch = Regex.Match(head, "^ref: refs/(?<branchType>head|tag)s/(?<branch>.*)");

You could then also use the` branchType` capture group to allow detecting whether the branch is a `head` or a `tag` and maybe this could be exposed on the GitRepository object too.

**Comment by matkoch** [comment]
I’m not sure how this is intended to work. A commit can have multiple tags.

**Comment by mattbrailsford** [comment]
Ahh, didn’t know you could. All I know is if you push a tag and want to run a build target based on that tag you can’t get a reference. 

I know in azure pipelines you can detect the tag that has triggered the build so it was mostly this I’m trying to mimic. I.e., if I push a tag ‘v1.0.0’ I’d like to only run a target if the tag starts with ‘v’ so I know it’s a release.

**Comment by mattbrailsford** [comment]
In an azure pipeline I can have a condition on a task like

    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')

**Comment by matkoch** [comment]
Could probably still work, in the following image, both tags have the same reference as develop.

![image](https://user-images.githubusercontent.com/5005566/87364071-e78de080-c572-11ea-9181-901303af1557.png)

**Comment by matkoch** [comment]
Available on `GitRepository.Tags` now...

**Comment by mattbrailsford** [comment]
I can confirm this works great 👍

**Comment by jamotaylor** [comment]
> Available on `GitRepository.Tags` now...

When I run `git tag --list` in my repository it returns over 50 tags, but calling `GitRepository.Tags` returns an empty collection.

**Comment by matkoch** [comment]
@nwtnwrkshp this is only for the tags of the current commit.

**Comment by robvanuden** [comment]
I have the same problem, tags made in Azure DevOps aren't returned when calling `GitRepository.Tags`. I found out it has to do with the fact that Azure DevOps creates annotated tags instead of simple tags. Annotated tags aren't supported right now.
