### ISSUE TITLE
Interactive mode for parameters doesn't allow some characters

### ISSUE THREAD

**Issue by tuscen** [nuke-build/nuke#536]
### Description

Interactive mode doesn't allow to enter a colon (:), even if you paste it from a clipboard. There might be more such ignored characters, but that's one I stumbled upon.

### Steps to reproduce

1. Add a parameter to your build 
2. Invoke a target that requires this parameter to be set without explicitly passing it
3. Try to enter a colon either manually or by pasting it

```
[Parameter("")]
readonly string Test;

Target TestTarget => _ => _
	.Requires(() => Test)
	.Executes(() => {});
```

### Relevant log output

Nuke version: 0.24.11

**Comment by smezger** [comment]
@matkoch Is there a specific reason you have limited the input in interactive mode?
I can propose a change of the  `ConsoleUtility.PromptForInput` method via a PR if you are open for it.

**Comment by matkoch** [comment]
Hi, I'm closing this due to the new contribution guidelines.
