### ISSUE TITLE
ParameterAttribute does not allow ':' character

### ISSUE THREAD

**Issue by smezger** [nuke-build/nuke#538]
### Description
Not possible to insert ':' characters within Parameter values, when falling back to console input. However e.g. Artifactory uses ':' characters in their API keys.
### Steps to reproduce

1. Define a [Parameter] string Key;
2. Add Requires to the parameter 
3. do not specify via arg or env var -> triggers console fallback
4. Not possible to insert ':' char

**Comment by matkoch** [comment]
#536
