### ISSUE TITLE
Using quotes in Tool invocation causes an error

### ISSUE THREAD

**Issue by fogzot** [nuke-build/nuke#539]
### Description

Let's suppose you want to deploy using `rsync` and add a `PathExecutable` tool as follows:
```
[PathExecutable("rsync")] readonly Tool Rsync;
```
then you invoke it with string that contains quotes to pass a complex argument with whitespace in it:
```
Rsync($"-varc -e 'ssh -l webapp -p 2222' api management {GetDeployDestination()}",
     workingDirectory: PublishDirectory);
```
The invocation results in an error because the arguments somehow get splitted and the shell used to execute the command issues the following error:
```
Missing trailing-' in remote-shell command.
```

### Steps to reproduce

See above.

### Relevant log output
```
> /usr/bin/rsync -varc -e 'ssh -l webapp -p 2222' api management aaa@xxx.yyy.it:production/
@ /home/fog/xxx/yyy/_publish
Missing trailing-' in remote-shell command.
rsync error: syntax or usage error (code 1) at main.c(530) [sender=3.2.2]
Process 'rsync' exited with code 1.
   > /usr/bin/rsync -varc -e 'ssh -l webapp -p 2222' api management aaa@xxx.yyy.it:production/
   @ /home/fog/Customers/xxx/_publish
Error output:
   Missing trailing-' in remote-shell command.
   rsync error: syntax or usage error (code 1) at main.c(530) [sender=3.2.2]

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.Tooling.ToolExecutor.Execute(String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Action`2 customLogger, Func`2 outputFilter)
   at Build.<get_Deploy>b__20_1() in /home/fog/Customers/turintech/hr/build/Build.cs:line 80
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
```

**Comment by matkoch** [comment]
How about double quotes? The arguments get passed as is to Process.Start

**Comment by fogzot** [comment]
That works. I didn't know Process.Start had special management of double quotes but not single ones, sorry.

This should probably be documented? If you want I can submit a patch.

**Comment by matkoch** [comment]
`Process` is a BCL class, I'm not sure what you mean by submitting a patch. Not my repository :)

**Comment by fogzot** [comment]
Sorry, what I mean is: shouldn't the Nuke documentation about the `Tool` and `XXXExecutableAttribute` classes tell the user about this? Using single quotes, especially if you are used to writing shell scripts on UNIX, is pretty common and paragraph about how it *will not work* will help new users to avoid the problem I had.

**Comment by matkoch** [comment]
I'm a bit reluctant to document behavior that resides in code that I don't own.

**Comment by matkoch** [comment]
Just like I wouldn't document that you can't pipe commands using this.
