### ISSUE TITLE
How to interact with external tools that use color in output?

### ISSUE THREAD

**Issue by fogzot** [nuke-build/nuke#540]
### Description

I am happily using Nuke and I find the simplicity of calling an external tool extremely useful and I don't consider this a real bug, but if Nuke could solve the problem outlined below it would be much better when looking at the output.

For some reason, the first line of output of an external tool that uses color in its output is always colored red and reported at the end of the run as an error. Also, the following output, depending on the tool, sometime has the wrong color (always red). I don't know if it is possible but it would be nice for Nuke to somehow "reset" the console and start the tool as if it just launched from the command line. Some tools that exhibit the problem are, for example, `yarn` and `gcloud`.

### Alternatives

Running with a monochrome terminal without any feature works (TERM=unknown) but the output is pretty dull.

**Comment by matkoch** [comment]
Capturing output causes colors to be lost. If a tool follows specific rules, like starting a line with `error: .....` or `warn: ...` this can be implemented in a custom logger to make use of `Logger.Warn` and `Logger.Error`.

**Comment by matkoch** [comment]
And the issue with yarn I believe, is that it uses error output for non-critical messages.
