### ISSUE TITLE
Please upgrade to the new Key Vault client libraries

### ISSUE THREAD

**Issue by heaths** [nuke-build/nuke#543]
We have released [new versions](https://aka.ms/azsdk/net) of the Azure SDK Client Libraries for Key Vault, Storage, and other Azure services. We see that you are still using the older packages. The new Azure SDK is faster, leaner, and more extensible. Please see our [introductory video](https://aka.ms/azsdk/intro) and our [value propositions](https://aka.ms/azsdk/valueprop) for more information. We hope that you upgrade to these new packages. We are happy to offer assistance in upgrading while we work on migration guides.

For Key Vault, we have split the client libraries into 3 separate packages that can be used together but, individually, are smaller dependencies:

* [Azure.Security.KeyVault.Certificates](https://www.nuget.org/packages/Azure.Security.KeyVault.Certificates/) ([README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md), [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/samples))
* [Azure.Security.KeyVault.Keys](https://www.nuget.org/packages/Azure.Security.KeyVault.Keys/) ([README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/README.md), [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys/samples))
* [Azure.Security.KetVault.Secrets](https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/) ([README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/README.md), [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/samples))

Samples are also available in our [samples browser](https://aka.ms/azsdk/net/keyvault/samples).

**Comment by totollygeek** [comment]
I am also interested in this, since the old libraries pose a security problem, since they reference older NuGet packages, which include security vulnerabilities. Our security system is marking our repositories as vulnerable due to this. I will prepare a PR with the update.

**Comment by GeorgDangl** [comment]
Maybe also consider including #703 then as well😀

**Comment by totollygeek** [comment]
I just noticed there is already another one here #575  🤔

**Comment by GeorgDangl** [comment]
Well at least there's now two people in the world using KeyVault😀

**Comment by eatdrinksleepcode** [comment]
@heaths I think #575 resolved this, correct? Can this issue be closed?
