### ISSUE TITLE
Check DotNetTest output

### ISSUE THREAD

**Issue by zplan** [nuke-build/nuke#545]
### Description
It is more a question than a bug:
I am calling DotNetTest() and after that, I upload the trx and the coverage file to azure devops.
When a test is failing, DotNetTest() terminates with an exception and the code after DotNetTest() is not executed anymore.
But the users want to see, especially if a test has failed, the test results on the server.

How should I handle DotNetTest to upload results in good an bad case?

- try catch around DotNetTest?
- better ways?

### Steps to reproduce

ConvertCodeCoverage() and UploadTestsWithCoverage() are not executed, if a test failed.

or

```

  Target Test => _ => _
        .Executes(() =>
        {

           DotNetTest(_ => _
                .SetConfiguration(Configuration)
                .SetNoBuild(true)
                .SetVerbosity(DotNetVerbosity.Normal)
                .SetResultsDirectory(TestResultsDirectory)
                .EnableCollectCoverage()
                .SetCoverletOutputFormat(CoverletOutputFormat.opencover)
               .CombineWith(testProjects, (_, v) => _
                    .SetProjectFile(v)
                    .SetLogger($"trx;LogFileName={v.Name}.trx")
                    .SetCoverletOutput(TestResultsDirectory / $"{v.Name}.xml")
                ));

        ConvertCodeCoverage();

       UploadTestsWithCoverage();

});

```

**Comment by GeorgDangl** [comment]
I'm just wrapping it in a `try/finally` block, to ensure that the code after is executed by the target itself fails.

**Comment by iwillspeak** [comment]
Personally I put the Upload in a finally

**Comment by iwillspeak** [comment]
If you want to break the  upload into a separate target you could use the 
`AssuredAfterFailure` method to ensure tests are uploaded in all cases. 

See https://nuke.build/docs/authoring-builds/fundamentals.html#failure-behavior for more infomation.

<blockquote><img src="../../favicons/favicon.ico" width="48" align="right"><div><strong><a href="https://nuke.build/docs/authoring-builds/fundamentals.html#failure-behavior">Fundamentals | NUKE</a></strong></div></blockquote>
