### ISSUE TITLE
ReSharper extension is not updated on the correct feed

### ISSUE THREAD

**Issue by Nezrahm** [nuke-build/nuke#551]
"NUKE Support 2020.2.0" is on the feed "Nuke.Common:0.24.11 Wave:[202.0.0-eap09]"

Should be available for "https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v202.0/"?

**Comment by synesthesia** [comment]
Would this explain why it isn't visible in R# Extension Manager even if  I download it into a directory I have configured as a local extension source for R#? (Running R# 2020.2)
