### ISSUE TITLE
 Add support for Parameter in AzurePipelines configurations

### ISSUE THREAD

**Issue by kthompson** [nuke-build/nuke#552]
### Description
Add support for `Parameter` in `AzurePipelines` configurations

**Comment by kthompson** [comment]
I could take a stab at this by copying some of the code in the TeamCityAttribute.GetGlobalParameters and injecting it into the AzurePipelinesConfiguration object if that is the right approach?

**Comment by matkoch** [comment]
Do they have an UI for parameters now?

**Comment by kthompson** [comment]
Yea its not too detailed.
 ![Set a variable](https://mrunleaded.keybase.pub/Capture.PNG)
 ![Add a variable](https://mrunleaded.keybase.pub/Capture2.PNG)

My thought was basically to just append the parameters like `--api-key $(ApiKey)`

I have a workaround for my use case but it would be nice to have slightly better support 😄 

If you want to see my workaround its here:
https://github.com/kthompson/glob/commit/6421e4d22a0b979fd104cb8c8182b27025396035#diff-d276c46d8e2c971daec679a927be519fR61
https://github.com/kthompson/glob/commit/6421e4d22a0b979fd104cb8c8182b27025396035#diff-d276c46d8e2c971daec679a927be519fR96

**Comment by matkoch** [comment]
Can't you use environment variables? `Parameter` fields are resolved from them as well. Otherwise, sure... if you draft something we can discuss it.

**Comment by kthompson** [comment]
It does not appear to work without referencing the parameter in the config. Access to environment variables needs to be declared

**Comment by matkoch** [comment]
@kthompson is this meant to be used for secrets?

**Comment by kthompson** [comment]
It is not exclusive to secrets but they support that option

**Comment by matkoch** [comment]
I’m asking if _you_ tried it with secrets :)

**Comment by kthompson** [comment]
Oh yeah 😂 that's what I used it for. An ApiKey for nuget.

**Comment by matkoch** [comment]
That should already be possible via `AzurePipelinesAttribute.ImportSecrets`

**Comment by matkoch** [comment]
Secrets can be defined with latest `0.25.0` prereleases. See https://github.com/nuke-build/nuke/issues/531. Other environment variables should be readable without declaring them.

**Comment by kthompson** [comment]
Alright I'll check it out thanks! 😊

**Comment by matkoch** [comment]
Let me know if it's not working. Closing for now.
