### ISSUE TITLE
Add teamcity features to target + method GetVCSRoot()

### ISSUE THREAD

**Issue by Tiraflo** [nuke-build/nuke#553]
First of all, thank you for this tool. Nuke is very convenient and I'm enjoying it much. I can't wait for using it for Unity projects needs.

### Description
I have two (or three) questions coming from the same situation.
After generating  the settings.kts file through Nuke which is then used by TeamCity. I needed some changes to my actual config (done manually from TeamCity UI):
- add a feature for packages indexing
- define a parameter env.Git_branch equals to %teamcity.build.vcs.branch.{vcsid}% (https://gitversion.readthedocs.io/en/latest/input/docs/build-server-support/build-server/teamcity/)

Thoses modifications result in creating patches from TeamCity. For the sake of cleanliness, I merged patches into settings.kts. As a consequence, a Nuke build overwrites the settings.kts file.

Then here are my questions: 
- Is there a way to not overwrite settings.kts? Adding it to .gitignore does not seem to me like a suitable workaround.
- I think I could define the env.Git_branch parameter within the Nuke build.cs file but I'm struggling using method GetVCSRoot() (class TeamCityAttribute)
- Would it be possible to configure the TeamCity features (e.g. packages indexing, VCS labelling) from the Nuke build file? I haven't seen a related attribute or method in the documentation. I don't know how relevant would it be?

Many thanks.

Regards.

**Comment by matkoch** [comment]
I'm not aiming for adding CI specific features in order to keep nearly parity between different vendors. Also the patch files for TeamCity are actually a great way to customize the build without worrying that the infrastructure isn't there in NUKE. If you want to edit the settings.kts file, you can set the AutoGenerate property to false.
