### ISSUE TITLE
Parameter attribute has "Name" & TeamCity CI Integration

### ISSUE THREAD

**Issue by Simonl9l** [nuke-build/nuke#555]
## Description

When setting up Parameters in Nuke, the Parameter Attribute has a `Name` property. The expect is that this defined/results in the name of the Configuration Property in the TeamCity project Build Configuration once the Kotlin in generated.

### Steps to reproduce

Add Parameter
```C#
[Parameter(Name = "My_TC_Parameter_Name")] string MyParameter { get; set; }
```

Generates this:
```Kotlin
params {
        text (
            "env.MyParameter",
            label = "MyParameter",
            allowEmpty = true,
            display = ParameterDisplay.NORMAL)
```

However we expect this:
```Kotlin
params {
        text (
            "env.My_TC_Parameter_Name",
            label = "My_TC_Parameter_Name",
            allowEmpty = true,
            display = ParameterDisplay.NORMAL)
```

**Comment by matkoch** [comment]
Hi, I'm closing this due to the new contribution guidelines.

**Comment by Simonl9l** [comment]
Hi @matkoch - slightly confused...

Per inference of the “new” contribution guidelines since this was a new issues, is it “fix it yourself” and send a pull request?

just checking ? Per labeling - what other discussion was otherwise needed?

**Comment by matkoch** [comment]
This issue hasn't received any attention, and I closed it (like many others), with the intent to clean up the backlog and improve project continuity (sponsorship requirement). The _discussion-needed_ tag was mostly whether the change is a good idea. I don't even remember why I introduced custom naming of parameters.
