### ISSUE TITLE
Pulumi command line tool syntax

### ISSUE THREAD

**Issue by nloum** [nuke-build/nuke#557]
### Description

Pulumi is an infrastructure-as-code tool that supports including C#. To use it, you create a C# project, write C# code to create virtual machines (or some other cloud infrastructure), and then run `pulumi up` from the command line. This will create the virtual machines.

Pulumi and Nuke share a common goal: keep complex logic related to programming in the main programming language, instead of using YAML, XML, etc. I use both Pulumi and Nuke and I'd like to integrate them so that I could have a target something like this:

```
Target Deploy => _ => _
	.DependsOn(Test)
	.Executes(() =>
	{
		PulumiUp(_ => _
			.SetStack("dev")
			.AutomaticallyApproveDeployment());
	});
```

Links:

- [Pulumi command line documentation](https://www.pulumi.com/docs/reference/cli/)

- [Pulumi .NET documentation](https://www.pulumi.com/docs/intro/languages/dotnet/)

### Alternatives

Right now I can do:

```
Target Deploy => _ => _
    .DependsOn(Test)
    .Executes(() =>
    {
	    ProcessTasks.StartProcess("pulumi", "up -y");
    });
```

Which isn't bad, but it would be nicer if it used custom tool syntax.

**Comment by VolkmarR** [comment]
Nuke uses a specification file to [generate the classes for cli tools](https://nuke.build/docs/writing-addons/code-generation.html). You can check out the existing specification files of the [currently supported tools like dotnet, msbuild, ...](https://github.com/nuke-build/nuke/tree/develop/build/specifications).

**Comment by nloum** [comment]
Cool, thanks for the links! I plan to create a PR for this soon.
