### ISSUE TITLE
.tmp\shell-completion.yml blocked by another process

### ISSUE THREAD

**Issue by markayby** [nuke-build/nuke#560]
### Description
On the start of running script i get an error **_The process cannot access the file 'C:\...\.tmp\shell-completion.yml' because it is being used by another process._**

### Steps to reproduce

I have 4.7 .NET Framework project and try to build it using Nuke 0.24.11. When i start a script "./build.ps1 --target npm --configuration Release --customerName 'Demo' --environmentName 'Prod'" (or another one to run with another targets, so the error doesn't depend on targets content) i get that error, but it is not reproducible constantly. Please see the attached screenshot.

![image](https://user-images.githubusercontent.com/34906768/93582279-ec27a880-f9aa-11ea-8243-54543ddc79b5.png)

**Comment by matkoch** [comment]
Sorry but this is nothing I can help with if it doesn't really reproduce.

**Comment by matkoch** [comment]
Sorry but this is nothing I can help with if it doesn't really reproduce.

**Comment by valadas** [comment]
It happened to me once or twice but not consistently... I think in my case it was when I forgot to close one terminal window and ran it too in another one...

**Comment by matkoch** [comment]
Should be fixed for 0.25.0 already.

**Comment by matkoch** [comment]
@markayby screenshots are not a great way to read logs. I recommend pasting the text next time.

**Comment by markayby** [comment]
Updates. 
It reproducible for me only when i use the following attributes:
[TeamCity(
		TeamCityAgentPlatform.Windows,
		CleanCheckoutDirectory = false,
		VcsTriggeredTargets = new[] { nameof(Test), nameof(DeployBackend), nameof(DeployFrontend) },
		NightlyTriggeredTargets = new[] { nameof(Test), nameof(DeployBackend), nameof(DeployFrontend) })]
[AzurePipelines(
		AzurePipelinesImage.UbuntuLatest,
		AzurePipelinesImage.WindowsLatest,
		AzurePipelinesImage.MacOsLatest,
		InvokedTargets = new[] { nameof(Test), nameof(DeployBackend), nameof(DeployFrontend) })]
internal class Build : NukeBuild {
...
If remove them i do not catch the issue.
@matkoch ok, thank you
