### ISSUE TITLE
PowerShell completion suggests "NUKE Global Tool..."

### ISSUE THREAD

**Issue by VulumeCode** [nuke-build/nuke#561]
### Steps to reproduce

Follow these steps for powershell https://nuke.build/docs/running-builds/global-tool.html
Try a completion

It works, but the first completion is always something like "NUKE Global Tool version 0.24.11 (Windows,.NETCoreApp,Version=v2.1)" and it will be selected if there are no real suggestions. 

The snippet for bash seems to work fine.

**Comment by matkoch** [comment]
Could you install the prerelease? Should be fixed there.

**Comment by VulumeCode** [comment]
Super fast response! It works, thanks!

**Comment by matkoch** [comment]
@VulumeCode please star :)
