### ISSUE TITLE
How to add version number to Path?

### ISSUE THREAD

**Issue by devmaestro1** [nuke-build/nuke#563]
I am trying to name my setup executable based on the version of .NET application executable.
For example, if app.exe is version 2.0.0, I want to create a setup filename like so:

AbsolutePath SetupFilename = MyOutputPath / "MyAppSetup-" + GetVersion("app.exe")

Could point me to the correct way to do this? I have tried to create a GetVersion() method but AbsolutePath does not support concatenations in this way (nor method calls). I imagine I could convert everything to strings, but doesn't that defeat the purpose of having AbsolutePath?

Thank you.

**Comment by matkoch** [comment]
Division has higher priority than addition, so you need to use parenthesis.

**Comment by devmaestro1** [comment]
Hello,

Sorry, this didn't answer my question. I obviously wasn't being clear enough. My question is about how to correctly create a Path with a version number while keeping the declaration as a class variable.

Here is my solution:

```
static AbsolutePath MainExeFullPath => FinalBinariesFolder / FileMainExe;
static string FileSetup = "AppSetup" + "-" + GetVersion(MainExeFullPath);
static AbsolutePath SetupFullPath => FinalSetupFolder / (RelativePath)(FileSetup + ".exe");

   private static string GetVersion(string filename)
    {
        var versionInfo = FileVersionInfo.GetVersionInfo(filename);
        string version = versionInfo.FileVersion;
        return version;
    }

```

Hope it helps someone.
