### ISSUE TITLE
Rider EAP 2020.3 Compatibility

### ISSUE THREAD

**Issue by andi0b** [nuke-build/nuke#569]
It seems like once again the NUKE plugin for Rider is not compatible with the newest EAP. Is there a reason, why the compatibility is not open to new versions? like 2020.2+, for example like the IdeaVim Plugin? https://plugins.jetbrains.com/plugin/164-ideavim/versions

For 2020.2 there was the same issue. Only on the final release date for Rider 2020.2 a new NUKE plugin was released. As it is closed source now, I can't compile it on my own.

I'm using EAP versions around 50% of the year, so i have only NUKE support in my IDE for 50% of the year. Thats sad :(

**Comment by matkoch** [comment]
ReSharper and Rider plugins always have to be compiled for a specific version. So there is no open upper bound. You can get access to EAP builds when joining as a sponsor.
