### ISSUE TITLE
Wrong out time format for SetTimeout for Kubernetes

### ISSUE THREAD

**Issue by Elufimov** [nuke-build/nuke#580]
### Description and Steps to reproduce
Right now `SetTimeout` (for example in  `Nuke.Common.Tools.Kubernetes.KubernetesWaitSettingsExtensions.SetTimeout`) produces string in default format `--timeout=00:00:30` (for example for `.SetTimeout(TimeSpan.FromSeconds(30))`) Kubernetes takes time in format `--timeout=30s`.

### Relevant log output

```
Nuke.Common 0.24.11
```

**Comment by matkoch** [comment]
I don't take issues for specific tools atm. Feel free to use `SetArgumentConfigurator`.

**Comment by Elufimov** [comment]
Would you take pull request with fix?

**Comment by matkoch** [comment]
At this time probably not. It's generated.

**Comment by Elufimov** [comment]
One could change the source (https://github.com/nuke-build/nuke/blob/develop/build/specifications/Kubernetes.json) file and run generator. Or this is not a right way?

<blockquote><img src="https://repository-images.githubusercontent.com/93804681/cccf0d00-e1ab-11ea-8e53-d985c08819a3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>
