### ISSUE TITLE
Tools.EntityFramework does not find executable if embedded in tool

### ISSUE THREAD

**Issue by Nefarion** [nuke-build/nuke#586]
### Description
Embedding dotnet-ef as a PackageDownload in the Project does not work.
Embedding ReportGenerator as a PackageDownload in the Project works fine.

I think a fix would look like this [ReportGenerator](https://github.com/nuke-build/nuke/blob/80646fd57a1bf18ed52c2a202f81e50f147f8918/source/Nuke.Common/Tools/ReportGenerator/ReportGeneratorTasks.cs#L23-L40).

### Steps to reproduce

1. Add a `PackageDownload `for dotnet-ef
2. publish the build project
3. dotnet-ef.exe is present in the .nupkg
4. instead of calling `dotnet-ef.exe <args>` nuke tries to call `dotnet ef <args>`

### Relevant log output

```
> "C:\Program Files\dotnet\dotnet.exe" ef migrations script --output <> --idempotent --context DataContext --project <> --startup-project <> /clp:ForceConsoleColor
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by matkoch** [comment]
It's the exact same change then, feel free for PR

**Comment by Nefarion** [comment]
Well, this looks like a issue without quickfix to me, because the specfile is only considering the `dotnet ef` tool.  
There is a [dotnet-ef package](https://www.nuget.org/packages/dotnet-ef/) on nuget, that one can use, and then it will never be found by the ToolPathResolver.

**Comment by matkoch** [comment]
don't follow, for entityframework.json you'd apply the same fix... that should be enough

**Comment by matkoch** [comment]
change regarding packageExecutable also sounds reasonable .. @RLittlesII added the file afaik, maybe he has an opinion

**Comment by nrovdoitra** [comment]
I've resolved that with 

```
   DotNet($"tool install --global dotnet-ef");
   DotNet($"ef migrations script --idempotent  -o {AppDirectory.Parent}\\{AppDirectory.Name}\\{MigrationsFileName}");
```
