### ISSUE TITLE
Output sinks should handle parallel processing

### ISSUE THREAD

**Issue by levdimov** [nuke-build/nuke#602]
_Hi! First of all, thank you for Nuke! We are now able to develop a complex build with ease and confidence._

To speed up some things I am using some parallelling tricks (using TPL). But it seems that output sinks can't handle output from simultaneously running threads. The output from such build will be random: in TeamCity, blocks will be written under root context.

For example, it is quite easy to implement this for TeamCity sink using [Message FlowId](https://www.jetbrains.com/help/teamcity/service-messages.html#Message+FlowId).

**Comment by matkoch** [comment]
That might be a solution for TeamCity, but it's not a general solution. For now I have no plans to address this, as it's coupled to many more issues.
