### ISSUE TITLE
Issues while installing Resharper plugin

### ISSUE THREAD

**Issue by madhusameena** [nuke-build/nuke#605]
Not able to install Nuke extension from Resharper
Please find the logs below.

[Huruhev.txt](https://github.com/nuke-build/nuke/files/5502123/Huruhev.txt)
[InstallLog_2020-11-06T20-47-38.txt](https://github.com/nuke-build/nuke/files/5502124/InstallLog_2020-11-06T20-47-38.txt)

Environment: 
Microsoft Visual Studio Enterprise 2019 - Version 16.7.7
Resharper - 2020.2.4

**Comment by madhusameena** [comment]
Hi any workaround for this issue?  
with Microsoft Visual Studio Enterprise 2019
Version 16.8.1also getting same error

**Comment by matkoch** [comment]
Should work now. Otherwise please wait for 2020.3
