### ISSUE TITLE
net5.0 sdk and gitversion

### ISSUE THREAD

**Issue by vip32** [nuke-build/nuke#606]
Am trying to build some .net 5.0 projects with nuke.

my global.json: this installs .net 5.0 when not installed already.
{
  "sdk": {
    "version": "5.0.100"
  }
}

however, when running nuke the following error appears:

Assertion failed: Package executable GitVersion.dll, or GitVersion.exe [GitVersion.Tool|GitVersion.CommandLine] requires a framework:
 - netcoreapp2.1
 - netcoreapp3.1

When I indeed tag the gitversion with a 3.1 framework it works locally. The issue is my build server does not have 3.1 and neither is it installed by nuke (as it does with the framework specified in global.json) 
![image](https://user-images.githubusercontent.com/164303/98948689-1010f180-24f7-11eb-8888-855f0f9afa10.png)

what am I missing here? does the gitversion task not work with framework net5.0 and why do we need to specify this framework on the gitversion property?

my build file can be found [here](https://github.com/vip32/Zeta/blob/a4fda51a6f3365e378352bf1938b608a9ae20464/build/Build.cs)

**Comment by PascalSenn** [comment]
Hi @vip32 
I currently have also run into issue with .net 5 but I think I know what your issue is.
I think when you install netcoreapp3.1 and 5.0.100 you should not see the issue you described above. 
GitVersion has executables in the nuget package. I think it includes netcoreapp2.1 and netcoreapp3.1. 
You will need both versions on the build server to be able to work with GitVersion and net5.0 
We use dotnet-install.sh to install both versions on the pipeline

**Comment by vip32** [comment]
Yes that was also my workaround, install both .net sdks on the build server. However when the [build script](https://github.com/vip32/Zeta/blob/a4fda51a6f3365e378352bf1938b608a9ae20464/azure-pipelines.yml) is generated by using the AzurePipelines attribute it is impossible to hook that 3.1 installation in as a pre-step. 

![image](https://user-images.githubusercontent.com/164303/98961579-00e57000-2506-11eb-9604-2620e4803e63.png)

somehow a gitversion based on net 5.0 makes sense here, but it's newer packages all target 2.1/3.1
global.json only supports one sdk install, right?

**Comment by vip32** [comment]
maybe the correct way to take care of this is to add net5.0 as a targetframework in GitVersion.Tool
https://github.com/GitTools/GitVersion/issues/2431

does that make sense? (comments please, before I start on a PR there)

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/commit/d41ec4542efd7a3a0218bd71ed331658862c2a54

**Comment by matkoch** [comment]
@vip32 please no images and also use the issue template next time
