### ISSUE TITLE
generated github actions/azure pipelines uses wrong build bootstrapper

### ISSUE THREAD

**Issue by vip32** [nuke-build/nuke#607]
the following attribute generates a github action workflow. Note ubuntu is specified.
![image](https://user-images.githubusercontent.com/164303/98949616-3d11d400-24f8-11eb-9a8f-1b2fb1803987.png)

then this generated workflow should point to the build.sh file and not the build.cmd file. The build.sh also needs execute permissions set in the workflow somewhere.
![image](https://user-images.githubusercontent.com/164303/98950122-e3f67000-24f8-11eb-98e1-3ff5d4f4f6ed.png)

Is this a bug or am I doing something wrong? The same behavior appears when using the azure pipeline attribute:
![image](https://user-images.githubusercontent.com/164303/98949948-a85ba600-24f8-11eb-961c-1fd39770e2e0.png)

**Comment by matkoch** [comment]
`build.cmd` works cross-platform

**Comment by vip32** [comment]
@matkoch great, neat trick with the cmd file 👍 

however, not setting the x permission on the cmd file (linux) is preventing it from executing (azure devops + github actions). 
an example can be found [here](https://github.com/vip32/Zeta/runs/1391583656?check_suite_focus=true)

![image](https://user-images.githubusercontent.com/164303/98968346-dac3ce00-250d-11eb-8505-6f5c97f10c2e.png)

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/blob/3a1dfe91911055f05ec4a355946ab7e92800cf4a/source/Nuke.GlobalTool/Program.Setup.cs#L263

I guess you must have been doing something different than the recommended path.

**Comment by vip32** [comment]
ah yes, I have not used the nuke setup tool. Copied the nuke assets from some other project and continued from there.
Now I see that the git index for this cmd file takes care of that. Thx for the help!
