### ISSUE TITLE
AppVeyor encoding issues with Nuke 5.0.0

### ISSUE THREAD

**Issue by zvirja** [nuke-build/nuke#609]
### Description

After updating to Nuke 5 I started to observe encoding issues with AppVeyor. 

### Steps to reproduce

1. Install Nuke 5.0.0
2. Add AppVeyor script to invoke the build:
    ```
    build_script:
    - ps: |
        & .\build.ps1 --target Build --no-logo
    ```

### Relevant log output

```
PowerShell Desktop version 5.1.17763.1007
[00:00:02] Microsoft (R) .NET Core SDK version 5.0.100
[00:00:16] Creating directory 'C:\projects\git-sync-creation-date\.tmp'...
[00:00:17] NUKE Execution Engine version 5.0.0 (Windows,.NETCoreApp,Version=v2.1)
[00:00:17] 
[00:00:17] 
[00:00:17] Γò¼ΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉ
[00:00:17] Γòæ AppVeyor_DescribeState
[00:00:17] Γò¼ΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉ
```

### Workaround

Set PowerShell encoding prior to running the script:

```
build_script:
- ps: |
    (& cmd /c); [console]::OutputEncoding = New-Object System.Text.UTF8Encoding;
    & .\build.ps1 --target Build --no-logo
```

### Details

The issue has been reported before: #530 #527, but nothing has been done. The issue is that after migration to 5.0.0 it stopped "to just work" with AppVeyor and finding a workaround is not trivial. Especially having that weird `(& cmd /c)` invocation to ensure that console output handle is valid. Given that previously it worked fine, I suspect there was some change in the code.

Even though it's not a Nuke bug, it might be still a good idea to have a fix included here. If application is emitting Unicode characters, we could set a proper encoding in the `build.ps1` file prior to running the script. This way people will not struggle when they try the product for the first time and love it even more 😊

**Comment by matkoch** [comment]
The issue you linked was assigned to the 0.25 milestone, which already got released.

https://github.com/nuke-build/nuke/blob/develop/appveyor.yml#L23-L25

<blockquote><img src="https://repository-images.githubusercontent.com/93804681/cccf0d00-e1ab-11ea-8e53-d985c08819a3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by matkoch** [comment]
Here's the output on Ubuntu and Windows:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/5005566/99418153-01fa1100-28fb-11eb-89f2-46004701682b.png">
<img width="673" alt="image" src="https://user-images.githubusercontent.com/5005566/99418162-04f50180-28fb-11eb-9f8d-3868d6765b29.png">

**Comment by zvirja** [comment]
@matkoch Thank you for the quick reply! I've just installed Nuke 5.0.0 and found that this issue is reproducible if I use `ps1` runner. Could you please advise what I'm doing wrong?

Thank you!

**Comment by matkoch** [comment]
I already linked to how you should invoke nuke: https://github.com/nuke-build/nuke/blob/develop/appveyor.yml#L23-L25

<blockquote><img src="https://repository-images.githubusercontent.com/93804681/cccf0d00-e1ab-11ea-8e53-d985c08819a3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by matkoch** [comment]
It's also the way it gets generated using the `AppVeyor` attribute.

**Comment by zvirja** [comment]
Does it mean that PowerShell runner usage for AppVeyor is not supported by Nuke out of the box?

This is how I run it: https://github.com/zvirja/git-sync-creation-date/blob/84dc85d52feaf457666666fe2af87f02b70dc1ba/appveyor.yml#L13
I need to proxy environment variables as parameters to the build script, so it's nicer to do that with PowerShell.

**Comment by matkoch** [comment]
You don't need to proxy anything. If you define `[Parameter] readonly string NuGetApiKey`, then it will be bound to the environment variable available. AppVeyor specific vars you should rather access via `AppVeyor.Instance`.

**Comment by zvirja** [comment]
@matkoch Thank you for the advice! Actually I did it on purpose. I did not want my build script to rely on information about environment variables defined in AppVeyor file. Rather I pass environment variables to the build script, so it's kind of CI agnostic. That is however irrelevant to the issue I reported. There might be various reasons for the PS runner usage.

When PS runner is used to invoke the build, the issue with encoding happens. You showed the samples where it works with `cmd` runner. Given that you closed the issue, does it mean that you officially does not support PS runner on AppVeyor OOTB?

**Comment by matkoch** [comment]
No intent, no. The bootstrappers are – on their own – minimal as possible. If you want, you can put it there... but since the guiding is towards using the attributes, I don't feel like putting something CI specific (there again :)) into the bootstrappers.

**Comment by zvirja** [comment]
@matkoch Sorry for taking your time, but I'm not sure I clearly understand your answer. So far we know that the following works fine for AppVeyor
```
build_script:
  - cmd: .\build.cmd Test Pack
  - sh: ./build.cmd Test Pack
```

This one, however, does not:
```
build_script:
  - ps: .\build.ps1 Test Pack
```

My point is that it's might be a bit confusing for the newcomers, so would be nice to fix. But that's not critical though, as there are workarounds (either use `cmd/sh` or switch PS to Unicode).

Do you decide to not bother with the PS runner and accept having an issue for AppVeyor OOTB? Just answer "yes" or "no" so I understand it clearly - anyway it's your project 😉 

P.S. BTW, `- sh: ./build.cmd Test Pack` looks like a typo, as I would expect `sh` bootstrapper to be used.

**Comment by matkoch** [comment]
> Do you decide to not bother with the PS runner and accept having an issue for AppVeyor OOTB? Just answer "yes" or "no" so I understand it clearly - anyway it's your project 😉

Yes. Although it's not "issue OOTB" for me. As the advised way works as expected. Also, this is working on any other CI system, so I guess it's rather AppVeyor that should fix something :)

> P.S. BTW, - sh: ./build.cmd Test Pack looks like a typo, as I would expect sh bootstrapper to be used.

No, that's correct. The `build.cmd` file works cross-shell.
