### ISSUE TITLE
Getting package directories

### ISSUE THREAD

**Issue by jeffreycoxdoosan** [nuke-build/nuke#615]
### Description

I've run across several situations where I need a nuget tool package's directory, and not an executable in that directory. For example, setting the --test-adapter-path argument on 'dotnet test' to use the NunitXml.TestLogger package.

My current work-around is `ToolPathResolver.GetPackageExecutable` on a random file in the package directory and then call `Path.GetDirectoryName`:
```c#
  var logger_path = Path.GetDirectoryName(ToolPathResolver.GetPackageExecutable("NunitXml.TestLogger", ".nupkg.metadata"));
  DotNetTest(s => s
    .SetResultsDirectory("TestResults")
    .SetTestAdapterPath( logger_path )
    .SetLogger("nunit")
  );
```

What I really want to do is call `ToolPathResolver.GetPackageDirectory`. Unfortunately, that's a private method.

I didn't see anything in [the faq](https://nuke.build/docs/getting-started/faq.html#how-can-i-execute-tools-from-nuget-packages) about this case. What is the recommended procedure for cases like this? If there isn't one, would you consider making GetPackageDirectory public?

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tooling/NuGetPackageResolver.cs#L194 ?

<blockquote><img src="https://repository-images.githubusercontent.com/93804681/cccf0d00-e1ab-11ea-8e53-d985c08819a3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by jeffreycoxdoosan** [comment]
`NuGetPackageResolver.GetGlobalInstalledPackage( "NunitXml.TestLogger",null,null ).Directory`
That works, thanks.
