### ISSUE TITLE
WIX installer

### ISSUE THREAD

**Issue by ahmedMabdo** [nuke-build/nuke#616]
Hello, thanks for that great tool
### Description
Add support for wix installer 
#259 #475 #212

**Comment by matkoch** [comment]
Hi, as noted in the other issue, I'm not keeping these open and rather expect PRs. However, for sponsors I'd also add the support :) https://github.com/nuke-build/nuke/issues/475

**Comment by vokounjan** [comment]
Take a look at WixSharp (if you haven't already). Awesome project which makes working with WiX much easier.
