### ISSUE TITLE
CI Integration documentation improvement

### ISSUE THREAD

**Issue by laurentkempe** [nuke-build/nuke#623]
### Description

The [CI Integration](https://nuke.build/docs/authoring-builds/ci-integration.html) could be improved by describing how you can generate the CI configuration. I could easily add the `TeamCity` attribute but then I was confused about how should I go on with configuring TeamCity with it. It is only by watching again the video [Nuke — Designing a Build System with IDE Support in Mind](https://youtu.be/N57Zjb5-08I?t=2550) that I learned that running `nuke --help` will generate a Kotlin configuration file which I need to import in TeamCity, also [explained in the video](https://youtu.be/N57Zjb5-08I?t=2627).

I think having sub-sections per CI would be helpful.

**Comment by matkoch** [comment]
I went with an info box for TeamCity. All other CIs don't need any manual steps.
