### ISSUE TITLE
Support R#/Rider 2020.3

### ISSUE THREAD

**Issue by inyutin-maxim** [nuke-build/nuke#627]
JetBrains released R# and Rider. Please update references and publish new release for you cool plugin

**Comment by matkoch** [comment]
@inyutin-maxim you created at least 4 issues regarding ReSharper/Rider updates in 4 different repositories. It'd be great if you could stop this, especially if it was just a few hours after release. Not every maintainer has the time to immediately react to the release, and it puts pressure on them.

**Comment by inyutin-maxim** [comment]
@matkoch Sorry for the inconvenience, I will try to create PR where I can. Just wanted to attract the attention of those participants who have this time
