### ISSUE TITLE
Update/Upgrade Unity API

### ISSUE THREAD

**Issue by Tiraflo** [nuke-build/nuke#631]
### Description

The current Unity API implementation seems to be based on version 2018. For example, argument "-runEditorTests" is deprecated since Unity 2019.3 and has been replaced by other arguments such as "-runTests", "-testResults" and "-testPlatform".

What is your approach about updating/upgrading (CLI) tools ? Would it be possible to make this upgrade for Unity ? I would be glad to help if possible.

I didn't forget my previous topic (https://github.com/nuke-build/nuke/issues/626) and I planned to try to make it soon, perhaps along with the current topic.

**Comment by matkoch** [comment]
If you want to provide a PR, you can start from here:

- https://github.com/nuke-build/nuke/blob/develop/build/specifications/Unity.json
- https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/Unity/UnityTasks.cs 

As described in the contribution guidelines, I'm not keeping related issues open, so just open a PR when you're finished!

<blockquote><img src="https://repository-images.githubusercontent.com/93804681/cccf0d00-e1ab-11ea-8e53-d985c08819a3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/93804681/cccf0d00-e1ab-11ea-8e53-d985c08819a3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by Tiraflo** [comment]
Fine by me, as long as I can still write a comment if needed.

> 6. No issues for additional CLT support or missing arguments. We expect pull-request instead as they can be easily declared using a specification file, and otherwise aren't affecting the core functionality.

Sorry for not having read the contribution guidelines first...
