### ISSUE TITLE
Solution files in subfolders of the .tmp folder are not ignored

### ISSUE THREAD

**Issue by bengtr** [nuke-build/nuke#634]
## **Description**

When a solution file exists anywhere inside a subfolder of the _.tmp_ folder (or any other folder starting with '.') it is being picked up and parsed. In our case, that  solution has multiple projects with the same GUID (don't ask us why, ask boost) and makes [SolutionsSerializer.GetGlobalSection](https://github.com/nuke-build/nuke/blob/3a2873864686781c216e4b71ebbaab2036da3c67/source/Nuke.Common/ProjectModel/SolutionSerializer.cs#L80) fail with an error when building the dictionary.

[CheckBuildProjectConfigurationsAttribute.OnAfterLogo](https://github.com/nuke-build/nuke/blob/3a2873864686781c216e4b71ebbaab2036da3c67/source/Nuke.Common/Execution/CheckBuildProjectConfigurationsAttribute.cs#L34) attempts to exclude directories starting with the character '.' but it will still pick up folders **inside** those folders.

For example, the call to
`rootDirectory.EnumerateDirectories("*", SearchOption.AllDirectories).Where(x => !x.Name.StartsWith(".") `
will make it not visit files in _.tmp_ itself, but _.tmp/boost_ is still examined. This is because DirectoryInfo.Name is 'boost', which  does not start with the character '.'
However, a parent folder does.

## **Steps to reproduce**

Add a subfolder into _.tmp_ with a random name not starting with '.' containing any file.

## **Current behavior**

The file is discovered in the search for solution files.

## **Expected behavior**

Any file and subdirectory in the _.tmp_ folder is ignored.

## **Suggested fix**

Filter all folders whose name start with the character '.' **or have any parent folder doing so** up until nuke root.

**Comment by ReedCopsey** [comment]
Out of curiosity, why was this closed as "wontfix"? @matkoch this is a true bug which is causing significant grief when working with some dependencies...

**Comment by matkoch** [comment]
@ReedCopsey I assume you're working together?

**Comment by matkoch** [comment]
1. Issue template not read
2. "multiple projects with the same GUID (don't ask us why, ask boost)"

**Comment by bengtr** [comment]
> 1. Issue template not read

I am not very experienced with GitHub, I hoped this would suffice and not be a reason to completely ignore the issue. I can re-file the issue if I can be certain it won't be closed immediately too. I'd also be willing to submit a PR to fix it if you acknowledge this is a bug.

> 2. "multiple projects with the same GUID (don't ask us why, ask boost)"

What's wrong with this if I may ask? We are dealing with a solution file from the boost library which is read by nuke, despite being in the .tmp folder, and results in a crash. That solution file is not made by us but by boost.

**Comment by matkoch** [comment]
1. The filed issue is fine. But the template says "starring the project is a requirement" .... Now this might sound ridiculous, but I just don't bother with issues if I see that the creator hasn't invested a minimal effort in reading it.
2. I literally stopped reading after "don't ask us why, ask boost" ..... I'm not here to dig into every problem that is thrown at me. Moreover, this is clearly a fault in boost.

Back to the issue. Feel free to open a PR. I'll see in which release I'm going to put that. As a side-note, you can also just remove the attribute from your build class.

**Comment by bengtr** [comment]
> Now this might sound ridiculous, but I just don't bother with issues if I see that the creator hasn't invested a minimal effort in reading it.

I don't want to argue but I gave you the exact point of failure and the reason for the failure so it is obvious we did invest some effort into it.

> 2. I literally stopped reading after "don't ask us why, ask boost" ..... I'm not here to dig into every problem that is thrown at me. Moreover, this is clearly a fault in boost.
> 

We are not asking to fix boost. We were asking whether the current behavior, namely nuke even detecting that solution, which Visual Studio reads perfectly fine by the way, is a bug. 

I am a little confused why this issue turned so hostile over minor things, we tried to help and not attack anyone.
Anyway, thanks for confirming this is a bug, that's all we wanted, We like nuke so we'll open a PR soon.

Edit: I now see the misunderstanding. The "don't ask us" thing was meant rhetorically. We didn't expect you to ask boost, just wanted to express that we have no idea why they did it that way. Sorry about that!

**Comment by matkoch** [comment]
Mh, you misunderstood. I'm not hostile, in fact I was very blunt when stating the reasons why. I just don't feel like investing any effort when I see effort wasn't spent on the other end (reading the issue template). And further I read that as being told what to do ("ask boost").

**Comment by matkoch** [comment]
Saw the edit just now. It's alright. And FYI, the first thing stated in the issue template is "starring the repo is a requirement". I see this as a minimal courtesy towards the work that went into the project. Anyways, all good now, feel free to send a PR.
