### ISSUE TITLE
EntitiyFrameworkTask needs fixes and updates for .NET 5

### ISSUE THREAD

**Issue by parc1vaL** [nuke-build/nuke#638]
### Description
Some of the tasks in the `EntityFrameworkTasks` need fixes to their configured properties. Examples include the 'DatabaseUpdate' task that has an invalid `DryRun` property that is not available in the `dotnet-ef` global tool ([reference](https://docs.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-database-update)). Other tasks and properties that were introduced with .NET 5 are not yet available in Nuke (examples: `dotnet ef migrations script` task, `dotnet ef database update --connection <value>` property)

### Steps to reproduce
Calling a target that contains
```
EntityFrameworkTasks.EntityFrameworkDatabaseUpdate(c => c.EnableDryRun());
```
will result in the error
```
Unrecognized option '--dry-run'.
```
### Relevant log output
```
NUKE Execution Engine version 5.0.2 (Linux,.NETCoreApp,Version=v2.1)
```

I have created an updated specification json file which I could provide as a PR, though I'm not entirely sure if any other changes except for the specification are required.

**Comment by matkoch** [comment]
PR would be appreciated. I'm closing this already.
