### ISSUE TITLE
Strange characters in console

### ISSUE THREAD

**Issue by peter-perot** [nuke-build/nuke#643]
### Steps to reproduce

1. Inject nuke into project (which can be an empty console application or something else): `nuke :setup`.
2. Run build.ps1 (or build.cmd, or debug in VS).

### Relevant log output

![image](https://user-images.githubusercontent.com/15671569/104173074-8b165b80-5405-11eb-9080-7cf8d7cd717c.png)

I tried to fiddle around with codepage settings, but I can't get Nuke to work.

What is wrong here?

**Comment by matkoch** [comment]
Can't reproduce
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/5005566/104204650-cc226600-542d-11eb-9995-a87fb346f6c0.png">

**Comment by peter-perot** [comment]
@matkoch, I see that you are using NUKE Execution Engine 1.0.0 - I use 5.0.2. Could you please try it with version 5.0.2?

It seems to me that the special characters of the "NUKE" logo do not work on my console output, but I didn't find a way to fix it. Even trying to explicitly set the encoding to UTF8 did not work.

In the meantime I asked a colleague of mine to reproduce it. Still waiting for his results.

**Comment by matkoch** [comment]
that's just my local development.. it's the same version

**Comment by peter-perot** [comment]
@matkoch NUKE works on the workstation of my colleague and it came out that he uses **Windows 10**  in contrast to me who uses Windows 8. Windows 10 uses UTF8 for the cmd.exe shown in the properties dialog of the console window, whereas the cmd.exe of Windows 8 doesn't show this information. I will update my system to Windows 10 to get over this issue.
