### ISSUE TITLE
API for git

### ISSUE THREAD

**Issue by oli-unreal** [nuke-build/nuke#646]
### Description

It would be awesome if there is an API to call git.

In my use case, I use GitVersion and the GitFlow, so I have automated semantic version number. I have a Ci task to create a release branch and a task to create the tag once the release is done and I would like to do it with nuke.

I am curious to know how it is done in nuke, manually?

**Comment by matkoch** [comment]
`GitTasks`

**Comment by oli-unreal** [comment]
Thanks, I am blind, I saw all other Git Api except the one I needed.
