### ISSUE TITLE
Generated build project for legacy solution not working

### ISSUE THREAD

**Issue by chaquotay** [nuke-build/nuke#650]
### Description

The generated NUKE build project for classic .NET framework / legacy project format solutions does not work due to several problems:

1. Missing reference to `Configuration.cs`
2. Wrong target framework version: 4.6.1 instead of 4.7.2
3. Broken version in Nuke.Common reference: `<Reference Include="Nuke.Common, Version=5.0.2MAJOR_MINOR_.0.0, Culture=neutral, processorArchitecture=MSIL">`

### Steps to reproduce

1. Create a fresh .NET project (.NET Framework 4.8)
2. Create NUKE build project with `nuke :setup --boot`
3. Select `.NET Framework/Mono` and `Legacy Format`, otherwise confirm defaults
4. Restore nuget packages in `build\packages.config`
5. Open solution in VisualStudio
6. Compile the generated NUKE build project

#### NUKE execution
```
> nuke :setup --boot
NUKE Global Tool version 5.0.2 (Windows,.NETCoreApp,Version=v2.1)
How should the build project be named?
¬  _build
Where should the build project be located?
¬  ./build
What bootstrapping method should be used?
¬  .NET Framework/Mono
What project format should be used?
¬  Legacy Format: supported by all MSBuild/Mono versions
Which NUKE version should be used?
¬  5.0.2 (latest release)
Which solution should be the default?
¬  NukeIt.sln
```

#### Compilation in VisualStudio

```
------ Build started: Project: _build, Configuration: Debug Any CPU ------
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Glob, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3106: Assembly strong name "Nuke.Common, Version=5.0.2MAJOR_MINOR_.0.0, Culture=neutral, processorArchitecture=MSIL" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3106: Assembly strong name "Nuke.Common, Version=5.0.2MAJOR_MINOR_.0.0, Culture=neutral, processorArchitecture=MSIL" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(3,7,3,11): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(4,7,4,11): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(5,7,5,11): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(6,7,6,11): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(7,7,7,11): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(8,7,8,11): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(9,7,9,11): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(10,14,10,18): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(11,14,11,18): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(12,14,12,18): error CS0246: The type or namespace name 'Nuke' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(15,15,15,24): error CS0246: The type or namespace name 'NukeBuild' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(14,2,14,33): error CS0246: The type or namespace name 'CheckBuildProjectConfigurationsAttribute' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(14,2,14,33): error CS0246: The type or namespace name 'CheckBuildProjectConfigurations' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(30,5,30,11): error CS0246: The type or namespace name 'Target' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(36,5,36,11): error CS0246: The type or namespace name 'Target' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(41,5,41,11): error CS0246: The type or namespace name 'Target' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(26,14,26,27): error CS0246: The type or namespace name 'Configuration' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(28,25,28,33): error CS0246: The type or namespace name 'Solution' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(25,6,25,15): error CS0246: The type or namespace name 'ParameterAttribute' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(25,6,25,15): error CS0246: The type or namespace name 'Parameter' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(28,6,28,14): error CS0246: The type or namespace name 'SolutionAttribute' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\stephan.mueller\source\repos\NukeIt\build\Build.cs(28,6,28,14): error CS0246: The type or namespace name 'Solution' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by matkoch** [comment]
Are you actually using such an old version of msbuild?

**Comment by matkoch** [comment]
And JFYI, a .NET Core build project can build .NET Framework projects.

**Comment by chaquotay** [comment]
I think not every developer at my company has .NET Core installed (we do mostly WinForms stuff), an since we are starting to migrate our old NAnt build scripts to NUKE it was at least a nice option to go this way.

**Comment by chaquotay** [comment]
My proposed pull request seems to be broken, have to check later.

**Comment by chaquotay** [comment]
If supporting this scenario isn't worth the hassle: that's of course totally fine, having to switch to .NET Core is no show-stopper for me. But I thought: since it seems to be supported, then why not give it a try.

**Comment by matkoch** [comment]
You don't need to have .NET Core installed. Either the build would download it, or you just have to have a new MSBuild version installed, which comes with VS2019 or even VS2017 (don't remember exactly).

**Comment by chaquotay** [comment]
Good point, forgot about that part of NUKE.

Are there any plans regarding the legacy support? Drop it completely and support .NET Core and SDK style projects only? Leave it in its current state? Fix it nevertheless?

Should I close this issue and the associated PR (totally fine with me)?

**Comment by GeorgDangl** [comment]
In my opinion, the legacy project format should not be supported. There's really no reason for that.

The solution itself can have any configuration you like, and for the build project you need either a recent MSBuild installed or let NUKE just download it's own runtime. So I don't see a scenario where this would add any benefit.

**Comment by matkoch** [comment]
It's currently hidden behind the `--boot` flag. Also described in the docs:

> By default, NUKE will use the .NET Core SDK as bootstrapping method. Passing the --boot parameter, will reveal .NET Framework/Mono as another option. Note that even with .NET Core SDK bootstrapping, the build will be able to compile projects targeting .NET Framework. For further comparison, the template scripts build.netcore.ps1/build.netcore.sh and build.netfx.ps1/build.netfx.sh can be checked.

I'm okay with merging the PR, but yes, this issue pops up every now and then. @chaquotay maybe the docs could be improved? What would've helped you to not assume that the legacy format is necessary?

**Comment by chaquotay** [comment]
@matkoch I know that I read that part of the documentation a few weeks ago, but I guess that I was so focused on legacy stuff (the actual projects and some of our existing build utilities use the classic .NET framework and non-SDK-style projects), so that I forgot about the way the NUKE bootstrapping mechanism works.

Maybe the docs could be improved a little, I'm not sure. Perhaps a new FAQ entry could help where it is explicitly stated that the project format and target framework of the NUKE build project are **completely independant** of the project format and target framework of the actual projects?

**Comment by matkoch** [comment]
Or we just remove the option between legacy and SDK-based project files? The [relevant package](https://www.nuget.org/packages/Nuke.MSBuildLocator/) has only a few downloads per day. And even that is not a 100% mapping to legacy format csprojs.

**Comment by chaquotay** [comment]
Given these low usage numbers it sounds like dropping legacy support might be the more sensible option.

**Comment by chaquotay** [comment]
Should I then prepare a new PR which removes the legacy support?
