### ISSUE TITLE
Could not find package 'ReportGenerator'

### ISSUE THREAD

**Issue by oli-unreal** [nuke-build/nuke#654]
### Description

Could not find package 'ReportGenerator' on windows, but works on linux. Workaround mention in https://github.com/nuke-build/nuke/issues/585 doesn't works since `ToolPathResolver.ExecutingAssemblyDirectory ` do not exist anymore.

### Steps to reproduce

1. I created a nuget package to call `ReportGeneratorTasks.ReportGenerator`
2. The nuget package doesn't reference ReportGenerator but the _build does
3. Calling `nuke :fix` will add `<PackageDownload Include="ReportGenerator" Version="[4.8.4]" />` thus I get this error: `Package 'ReportGenerator' is referenced with multiple versions. Use NuGetPackageResolver and SetToolPath.`
4. Calling: `./build.ps1 --target Test` will produce the following output

### Relevant log output

```
Assertion failed: Could not find package 'ReportGenerator' using:
 - Project assets file 'C:\builds\0\sdk\build\obj\project.assets.json'
 - NuGet packages config 'C:\builds\0\sdk\build\_build.csproj'
Run 'nuke :fix' to add missing references.
```

_build.csproj:
``` _build.csproj
<ItemGroup>
    <PackageReference Include="Eos.Client.Ci" Version="1.0.0-unstable0078" />
    <PackageReference Include="Nuke.Common" Version="5.0.2" />
    <PackageReference Include="ReportGenerator" Version="4.8.4" />
  </ItemGroup>
```

**Comment by matkoch** [comment]
Works as designed.

**Comment by oli-unreal** [comment]
<del>Do you have doc on the design?</del> Found out in the FAQ 
<del>On how to create a nuke nuget package?</del>
And why do it works on Linux but not on Windows?

**Comment by matkoch** [comment]
Sorry i don't have a linux machine, so can't comment on that.
