### ISSUE TITLE
CopyDirectoryRecursively fails for folders with similar names

### ISSUE THREAD

**Issue by arian2ashk** [nuke-build/nuke#656]
### Description
If you have two folders where one of the folder's name starts with the other folder name then you cannot copy the data between them. the exception thrown complains that "Target directory must not be in source directory" even though it is not. The issue is in the `public static bool IsDescendantPath(string basePath, string destinationPath)` function in `PathConstruction`. 

### Steps to reproduce
Use this code to see the exception.
```
      var folderPath = TemporaryDirectory / "folder";
      var folder2Path = TemporaryDirectory / "folder2";
      Directory.CreateDirectory(folderPath);
      Directory.CreateDirectory(folder2Path);
      FileSystemTasks.CopyDirectoryRecursively(folderPath, folder2Path);
```

### Relevant log output

```
Nuke.Common Version: 5.0.2

System.Exception
  HResult=0x80131500
  Message=Assertion failed: Target directory '...' must not be in source directory '...'.
  Source=Nuke.Common
  StackTrace:
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.Assert(Boolean condition, String text)
   at Nuke.Common.IO.FileSystemTasks.CopyDirectoryRecursively(String source, String target, DirectoryExistsPolicy directoryPolicy, FileExistsPolicy filePolicy, Func`2 excludeDirectory, Func`2 excludeFile)
```

**Comment by arian2ashk** [comment]
My suggestion for fixing it is to do something like this:
```
public static bool IsDescendantPath(string basePath, string destinationPath)
{
    return NormalizePath(destinationPath).StartsWith(NormalizePath(basePath) + GetSeparator(basePath));
}
```

**Comment by arian2ashk** [comment]
If my solution sounds ok I can make a PR for it.

**Comment by matkoch** [comment]
PR would be appreciated. I guess you need to use `.Split(s_allSeparators)` make the two collections equal in length, and then check `SequenceEquals` ... Could you also add a couple of tests (`Theory` + `InlineData`)?

**Comment by arian2ashk** [comment]
@matkoch Sure, I will also add tests.

**Comment by arian2ashk** [comment]
@matkoch I expanded on your idea by creating a new extension for sequence starts with. Here is my PR for this issue https://github.com/nuke-build/nuke/pull/658
