### ISSUE TITLE
ArgumentOutOfRangeException during :setup

### ISSUE THREAD

**Issue by andrewlock** [nuke-build/nuke#657]
### Description

I was going to try out nuke for a blog post, so I was following the instructions in the [getting started](https://nuke.build/docs/getting-started/setup.html) section. I installed the global tool, run `nuke :setup` , but got an `ArgumentOutOfRangeException` during setup.

> Note: I ran the command in [this directory](https://github.com/andrewlock/blog-examples/tree/master/BlazorPreRender/BlazorApp1) of my blog-examples repo. That directory only has a _single_ `.sln` file, but the setup process listed all the solutions in that repo - is that to be expected?

### Steps to reproduce

1. Install global tool `dotnet tool install Nuke.GlobalTool --global`
2. Open a console window with limited height
3. Run `nuke :setup` in a folder that contains many solutions (in parent folders)
4. Accept defaults until you get to `Which solution should be the default?` In my case, it listed all 60 solutions [in my repo](https://github.com/andrewlock/blog-examples/tree/master/BlazorPreRender/BlazorApp1) (though there was only 1 solution in the directory that I ran the command)
5. Pressing a cursor gives `ArgumentOutOfRangeException`:

On a hunch, I zoomed out my console, so I could fit all 60 solutions on the screen at once, and re-ran the setup process. This time it worked without a hitch 🎉

### Relevant log output

```csharp
ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -7.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.set_CursorTop(Int32 value)
   at Colorful.Console.set_CursorTop(Int32 value)
   at Nuke.Common.Utilities.ConsoleUtility.PromptForChoice[T](String question, ValueTuple`2[] options) in /Users/runner/work/nuke/nuke/source/Nuke.Common/Utilities/ConsoleUtility.cs:line 101
   at Nuke.GlobalTool.Program.Setup(String[] args, String rootDirectory, String buildScript) in /Users/runner/work/nuke/nuke/source/Nuke.GlobalTool/Program.Setup.cs:line 105
```

**Comment by matkoch** [comment]
Hi Andrew! Great to hear about the blog post plans! I hope this won't negatively affect it :) I'm actually already aware of the bug, but just wanted to wait until someone experiences it. I guess I will go with just limiting the number of presented solutions (`Take(5)`).

**Comment by matkoch** [comment]
I assume this is not blocking. I can soon push a hotfix, but would like to include some other fixes along the way. In any case, let me know if you discover any other issues.

**Comment by matkoch** [comment]
Oh, and I missed addressing the note: by default the setup assumes you want to have a single build per repo (it actually searches for `.git` and `.svn` directories). If you want to have the build more _local_, then you can just create an empty `.nuke` file in a particular directory. That will mark it as the root directory. Executing the setup afterwards will then skip searching for the VCS directories.

**Comment by andrewlock** [comment]
Hey @matkoch, thanks for the super quick reply! 

> I hope this won't negatively affect it :)

Of course not 🙂

> I assume this is not blocking.

Nope, not blocking at all, I worked around it by making my terminal font smaller! 

> If you want to have the build more local, then you can just create an empty .nuke file in a particular directory.

I think that's exactly what I wanted! Might be worth mentioning that on the setup page, or otherwise making that configurable in the `setup` task? I'm guessing it's not very common, but might be worth mentioning in the getting started docs at least?

Thanks again!

**Comment by matkoch** [comment]
I guess it's time to address this:

https://github.com/nuke-build/nuke/blob/develop/source/Nuke.GlobalTool/Program.cs#L25-L26

Will make a note for the docs. Thank you!

<blockquote><img src="https://repository-images.githubusercontent.com/93804681/cccf0d00-e1ab-11ea-8e53-d985c08819a3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>🏗 The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by andrewlock** [comment]
Awesome, appreciate all your efforts 😁
