### ISSUE TITLE
Option to specify Parameter Value

### ISSUE THREAD

**Issue by Nefarion** [nuke-build/nuke#660]
I have a "generic" Target Build, and it takes some required parameters.

```
Target Build => _ => _
    .Requires(() => ProjectName)
    ...
```

It would be nice to do something like this:
```
Target BuildServer => _ => _
    .With(() => ProjectName = "Server")
    .Inherit(Build) // or .Triggers()
    ...
```

I did not find a way for this, unless i change all the Requires() to OnlyWhenDynamic(), and then set the ProjectName in the `Executes `body

**Comment by matkoch** [comment]
Hi, I'm closing this due to the new contribution guidelines.
