### ISSUE TITLE
Code Generation documentation: link to outdated example for pipe-separated values

### ISSUE THREAD

**Issue by chaquotay** [nuke-build/nuke#671]
### Description

The example for `packageId` and `packageExecutable` receiving pipe-separated values no longer links to a specification with pipe-separated values (has changed to `customExecutable`).

### Steps to reproduce

1. Visit https://nuke.build/docs/writing-addons/code-generation.html
2. Click on the example link for "pipe-separated values" (https://github.com/matkoch/common/blob/develop/build/specifications/GitVersion.json#L10-L11)

**Comment by matkoch** [comment]
It hasn't changed, `customExecutable` is usually used when the executable name depends on x86/x64... links are fixed locally already, so gonna close.
