### ISSUE TITLE
Console font is changed to raster font on second nuke command

### ISSUE THREAD

**Issue by Cylox** [nuke-build/nuke#681]
### Description
Whenever I run a more than one nuke command the font of the console window gets changed to the old bitmap raster fonts. Per default I use the Consolas TT font.
Instead of explaining it a lot here is a video of the issue:
https://user-images.githubusercontent.com/5357159/109649206-e0e0c780-7b5b-11eb-98d0-7eedb27a23f4.mp4

I'm using Nuke 5.0.2.
I can issue other commands after the first nuke command and no font is changed. Only when I execute the second nuke command the font changes. 
You can see that the last characters of the last line written by nuke are not correctly displayed in the Consolas Font, but are displayed as soon as the font changes. It looks like an encoding issue. Does the invalid encoding maybe trigger some sort of console command to change the font?

### Steps to reproduce

1. Create C# Console app
2. Use nuke :setup, accept defaults
3. Add hello step:
    ```
    public Target Hello => _ => _.Executes(() => Logger.Normal("Hello World"));
    ```
4. Execute nuke hello command twice

### Relevant log output

See linked video

**Comment by matkoch** [comment]
Could you try with Windows Terminal?

**Comment by Cylox** [comment]
I have verified this happens both with powershell and cmd.exe which is not surprising because both are hosted by conhost.exe

**Comment by matkoch** [comment]
I'm talking about the actual Windows Terminal: https://github.com/microsoft/terminal

<blockquote><img src="https://repository-images.githubusercontent.com/100060912/dc77b180-764a-11e9-9e12-aace7d0ecd7d" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/microsoft/terminal">microsoft/terminal</a></strong></div><div>The new Windows Terminal and the original Windows console host, all in the same place! - microsoft/terminal</div></blockquote>

**Comment by Cylox** [comment]
The problem does not exist on the Windows Terminal. Didn't even know this existed :)

**Comment by matkoch** [comment]
Glad that it works. If you're fancy you can still check for a PR to fix it. There's only one place that sets the output encoding (BuildManager).

**Comment by matkoch** [comment]
And please give the repo a star :)
