### ISSUE TITLE
Support Execute Tragets Starting From Specifc Parent Target in the IDE/Plugin

### ISSUE THREAD

**Issue by AlBannaTechno** [nuke-build/nuke#682]
### Description
I Have the next build flow

```C#

    Target Clean => _ => _
        .Before(Restore)
        .Executes(() =>
        {
		//
        });

    Target Restore => _ => _
        .Executes(() =>
        {
		//
        });

    Target Compile => _ => _
        .DependsOn(Restore)
        .Executes(() =>
        {
		//
        });
    
    Target ProtectAllDlLs => _ => _
        .DependsOn(Compile)
        .Executes(() =>
        {
		//
        });
    
    Target ProtectStartupAndCombineAllProtected => _ => _
        .DependsOn(ProtectAllDlLs)
        .Executes(() =>
        {
		//
        });
    
    Target CleanupProtectedNonUsedArtifacts => _ => _
        .DependsOn(ProtectStartupAndCombineAllProtected)
        .Executes(() =>
        {
             //
        });

    Target CopyTheRestFiles => _ => _
        .DependsOn(CleanupProtectedNonUsedArtifacts)
        .Executes(() =>
        {
       		//
        });

```

Now, after the first time executing `CopyTheRestFiles` which will execute all its dependencies `parents`,
Suppose, I modified `ProtectAllDlLs ` logic, so, now I only need to execute  `ProtectAllDlLs ` to `CopyTheRestFiles `
But when I open the suggestions menu at `CopyTheRestFiles` in *Rider* I get

![2021-03-02_160828](https://user-images.githubusercontent.com/13814190/109660484-9702dc00-7b71-11eb-9dc6-5e6d153d50c6.png)

So, if there is an option that says, Run/Debug Started From 
`CleanupProtectedNonUsedArtifacts || ProtectStartupAndCombineAllProtected || ProtectAllDlLs  ...`
to be like this

![2021-03-02_160828_mod](https://user-images.githubusercontent.com/13814190/109662076-54da9a00-7b73-11eb-8a1f-af8f94b56856.png)

This will be very helpful.

### Alternatives

Just execute each target manually.

**Comment by matkoch** [comment]
Could be possible as a sponsored feature, but as of now I don't think i will approach it any time soon since it requires a lot of changes. Closing for now.

**Comment by AlBannaTechno** [comment]
@matkoch if the complete source of the plugin is available,` Java/Kotlin & C#` guide me to its location, and I will try to work on this feature,
I watched your video [Nuke — Designing a Build System with IDE Support in Mind](https://www.youtube.com/watch?v=N57Zjb5-08I) but can not figure where is the source code of the plugin,

Is the plugin not open-source, and if that, is it legal to decompile the code and modify it? or I will be enforced to create my own parser plugin to work on top of your Nuke-Plugin.

Another question, you said ` Closing for now.`, why not just mark it with `Postponed Feature`,  **Tag**, so may some sponsors think this is good and request it, or someone sees
it and work on it.

since, the closed issue gives an impression, that there is no longer work on this issue, so no one even needed to see it.! am I wrong?

**Comment by matkoch** [comment]
I closed because I'd like to keep the issue list concise and not full of issues I'll never get to work on. But you're right, I will reopen and add a label for sponsorships.

The source is currently not open, because I plan to develop some sponsor-only features. I can provide you with the source from a couple of months ago. Just send me a message. Just a warning though that I won't be able to help.

**Comment by AlBannaTechno** [comment]
Ok, i will send you a message on twitter with my gmail, 
But I want to know,
if I implemented this feature on the old code, **I will try to make it modular as I can,**
then I will send it to you, to copy / merge the solution here, to make it available for the community  in your version, do you will accept that ?

i have  a question , what do you means by `sponsor-only features`, who can ask for it `sure sponsers`, but who can use it ? `ALL || Sponsers(HOW)`

thank you for this awsome system.

**Comment by matkoch** [comment]
Giving this a little more thought, I think chances aren't good to actually merge it. I feel it doesn't scale very well, would need to take triggers into account, and is also limited in use.

My vision of this is to have a live graph as tool window shown where you can select targets and then hit the run button. Should be much more flexible. This is exactly the part that I will only offer to sponsors, but I don't have any specifics yet. It's not even implemented yet :)

**Comment by AlBannaTechno** [comment]
Yeah, this is a very great idea, but It more way complex in the implementation :(
But what you said is the right path, for this feature 👍

**Comment by matkoch** [comment]
@AlBannaTechno i'll close this again, it's not a way that I particularly want to go. Thanks for the discussion anyways.
