### ISSUE TITLE
HelmTasks does not contain `helm show chart`

### ISSUE THREAD

**Issue by winromulus** [nuke-build/nuke#683]
Hi,

Under HelmTasks there is no equivalent for `helm show chart [CHART] [flags]` (https://helm.sh/docs/helm/helm_show_chart/).

I don't have enough insight into `nuke` yet to add this, but I was under the impression that for tools such as `helm` the supported tasks are added automatically via some sort of discovery?

**Comment by matkoch** [comment]
Please check the issue template and contribution guidelines.

**Comment by winromulus** [comment]
GitHub did not load the templates when loading this. Closing as opened in #684 .
