### ISSUE TITLE
Support Helm Show Chart

### ISSUE THREAD

**Issue by winromulus** [nuke-build/nuke#684]
### Description
Under HelmTasks there is no equivalent for helm show chart [CHART] [flags] (https://helm.sh/docs/helm/helm_show_chart/).

I don't have enough insight into nuke yet to add this, but I was under the impression that for tools such as helm the supported tasks are added automatically via some sort of discovery?

### Alternatives
Currently using `Helm($"show chart {helmChartFileAbsolutePath}"` and parsing the output.

**Comment by matkoch** [comment]
I was referring to the contribution guidelines (https://github.com/nuke-build/.github/blob/master/.github/CONTRIBUTING.md#filing-issues), mostly looking at number 6 of the list. We don't take issues for missing CLI arguments, it would never scale.

**Comment by winromulus** [comment]
Ah, I understand. I will submit a PR for this once I get my bearings around the repository. Thank you.
