### ISSUE TITLE
Allow builds to be invoked with targets / parameters provided programatically

### ISSUE THREAD

**Issue by macsux** [nuke-build/nuke#685]
### Description
Currently it's not possible to invoke a build programmatically by specifying targets and parameters to use, because those are read directly from the process environment (`Environment.GetCommandLineArgs` and `Environment.GetEnvironmentVariables`). 

The use-case for this feature is providing an interactive mode for a building project that would allow building up targets to invoke and parameters to pass by promting user what they would like to accomplish. Nuke already does this to some degree for Required parameters.

Proposal is to add new override to `BuildManager.Execute`
```csharp
public static int Execute<T>(Expression<Func<T, Target>>[] invokedTargets, Action<T> onBuildInitialized)
```
The second parameter allows a configurator callback that sets the parameters after the build has initialized.

### Alternatives
The alternative is to allow a target to rebuild an execution plan with new targets. Example:
```csharp
Target Init => _ => _
    .Executes(() =>
    {
        var targetsToInvoke = new List<Expression<Func<Target>>>();
        if (Confirm("Do you want to setup Git?"))
        {
            targetsToInvoke.Add(() => InitializeGit);
            this.RemoteUrl = Prompt("What is the remote URL you want to publish to?"); // set parameter that will be used by new target
        }
        this.RebuildExecutionPlan(targetsToInvoke);
    });
```

The RebuildExecutionPlan would effectively abandon the current execution plan, and restart it with new targets.

**Comment by matkoch** [comment]
As discussed, there are a few other ways to solve this:

1. Restart build (https://github.com/nuke-build/nuke/blob/develop/build/Build.Enterprise.Enable.cs)
2. Put `Confirm` into `OnlyWhenDynamic`

The premise for not allowing to reorganize the execution plan is to have consistency between what was invoked, and what gets executed.

<blockquote><img src="https://repository-images.githubusercontent.com/93804681/cccf0d00-e1ab-11ea-8e53-d985c08819a3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>🏗 The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>
