### ISSUE TITLE
Parameter stay empty while debugging NUKE based build project

### ISSUE THREAD

**Issue by var-seven** [nuke-build/nuke#686]
### Description
If I try to debug my nuke generated build using Visual Studio Code and pass arguments via launch.json, the corresponding parameter definition in my Build.cs stays empty. Try to pass the arguments via dotnet MyBuild.dll --param value or via build.cmd --param value works as expected.

### Steps to reproduce

1. Create a new NUKE based project
2. Create a new parameter like
```csharp
[Parameter]
readonly string MyTestParam;
```
3. Edit launch.json and change key *args*
```json
"args": [
    "--my-test-param Foo"
],
```
4. Run the debugger and output the expected parameter
```csharp
Target Restore => _ => _
        .Executes(() =>
        {
            Logger.Info($"MyTestParam={this.MyTestParam}");
        });
```

I have also checked the defined arguments from launch.json passed correctly to the NUKE based build process. If I debug it and watch *Environment.GetCommandLineArgs()* I get an array with two elements. First is the executed DLL and second is *"--my-test-param Foo"*.
So I assumed that the problem should be NUKE rather than VSCode. 

### Relevant log output

This is the output while **debugging**

> NUKE Execution Engine version 5.0.2 (Windows,.NETCoreApp,Version=v2.1)
> 
> ╬════════════
> ║ Restore
> ╬═══
> 
> MyTestParam=

And this is the output while calling **build --my-test-param Bar**

> NUKE Execution Engine version 5.0.2 (Windows,.NETCoreApp,Version=v2.1)
> 
> 
> ╬════════════
> ║ Restore
> ╬═══
> 
> MyTestParam=Bar

I hope you can give me a hint in the right direction. Thanks.

**Comment by matkoch** [comment]
`args` is an array. it must be `[ "--param", "value" ]`. That's how arguments are passed from the command-line.

**Comment by var-seven** [comment]
I never thought of this simple variant, embarrassing (¬_¬ ) Thank you.
