### ISSUE TITLE
Support for JetBrains Rider 2021.1

### ISSUE THREAD

**Issue by Simonl9l** [nuke-build/nuke#690]
### Description
Please can you update support for latest Rider (currently EAP.6)
<img width="403" alt="image" src="https://user-images.githubusercontent.com/66816457/110225083-92526680-7e96-11eb-840f-d90982b05c26.png">

**Comment by matkoch** [comment]
Will be released with the 2021.1 release.

**Comment by Simonl9l** [comment]
Thanks - no preview to test with the EAP's - need to use that is there is a fix we need vs release version ?

**Comment by matkoch** [comment]
sry i don't understand the question?!

**Comment by Simonl9l** [comment]
will any previews of Nuke support an upcoming release version ever be available...since per your "Will be released with the 2021.1 release." comment, it is perhaps under development - via a nightly build or similar ?

**Comment by matkoch** [comment]
movie? no, i will upgrade what's necessary once the release is available.
