### ISSUE TITLE
Allow to create custom OutputSinks

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#699]
Currently, the public class `OutputSink` has `internal` abstract methods which are impossible to override except in Nuke assembly.

```
        internal abstract void WriteNormal(string text);
        internal abstract void WriteSuccess(string text);
        internal abstract void WriteTrace(string text);
        internal abstract void WriteInformation(string text);
```

In order to allow to create custom OutputSinks, those methods should be `protected internal`.

**Comment by matkoch** [comment]
https://github.com/nuke-build/nuke/pull/698#issuecomment-797857389
