### ISSUE TITLE
nuget.exe fails to restore packages for .build.csproj

### ISSUE THREAD

**Issue by abhinav2004** [nuke-build/nuke#7]
After running the powershell script nuget fails restore the packages for .build.csproj. I have setup nuke for .Net FW and legacy project structure.

```
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 4.3.0.
NuGet.exe is up to date.
MSBuild auto-detection: using msbuild version '15.3.409.57025' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
Cannot determine the packages folder to restore NuGet packages. Please specify either -PackagesDirectory or -SolutionDirectory.
The following call failed with exit code 1. ' & $NuGetFile restore $BuildProjectFile '
At <redacted>\build.ps1:31 char:32
+ ... de -ne 0) { throw "The following call failed with exit code $LastExit ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The following c...ldProjectFile ':String) [], RuntimeException
    + FullyQualifiedErrorId : The following call failed with exit code 1. ' & $NuGetFile restore $BuildProjectFile '
```

Am I missing something?

**Comment by matkoch** [comment]
@abhinav2004 I assume you have your solution file (sln) and the build.ps1 in different locations? That would be indeed a situation I didn't think of, when I recently cleaned up some parts of the bootstrapping.

What you're probably missing is the `-SolutionDirectory` flag for nuget.exe:

https://github.com/nuke-build/nuke/commit/7001502817a4e4457a49afd55bd42aedb968a2a8#diff-17bf411711a25aa07727e1ee506981afL16
https://github.com/nuke-build/nuke/commit/7001502817a4e4457a49afd55bd42aedb968a2a8#diff-17bf411711a25aa07727e1ee506981afL40

I can revert this change, but could you first check if this fixes the situation for you?

**Comment by abhinav2004** [comment]
@matkoch actually they are at the same location:

```
<redacted>@<redacted> MINGW64 ~/Workspace/<redacted> (<redacted>)
$ ls -al *.sln *.ps1
-rw-r--r-- 1 <redacted> 197121 7703 Oct  3 17:04 <redacted>.sln
-rw-r--r-- 1 <redacted> 197121 1922 Oct  3 17:04 build.ps1
```

I'll check if the fix given by you works and get back to you.

**Comment by matkoch** [comment]
Are you executing from a different working directory? As far as I know nuget.exe tries to find the solution file by walking up the current directory.

**Comment by abhinav2004** [comment]
I am executing it from where both the sln and ps1 files are.

**Comment by matkoch** [comment]
Maybe it finds more than one solution file? Anyway, I'm sure specifying that parameter will fix it.

**Comment by abhinav2004** [comment]
Actually there are submodules in the project which have their own solution files but they are down in the sub paths. The immediate solution is just outside the build folder. 

And yes the change did fix it somewhat but now I have dependency issues :(
I found out by manually restoring nuget packages.

```
Update-Package : Unable to resolve dependencies. 'Newtonsoft.Json 10.0.1' is not compatible with 'Nuke.Common 0.1.340 constraint: Newtonsoft.Json (>= 10.0.3)', 'Refit 4.0.1 constraint: 
Newtonsoft.Json (>= 10.0.3)'.
```

**Comment by matkoch** [comment]
I really don't like supporting the legacy format. But I will still try :) It's much more fragile than using the sdk-based project files.

In that case you could simply replace the version `10.0.1` with `10.0.3` in both - project file and packages.config.

**Comment by abhinav2004** [comment]
Yeah legacy can be a pain at times. I'll try that and see if it works.

**Comment by matkoch** [comment]
No chance you can install msbuild 15 or use netcore ?

**Comment by abhinav2004** [comment]
I am on msbuild 15. But need to use old .Net FW

**Comment by matkoch** [comment]
Then you should be able to use .NET Framework + SDK-based project file.

**Comment by abhinav2004** [comment]
Ok now I feel like an idiot. Thanks! The SDK based one worked without a hiccup.

**Comment by matkoch** [comment]
That sounds great :D Everything alright, much appreciated that you actually found 2 bugs :)
