### ISSUE TITLE
Execution plan legend description is wrong

### ISSUE THREAD

**Issue by mbenedykconfigit** [nuke-build/nuke#702]
*5.0.2

### Description
Execution plan legend description is wrong.

### Steps to reproduce

1. Run nuke with `--plan`
2. Look at legend: 
![image](https://user-images.githubusercontent.com/75312900/110642437-52032900-81b3-11eb-891b-855c18e37a81.png)
3. Arrows description is wrong, however description from [fundamentals](https://nuke.build/docs/running-builds/fundamentals.html) is correct

>The default target is highlighted in light-blue. Solid grey edges mark execution dependencies, dashed grey edges signal ordering dependencies and solid yellow lines indicate triggers.

![image](https://user-images.githubusercontent.com/75312900/110643970-eb7f0a80-81b4-11eb-9bdc-6df745133023.png)

**Comment by matkoch** [comment]
already fixed in branch
