### ISSUE TITLE
Errors when install resharper nuke support extension in VS 2019

### ISSUE THREAD

**Issue by pistotniks** [nuke-build/nuke#714]
I have tried to install the nuke support extension in VS 2019. I get the following 5 errors in the log (I also had to start the VS as administrator, otherwise I get permissions denied). I am attaching the file with a whole log.

[Gumezuz.txt](https://github.com/nuke-build/nuke/files/6149165/Gumezuz.txt)

When I look at the Build.cs I see the abilities to debug. But if I start to debug, the debugging does not stop at the breakpoint. It just opens the console window and runs to the end.

Install completed with 5 errors.
  13:58:41.649 ReSharperPlatformVs16_1f44c6d1: Error resolving type Microsoft.Azure.KeyVault.WebKey.JsonWebKey from assembly “Microsoft.Azure.KeyVault.WebKey, Version=3.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
  13:58:41.753 ReSharperPlatformVs16_1f44c6d1: Error resolving type System.Net.Http.HttpClient from assembly “System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
  13:58:41.788 ReSharperPlatformVs16_1f44c6d1: Error resolving type NuGet.Versioning.NuGetVersion from assembly “NuGet.Versioning, Version=5.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
  13:58:41.791 ReSharperPlatformVs16_1f44c6d1: Error resolving type NuGet.Versioning.NuGetVersion from assembly “NuGet.Versioning, Version=5.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
  13:58:41.795 ReSharperPlatformVs16_1f44c6d1: Error resolving type NuGet.Packaging.NuspecReader from assembly “NuGet.Packaging, Version=5.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.

**Comment by matkoch** [comment]
The errors are okay to have, and debugging works for me.
