### ISSUE TITLE
The colon ':' character is not supported in the value of required parameter.

### ISSUE THREAD

**Issue by vova-lantsov-dev** [nuke-build/nuke#715]
### Steps to reproduce
1. Create the following target:
```c#
[Parameter("Absolute path to directory")]
readonly string PathToDirectory;

Target DoWork => _ => _
    .Requires(() => PathToDirectory)
    .Executes(() => { } );
```
2. Run `nuke DoWork` (without specifying of `--path-to-directory` CLI parameter)
3. You will be asked to input the string.
4. Copy any windows path (for example `C:\files\any-file.txt`.
5. Paste this path to the cmd.
6. You will see that `:` is missed. You can't even type it manually, by pressing the corresponding button on keyboard. The real pasted text is:
`C\files\any-file.txt`

#### Workaround
Set the parameter manually via command line:
`nuke DoWork --path-to-directory "C:\files\any-file.txt"`

### Relevant log output
Nuke 5.0.2, latest version of command line package installed by `nuke :fix`
Win 10 x64
.NET Core 3.1

**Comment by matkoch** [comment]
#536
