### ISSUE TITLE
Cake to Nuke Conversion

### ISSUE THREAD

**Issue by corey-underdown** [nuke-build/nuke#716]
### Description

At Octopus Deploy, we have well over 100 different projects using Cake that we want to be able to convert to Nuke. We've chosen Nuke as our new standard for new projects, and we are slowly converting old projects over from Cake.  We're looking for a tool that can convert the Cake files we have for each project to a Nuke file as accurately as possible to cut down on the time it'll take to migrate from Cake. 

We have fairly simple cake files like [Sashimi.AzureAppService](https://github.com/OctopusDeploy/Sashimi.AzureAppService/blob/main/build.cake), a little more complex like [Calamari](https://github.com/OctopusDeploy/Calamari/blob/master/build.cake), and we have fairly complex ones like Octopus Deploy product itself. We don't expect a tool can convert perfectly more complex ones, but we'd like it to give up a good step up and only require us to convert a small remaining part rather than the whole thing. 

### Alternatives

We are migrating them one by one by hand currently. This is a good way to become familiar with Nuke and understand it better, however it'll take a large amount of time to convert all projects over.

**Comment by cmenzi** [comment]
We have just created a nuke-it.ps1 for this. If you like I can share it.

**Comment by matkoch** [comment]
A converter will be included in the 5.1.0 release (already available as prerelease). It includes conversion of:

- Target definitions
- Default targets
- Parameter declarations
- Absolute paths
- Globbing patterns
- Tool invocations (dotnet CLI, SignTool)
- Addin and tool references
