### ISSUE TITLE
Add support for multiple loggers in DotNetTest

### ISSUE THREAD

**Issue by sevenate** [nuke-build/nuke#721]
### Description

`dotnet test` tool [support](https://github.com/microsoft/vstest/issues/2368) multiple loggers as parameters, so that you can have, say, both **trx** and **html** test results generated after single run:

    dotnet test --logger:"trx;LogFileName=foo.trx" --logger:"html;LogFileName=foo.html"

`DotNetTest` task also supports logger, but only one:

    DotNetTest(o => o
        .SetProjectFile(RootDirectory / "foo.tests" / "foo.tests.csproj")
        .SetDataCollector("XPlat Code Coverage")
        .EnableCollectCoverage()
        .SetResultsDirectory(RootDirectory / "tests")
        .SetLogger("trx;LogFileName=foo.trx")
        .SetLogger("html;LogFileName=foo.html") // the second logger will override the first one
        .EnableNoBuild()
        .EnableNoRestore()
    );

It would be nice if you could specify multiple loggers with new tool settings API extension method **SetLoggers()**:

    SetLoggers(this T toolSettings, IEnumerable<string> loggers)

like this:

    DotNetTest(o => o
        .SetProjectFile(RootDirectory / "foo.tests" / "foo.tests.csproj")
        .SetDataCollector("XPlat Code Coverage")
        .EnableCollectCoverage()
        .SetResultsDirectory(RootDirectory / "tests")
        .SetLoggers("trx;LogFileName=foo.trx", "html;LogFileName=foo.html")
        .EnableNoBuild()
        .EnableNoRestore()
    );

### Current Workaround

    DotNet("test foo.tests/foo.tests.csproj --collect:\"XPlat Code Coverage\" --results-directory:\"tests\" --logger:\"trx;logFileName=foo.tests.trx\" --logger:\"html;logFileName=foo.tests.html\" --no-build --no-restore --nologo");

**Comment by sevenate** [comment]
Geez, that was fast, thanks, man! 👍🏻

**Comment by sevenate** [comment]
![image](https://user-images.githubusercontent.com/1175845/112392931-7aad1780-8cb7-11eb-9037-107485d94638.png)

![image](https://user-images.githubusercontent.com/1175845/112392966-84cf1600-8cb7-11eb-866f-0436d3724b0f.png)

🎆 and 🎉 eh?

No pressure, though 😉

**Comment by matkoch** [comment]
I wonder why the ones that are sponsoring are always the most patient people.

"No pressure" doesn't make it better... it's a very unnecessary comment...

**Comment by sevenate** [comment]
Don't take it to close to the heart, man, as it was merely a kidding nod. I do appreciate your work greatly and also have more patience than it might looks like (speaking of which it is not always as you put it - some people tend to think that if they are paying for something that fact gives them some rights to ask or even demand something while others may really appreciate free open source software and be ready to wait as long as it takes to finish something).

As for the timeline - you put this "will be published when the goal of 20 sponsors is reached" yourself instead of any due date (which are also not obligatory, of cause), so for a complete stranger who just landed on your project and have no idea whether this goal was reached yesterday or a year ago it seems reasonable to wonder if you have any more specific time window in mind for the next release, considering that the condition you've committed yourself to seems to be already met (it usually doesn't hurt to just ask, does it?). And if you don't have any more specific release date in mind yet - that is totally fine too - you can just say so. This is open source world after all and nobody will ever press you to give out any ETAs 😇

Apology if I didn't quite worded this thought clearly in my previous comment ☮
