### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by nikoudel** [nuke-build/nuke#725]
As the https://nuke.build/ site appears to be down ATM, can you consider writing a short getting started section here in Github?
Just the basics, i.e. how to create a project and run a target from command line...

![image](https://user-images.githubusercontent.com/1636683/112532959-1b7ffd80-8db2-11eb-8ad1-5ed849cc0a28.png)

**Comment by matkoch** [comment]
not really

**Comment by nikoudel** [comment]
It's back up, cool!

Here's a [nice intro](https://blog.codingmilitia.com/2020/10/24/2020-10-24-setting-up-a-build-with-nuke/), just in case...
