### ISSUE TITLE
[5.1.0-beta0001] Collective Target incorrectly caused NotSupportedException in The WriteSummaryTable()

### ISSUE THREAD

**Issue by ilharp** [nuke-build/nuke#728]
### Description

The `WriteSummaryTable()` function throws `System.NotSupportedException: Collective` when build project has Collective Target.

### Steps to reproduce

```cs
Target NukeTestA => _ => _
    .Executes(() => {});

Target NukeTestB => _ => _
    .DependsOn(NukeTestA);
```

Run `NukeTestB` and it BOOMs.

Also, you can see [this GitHub Action run](https://github.com/Ruminoid/Toolbox/actions/runs/711520878) which is run with `--verbosity Verbose`.

### Relevant log output

```
Unhandled exception. System.NotSupportedException: Collective
   at Nuke.Common.OutputSinks.OutputSink.WriteSummaryTable(NukeBuild build)
   at Nuke.Common.OutputSinks.OutputSink.WriteSummary(NukeBuild build)
   at Nuke.Common.Execution.BuildManager.<>c__DisplayClass5_0`1.<Execute>g__Finish|5()
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
   at Nuke.Common.NukeBuild.Execute[T](Expression`1[] defaultTargetExpressions)
   at Build.Main()
```

### Commit which caused this

[d17cd03e](https://github.com/nuke-build/nuke/commit/d17cd03e9458aa163045dfd56067a6f1d25c50c5#diff-6f70b2afd85c904c5c78d9a821eda55d9bacb3071d40c80b4bb2ce4975383285R195-R196)

### Pull Request to fix this

#729

### By the way...

NUKE is a great project! Thanks to NUKE, I can implement complex operations in CI such as downloading tools and packing installers. Thanks for your great work.

I'm Chinese and I'd be happy to contribute to the zh-CN document project of Nuke. If there will be any open source repo doing this, please let me know then.

**Comment by matkoch** [comment]
Regarding the translation, could you send me a message to ithrowexceptions@gmail.com ?

**Comment by matkoch** [comment]
For the moment being, just add an empty Executes block to the collective target.
