### ISSUE TITLE
Improve netstandard check for defining NETCORE compiler constant.

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#73]
We wish for something like `StartsWith`.

https://github.com/nuke-build/nuke/blob/88f134db3e80fc9c8dbb13ea468279ff1047aeb9/shared/Configuration.props#L11

**Comment by GeorgDangl** [comment]
Something like in this SO answer?  
https://stackoverflow.com/a/10784815/4190785

**Comment by arodus** [comment]
maybe something like `<PropertyGroup Condition="'$(TargetFramework.Substring(0,11))' == 'netstandard' OR '$(TargetFramework.Substring(0,10))' == 'netcoreapp'">`
