### ISSUE TITLE
Documentation outdated after release 5.1.0

### ISSUE THREAD

**Issue by zplan** [nuke-build/nuke#732]
With release 5.1.0 the .nuke file changed to a directory.

The documentation seems outdated now:
https://nuke.build/docs/getting-started/setup.html

Where do I have to specify now the default solution which was in the .nuke file before?
Here I guess:
.nuke\parameters.json:

{
  "$schema": "./build.schema.json",
  "Solution": "MySolution.sln"
}

Please update the docu together with the release. Thanks

**Comment by matkoch** [comment]
please read the issue template
