### ISSUE TITLE
 error MSB3491: Could not write lines to file "obj\lp:NoSummary\_build.GeneratedMSBuildEditorConfig.editorconfig"

### ISSUE THREAD

**Issue by seayxu** [nuke-build/nuke#747]
### Version

5.1.1

### Relevant Code / Invocations

```code
NUKE Global Tool version 5.1.1 (Windows,.NETCoreApp,Version=v2.1)
How should the build project be named?
?  _build
Where should the build project be located?
?  ./build
Which NUKE version should be used?
?  5.1.1 (latest prerelease)
Which solution should be the default?
?  ConsoleApp7.sln
Do you need help getting started with a basic build?
?  Yes, get me started!
Restore, compile, pack using ...
?  MSBuild/Mono
Source files are located in ...
?  ./src
Move packages to ...
?  ./artifacts
Where do test projects go?
?  ./tests
Do you use GitVersion?
?  No, custom versioning
Creating directory 'C:\Users\seay\Source\Repos\ConsoleApp7\.nuke'...
Creating directory 'C:\Users\seay\Source\Repos\ConsoleApp7\build'...
```

### Expected Behavior

run nuke build

### What actually happened?

C:\Program Files\dotnet\sdk\6.0.100-preview.1.21103.13\Roslyn\Microsoft.Managed.Core.targets(150,5): error MSB3491: Could not write lines to file "obj\lp:NoSummary\_build.GeneratedMSBuildEditorConfig.editorconfig". The directory name is invalid. : 'C:\Users\seay\Source\Repos\ConsoleApp7\build\obj\lp:NoSummary' [C:\Users\seay\Source\Repos\ConsoleApp7\build\_build.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.1.21103.13\Microsoft.Common.CurrentVersion.targets(5472,5): error MSB3191: Unable to create directory "obj\lp:NoSummary\". The directory name is invalid. : 'C:\Users\seay\Source\Repos\ConsoleApp7\build\obj\lp:NoSummary\' [C:\Users\seay\Source\Repos\ConsoleApp7\build\_build.csproj]
    6 Warning(s)
    2 Error(s)

Time Elapsed 00:00:01.28

### Anything else we should know?

It is normal to run the` _build` project directly

**Comment by matkoch** [comment]
Please provide a repro. The setup doesn't seem much relevant.

**Comment by seayxu** [comment]
@matkoch This repo  [NukeTest](https://github.com/seayxu/NukeTest)

**Comment by matkoch** [comment]
Works on 5.0.200

**Comment by seayxu** [comment]
not support net6.0-preview

**Comment by matkoch** [comment]
you can test and track against dotnet preview versions, but I won't
