### ISSUE TITLE
AzurePipelinesAttribute - allow to set `pool name` from attribute

### ISSUE THREAD

**Issue by rafek1241** [nuke-build/nuke#749]
### Description

```
pool:
  name: 'XXX' <- this one cannot be set at all
  vmImage: 'ubuntu-latest' <-- this one can be set currently via AzurePipelinesImage enum
```

### Usage Example

```code
[AzurePipelines(
    AzurePipelinesImage.UbuntuLatest,
    PoolName = "elo" //<- new
    AutoGenerate = true,
    InvokedTargets = new[] { nameof(ContinousIntegration) },
    TriggerBranchesExclude = new[] { "master" }
)]
```

### Alternative

None

**Comment by matkoch** [comment]
@rafek1241 have you read the issue template?

**Comment by rafek1241** [comment]
@matkoch 
Yes, I read about sponsorship requirement (are you talking about that one?). I will do this in spare time.

**Comment by matkoch** [comment]
what do you mean spare time?

**Comment by rafek1241** [comment]
Oh, my bad. I mean I will do this change after working hours.

**Comment by matkoch** [comment]
Unfortunately that doesn't change the fact :) It's about my time.

**Comment by guillaume86** [comment]
@matkoch forgive me if I'm missing something obvious, but I don't really get what happened here, can you explain?
I looked at the issue template for feature suggestions and did not see anything about sponsorships.
I'm evaluating nuke for my project but I would need this feature if I decide to go ahead, I could probably submit a PR if it's OK'd.

**Comment by matkoch** [comment]
I've relaxed the rules a bit, but I'm still very occupied with a lot of other things currently. So definitely take this into account.

**Comment by guillaume86** [comment]
Ha ok, thanks for your reply I'll keep this in mind.
