### ISSUE TITLE
Add OnlyWhen parameter to specify time of evaluation

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#75]
Currently, conditions provided via `OnlyWhen` are checked exactly prior to execution of a target. Another use-case is to check those during dependency resolution, so that we allow to skip targets, which are dependencies for a skipped target.

Proposal:
```
ITargetDefinition OnlyWhen(Func<bool> predicate, CheckBefore checkMode);

enum CheckBefore
{
  ThisTarget,
  AllTargets
}
```

To be defined. What to do with the existing `OnlyWhen` method? Deprecate? Default to `CheckBefore.ThisTarget` ?

**Comment by arodus** [comment]
We shouldn't mix **'when the condition is evaluated'** and **'should the dependencies also be skipped'**. I think it's better to introduce two new parameters:
- `CheckBefore` which defines when the condition should be evaluated
- Something like `DependencyBehaviour` which defines if the dependent targets should be skipped.

**Comment by arodus** [comment]
Implemented in and https://github.com/nuke-build/nuke/commit/e0cef674c7173b7527b34b7d9b8caf67fd100ea8.
