### ISSUE TITLE
Source code generation fails in 5.1.1

### ISSUE THREAD

**Issue by ThatSlacker** [nuke-build/nuke#752]
### Usage Information

Nuke 5.1.1 / .NET Framework 4.7.2 / Windows 10

### Relevant Code / Invocations

```code
When the source code generator is called and StronglyTypedSolutionGenerator is invoked we run into problems with TryGetRootDirectoryFrom.  There are two things that seem like they could be causing this:

* We're including source files from a folder outside of the project folder (e.g.  C:\source\project\..\..\common\common.cs).
* We're using the --root parameter when we launch the executable and as such there's no .nuke folder in the project directory structure (upgrading from version 0.25 where that wasn't a requirement)

The build fails with the message "AbsolutePath != null" in \Nuke.SourceGenerators\StronglyTypedSolutionGenerator.cs since it can't find a .nuke folder or file in the directory structure for the first file path in the syntax tree:

return Constants.TryGetRootDirectoryFrom(startDirectory).NotNull();

```

### Expected Behavior

The build should be able to handle source files that are not in the project folder.  Ideally I'd also like to be able to build without a .nuke folder in the project hierarchy but that's just preference and I understand if that's a hard requirement. 

Previously we would build the .exe, point it at a content output folder, and it would create the .nuke temporary directory there.  That would maintain the logs and build output for the piece of content in a content specific folder.

By creating a .nuke folder in each project folder and modifying StronglyTypedSolutionGenerator.cs to skip any files that have ".." in the file path (as a quick test) I was able to build.  Doing only one of those two wasn't enough to solve the issue.

### What actually happened?

The build fails with the error:

CSC : error CS8785: Generator 'StronglyTypedSolutionGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'Exception' with message 'AbsolutePath != null'

### Stacktrace / Log

```code
CSC : error CS8785: Generator 'StronglyTypedSolutionGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'Exception' with message 'AbsolutePath != null'
```

**Comment by matkoch** [comment]
Thanks for the detailed report and the sponsorship! I'll check on this as soon as possible.

**Comment by dennisdoomen** [comment]
Did you fix this somehow?

**Comment by matkoch** [comment]
See milestone?! 😄

**Comment by dennisdoomen** [comment]
Yeah, but I didn't see a PR attached to it, so I was unsure.

**Comment by matkoch** [comment]
If it's assigned to a milestone, it was handled
