### ISSUE TITLE
ReSharper plugin: Install completed with 5 errors

### ISSUE THREAD

**Issue by genu4a** [nuke-build/nuke#759]
### Usage Information

2021.1.0

### Expected Behavior

Installation of "Nuke Support" plugin completes fine

### What actually happened?

The plugin actually works. Only installation of "Nuke Support" plugin (or ReSharper update with plugin installed) completes with errors. 
Visual Studio 16.10.1

### Stacktrace / Log

```code
13:19:55.618 |I| ReadyToInstallPage            | Install completed with 5 errors.
13:19:55.618 |I| ReadyToInstallPage            |   13:19:50.232 ReSharperPlatformVs16_442531f6: Error resolving type Microsoft.Azure.KeyVault.WebKey.JsonWebKey from assembly “Microsoft.Azure.KeyVault.WebKey, Version=3.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
13:19:55.618 |I| ReadyToInstallPage            |   13:19:50.266 ReSharperPlatformVs16_442531f6: Error resolving type System.Net.Http.HttpClient from assembly “System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
13:19:55.618 |I| ReadyToInstallPage            |   13:19:50.268 ReSharperPlatformVs16_442531f6: Error resolving type NuGet.Versioning.NuGetVersion from assembly “NuGet.Versioning, Version=5.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
13:19:55.618 |I| ReadyToInstallPage            |   13:19:50.269 ReSharperPlatformVs16_442531f6: Error resolving type NuGet.Versioning.NuGetVersion from assembly “NuGet.Versioning, Version=5.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
13:19:55.618 |I| ReadyToInstallPage            |   13:19:50.271 ReSharperPlatformVs16_442531f6: Error resolving type NuGet.Packaging.NuspecReader from assembly “NuGet.Packaging, Version=5.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”, request originating from assembly “Nuke.Common, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
```

**Comment by pgrawehr** [comment]
Unfortunately, things just got worse: With the latest resharper version (2021.3.2) an installed Nuke extension prevents the upgrade of Resharper. One has to uninstall the Nuke plugin or Resharper will show an installation error during update. 

I was trying to update because previously, the Nuke plugin wouldn't work any more. The icon next to the build tasks was there, but clicking any of the options would just not do anything. Couldn't get it to run neither in VS2019 nor 2022 any more.

**Comment by matkoch** [comment]
@pgrawehr this is a different issue that is already fixed in branch.

**Comment by pgrawehr** [comment]
@matkoch Do you mean the resharper update was fixed or the "plugin doesn't work" issue? And which version will include the fix?

**Comment by matkoch** [comment]
The latter. The next version will include the fix.

**Comment by MPleskunina** [comment]
Still getting installation errors, ReSharper Nuke 2021.3.0.

**Comment by matkoch** [comment]
**For the record, the plugin works even though there are errors during installation.**

**Comment by Dessyreqt** [comment]
The plugin does not seem to work, when I try to run a target from the sidebar the icon just disappears and nothing happens.
![image](https://user-images.githubusercontent.com/12574786/182941784-adc1937a-0aad-454b-89db-88eac127aead.png)
![image](https://user-images.githubusercontent.com/12574786/182941823-fc892fa0-da16-4478-90da-e0082c2f74df.png)

**Comment by matkoch** [comment]
@Dessyreqt not related to the original issue here. if you create a new issue, please attach a repro solution.

**Comment by Dessyreqt** [comment]
Please see https://resharper-support.jetbrains.com/hc/en-us/requests/4199031, as I have posted logs of my install there. Your comment "For the record, the plugin works even though there are errors during installation." is inaccurate as after the install I have experienced symptoms I detailed above, for every solution I have tried. One such solution can be found at https://github.com/Dessyreqt/HeliosDiscordBot, but it occurs for many others.
