### ISSUE TITLE
Interactive mode for parameters

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#76]
When executing a build locally (`HostType == Console`), we could initialize parameters like `ApiKey` or `Password` via console input. It is important to [mask out passwords](https://stackoverflow.com/questions/3404421/password-masking-console-application).

Interactive input is only possible for properties/fields without property/field initialization.

**Comment by matkoch** [comment]
To be defined is, whether we should introduce a new attribute for this. Should we mask out everything? Even if it's a username? Probably not. Entering the username without mask is okay for instance.

```
[Parameter(Interactive = InputType.Normal)] readonly string Username;
[Parameter(Interactive = InputType.Password)] readonly string Password;
```

**Comment by lt-gerjan** [comment]
I like this feature. what I would like to add is questions phrases (`Question = ""`) to parameters so you can create the following:

```
Welcome to Nuke build
> Which target do you want to execute?
(select from a list of available targets): Compile
> Which configuration?
(list configurations): Release
> Do you want to run a specific project (custom parameter of my build)
(list all projects): MyProject
```

If you want to achieve the list/autocompletion you also need to specify that for the parameters (`PossibleValues/SuggestionList = list`) or something, but I guess that not possible with attributes (not compile time)
