### ISSUE TITLE
GitLab is not detected as Host if jenkins is installed

### ISSUE THREAD

**Issue by Schreini** [nuke-build/nuke#760]
### Usage Information

Nuke 5.2.1 / OS is Windows

### Relevant Code / Invocations

```code
var instance = Host.Instance;
Logger.Info($"Instance: {instance}; name: '{instance?.GetType()}'");
```

### Expected Behavior

GitLab should be logged

### What actually happened?

Jenkins is logged

### Stacktrace / Log

```code
Instance: Nuke.Common.CI.Jenkins.Jenkins; name: 'Nuke.Common.CI.Jenkins.Jenkins'
```

### Anything else we should know?

We are in the process of moving CI from Jenkins to GitLab self hosted. So on our BuildServer we have Jenkins AND a GitLab runner installed. When the Pipeline is executed in GitLab we get Jenkins as a Host.

**Comment by GeorgDangl** [comment]
That's curious. @Schreini, have you checked the implementation of how the host type is detected? Maybe that's done via some environment variables and that's what's causing the false positive here?

**Comment by Schreini** [comment]
Jenkins is detected by looking for the JENKINS_HOME environment variable. For GitLab it is the GITLAB_CI environment variable. So it is a matter of order which check runs first. But changing this might break things for others.

For now I have a workaround by specifying GitLab as the host in the gitlab-ci.yml
