### ISSUE TITLE
Expose "PropertyInfo Target" on ITargetDefinition

### ISSUE THREAD

**Issue by amoerie** [nuke-build/nuke#762]
### Description

Hi! I'm using NUKE Build to automate my local dev environment, and so far it's been really great!

I did run into a specific pickle, which I'll try to explain: some of my targets take a while (building large .NET projects, configuring RabbitMQ, etc.) and even if everything is already done and configured, just checking if everything is okay takes a while. That's why I introduced an extension to `ITargetDefinition` called `ExecutesOnceDaily`, which - as the name implies - only executes the target if _it hasn't already executed yet today_.

Usage looks like this:

```csharp
private Target ConfigureRabbitMQ => _ => _
            .ExecutesOnceDaily(async () => { ... });
```

To implement this extension, I'm writing a JSON file that keeps track of which targets were executed by ExecutesOnceDaily, and to do so I need access to the name of the target that is currently executing. 

I snooped around a bit in the code, and found that `ITargetDefinition` is implemented by an internal class `TargetDefinition` which has a public property called `Target` of type `PropertyInfo`! That's exactly what I need!

If there's a better way of obtaining this information, please let me know!

So now I'm doing this:

```csharp
private static readonly PropertyInfo InternalTargetProperty = typeof(ITargetDefinition).Assembly
    .GetTypes()
    .Single(t => t.IsAssignableTo(typeof(ITargetDefinition)) && t.Name == "TargetDefinition")
    .GetProperty("Target", typeof(PropertyInfo))
    ?? throw new InvalidOperationException("Oh noes! " +
                                           "Nuke Build changed their internal TargetDefinition class so it no longer exposes the Target info :(");

private static string GetTargetName(ITargetDefinition targetDefinition)
{
    var targetPropertyInfo = InternalTargetProperty.GetValue(targetDefinition) as PropertyInfo;

    if (targetPropertyInfo == null)
    {
        throw new InvalidOperationException("Failed to extract Target property info from NUKE target definition :(");
    }

    return targetPropertyInfo.Name;
}
     
public static ITargetDefinition ExecutesOnceDaily(this ITargetDefinition targetDefinition, Action action)
{
    var name = GetTargetName(targetDefinition);
    return targetDefinition.Executes(() =>
    {
          if(!AlreadyExecutedToday(name))
          {
              action();
          }
          UpdateExecutionJsonFile(name);
    }
}
```

So, that was a long explanation for how I would propose to add that property to ITargetDefinition, so it's much easier and less fragile to use that information. I'm not sure if my use case is unique, but I think it could help other people making NUKE build extensions too.

I am willing to make a pull request if you would consider it. 

### Usage Example

My code would change to:

```csharp
public static ITargetDefinition ExecutesOnceDaily(this ITargetDefinition targetDefinition, Action action)
{
    var name = targetDefinition.Target.Name;
    return targetDefinition.Executes(() =>
    {
          if(!AlreadyExecutedToday(name))
          {
              action();
          }
          UpdateExecutionJsonFile(name);
    }
}
```

### Alternative

I have to do brittle reflection to extract the target name

```csharp
private static readonly PropertyInfo InternalTargetProperty = typeof(ITargetDefinition).Assembly
    .GetTypes()
    .Single(t => t.IsAssignableTo(typeof(ITargetDefinition)) && t.Name == "TargetDefinition")
    .GetProperty("Target", typeof(PropertyInfo))
    ?? throw new InvalidOperationException("Oh noes! " +
                                           "Nuke Build changed their internal TargetDefinition class so it no longer exposes the Target info :(");

private static string GetTargetName(ITargetDefinition targetDefinition)
{
    var targetPropertyInfo = InternalTargetProperty.GetValue(targetDefinition) as PropertyInfo;

    if (targetPropertyInfo == null)
    {
        throw new InvalidOperationException("Failed to extract Target property info from NUKE target definition :(");
    }

    return targetPropertyInfo.Name;
}
```

**Comment by matkoch** [comment]
Have you seen these?
![B6550A16-9FE7-4AC4-832D-56B42312030B](https://user-images.githubusercontent.com/5005566/123948190-7755b600-d9a1-11eb-9b06-a60d722d5c7a.jpeg)
![9C087FBB-5EAD-4B3B-80CB-33CBD6BA618E](https://user-images.githubusercontent.com/5005566/123948214-7c1a6a00-d9a1-11eb-9faa-35cde6d80856.jpeg)

**Comment by amoerie** [comment]
@matkoch I did read and see that. I was hoping that if I was making the PR it would be okay to suggest it here. 

My sincere apologies, I didn't mean to offend, I'll take this to Slack then.

**Comment by matkoch** [comment]
@rCartoux I saw your downvote during my preparation for the next release. If you have any suggestions on how I can create guidelines that are clear for everyone, I'm open to hearing about them.
