### ISSUE TITLE
Nuke does not work in single-file executable

### ISSUE THREAD

**Issue by tyb-dev** [nuke-build/nuke#764]
### Usage Information

5.2.1 / .NET 5 / Windows/Linux

### Relevant Code / Invocations

```code
Any nuke-based build will suffer from this error due to an exception in static constructor of NukeBuild.
```

### Expected Behavior

Publish nuke as single-file executable should work without an exception.

### What actually happened?

An exception is thrown.

### Stacktrace / Log

```code
Unhandled exception. System.TypeInitializationException: The type initializer for 'Nuke.Common.NukeBuild' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Nuke.Common.EnvironmentInfo' threw an exception.
 ---> System.Exception: Assertion failed: System.String != null
   at Nuke.Common.ControlFlow.Fail(String text, Exception exception)
   at Nuke.Common.EnvironmentInfo.GetSurrogateArguments()
   at Nuke.Common.EnvironmentInfo..cctor()
   --- End of inner exception stack trace ---
   at Nuke.Common.EnvironmentInfo.get_CommandLineArguments()
   at Nuke.Common.ValueInjection.ParameterService.<>c.<.cctor>b__32_0()
   at Nuke.Common.ValueInjection.ParameterService.get_Arguments()
   at Nuke.Common.ValueInjection.ParameterService.GetCommandLineArgumentIndex(String argumentName)
   at Nuke.Common.ValueInjection.ParameterService.HasCommandLineArgument(String argumentName)
   at Nuke.Common.ValueInjection.ParameterService.<GetParameter>g__TryFromCommandLineArguments|19_0(<>c__DisplayClass19_0& )
   at Nuke.Common.ValueInjection.ParameterService.GetParameter(String parameterName, Type destinationType, Nullable`1 separator)
   at Nuke.Common.ValueInjection.ParameterService.GetFromMemberInfo(MemberInfo member, Type destinationType, Func`4 provider)
   at Nuke.Common.EnvironmentInfo.GetParameter[T](MemberInfo member, Type destinationType)
   at Nuke.Common.EnvironmentInfo.GetParameter[T](Expression`1 expression)
   at Nuke.Common.NukeBuild.GetRootDirectory()
   at Nuke.Common.NukeBuild..cctor()
   --- End of inner exception stack trace ---
   at Nuke.Common.NukeBuild.Execute[T](Expression`1[] defaultTargetExpressions)
   at Build.Main()
```

### Anything else we should know?

When a .NET application is run in a single-file executable, the method Environment.GetSurrogateArguments accesses entryAssembly.Location which returns "", which will throw when fed into Path.GetDirectoryName. 

source/Nuke.Common/EnvironmentInfo.Others.cs

Replace:
```
        private static string[] GetSurrogateArguments()
        {
            var entryAssemblyLocation = Assembly.GetEntryAssembly()?.Location;
            if (entryAssemblyLocation == null)
                return null;
```
by
```
        private static string[] GetSurrogateArguments()
        {
            var entryAssemblyLocation = Assembly.GetEntryAssembly()?.Location;
            if (string.IsNullOrEmpty(entryAssemblyLocation))
                return null;
```

**Comment by tyb-dev** [comment]
Using AppContext.BaseDirectory seems to be the right way
https://stackoverflow.com/questions/63470279/appcontext-basedirectory-vs-assembly-getentryassembly-location-will-be-same-af

MS has a fallback switch to simulate it
https://github.com/dotnet/corert/issues/5467

Although the switch seems ineffective in .net 5.

**Comment by tyb-dev** [comment]
Would it make sense to replace `Assembly.GetEntryAssembly()?.Location` + `Path.GetDirectoryName` by `AppContext.BaseDirectory`?
Or alternatively replace the null check by null-or-empty check to disable surrogate arguments when the location is not available instead of crashing with `TypeInitializationException`?

**Comment by eatdrinksleepcode** [comment]
Can you expand on your scenario a little more? Are you publishing your local `_build` project as a single-file executable? Are you doing that with `<PublishSingleFile>true</PublishSingleFile>`?

Using `AppContext.BaseDirectory` instead of `Assembly.GetEntryAssembly()?.Location` looks like it is the recommended approach (thanks for that research!), _if_ we are just interested in the app directory. But in this case we don't just want the directory, we want the executable itself, because it is prepended to the list of arguments from "nuke.tmp". This is to maintain compatibility with `Environment.GetCommandLineArgs()`, which is the fallback and also prepends the executable to the list of arguments.

So I think the right solution here is to change the null check to a null-or-empty check to trigger the fallback, as you suggested. Are you interested in submitting a PR for that?

**Comment by matkoch** [comment]
I think for this one we should go with `string.IsNullOrEmpty` first. If someone is creating a PR, note that there is an extension method. I opened another issue #783 that should further investigate when `AppContext.BaseDirectory` is appropriate.

**Comment by tyb-dev** [comment]
> Can you expand on your scenario a little more? Are you publishing your local `_build` project as a single-file executable? Are you doing that with `<PublishSingleFile>true</PublishSingleFile>`?

Yes, we are intending to create a self-contained, single-file executable for use on Linux. We build C# and non-C# projects. For the non-C# projects, it is desirable not to have to have the (large) .NET SDK installed in all stages' containers used for the build. We'd nevertheless like to use Nuke to have a consistent code base for the pipeline logic.

We are currently applying a monkey-patch to `System.Reflection.RuntimeAssembly.Location` using Harmony.Lib to return a value based on `AppContext.BaseDirectory`, so I can confirm that this works at least in our case. But I agree with both of you that `string.IsNullOrEmpty` is a good first step. It will be backward compatible and will handle this additional case gracefully.

**Comment by tyb-dev** [comment]
Thanks for this. I removed my monkey-patch and used the 5.4.0-preview. Now I noticed that there is new an exception at:
`NukeBuild.GetBuildAssemblyDirectory`

I had missed this because the monkey-patch overrides all occurrences. 

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Nuke.Common.NukeBuild' threw an exception.
27 ---> System.ArgumentException: Expected object of type 'System.String' to be not null
28   at Nuke.Common.Assert.NotNull[T](T obj, String message, String argumentExpression)
29   at Nuke.Common.NukeBuild.GetBuildAssemblyDirectory()
30   at Nuke.Common.NukeBuild..cctor()
31   --- End of inner exception stack trace ---
32   at Nuke.Common.NukeBuild.Execute[T](Expression`1[] defaultTargetExpressions)
33   at Build.Main()
```

It's a similar occurrences with `== null`. Should I open a new issue, or shall we re-open this one?
