### ISSUE TITLE
Plugin support for Rider 2021.2

### ISSUE THREAD

**Issue by vova-lantsov-dev** [nuke-build/nuke#769]
### Usage Information

NUKE Support plugin, version 2021.1.0, MacOS Big Sur with M1 chip

### Relevant Code / Invocations

```code
Plugin 'NUKE Support' (version '2021.1.0') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is RD-212.4746.59
```

### Expected Behavior

Rider 2021.2 comes with a really important change - it officially supports M1 (arm64) chip of Apple MacBook.
Currently, Rider 2021.2 EAP 8 is available.
Unfortunately, I can't stay on 2021.1 until 2021.2 is released as stable, I need to use EAP version for all features to work correctly, and plugin doesn't support this version of Rider. It would be great, if you can upload a new version with Rider 2021.2 support

**Comment by matkoch** [comment]
Uploaded :shipit:
