### ISSUE TITLE
Build apk

### ISSUE THREAD

**Issue by ocsike** [nuke-build/nuke#770]
### Usage Information

5.2.1, Xamarin.Forms, Android, Windows10

### Expected Behavior

Hi,
Is there a way to build signed apk with this tool?  With msbuild I can compile my Xamarin.Forms project successfully , but what is the next step to make and sign apk. I not found any solution for this.

**Comment by matkoch** [comment]
You can ask around in our slack workspace: https://nuke.build/slack
