### ISSUE TITLE
Not compatible 2021.2

### ISSUE THREAD

**Issue by seayxu** [nuke-build/nuke#775]
### Description

Plugin 'NUKE Support' (version '2021.1.0') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is RD-212.4746.113

**Comment by vova-lantsov-dev** [comment]
+1 for this

**Comment by matkoch** [comment]
Uploaded. Just a friendly reminder, please give the plugin a review if you're using it regularly. 😉
