### ISSUE TITLE
VisualStudio CodeLens plugin

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#78]
According to the [VisualStudio roadmap](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2018-roadmap), CodeLens API will be made public in Q3.

Also have a look at an [existing extension](https://github.com/jeffchen-codingconsultantco/CodeMetric/).

**Comment by arodus** [comment]
https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/CodeLensOopSample

The codelens provider is loaded by the codelens service which runs outside of Visual Studio. Afaik there is no possibility to search the targets in proc by using the semantic model and sending the results to the codelens provider. So we either have to analyze the build project externally or just use RegEx to find the targets.

**Comment by matkoch** [comment]
https://marketplace.visualstudio.com/items?itemName=nuke.visualstudio
