### ISSUE TITLE
InvalidOperationException after succeeded target execution

### ISSUE THREAD

**Issue by Marat-Gumerov** [nuke-build/nuke#785]
### Usage Information

5.3.0/.NET SDK 5.0.303/netcoreapp3.1/Windows Server 2016

### Expected Behavior

No stacktraces in the log. Script ended successfully without error codes.

### What actually happened?

build.cmd ended with exit code -1

### Stacktrace / Log

```code
03:10:14  InvalidOperationException: Sequence contains no matching element
03:10:14     at System.Linq.ThrowHelper.ThrowNoMatchException()
03:10:14     at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
03:10:14     at Nuke.Common.NukeBuild.ReportSummary(Configure`1 configurator)
03:10:14     at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
03:10:14     at Nuke.Common.Execution.BuildExecutor.<>c__DisplayClass2_0.<Execute>b__0(ExecutableTarget x)
03:10:14     at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
03:10:14     at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
03:10:14     at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

### Anything else we should know?

Take a look at this code:
```
            ...
            using (Logger.Block(target.Name))
            {
                target.Stopwatch.Start();
                target.Status = ExecutionStatus.Running;
                build.ExecuteExtension<IOnTargetRunning>(x => x.OnTargetRunning(build, target));
                try
                {
                    target.Actions.ForEach(x => x());
                    target.Stopwatch.Stop();
                    target.Status = ExecutionStatus.Succeeded;
                    build.ExecuteExtension<IOnTargetSucceeded>(x => x.OnTargetSucceeded(build, target));

                    AppendToBuildAttemptFile(target.Name);
                }
                catch (Exception exception)
                {
                    build.ReportSummary(_ =>
                        target.SummaryInformation.Any()
                            ? target.SummaryInformation
                            : _.AddPair(exception.GetType().Name, exception.Message.SplitLineBreaks().First()));
                    ...
```
You call the ReportSummary method. This method searches for a target with the Running execution status. But there could be no such target if the exception is thrown during IOnTargetSucceeded extension execution. For example, it could be a telemetry error.

**Comment by Marat-Gumerov** [comment]
The link to the code mentioned above:
https://github.com/nuke-build/nuke/blob/70f1f75c0c315137478073880f4dbdb73723544d/source/Nuke.Common/Execution/BuildExecutor.cs#L113

**Comment by matkoch** [comment]
Would another overload help? `ReportSumary(target, ...)` ?

**Comment by Marat-Gumerov** [comment]
I thought about that. But I'm not sure about the reporting logic. 
We already know, that the target executed successfully, should we report the failure in case of IOnTargetSucceeded execution errors?
I see some options here:
1) If I want to report that the target was failed, I should change the target status to Failed in the catch section and use the overload ReportSummary(target, ...)
2) On the other hand, I think that `build.ExecuteExtension<IOnTargetSucceeded>` should not be related to the target and should not affect the target results. In this case, maybe we should report extension failures separately:
```
----------------------------
TargetName    Succeeded
|-<OnSuccessExtensions>    Failed
----------------------------
Total     Succeded
```
3) or suppress them, because (for example) we know that code execution from extensions `build.ExecuteExtension<IOnTargetSucceeded>` is not important and all errors from it could be ignored.

**Comment by matkoch** [comment]
I thought about this a bit, also since I've personally experienced it with one of my custom build extensions. For now, I suggest just wrapping your extension code in a try-catch block. I don't think it's worth changing the infrastructure to include extensions in the summary table. It would be a major refactoring with very little use.

Let me know if we might close this issue.

**Comment by Marat-Gumerov** [comment]
I have no custom extensions. I think the reason for the failure was the telemetry extension (maybe there were some network issues).
Anyway, I think that printing the stack trace is unexpected behavior. You should at least use another overload of the `ReportSummary(target, ...)` method as you said in the [comment](https://github.com/nuke-build/nuke/issues/785#issuecomment-901276681).

**Comment by matkoch** [comment]
It wasn’t clear to me that this happens with just the framework code. Are you continuously experiencing this?

**Comment by Marat-Gumerov** [comment]
I turned off the telemetry on this machine and now it works fine.

**Comment by matkoch** [comment]
Is it only one machine where it happened? What about CI?

**Comment by Marat-Gumerov** [comment]
It happened only on one CI node. Everything was fine on my local machine.
