### ISSUE TITLE
Cryptic symbols in Bamboo build output instead of ASCII graphics

### ISSUE THREAD

**Issue by gleb-osokin** [nuke-build/nuke#804]
### Usage Information

NUKE Execution Engine version 5.2.1 (Windows,.NETCoreApp,Version=v5.0)

### Relevant Code / Invocations

```code
Build run from Bamboo via execute PowerShell task for ./build.ps1
```

### Expected Behavior

NUKE logo and ASCII graphics should be printed correctly or not printed at all, especially for the sake of HTML rendering. This might be controlled via some parameter/settings, perhaps.

### What actually happened?

Some cryptic symbols are printed in Bamboo logs instead of ASCII graphics:

```
build	30-Sep-2021 09:22:16	â–ˆâ–ˆâ–ˆâ•—Â Â Â â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—Â Â Â â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—Â Â â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
build	30-Sep-2021 09:22:16	â–ˆâ–ˆâ–ˆâ–ˆâ•—Â Â â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘Â Â Â â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘Â â–ˆâ–ˆâ•”â•�â–ˆâ–ˆâ•”â•�â•�â•�â•�â•�
build	30-Sep-2021 09:22:16	â–ˆâ–ˆâ•”â–ˆâ–ˆâ•—Â â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘Â Â Â â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•�Â â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—  
build	30-Sep-2021 09:22:16	â–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘Â Â Â â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•�â–ˆâ–ˆâ•—Â â–ˆâ–ˆâ•”â•�â•�â•�  
build	30-Sep-2021 09:22:16	â–ˆâ–ˆâ•‘Â â•šâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•�â–ˆâ–ˆâ•‘Â Â â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
build	30-Sep-2021 09:22:16	â•šâ•�â•�Â Â â•šâ•�â•�â•�â•�Â â•šâ•�â•�â•�â•�â•�â•�Â â•šâ•�â•�Â Â â•šâ•�â•�â•šâ•�â•�â•�â•�â•�â•�â•�

build	30-Sep-2021 09:22:16	NUKE Execution Engine version 5.2.1 (Windows,.NETCoreApp,Version=v5.0)

...

build	30-Sep-2021 09:22:17	â•¬â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�â•�
build	30-Sep-2021 09:22:17	â•‘ Restore
build	30-Sep-2021 09:22:17	â•¬â•�â•�â•�
```

### Anything else we should know?

I know this might be a Bamboo build server issue as well, but I think we should not rely on every build system supporting all kinds of ASCII symbols in the output logs, especially when those are rendered into HTML.

**Comment by chaquotay** [comment]
I think it's an issue with the encoding used by Bamboo. Have you tried something like this:   https://confluence.atlassian.com/bamkb/how-to-change-the-wrong-encoding-in-bamboo-that-is-causing-the-application-to-crash-318670134.html

**Comment by gleb-osokin** [comment]
@chaquotay thanks for a quick reply! Yes, we actually found out that our build agents were not set up to use UTF8 as default encoding. Updating them fixed the issue.

**Comment by matkoch** [comment]
@gleb-osokin next time please mind the issue template
