### ISSUE TITLE
Console-based OutputSinks should output errors to standard error

### ISSUE THREAD

**Issue by gleb-osokin** [nuke-build/nuke#805]
### Description

The SystemColorOutputSink and AnsiColorOutputSink output errors to standard output stream, whereas some build hosts also rely on standard error stream to extract error information. One example is Bamboo Build Server.

The fix would be to replace Console.WriteLine calls within WriteError implementation to Console.Error.WriteLine.

Disclaimer: yes, I've seen the template. I'm neither a sponsor, nor an active member of the community. Nonetheless, I feel this is a good project that might also benefit from improvements introduced by people that don't pay for their own work.

**Comment by matkoch** [comment]
What does "don't pay for their own work" mean?

**Comment by gleb-osokin** [comment]
@matkoch well, as far as I could see, I'm obliged to be a sponsor to even create a PR. Which means I'm obliged to pay in order to be able to contribute, hence, pay for my own work for the project. Please correct me if I'm wrong.

**Comment by matkoch** [comment]
yes, because from there on i take the responsibility to maintain the code and also reviewing takes time.

**Comment by gleb-osokin** [comment]
Right, you also get paid for that by other sponsors and don't share your incomes to contributors, do you? That's perfectly fine, that's just how open source projects grow and proliferate. However, when you restrict voluntary contributions by a pay wall, you will see the number of your contributors diminish.

This is kind of not related to the issue, so, if you are willing to discuss this further, I can create a separate issue on the sponsorship model.

**Comment by matkoch** [comment]
Sure. Let's discuss so that you and your company don't have to contribute anything back for something that is probably very helpful.
