### ISSUE TITLE
VS2022 Support for .net 6 Features (file scoped namespaces, global usings, etc)

### ISSUE THREAD

**Issue by rog1039** [nuke-build/nuke#817]
### Usage Information

5.3.0

### Relevant Code / Invocations

```code
MSBuild(s => s
                        .SetProcessToolPath(@"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe")
                        .SetTargetPath(Solution)
                        .SetTargets("Build")
                        .SetConfiguration(Configuration)
                        .SetMaxCpuCount(Environment.ProcessorCount)
                        .SetNodeReuse(IsLocalBuild));
```

### Expected Behavior

I was unable to compile my solution using Nuke because I have switched over to using .net 6 compiler features. After some research I found the pull request #814 which seems to contain the fix necessary for .net 6 features.

However, that fix seems slated for 5.4.0 which is not available yet. For those who wish to perform a build right now without v5.4.0, you can make it work by using the SetProcessToolPath like I showed up above.

For those interested, Nuke will use the 2019 version of MsBuild which will not compile .net 6 features. We can force Nuke to use the 2022 version of MsBuild via SetProcessToolPath. Your path to the 2022 MsBuild might be different in which case you'll need to tweak that line appropriately.

### What actually happened?

No bug here, just showing a work-around for others who run into the same issue I did until v5.4.0 is released.

**Comment by matkoch** [comment]
Thanks. I will close this anyway since it's then still searchable.
