### ISSUE TITLE
NET6 Self-contained single exe issues when using GitVersion task

### ISSUE THREAD

**Issue by jrodrigv** [nuke-build/nuke#822]
### Usage Information

NUKE Version 6.0.0-beta.9/NET 6.0/NET 6.0/Win-x64

### Relevant Code / Invocations
Hi!

So I have recently upgraded my Nuke library to NET 6 using the latest Nuke pre-release version. My goal is to test if we can use a single exe containing all our Nuke libraries, etc. 

I have managed to compile it and execute it, but I have found an issue when trying to use the GitVersion attribute from Nuke and it only happens when executing the Self-contained single exe.

```code
[GitVersion(Framework = "net6.0")]
GitVersion GitVersion => TryGetValue(() => GitVersion);
```
The error output has been added to stacktrace section.

It works fine when execute Nuke normally using the ps1 script or even calling dotnet run manually

### Expected Behavior

I'd like that Nuke ToolPathResolver can deal with this scenario so that it can discover the tools properly even in self-contained mode.

### What actually happened?

It fails to find the GitVersion tool. I suspect that the Nuke.Common.Tools.GitVersion.GitVersionTasks.GetToolPath and Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable are failing to discover the location of the GitVersion tool when  Nuke is executed in Self-contained mode. I know in this mode some version attributes and location of assemblies is not returning the same values so maybe some workarounds are needed?

### Stacktrace / Log

```code
PS D:\REPOS\GITLAB\onecicd> .\onecicd.exe Version
​
███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
​
NUKE Execution Engine version 6.0.0-beta.9 (Windows,.NETCoreApp,Version=v6.0)
​
14:49:29 [WRN] Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Nuke.Common.Utilities.StringExtensions.EndsWithOrdinalIgnoreCase(String str, String other)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageDirectory(String[] packageIds, String version)
   at Nuke.Common.Tooling.ToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GetToolPath(String framework)
   at Nuke.Common.Tools.GitVersion.GitVersionSettings.get_ProcessToolPath()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings)
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator)
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
   --- End of inner exception stack trace ---
```

### Anything else we should know?

We really want to use the self-contained mode to avoid the need of having .NET SDK installed for non .NET pipelines

**Comment by matkoch** [comment]
Hi @jrodrigv 

I think this would be a pretty big feature to implement. It would have to deal with embedding the whole tool and later also extracting and invoking it. So I just switched the tag to enhancement.

**Comment by jrodrigv** [comment]
Thanks @matkoch for the fast response :)

**Comment by jrodrigv** [comment]
Hi @matkoch . 

I was thinking on a possible workaround for this. Would it be possible to pass the location of the different external tools that Nuke requires for things like GitVersion or even Sonarqubegin/end?

I think this can be beneficial for end-users and also reduce the maintenance cost for Nuke.

I'm mentioning the sonarqube here, because yesterday I found an issue trying to user SonarScannerBegin using Nuke with NET6. The reason is that dotnet-sonarscanner is using DOTNET_ROLL_FORWARD and it doesn't have a NET6 folder inside its nupkg, but Nuke tool resolver in NET6 is trying to find the NET6 version of the tool which does not exists (causing an error).

So in order to use SonarScannerBegin I need both NET5 and NET6 SDKs atm, and that made me think that if I could somehow override the path for the tool I could make it work ;)

**Comment by matkoch** [comment]
Nuke doesn't choose any runtime on its own. You can specify `Framework` with the invocation.
