### ISSUE TITLE
Using external files by including an .ext file with an URL does not work anymore (docs outdated)

### ISSUE THREAD

**Issue by reijerh** [nuke-build/nuke#826]
### Usage Information

Nuke 5.3.0 / GlobalTool 6.0.0-beta0012 / Core SDK 6.0.101 / net6.0 / W10

### Relevant Code / Invocations

```code
Having a `Build.Defaults.cs.ext` file included through `<NukeExternalFiles Include="**\*.*.ext" Exclude="bin\**;obj\**" />`, which contains an URL to an online .cs file.
```

### Expected Behavior

The .cs file is downloaded from the URL specified in the .ext file and used in the build.

### What actually happened?

Build exits directly with the following error:
`Build.Defaults.cs.ext : Build error : Invalid URI: The format of the URI could not be determined. `

### Anything else we should know?

Seems the behavior was changed at some point: it seems we now need to put the URL of the online file directly in the .csproj (instead of including the .ext file).

The docs still describe the old way: https://nuke.build/docs/sharing-builds/external-files.html

**Comment by matkoch** [comment]
will be part of the new docs
