### ISSUE TITLE
Output invisible in non-ANSI terminals

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#836]
### Usage Information

6.0.0

### Description

Some output is not visible because foreground and background color are the same.

### Reproduction Steps

None

### Expected Behavior

Text is readable.

### Actual Behavior

Text is not readable.

### Known Workarounds

Text must be selected to be read.

**Comment by comptoiragricole** [comment]
Hi, why is this bug closed without any resolution ? thx

**Comment by matkoch** [comment]
milestone 6.0.1
