### ISSUE TITLE
Target headers and summaries no longer display in Windows console

### ISSUE THREAD

**Issue by gtbuchanan** [nuke-build/nuke#838]
### Usage Information

NUKE 6.0.0 / net6.0 / Windows 10

### Description

The logged target headers and summaries no longer display in PowerShell or CMD consoles. It appears they are being logged but the foreground color matches the background color.

![image](https://user-images.githubusercontent.com/715687/148602732-a2f982a1-e5e0-45c5-8b28-f962c0c84a87.png)

I can copy and paste the seemingly blank space into a text editor and see the text:

```
███╗   ██╗██╗   ██╗██╗  ██╗███████╗
████╗  ██║██║   ██║██║ ██╔╝██╔════╝
██╔██╗ ██║██║   ██║█████╔╝ █████╗  
██║╚██╗██║██║   ██║██╔═██╗ ██╔══╝  
██║ ╚████║╚██████╔╝██║  ██╗███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
​
NUKE Execution Engine version 6.0.0 (Windows,.NETCoreApp,Version=v6.0)
...
╬══════════
║ Clean
╬══
​...
╬════════════
║ Restore
╬═══
...
```

### Reproduction Steps

Run any NUKE 6.0 build on Windows with PowerShell or CMD

### Expected Behavior

Target headers and summaries should be visible

### Actual Behavior

Target headers and summaries are not visible

### Regression?

This worked in NUKE 5.3 before I upgraded.

**Comment by matkoch** [comment]
dup of #836

**Comment by comptoiragricole** [comment]
Hi, why is this bug closed without any resolution ? thx

**Comment by matkoch** [comment]
milestone 6.0.1

it's enough to ask in one issue ;)

**Comment by kirbatious** [comment]
Hi @matkoch I just installed 6.0.1 on win10 and I can still read nothing in either powershell or cmd. Can this bug be reopened? Is there any further info I can provide to help you resolve this?

**Comment by kirbatious** [comment]
To add an additional weird detail, I uninstalled 6.0.1, installed 5.3.0 and had the same problem. I then tried 5.0.1 and that worked fine.

Then I tried changing the colour scheme to have a white background, and it's back to all working for me. Obviously I would prefer to be able to go back to my old colour scheme, but it's nice that's it's usable again!

[Note on colour scheme change for anyone stuck on this: I'm using Windows Terminal and in the settings.json file you can add "colorScheme": "Tango Light" which gives you a white background https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes ]

**Comment by gtbuchanan** [comment]
6.0.1 works fine for me in PowerShell and PowerShell Core both directly and through ConsoleZ. I installed Windows Terminal from the Microsoft Store and it appears to work there too. Windows 10 Pro 21H2.
