### ISSUE TITLE
Package 'CycloneDX 2.3.0' has a package type 'DotnetTool' that is not supported by project 'XXXXXX'.

### ISSUE THREAD

**Issue by anandsutar2122** [nuke-build/nuke#848]
### Usage Information

.NET Framework 4.7.2

### Description

I have try to install CycloneDX.2.3.0 on specific class library project but did not work below are getting error message but when i try to install through console in the solution it was installed sucessfully also it generate the bom.xml report file.

But my case one solution having different project so i want to do report bom.xml file for each project.

**Below log message received -** 

Attempting to gather dependency information for package 'CycloneDX.2.3.0' with respect to project 'xxxxxxx', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 5.13 sec
Attempting to resolve dependencies for package 'CycloneDX.2.3.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'CycloneDX.2.3.0'
Resolved actions to install package 'CycloneDX.2.3.0'
Install failed. Rolling back...
Package 'CycloneDX.2.3.0' does not exist in project 'XXXXXX'
Package 'CycloneDX.2.3.0' does not exist in folder 'XXXXXXXX'
Executing nuget actions took 877 ms
Package 'CycloneDX 2.3.0' has a package type 'DotnetTool' that is not supported by project 'XXXXXXXXXX'.
Time Elapsed: 00:00:06.7955388
========== Finished ==========

### Reproduction Steps

Tried below steps :

Click on solution - > Manage nuget package from solution - > 

Browse - >  search for CycloneDX  -  > selected project - > click on install 

Getting error logs 

### Expected Behavior

it should install in the project. then we are get the report project wise. 
Or only install in the solution ? when i try this it was install correctly also generate the BOM.xml file

### Actual Behavior

We are getting Package 'CycloneDX 2.3.0' has a package type 'DotnetTool' that is not supported by project 'XXXXXX'.

**Comment by matkoch** [comment]
Are you using `PackageDownload` ? If not, you should: https://nuke.build/docs/authoring-builds/cli-tools.html
