### ISSUE TITLE
Sonarscanner missing parameter

### ISSUE THREAD

**Issue by SierraNL** [nuke-build/nuke#849]
### Usage Information

6.0.1 / .Net 6 / Linux

### Description

As described on https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-msbuild/
there is a parameter `/d:sonar.dotnet.excludeTestProjects=true` that currently isn't supported by the SonarScanner task.

This is possible by passing the parameter using the `ConfigureProcessArguments` method.

### Reproduction Steps

Create a Target where you want to start the sonarscanner, but you don't want to detect issues in dotnet test projects.
To do this you would need to specify `/d:sonar.dotnet.excludeTestProjects=true` via the fluent api, but this isn't possible.

### Expected Behavior

A method on the Fluent API to exclude the dotnet test projects.

### Actual Behavior

No method available.

### Known Workarounds

Use the `ConfigureProcessArguments` method

**Comment by matkoch** [comment]
Could you please create a PR?
