### ISSUE TITLE
NSwag runtime targets support

### ISSUE THREAD

**Issue by jvmlet** [nuke-build/nuke#856]
### Description

Please support `Net50` and  `Net60` NSwag  targets [here ](https://github.com/nuke-build/nuke/blob/bcd5968c41b2a4c21eacfa6b336230971988adb9/source/Nuke.Common/Tools/NSwag/NSwagSettings.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L22)

and [Runtime enum ](https://github.com/nuke-build/nuke/blob/bcd5968c41/source/Nuke.Common/Tools/NSwag/NSwagTasks.cs)as well 

Thanks

**Comment by matkoch** [comment]
Could you please create a PR instead?
