### ISSUE TITLE
{target} value in log message for CopyFileToDirectory displays unexpected value

### ISSUE THREAD

**Issue by VolkmarR** [nuke-build/nuke#860]
### Usage Information

6.0.1 / net 5.0 / windows

### Description

After migrating from 5.3.0 to 6.0.1, the {target} value in log message for CopyFileToDirectory displays an unexpected value. Instead of the target directory the current nuke target is shown.

### Reproduction Steps

Extract zip and run nuke. 

[NukeTestCopyFile.zip](https://github.com/nuke-build/nuke/files/7988816/NukeTestCopyFile.zip)

### Expected Behavior

Expected log message:

╬═════════
║ Test
╬══

Copying file 'C:\Projects\DotnetTest\NukeTestCopyFile\NukeTestCopyFile.sln' to 'C:\Projects\DotnetTest\NukeTestCopyFile\.nuke\temp\NukeTestCopyFile.sln'...

### Actual Behavior

Actual log message

╬═════════
║ Test
╬══

18:26:44 [INF] Copying file C:\Projects\DotnetTest\NukeTestCopyFile\NukeTestCopyFile.sln to Test...

### Regression?

Nuke 5.3.0 showed the message as expected. Might be related to the use of serilog and the TargetLogEventEnricher.

**Comment by sandrofigo** [comment]
Can confirm this also affects the method `CopyDirectoryRecursively()`.
