### ISSUE TITLE
Docker Tasks Build Output as ERR

### ISSUE THREAD

**Issue by rena0157** [nuke-build/nuke#861]
### Usage Information

NUKE Execution Engine version 6.0.1 (Windows,.NETCoreApp,Version=v6.0)

### Description

When running `DockerTasks.DockerBuild(b => b.Set....)` the logs that are output from docker are labelled as `[ERR]`.

 
![image](https://user-images.githubusercontent.com/33334607/152456982-4245ca3e-55a7-456a-ad9e-2b550a492e82.png)

Note that the step actually finishes without error. Just the log messages are labelled as errors.

### Reproduction Steps

Run a build step with `DockerTasks.DockerBuild`

### Expected Behavior

Log messages output as either `[DBG]` or `[INF]`

### Actual Behavior

Log messages output as `[ERR]`

### Regression?

For as long as I have been using Nuke this has always been an issue. Before Serilog was introduced as the logging framework the log messages would still be 'errors' denoted by the red colour.

**Comment by matkoch** [comment]
Docker writes to the error output, so it's kinda their fault. You can override that behavior by setting `DockerTasks.DockerLogger` like here: https://github.com/matkoch/azure-swa-demo/blob/main/build/Ext/Extensions.cs#L19

**Comment by rena0157** [comment]
I wonder why they would do that 😆  That work around works like a charm. Thanks!!

**Comment by matkoch** [comment]
Unfortunately, a lot of tools do that, including Git :)

**Comment by matt-richardson** [comment]
Annoying in *nix land, STDERR means "errors and progress and things that shouldn't be on STDOUT (cos they'll get piped to the next program)"
In windows, STDERR actually means errors.

I blame *nix.

I've had to copy and paste that line to a bunch of projects in the last couple of weeks... I wonder if it's wiser to change the default for docker?

**Comment by matkoch** [comment]
I just wrote the following for the new FAQ:
<img width="498" alt="Google Chrome-FAQ  NUKE-2022-02-05-43kzifXr" src="https://user-images.githubusercontent.com/5005566/152629235-bd1d451b-9476-4985-bded-0637d1859e93.png">


I'm not sure if it's a good argument though.

**Comment by tomachristian** [comment]
This is no longer possible with the latest Nuke 9.

**Comment by Arikael** [comment]
How are we supposed to handle this with Nuke 9?

**Comment by matt-richardson** [comment]
It now appears to work natively - https://github.com/nuke-build/nuke/commit/bf8fea77514212a9be11c3bb3d1b3aef26562cf3.
Overriding it is no longer required.
