### ISSUE TITLE
Allow to define conditional target dependencies based on input parameter

### ISSUE THREAD

**Issue by satano** [nuke-build/nuke#873]
### Description

I would like to define `DependsOn` based on input parameter. I have targets `A` and `B` and both can be executed separately on their own. But when I specify a parameter, then target `B` should depend on target `A` and so both will be run:

``` cs
class Build : NukeBuild
{
    [Parameter]
    readonly bool RunA;

    Target A => _ => _
        .Executes(() =>
        {
            Console.WriteLine("Executing A...");
        });

    Target B => _ => _
        .When(RunA, c => c.DependsOn(A)) // This does not work, it is only for illustratory purpose.
        .Executes(() =>
        {
            Console.WriteLine("Executing B...");
        });
}
```

I tried `OnlyWhenDynamic` and `OnlyWhenStatic`, but this way I cannot config target dependencies. Using `When` as in exmaple above, it seems, that I can configure dependencies. But evaluation of `When` runs very early and input parameters are not populated into the class. So the value of `RunA` parameter is always `false`.

### Usage Example

`nuke a` → Runs only target `A`.
`nuke b` → Runs only target `B`.
`nuke b --run-a` → Runs target `A` first, then target `B`.

### Alternative

I can manually run both targets `nuke a b --run-a`, but it would be nice to make this logic just base on parameter value.

**Comment by willsmith9182** [comment]
This is possible to do. 

```
using System;
using Nuke.Common;

class Build : NukeBuild
{
     public static int Main() => Execute<Build>(x => x.B);

    [Parameter]
    readonly bool RunA;

    Target A => _ => _
        .OnlyWhenDynamic(() => RunA)
        .WhenSkipped(DependencyBehavior.Execute)
        .Executes(() =>
        {
            Console.WriteLine("Executing A...");
        });

    Target B => _ => _
        .DependsOn(A)
        .Executes(() =>
        {
            Console.WriteLine("Executing B...");
        });
}
```

![image](https://user-images.githubusercontent.com/11752440/154659081-d170f634-c8fe-4375-b592-7e91f9375488.png)

![image](https://user-images.githubusercontent.com/11752440/154659237-37e6b3a8-47d9-4f9e-ba5e-d108eac655ee.png)

**Comment by satano** [comment]
It is not working. Now you can not run just the target `A` without specifying the parameter: `nuke a`

I need this, becase these targets can really be executed on ther own (without parameters). And actually, the `--run-a` parameter is just for target `B` (target `A` does not use it). But when `B` is executed **without** this parameter, it runs on its own. When the parameter is supplied, the logic in `B` is a bit different and target `A` must run to prepare the environment.

**Comment by willsmith9182** [comment]
I see, 

>But when B is executed without this parameter, it runs on its own. When the parameter is supplied, the logic in B is a bit different 

To me, this suggest that B should be 2 seperate targets. If the logic is different, and the triggering conditions are then why try and use the same target?

EDIT: had a tinker, and cannot find a way to acheive it. appologies

**Comment by satano** [comment]
Well. The logic is different, but `B` does still the same thing. To be specific, `B` is `Build` target. When executed as is, it builds the whole solution in the repository. This solution is quite big, it has more than 100 projects. That parameter `--run-a` (the real name is `--affected-only`) makes the build special in that way, that it builds different _solution_ (a special `.proj` file), which contains only list of _changed projects_, so the build is much faster.

This `.proj` file is generated by target `A`. The general logis is, it takes two commits, finds which files has changed between them and finds to which projects these files belong (we use [dotnet-affected](https://github.com/leonardochaia/dotnet-affected) for this). Then it creates `.proj` with the list of projects. We want to have this as a separate target to run it on its own, jus to generate the file. But We also want to run this automatically, when the `Build` is executed with that parameter, to make it sure, `.proj` file is generated and up to date.

This is not a big deal for us, because we will just run both targets (`nuke a b --run-a`), but I think, that it would be quite nice feature to have conditional dependencies. Of course, there are som issues, for example how/if to show such a thing in a nuke plan. 😄

**Comment by matkoch** [comment]
It seems you haven't completely read the documentation, so I will just post it: https://nuke.build/docs/authoring-builds/fundamentals.html

**Comment by satano** [comment]
I have read the documentation several times. Maybe I am still missing something, but I am not able to figure out, how to achieve what I wanted. I tried both `OnlyWhenStatic` and `OnlyWhenDynamic` methods, but with no success. It seems, that these conditions are for execution itself of the target, not for the other things (dependency). I tried for example something like this:

``` cs
Target B => _ => _
    .OnlyWhenStatic(() => CheckCondition()) // Attempt to make 'DependsOn' conditional.
    .DependsOn(A)
    .OnlyWhenStatic(() => true) // Attempt tu execute this always.
    .Executes(() =>
    {
        Console.WriteLine("Executing B...");
    });
```

And it seems only first `OnlyWhenStatic` is applied and it is applied only to main execution (`Execute` method). Depending on the result of `CheckCondition()`, `B` target is executed or not. `A` target is executed always. Tried several other combinations without success, tried using `DependentFor` instead of `DependsOn`, everything without success.

So really if this is possible, I do not know how to do it. And the documentation did not helped me with it.

**Comment by matkoch** [comment]
So you want two targets to only be ordered in a certain way without necessarily being dependent on each other?

**Comment by satano** [comment]
No. I would like to have one target dependent on the other target, but not always. It may be dependent or may not, based on input parameter. Having twho targets `A` and `B`, both targets can be executed independently, without any dependency:

- `nuke a` → Runs only target A (no dependencies).
- `nuke b` → Runs only target B (no dependencies).
- `nuke b --some-parameter` → When this parameter is set, **it is a condition which makes `B` dependent on `A`**, so target `A` runs automatically first, then target `B`.

Now I have options to run both targets: `nuke a b --some-parameter`. I am quite fine with this, as I mentioned earlier, it just seems to me, that it could be fine to have conditional dependencies. There already are conditional executions of targets using `OnlyWhenStatic` and `OnlyWhenDynamic`. And we also can use conditions when building settings for built-in tools:

``` cs
DotNetBuild(s => s
    .SetConfiguration(Configuration)
    .SetProjectFile(Solution)
    .When(SomeCondition, ss => ss.SetProjectFile(SomeOtherSolution))
```

**And this functionality what I want already is in Nuke:**

``` cs
Target B => _ => _
    .When(false, s => s.DependsOn(A))
    .Executes(() => { });

❯ nuke --help
Targets (with their direct dependencies):

  A
  B (default)

----------------------------------------

Target B => _ => _
    .When(true, s => s.DependsOn(A))
    .Executes(() => { });

❯ nuke --help
Targets (with their direct dependencies):

  A
  B (default)          -> A
```

So this `When` when building target is exactly whan I want. **The only problem is, that this condition is evaluated before the build class is initialized. All parameters have default values, so it is not possible to build `When` condition using some input parameter.**
