### ISSUE TITLE
Sonar EnableVerbose dosen't work

### ISSUE THREAD

**Issue by glucaci** [nuke-build/nuke#874]
### Usage Information

6.0.1 / .NET 6

### Description

When enabling sonar verbose get the following warning and sonar doesn't output verbose
`[DBG] WARNING: Expecting the sonar.verbose property to be set to either 'true' or 'false' (case-sensitive) but it was set to 'True'.`

### Reproduction Steps

```
sonarScannerBeginSettings.EnableVerbose()
```

### Expected Behavior

Sonar to output verbose logs

### Actual Behavior

Verbose logs are not shown

**Comment by ron-myers** [comment]
Hey @glucaci, thanks for submitting this, if you are able - please submit a PR for this change.

If you need any help with that, DM me on the Nuke Slack.

**Comment by matkoch** [comment]
PR still welcome
