### ISSUE TITLE
[feature] Support ordering targets in the help text

### ISSUE THREAD

**Issue by LordMike** [nuke-build/nuke#881]
### Description

I had a bunch of targets that I compose other, bigger, targets with. But these small targets are all in the help text -- that is, until I discovered `Unlisted()`. Now, I have a number of compose targets, which have distinct groups of features, like "compile sass / prepare webpack", "build .net, pack .net, ..", "build docker, push docker, ..".

But orderwise, they're a bunch of scrambled targets.

I'd like to be able to order my targets, maybe by some arbitrary number.

Fun aside: I noticed that the `longestTargetName` is calculated from _all_ targets, while the listing is done from _listed_ targets. This means a very long (unlisted) target name will skew all targets in the help texts for seemingly no reason :).

https://github.com/nuke-build/nuke/blob/5505791f65e542a719d8481900e8a59876ea4821/source/Nuke.Common/Execution/HelpTextService.cs#L21-L34

### Usage Example

I imagine, like `.Unlisted()`, that I can do this:

```code
    Target MyTarget => _ => _
        .HelpOrder(200)
        .Executes(DoWork);
```

By default, the order number will be 0. Users can then place a specific target before or after the default sorting, by using negative or positive numbers. Alternatively, users can sort all targets by applying numbers to all.

This order will then be used in the following code:

https://github.com/nuke-build/nuke/blob/5505791f65e542a719d8481900e8a59876ea4821/source/Nuke.Common/Execution/HelpTextService.cs#L25-L34

If we wanted to, we could go all out and have the same "before / after" system that targets use for ordering themselves, to order their help texts. So users can order their new target before or after other targets, in the help texts. This could help with cases where targets come from different projects that don't know anything about each other.

### Alternative

N/A.

**Comment by matkoch** [comment]
At the moment I'm not interested in this and it also seems no one upvoted this.
