### ISSUE TITLE
Environment variables are cleared when starting a process

### ISSUE THREAD

**Issue by joostmeijles** [nuke-build/nuke#882]
### Usage Information

6.0.1, Windows

### Description

All environment variables are cleared when a user specifies environment variables for a certain process. 
This e.g. causes on Windows that the newly started process does not have network access (due to missing environment variables).

NB. This LOC causes the problem: https://github.com/nuke-build/nuke/blob/6051bd131ec9b9e48fbdc3a6a44bf8adb0429bc3/source/Nuke.Common/Tooling/ProcessTasks.cs#L137

### Reproduction Steps

```
var myVars = new Dictionary<string, string>() {
     ["Some"] ="Example",
};

ProcessTasks.StartShell($"C:/Windows/System32/PING.EXE google.com", ".", myVars).WaitForExit();
```

### Expected Behavior

Started process, in above example ping, to behave normally, i.e. have network connection.

### Actual Behavior

No network connection allowed due to missing environment variables.

### Known Workarounds

Supply all existing environment variables, e.g.
```
var myVars = new Dictionary<string, string>() {
     ["Some"] ="Example",
};

foreach (DictionaryEntry de in Environment.GetEnvironmentVariables())
{
                myVars.Add(de.Key as string, de.Value as string);
}

ProcessTasks.StartShell($"C:/Windows/System32/PING.EXE google.com", ".", myVars).WaitForExit();
```

**Comment by matkoch** [comment]
works as designed
