### ISSUE TITLE
SonarQube bool value are case sensitive

### ISSUE THREAD

**Issue by lillo42** [nuke-build/nuke#883]
### Usage Information

NUKE Version: 6.0.1 / SDK Version: 6.0.200 / Target Framework: 6.0 / Operating System: Linux Docker  

### Description

SonarQube,  bool value are case sensitive

When I run the sonarqube with verbose true or false I'm getting a sonarqube warning saying the value is case sensitive and could not define the value

### Reproduction Steps

```c#
SonarScannerBegin(s => s.EnableVerbose());
```

### Expected Behavior

generate this command: `/d:verbose=false` or `/d:verbose=true` and not sonarqube warning

### Actual Behavior

generate this command: `/d:verbose=False` or `/d:verbose=True` and sonarqube warning

### Regression?

No

**Comment by lillo42** [comment]
I would like to fix it, but I don't know how to do it, since the code is generated

**Comment by matkoch** [comment]
Left a note here

https://github.com/nuke-build/nuke/issues/884#issuecomment-1065403297
