### ISSUE TITLE
Sonarqube add support to missing property value

### ISSUE THREAD

**Issue by lillo42** [nuke-build/nuke#884]
### Description

Hi,

I need to add support for follow sonarqube parameter:

- sonar.dotnet.excludeTestProjects
- sonar.scm.provider
- sonar.qualitygate.wait
- sonar.qualitygate.timeout
- sonar.analysis.[yourKey]
- <analysis-parameter>=<value>

### Usage Example

```code
sonar.dotnet.excludeTestProjects  => Improve build performance on large project
sonar.scm.provider => enable git or svn
sonar.qualitygate.wait => ensure the quality
```

**Comment by matkoch** [comment]
Please create a pull-request. The metadata is listed in `NSwag.json`.
