### ISSUE TITLE
Custom OutputPath in Directory.Build.props breaks builds

### ISSUE THREAD

**Issue by Werebunny** [nuke-build/nuke#89]
Nuke worked great for my project, but I encountered a few issues.

## Expected Behavior
Builds work with a Directory.Build.props file in a parent directory containing:
```xml
<Project>
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <BaseIntermediateOutputPath>..\..\..\artifacts\nuke\obj\</BaseIntermediateOutputPath>
    <OutputPath>..\..\..\artifacts\nuke\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
</Project>
```

## Current Behavior
```c#
Assertion failed: buildProjectDirectory != null
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.ControlFlow.NotNull[T](T obj, String text)
   at Nuke.Common.EnvironmentInfo.get_BuildProjectDirectory()
   at Nuke.Common.NukeBuild.get_RootDirectory()
   at Nuke.Common.NukeBuild.get_SolutionFile()
   at Nuke.Common.ProjectModel.SolutionAttribute.GetStaticValue()
   at Nuke.Common.Execution.InjectionService.InjectValues(NukeBuild build)
   at Nuke.Common.Execution.BuildExecutor.Execute[T](Expression`1 defaultTargetExpression)
```

## Steps to Reproduce
1. Create project or clone [CreateAndFake](https://github.com/CreateAndFake/CreateAndFake).
2. Add/modify a Directory.Build.props file similar to the example.
3. Run any build.

## Additional Information

It seems to not be registering the setting.

**Comment by matkoch** [comment]
This is unfortunately also a *won't fix*.

We won't support `Directory.Build.props` in favor of a simpler bootstrapping. Also, I don't see the point in treating build assemblies as build artifacts. What is the use case for this?

**Comment by Werebunny** [comment]
This just keeps my solution consistent and tidy. Everything my solution generates goes to the artifacts dir. Everything.

Well, except the bin folder for Nuke. So, a minor annoyance.

Looking at your code it looks back for the nuke cspoj from the bin directory for the project. In my mind, looking for project sln file and taking the csproj path from it also works. But I'm only looking at that part here.
