### ISSUE TITLE
FileSystemTasks logging is broken since switch to Serilog

### ISSUE THREAD

**Issue by Nefarion** [nuke-build/nuke#904]
### Usage Information

NUKE Execution Engine version 6.0.1 (Windows,.NETCoreApp,Version=v6.0)

### Description

Since the switch to Serilog logging (5e1fbefcafb689202950dbfd985041f8b2b5d2c7), logging in FileSystemTasks is broken.

These calls use `{Target}` as property name for the destination, but there is [TargetLogEventEnricher](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Execution/Logging.cs#L215) that gets used [for every execution](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Execution/BuildExecutor.cs#L103), and it overrides the Property to the name of the Nuke Build Target.

- https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/IO/FileSystemTasks.cs#L152
- https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/IO/FileSystemTasks.cs#L173
- https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/IO/FileSystemTasks.cs#L205
- https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/IO/FileSystemTasks.cs#L251

I would propose to change these log lines to use {Destination} as Property instead?

### Reproduction Steps

`Target BuildTarget => _ => _.Executes(() => FileSystemTasks.CopyFile("<source>", "<destination>"));`

### Expected Behavior

13:47:36 [INF] Copying file `<source>` to `<destination>`...

### Actual Behavior

13:47:36 [INF] Copying file `<sourceFile>` to `BuildTarget`...

### Regression?

Yes, it worked in the old logging system before the change to Serilog logging (5e1fbefcafb689202950dbfd985041f8b2b5d2c7)

**Comment by matkoch** [comment]
#860

**Comment by Nefarion** [comment]
Wow, my search skills are still asleep today! I was looking for CopyFile and did not find any issues. My bad! Sorry for the duplicate!
