### ISSUE TITLE
unit tests fail if there is a space in the project path

### ISSUE THREAD

**Issue by jeffreycoxdoosan** [nuke-build/nuke#908]
### Usage Information

dev

### Description

The following unit tests will fail in dev if there is a space in the project path.
Nuke.Common.Tests.SettingsTest.TestMSBuild
Nuke.Common.Tests.SettingsTest.TestOpenCover

`Expected configurator.Invoke(newT()).GetProcessArguments().RenderForOutput() to be "C:\projects\Git Hub\nuke\source\Nuke.Common\Nuke.Common.csproj /nodeReuse:False /nologo /p:Platform=AnyCPU /p:Configuration=Release" with a length of 131, but ""C:\projects\Git Hub\nuke\source\Nuke.Common\Nuke.Common.csproj" /nodeReuse:False /nologo /p:Platform=AnyCPU /p:Configuration=Release" has a length of 133, differs near ""C:" (index 0).
`

### Reproduction Steps

pull dev to a path with a space, run unit tests

### Expected Behavior

tests to not fail

### Actual Behavior

tests fail

**Comment by matkoch** [comment]
i suggest you just rename your folder to `GitHub` ... that's the correct name anyways ;)

**Comment by jeffreycoxdoosan** [comment]
I deliberately put a space in my project path so I catch bugs related to spaces in paths.

**Comment by matkoch** [comment]
not really a bug, since it's only in tests, but thanks anyways

**Comment by jeffreycoxdoosan** [comment]
Yeah, it's annoying but pretty marginal.
