### ISSUE TITLE
Visual Studio Build Tools 22 Path not Resolved

### ISSUE THREAD

**Issue by simonGW** [nuke-build/nuke#912]
### Usage Information

6.0.1

### Description

The VS Build Tools Version 2022 installed in Progam Files (x86) are not found since they are looked for in Program Files.

### Reproduction Steps

Use VS Build Tools 2022 to build a project

### Expected Behavior

Path to MS Build should be resolved

### Actual Behavior

Path to MS Build is not resolved, build fails

### Regression?

no

**Comment by matkoch** [comment]
#850
