### ISSUE TITLE
DotNetTestSettingsExtensions.AddTeamCityLogger() causes unwanted delays

### ISSUE THREAD

**Issue by jwfx** [nuke-build/nuke#913]
### Usage Information

NUKE 6.0.1 / SDK 6.0.202 / net6.0 / Win10 x64

### Description

A call to `DotNetTestSettingsExtensions.AddTeamCityLogger()` is taking a lot longer than expected in NUKE projects where multiple NuGet packages are referenced in .csproj.

### Reproduction Steps

1. Create a NUKE project that has multiple NuGet packages referenced it its .csproj
2. Add a build step that executes unit tests, like so
```csharp
    Target Test => _ => _
        .DependsOn(Build)
        .Executes(() =>
        {
            var tests = Solution.GetProject("MyApp.Tests");

            DotNetTasks.DotNetTest(settings => settings
                .SetProcessWorkingDirectory(RootDirectory / "test" / "MyApp.Tests")
                .SetProjectFile(tests?.Path)
                .SetConfiguration(Configuration)
                .When(TeamCity.Instance != null, settings => settings
                    .AddTeamCityLogger()
                    .AddLoggers("console;verbosity=normal")));
        });
```
4. Execute it in TeamCity environment

### Expected Behavior

The "Test" build step should immediately start after the previous step finishes.

### Actual Behavior

Depending of the number of referenced NuGet packages and the performance of the machine it could take a long time until the unit test execution actually starts.
In our concrete case the build server takes ~65 seconds to crawl through 120MB of NuGet packages before it continues.

### Regression?

I don't think so, from what I can tell the extension method looks like that since its inception.

### Known Workarounds

https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/CI/TeamCity/DotNetTestSettingsExtensions.cs#L20

I believe `NuGetPackageResolver.GetLocalInstalledPackage()` should be called with `resolveDependencies` set to `false`, as in my understanding we're only interested in the path to the NuGet package itself here.

I've successfully tested this and the delay on the build server drops to ~12 seconds down from ~65.

**Comment by matkoch** [comment]
Where is your `TeamCity.Dotnet.Integration` referenced?

**Comment by jwfx** [comment]
In the `_build.csproj` like so

```
    <PackageReference Include="TeamCity.Dotnet.Integration" Version="1.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

**Comment by matkoch** [comment]
Does it also happen without the `PrivateAssets` ?

**Comment by jwfx** [comment]
Just tested it - yes it does.

**Comment by jwfx** [comment]
Did a bit more digging. I believe the underlying problem could be here:
https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tooling/NuGetPackageResolver.cs#L230

The ctor of `InstalledPackage` seems to open every .nupkg, which essentially means unzipping and reading the nuspec file, to acquire the metadata of the package. Doing this for all the references packages, especially recursively when `resolveDependencies` is set to true, is where all the time accumulates. 

Maybe there is potential for optimization here, by reading the nuspec file that is usually already present in the `.nuget\packages` cache directory instead of pulling it from the package itself.
![image](https://user-images.githubusercontent.com/39484381/166140826-7d73d266-cd21-4701-8dfe-bede7a92d979.png)

**Comment by matkoch** [comment]
That's definitely a good idea. When implementing this I must have completely ignored the fact that the metadata could be read from the nuspec file – or maybe I just forgot the reason by now. In any case, I think it makes sense to try and redesigning this whole approach.

**Comment by matkoch** [comment]
I think I remember... without `PackageReference`, packages are extracted to a local `packages` directory. In fact, this _does not_ extract the nuspec file. I assume this infrastructure is really only relevant for the build project itself. Judging by telemetry, there are no usages with .NET Framework. But it's still possible, though unlikely, that someone uses this on their old non-SDK projects.

<img width="393" src="https://user-images.githubusercontent.com/5005566/166155266-b9611bef-f6de-4039-a338-5e6bdab26d9f.png">

A possible solution without breaking could be to look for a neighboring nuspec file, and load everything from there. The `packageToCheck.Metadata.GetDependencyGroups()` call might be a bit tricky, but otherwise doable I think.

Would you be interested in drafting something?

**Comment by matkoch** [comment]
```
var xmlReader = new XmlTextReader(nuspecFile) { Namespaces = false };
var document = XDocument.Load(xmlReader);
var namespaces = ("ns", document.Root.NotNull().Name.NamespaceName);

var id = document.XPathSelectElementValues("/package/metadata/id", namespaces).Single();
var version1 = NuGetVersion.Parse(document.XPathSelectElementValues("/package/metadata/version", namespaces).Single());
var version2 = VersionRange.Parse(document.XPathSelectElementValues("/package/metadata/version", namespaces).Single());
var dependencies = document.XPathSelectElements("/package/metadata/dependencies/group/dependency", namespaces)
    .Select(x => (Id: x.GetAttributeValue("id"), Version: VersionRange.Parse(x.GetAttributeValue("version"))))
    .Distinct().ToList();
```

**Comment by jwfx** [comment]
I was thinking about something like this:
https://github.com/jwfx/nuke/commit/d3f7454104d5a50f217cb65fd9202db65a53751b

**Comment by matkoch** [comment]
oh that's even better, thanks for the research

**Comment by jwfx** [comment]
Thanks for the feedback.

Should I turn this into a PR? I wasn't sure, since it is just a trivial change.

Also, just for my understanding:
Do you think that setting `resolveDependencies` to false in the `GetLocalInstalledPackage` call in `AddTeamCityLogger` could have unwanted side effects?

**Comment by matkoch** [comment]
> Should I turn this into a PR? I wasn't sure, since it is just a trivial change.

Sure, but probably check for `.Lenght == 1` instead of `.Any()`. If there are multiple `nuspec` files, it should use the `nupkg`.

> Do you think that setting resolveDependencies to false in the GetLocalInstalledPackage call in AddTeamCityLogger could have unwanted side effects?

For now I'd say to keep this.
