### ISSUE TITLE
Support extension methods for "customValue" properties within generated settings classes.

### ISSUE THREAD

**Issue by williamb1024** [nuke-build/nuke#922]
### Description

When generating classes, prefix customValue properties with a "this" reference. 

https://github.com/nuke-build/nuke/blob/46fbb2f9aa1a548184aad66c28abef9846a5db09/source/Nuke.CodeGeneration/Generators/DataClassGenerator.cs#L205

would become:

```
property.CustomValue ? $"this.Get{property.Name}()" : property.Name
```

This change would allow the customValue property to implemented by an extension method. This allows for a decrease in the amount of code required to mix-and-match property sets within a generated task.

**Comment by matkoch** [comment]
I don't see a strong reason for having this
