### ISSUE TITLE
Arguments class lacks an Add method for arguments that are both "customValue" and a Dictionary type.

### ISSUE THREAD

**Issue by williamb1024** [nuke-build/nuke#924]
### Usage Information

6.0.3

### Description

Declaring a property that is both "customValue" and is based on a dictionary type results in Code Generation producing a call to `Arguments.Add` that is not backed by a matching method.

### Reproduction Steps

Declare a property:

```JSON
{
  "commonTaskPropertySets": {
    "unitAliases": [
          {
            "name": "UnitAliases",
            "type": "Dictionary<string, string>",
            "format": "\\\"-A{value}\\\"",
            "itemFormat": "{key}={value}",
            "customValue": true,
            "help": "TODO"
          }
        ]
  }
}
```

Generates:

```CSharp
              .Add("\"-A{value}\"", GetUnitAliases(), "{key}={value}", customValue: true);
```

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 3: cannot convert from 'string' to 'char?'

### Expected Behavior

Dictionary based properties support customValue implementations.

### Actual Behavior

A compiler error is generated:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 3: cannot convert from 'string' to 'char?'

### Regression?

Unknown.

### Known Workarounds

None yet.

**Comment by matkoch** [comment]
Hi @williamb1024, I'd like to ask you to take a little more time to understand how the CLI wrapper generation works. I can hardly imagine that we managed to support more than 40 CLI tools and there's still something missing.

**Comment by williamb1024** [comment]
It may be worth documenting, possibly within the [schema.json](https://github.com/nuke-build/nuke/blob/46fbb2f9aa1a548184aad66c28abef9846a5db09/source/Nuke.CodeGeneration/schema.json), which options are not compatible with `Dictionary<,>` and `Lookup<,>` . 

Assuming your intent is to indicate that the using "customValue" along with Dictionary<,> was not intended to be supported.
