### ISSUE TITLE
Make Target independent on each other

### ISSUE THREAD

**Issue by sparkmaratoss** [nuke-build/nuke#926]
### Description

is it possible to make Targets independent as f# fake does?
in this case we can define few targets like a pipeline and reuse these targets in any order

```f#
// *** Define Targets ***
Target.create "Clean" (fun _ ->
  Trace.log " --- Cleaning stuff --- "
)

Target.create "Build" (fun _ ->
  Trace.log " --- Building the app --- "
)

Target.create "Deploy" (fun _ ->
  Trace.log " --- Deploying app --- "
)

Target.create "All" ignore

// *** Define Dependencies ***
"Clean"
  ==> "Build"
  ==> "Deploy"
  ==> "All"

// *** Start Build ***
Target.runOrDefault "All"
```

### Usage Example

```code
I would like to reuse existed targets in different pipelines:


Target A => _ => _.Executes(() => {});
Target B => _ => _.Executes(() => {});
Target C => _ => _.Executes(() => {});

Target BuildPipeline => _ => _
	.DependsOn(A, x => x.OnlyWhen(() => isRequired))
	.DependsOn(B)
	.Executes(() => {});

Target DeployPipeline => _ => _
	.DependsOn(A)
	.DependsOn(C)
	.Executes(() => {});

Target DeployMobileAppsPipeline => _ => _
	.DependsOn(A)
	.DependsOn(B)
	.DependsOn(C)
	.Executes(() => {});
```
using
```
./build.ps1 --target DeployPipeline
...
./build.ps1 --target BuildPipeline
```

**Comment by matkoch** [comment]
From the docs:

> Note, that dependencies are solely specified at individual targets.

From the FAQ:

> Why are my targets executed out of order?

> It is very likely that wrong assumptions have been made. Calling nuke --plan will show a visual representation of all execution plans. Dependencies are solely defined at the individual targets. I.e., not by the order being passed from the command-line nor in which order they're mentioned in a DependsOn call and alike.
