### ISSUE TITLE
--root parameter should affect version.json location

### ISSUE THREAD

**Issue by simonfahrig** [nuke-build/nuke#928]
### Usage Information

Nuke Version: 6.0.2

### Description

I use Nerdbank.GitVersioning where a `version.json` file is located at the root level of the repository holding the actual version and some metadata.
As a part of my build pipeline, I used to call nukes target `Pack` from another repository using the `--root` parameter.
The problem is: nuke takes the version from the version.json in the current working directory instead of the one at the --root.

### Reproduction Steps

Suppose, you have two repositories. Both using Nerdbank.GitVersioning to provide a version to the Pack step from nuke.
So both repositories provide a `version.json` file:

```
|->parent
|  |->repositoryA
|  |  |->version.json ("version": "1.0.0")
|  |  [...]
|  |->repositoryB
|     |->version.json ("version": "2.0.0")
|     |->src
|     |  |->projectB
|     [...]
```

Now call `nuke Pack --root ../repositoryB` from within repositoryA:

```
cd parent/repositoryA
nuke Pack --root ../repositoryB
```

### Expected Behavior

I expect a package `projectB.2.0.0.nupk` to be packed.

### Actual Behavior

Instead, the package will be `projectB.1.0.0.nupk`.
From my point of view, this is not the intended behavior, since obviously the source code is taken from one repository and the version from another.

### Known Workarounds

I´d probably not have raised this issue, if I had known a workaround ;)

In fact, this runs on Teamcity as part of a Kotlin script, i.e. you can't change the current working directory:

> In a Java program you can't change your current working directory and you shouldn't need to. Simply use absolute file paths.

_Accepted answer on <https://stackoverflow.com/questions/4884681/how-to-use-cd-command-using-java-runtime>_

Edit: Just discovered: You can pass a workingDir-param to the task.

**Comment by simonfahrig** [comment]
@matkoch, i wondered why you removed the bug label.
Does nuke behave as intended? Or am I just not allowed to add the bug label?

**Comment by matkoch** [comment]
`-root` doesn't change the working directory. That's what you need to adapt.
