### ISSUE TITLE
SelfContained in DotNetBuildSettings

### ISSUE THREAD

**Issue by mvakili-axion** [nuke-build/nuke#929]
### Description

In DotNetPublishTask there is a method named EnableSelfContained() which creates a self-contained version by adding --self-contained parameter to the `dotnet publish` command.

The same approach can be applied to DotNetBuildTask since `dotnet build` accepts the same parameter as described in dotnet doc [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build)

### Usage Example

```code
DotNetBuild(
  s => s
  .SetProjectFile(...)
  ...
  .EnableSelfContained() // Or .DisableSelfContained()
  ...
);
```

**Comment by matkoch** [comment]
Can you please create a PR instead?
