### ISSUE TITLE
No instances of MSBuild could be detected

### ISSUE THREAD

**Issue by ep0x** [nuke-build/nuke#933]
### Usage Information

Nuke Version: v6.0.3 / Dotnet Version: 6.0.301 / Operation System : Mac Os Monyerey 12.4, M1 (CPU)

### Description

When i try to init setup in solution folder of  i got this problem.  I did try different solutions and project but result is same.

### Reproduction Steps

Type command nuke :setup in  your terminal on mac os with m1 cpu

output from terminal: 

NUKE Global Tool version 6.0.3 (OSX,.NETCoreApp,Version=v3.1)
No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.

### Expected Behavior

Should init Nuke without problem.

### Actual Behavior

Throwing error in terminal : 
No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.

### Known Workarounds

For now i didn't find any workaround.

**Comment by ep0x** [comment]
Maybe this is the case? https://github.com/microsoft/MSBuildLocator/issues/153

**Comment by matkoch** [comment]
would you be able to test a couple of private builds that i send you? and maybe chat besides so we can get it done more quickly? slakc would be good

**Comment by ep0x** [comment]
Sure, ill be available after 21:00h UTC+2 time

**Comment by matkoch** [comment]
ping me next week plz

**Comment by ep0x** [comment]
I can confirm your working solution @matkoch,  in commit [c4a17d4] i already tested ur fix.
Works normally without complaining about  "No instances of MSBuild".
