### ISSUE TITLE
TypeLoadException: Method 'get_ProcessCustomLogger'

### ISSUE THREAD

**Issue by Shyam268** [nuke-build/nuke#935]
### Usage Information

Nuke.Azure" Version="0.9.0"	"Nuke.Common" Version="6.0.3" 

### Description

we have upgraded the nuke tool to latest 6.0.3.  
i am facing couple of issues

Getting this error while publishing artifacts to azure devops
` TypeLoadException: Method 'get_ProcessCustomLogger' in type 'Nuke.Azure.AzureArtifactsUniversalPublishSettings' from assembly 'Nuke.Azure, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`
how to resolve the above error

Nuke.azure is used to publish artifacts to azure devops. and it is deprecated now.
this is how we are using to  publish artifacts now

```
AzureArtifactsTasks.AzureArtifactsUniversalPublish(s => s
				.SetFeed(Feed)
				.SetOrg(Org)
				.SetName(artifactName)
				.SetPath(zipFilPath)
				.SetVersion(version)
				.SetDescription(artifactDescription));
```

I tried removing Nuke.Azure deprecated package and following this link [https://github.com/nuke-build/nuke/issues/632]. but here how do i  provide all these parameters(Feed,org, artifactName, zipFilPath, version, Description)?

### Reproduction Steps

Reproduced using these packages
	<PackageReference Include="Nuke.Azure" Version="0.9.0" />
		<PackageReference Include="Nuke.Common" Version="6.0.3" />

### Expected Behavior

without any error artifacts should be published to azure devops

### Actual Behavior

Getting an error while publishing artifacts

**Comment by matkoch** [comment]
`AzurePipelines` has methods to publish artifacts. As you already mentioned, the `Nuke.Azure` package is obsolete, so please don't use it.

**Comment by Shyam268** [comment]
but here how do i provide all these parameters(Feed,org, artifactName, zipFilPath, version, Description)?

**Comment by Shyam268** [comment]
> `AzurePipelines` has methods to publish artifacts. As you already mentioned, the `Nuke.Azure` package is obsolete, so please don't use it.

but here how do i provide all these parameters(Feed,org, artifactName, zipFilPath, version, Description)?
