### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'Src\build\specifications' is denied

### ISSUE THREAD

**Issue by Shyam268** [nuke-build/nuke#937]
### Usage Information

    "Nuke.Common" Version="6.0.3" "Nuke.CodeGeneration" Version="6.0.3"  and dotnet 6.0

### Description

Not able to generate .cs file from .json using GenerateCode() method

### Reproduction Steps

Added a .json file in specifications folder which has a details about command line options for an AZ exe
```
    string SpecificationsDirectory => BuildProjectDirectory / "specifications";
    string ReferencesDirectory => BuildProjectDirectory / "references";
    AbsolutePath GenerationDirectory => RootDirectory / "source" / "Nuke.Common" / "Tools";
    string ToolSchemaFile => SourceDirectory / "Nuke.CodeGeneration" / "schema.json";

 Target Generate => _ => _
       .Executes(() =>
       {
           GenerateCode(
               SpecificationsDirectory,
               outputFileProvider: x => GenerationDirectory / x.Name / x.DefaultOutputFileName,
               namespaceProvider: x => $"Nuke.Common.Tools.{x.Name}");
       });
```

### Expected Behavior

it should create .cs file

### Actual Behavior

System.UnauthorizedAccessException: Access to the path "Src\build\specifications" is denied

**Comment by Shyam268** [comment]
i have created a sample project to reproduce this .please have a look . i am able to build solution but failed to generate code from .json file 
[TestNuke.zip](https://github.com/nuke-build/nuke/files/8896377/TestNuke.zip)
.

**Comment by Shyam268** [comment]
@matkoch Can I get some sample code to create the generated CS not depending on Git ?

**Comment by matkoch** [comment]
`GenerateCode` must be invoked on a file, not a directory.

**Comment by matkoch** [comment]
Next time please include the stacktrace as text/code right away, would make a lot of things easier.
