### ISSUE TITLE
 SyntaxError in Python 3.6.5

### ISSUE THREAD

**Issue by 0xF6** [nuke-build/nuke#94]
![image](https://user-images.githubusercontent.com/13326808/41949861-f3fdfcfa-79cb-11e8-8aa7-39f8f6d8e6bb.png)

**Comment by 0xF6** [comment]
![image](https://user-images.githubusercontent.com/13326808/41949991-b2700f5c-79cc-11e8-8d3d-90be04a6b436.png)
x2

**Comment by matkoch** [comment]
Thanks for your contribution! 😄🎉
