### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#941]

**Comment by cmandlbaur** [comment]
Looks like all the API docs are gone, but I got here from - https://nuke.build/api/Nuke.Docker/Nuke.Docker.DockerStackDeploySettings.html

**Comment by IP14Y3RI** [comment]
I got here from -
https://nuke.build/api/Nuke.Kubernetes/Nuke.Kubernetes.KubernetesCordonSettings.html

**Comment by matkoch** [comment]
@cmandlbaur maybe a star? ;)

**Comment by AntonC9018** [comment]
https://nuke.build/docs/writing-addons/code-generation.html

**Comment by matkoch** [comment]
@AntonC9018 intentionally removed. if you need examples, just take a look at some other json files

**Comment by cmandlbaur** [comment]
> @cmandlbaur maybe a star? ;)

Starred, thank you for the amazing work!

**Comment by johnstorey** [comment]
Presumably all API docs are still down, but I was looking for https://nuke.build/docs/cicd/azure-pipelinesundefined

**Comment by Rabosa616** [comment]
https://nuke.build/download/visual-studio is not working, the resharper and raider works correctly

**Comment by FreeYourMinds** [comment]
Hey,

_Kind of_ a dead link problem...

FYI:

Nuke.GlobalTool (9.0.2) generates the following comment

``` 
    /// Support plugins are available for:
    ///   - JetBrains ReSharper        https://nuke.build/resharper
    ///   - JetBrains Rider            https://nuke.build/rider
    ///   - Microsoft VisualStudio     https://nuke.build/visualstudio
    ///   - Microsoft VSCode           https://nuke.build/vscode
```

`https://nuke.build/resharper` redirects to `https://nuke.build/docs/common/cli-tools/?tool=ReSharper`, the other three bring you here 🤷‍♂️

**Comment by lksr-demant** [comment]
https://nuke.build/blog/2024/01/22/update-on-ide-extensions/
