### ISSUE TITLE
Could not register MSBuild

### ISSUE THREAD

**Issue by ferrygruiters** [nuke-build/nuke#942]
### Usage Information

Nuke 6.1.0 / dotnet SDK 6.0.301 / VS2022 / Windows 10

### Description

After installing Nuke 6.1.0 (upgraded from 5.0.2), I get the following warning:

```
22:10:39 [WRN] Attempting second-chance registration of MSBuild after RegisterDefaults failed
22:10:39 [WRN] Could not register MSBuild: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
22:10:39 [WRN] Exception was suppressed
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Nuke.Common.Execution.Telemetry.CheckAwareness()
```

I can run 'msbuild' via CMD/powershell. I have added 'C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin' to the environment PATH variables.

The inner exception of the error is:
```
No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.
```

### Reproduction Steps

I can get the inner exception by calling the MSBuildLocator manually.

```
    Target ExampleCode => _ => _
        .Executes(() =>
        {
            try
            {
                MSBuildLocator.RegisterDefaults();
            }
            catch(Exception ex)
            {
                Serilog.Log.Information(ex.Message);
            }
        });
```

### Expected Behavior

- Success result when calling MSBuildLocator.RegisterDefaults()
- No System.IO.FileNotFoundException for System.Runtime, Version=6.0.0.0

### Actual Behavior

- An error when calling MSBuildLocator.RegisterDefaults()
- A System.IO.FileNotFoundException for System.Runtime, Version=6.0.0.0

### Regression?

Version 5.0.2 was working fine. Had to upgrade to >6 to use VS2022.

**Comment by matkoch** [comment]
This is working for me on different machines. If you want this fixed, please contact me privately.

**Comment by oising** [comment]
I'm seeing this with System.Runtime 8.0.0.0 and Nuke 6.3, on windows on ARM (SL7) with sdk 8.0.303 / 8.0.400-preview installed
