### ISSUE TITLE
GitVersion ubuntu

### ISSUE THREAD

**Issue by eaba** [nuke-build/nuke#944]
### Usage Information

GitVersion

### Description

14:24:19 [INF] > /home/runner/.dotnet/dotnet/home/runner/.nuget/packages/gitversion.tool/5.10.3/tools/net6.0/any/gitversion.dll /nocache
Warning: Could not inject value for "Build.GitVersion"
14:24:20 [WRN] Could not inject value for Build.GitVersion
Nuke.Common.Tooling.ProcessException: Process 'dotnet' exited with code 1.
   > /home/runner/.dotnet/dotnet /home/runner/.nuget/packages/gitversion.tool/5.10.3/tools/net6.0/any/gitversion.dll /nocache
   @ /home/runner/work/SharpPulsar/SharpPulsar
   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process) in /_/source/Nuke.Common/Tooling/ProcessExtensions.cs:line 39
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(GitVersionSettings toolSettings) in /_/source/Nuke.Common/Tools/GitVersion/GitVersion.Generated.cs:line 83
   at Nuke.Common.Tools.GitVersion.GitVersionTasks.GitVersion(Configure`1 configurator) in /_/source/Nuke.Common/Tools/GitVersion/GitVersion.Generated.cs:line 121
   at Nuke.Common.Tools.GitVersion.GitVersionAttribute.GetValue(MemberInfo member, Object instance) in /_/source/Nuke.Common/Tools/GitVersion/GitVersionAttribute.cs:line 47
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.TryGetValue(MemberInfo member, Object instance) in /_/source/Nuke.Common/ValueInjection/ValueInjectionAttributeBase.cs:line 25

### Reproduction Steps

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Run './build.cmd Test'
        run: ./build.cmd Test

### Expected Behavior

no

### Actual Behavior

Target Compile => _ => _
        .DependsOn(Restore)
        .Executes(() =>
        {
            var vers = GitVersion.MajorMinorPatch;
            DotNetBuild(s => s
                .SetProjectFile(Solution)
                .SetNoRestore(InvokedTargets.Contains(Restore))
                .SetConfiguration(Configuration)
                //.SetAssemblyVersion(vers)
                .SetFileVersion(vers)
                .SetVersion(GitVersion.SemVer));
        });

**Comment by matkoch** [comment]
I don't see an issue here. More likely a configuration issue with GitVersion. Try to get the output of the invocation.

**Comment by eaba** [comment]
- uses: actions/checkout@v1


10:04:23 [WRN] Configuration files for GitHubActions (run_tests_transaction) have changed.
10:04:23 [WRN] Configuration files for GitHubActions (run_tests) have changed.
10:04:23 [WRN] Configuration files for GitHubActions (run_tests_api) have changed.
10:04:23 [WRN] Configuration files for GitHubActions (run_tests_autocluster) have changed.
10:04:23 [WRN] Configuration files for GitHubActions (run_tests_acks) have changed.
10:04:23 [WRN] Configuration files for GitHubActions (run_tests_tableview) have changed.
10:04:23 [WRN] Configuration files for GitHubActions (run_tests_partitioned) have changed.
10:04:23 [WRN] Configuration files for GitHubActions (build) have changed.
10:04:24 [WRN] Configuration files for GitHubActions (run_tests_multitopic) have changed.
10:04:25 [WRN] Configuration files for GitHubActions (run_tests_eventsource) have changed.
10:04:25 [WRN] Configuration files for GitHubActions (nuget) have changed.

- uses: actions/checkout@v2
- uses: actions/checkout@v2
- uses: actions/checkout@v2
- uses: actions/checkout@v2
- uses: actions/checkout@v2
- uses: actions/checkout@v2

**Comment by matkoch** [comment]
?

**Comment by ryanande** [comment]
@eaba did you get this issue resolved?
Experiencing the identical issue w/ gh actions, gitversion 5.10.3.

**Comment by eaba** [comment]
Yes.
FetchDepth = 0,

**Comment by igiona** [comment]
The very same issue happens on Bitbucket as well.
Luckily, the same clone option is available and solves the issue there as well:

```
    - step:
        name: Build & Test
        clone:
          depth: full
```
