### ISSUE TITLE
Fails on Apple M1

### ISSUE THREAD

**Issue by byme8** [nuke-build/nuke#954]
### Usage Information

6.1.1 / 6.0.301 / net 6? / MacOS  

### Description

Installed nuke via next command:
``` 
dotnet tool install Nuke.GlobalTool --global 
```

Then when I am trying to execute 
```
nuke
```
It just fails with the next error:
```
A fatal error occurred. The required library libhostfxr.dylib could not be found.
If this is a self-contained application, that library should exist in [/Users/stanislav/.dotnet/tools/.store/nuke.globaltool/6.1.1/nuke.globaltool/6.1.1/tools/netcoreapp3.1/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/local/share/dotnet/x64] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=osx.12-x64&apphost_version=6.0.6
```

### Reproduction Steps

```
dotnet tool install Nuke.GlobalTool --global 
nuke
```

### Expected Behavior

It works

### Actual Behavior

A fatal error occurred. The required library libhostfxr.dylib could not be found.
If this is a self-contained application, that library should exist in [/Users/stanislav/.dotnet/tools/.store/nuke.globaltool/6.1.1/nuke.globaltool/6.1.1/tools/netcoreapp3.1/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/local/share/dotnet/x64] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=osx.12-x64&apphost_version=6.0.6

**Comment by ron-myers** [comment]
Hey @byme8 -  Nuke global tool works on M1 for me.  

On M1 machine, after uninstalling the global tool:
```
> dotnet tool install Nuke.GlobalTool --global
You can invoke the tool using the following command: nuke
Tool 'nuke.globaltool' (version '6.1.1') was successfully installed.

> nuke :setup
NUKE Global Tool 🌐 version 6.1.1 (OSX,.NETCoreApp,Version=v3.1)

Let's setup a new build!

Could not find root directory. Falling back to working directory ...
🌳  Root directory:           /Users/ronmyers/workspace/nuke
🔩  Build runtime:            .NET (net6.0)
🔖  Build project name:       test
📍  Build project location:   ./build
💎  Nuke.Common version:      6.1.1
🧰  Default solution:         <none>

Setup completed! 🎉
```

What is the output on your machine for: 

```
dotnet --list-sdks
```

**Comment by byme8** [comment]
```
dotnet --list-sdks
6.0.300 [/usr/local/share/dotnet/sdk]
6.0.301 [/usr/local/share/dotnet/sdk]
```
Okay, looks like nuke works only on top of the netcoreapp3.1. This is not ideal, because it doesn't have native support for M1 and works through the Rosetta. At the same time, support for it will end soon.
Version | Original Release Date | Latest Patch Version | Patch Release Date | Support Level | End of Support
-- | -- | -- | -- | -- | --
.NET 6 | November 8, 2021 | 6.0.6 | June 14, 2022 | LTS | November 12, 2024
.NET Core 3.1 | December 3, 2019 | 3.1.26 | June 14, 2022 | LTS | December 13, 2022

**Comment by byme8** [comment]
So... It is fine that the nuke fails in the legit scenario? Am I right?

**Comment by matkoch** [comment]
![image](https://user-images.githubusercontent.com/5005566/177145595-7c5eb762-e6fd-490a-9a59-7563b77aec6b.jpeg)
