### ISSUE TITLE
Nuke cannot find 'SonarQube.Analysis.xml' at startup

### ISSUE THREAD

**Issue by Velociraptor45** [nuke-build/nuke#955]
### Usage Information

Nuke v6.1.1 / 6.0.201, 6.0.301 / .net 6 / ubuntu, windows (Azure)

### Description

Hey there,

we're executing Nuke in an Azure CI Pipeline for a new project. Nuke should be responsible for connecting to SonarCloud (SonarBegin / SonarEnd), compilation, testing & report generation.

However, in 99% of all cases it fails with this output at startup
```
PowerShell Core version 7.2.5
Microsoft (R) .NET SDK version 6.0.201
/azp/_work/2/.sonarqube/bin/targets/SonarQube.Integration.targets(241,5): error MSB4018: The "IsTestFileByName" task failed unexpectedly. [/azp/_work/2/s/build/_build.csproj]
/azp/_work/2/.sonarqube/bin/targets/SonarQube.Integration.targets(241,5): error MSB4018: System.IO.FileNotFoundException: /azp/_work/2/s/.tools/.store/dotnet-sonarscanner/5.7.1/dotnet-sonarscanner/5.7.1/tools/net5.0/any/SonarQube.Analysis.xml [/azp/_work/2/s/build/_build.csproj]
/azp/_work/2/.sonarqube/bin/targets/SonarQube.Integration.targets(241,5): error MSB4018:    at SonarScanner.MSBuild.Common.Serializer.LoadModel[T](String fileName) [/azp/_work/2/s/build/_build.csproj]
/azp/_work/2/.sonarqube/bin/targets/SonarQube.Integration.targets(241,5): error MSB4018:    at SonarScanner.MSBuild.Common.AnalysisProperties.Load(String fileName) [/azp/_work/2/s/build/_build.csproj]
/azp/_work/2/.sonarqube/bin/targets/SonarQube.Integration.targets(241,5): error MSB4018:    at SonarScanner.MSBuild.Common.ConfigSettingsExtensions.GetAnalysisSettings(AnalysisConfig config, Boolean includeServerSettings, ILogger logger) [/azp/_work/2/s/build/_build.csproj]
/azp/_work/2/.sonarqube/bin/targets/SonarQube.Integration.targets(241,5): error MSB4018:    at SonarScanner.MSBuild.Tasks.IsTestFileByName.Execute() [/azp/_work/2/s/build/_build.csproj]
/azp/_work/2/.sonarqube/bin/targets/SonarQube.Integration.targets(241,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/azp/_work/2/s/build/_build.csproj]
/azp/_work/2/.sonarqube/bin/targets/SonarQube.Integration.targets(241,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/azp/_work/2/s/build/_build.csproj]
##[error]PowerShell exited with code '1'.
Finishing: Nuke
```

We don't even see this fancy NUKE lettering with Nuke execution engine version information, etc.
So, for us it looks like Nuke is looking for `SonarQube.Analysis.xml` for some reason at startup and can't find it.
We even tried to install the 5.7.1 version of the `dotnet-sonarscanner` package in a previous step in the pipeline but that didn't change anything.

And sometimes it works and nukes executes all targets flawlessly, but we can't see any patterns regarding agents it was executed on, build arguments, targets, etc.

### Reproduction Steps

This is the minimal build class we were able to narrow it down to. So, we guess the actual content of the build class doesn't matter.
```
class Build : NukeBuild
{
    public static int Main() => Execute<Build>(x => x.Tgt);

    Target Tgt => _ => _
        .Executes(() =>
        {
            
        });
}
```

Azure pipeline step:
```
- task: PowerShell@2
  name: 'Nuke'
  inputs:
    filePath: 'build.ps1'
```

It doesn't make a difference if executed on a windows or ubuntu agent. Furthermore, we were **not** able to reproduce this locally on a windows 10 machine.

### Expected Behavior

Nuke starts executing its targets.

### Actual Behavior

Nuke throws above mentioned `FileNotFoundException` upon startup and exits without executing any targets.

**Comment by bitbonk** [comment]
It's not really NUKE that is  looking for that file but the rather the SonarQube MSBuild target (SonarQube.Integration.targets) that you referenced in your project.

https://community.sonarsource.com/t/error-msb4018-the-istestfilebyname-task-failed-unexpectedly/26212

Does the file `/azp/_work/2/s/.tools/.store/dotnet-sonarscanner/5.7.1/dotnet-sonarscanner/5.7.1/tools/net5.0/any/SonarQube.Analysis.xml` actually exist?

We are also using SonarQube with Nuke on Azure DevOps (Server, the on-premise variant) and never ran into this problem.

**Comment by Velociraptor45** [comment]
Thanks, your question if the file exists pushed me in the right direction of thought.
I mentioned that we tried to install SonarScanner in a step before executing nuke - but we installed it globally and not in the .tools/ directory of the working path (silly me). Now that it's installed in the right directory, the issue is gone. Here's the Azure task if anyone else has the same problem:
```
- task: CmdLine@2
  name: 'InstallSonarscanner'
  inputs:
    script: 'dotnet tool install dotnet-sonarscanner --version 5.7.1 --tool-path $(Build.SourcesDirectory)/.tools/'
```

Howerver, I still don't understand why the SonarQube MSBuild was executed in the first place. Is this always the case when you inherit from `NukeBuild`? Because as you can see in my minimal build class above, I don't do anything with Nuke here, it's just an empty target.

**Comment by bitbonk** [comment]
Why do you have this InstallSonarScanner task at all? It is definitely not needed when using NUKE's  built-in [SonarScannerTasks](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/SonarScanner/SonarScanner.Generated.cs).

**Comment by lahma** [comment]
I think you still need to have the package download though in your csproj if you want to use the built-in tasks:

```xml
<ItemGroup>
    <PackageDownload Include="dotnet-sonarscanner" Version="[5.7.1]" />
</ItemGroup>
```

**Comment by bitbonk** [comment]
> I think you still need to have the package download though in your csproj if you want to use the built-in tasks

Right, and if I remember right, NUKE told me that when I tried to run the task for the first time and even offered to do it for me.

**Comment by Velociraptor45** [comment]
@bitbonk We do use SonarScannerBegin & SonarScannerEnd in our targets. But what I tried to convey with the minimal Build class in my initial post is that it doesn't matter at all what kind of targets we use because nuke doesn't even get that far to execute targets. The process failes before that.

@lahma That also works and is probably better, thanks!
