### ISSUE TITLE
Support for 'Environments' in Azure Pipelines

### ISSUE THREAD

**Issue by mathiasi** [nuke-build/nuke#964]
### Description

We were looking into using Nuke for CI/CD. We use Azure Pipelines and one apparent thing that we could see that we would miss is the "Environments"-feature (I don't know if others have similar features). Is this something that is planned to be supported and does it even make sense for a tool like Nuke?

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops
https://faun.pub/azure-devops-environments-6696acfdb08f

**Comment by matkoch** [comment]
Not planned at the moment.

**Comment by BigHoss** [comment]
@matkoch is there any other way to achieve approvals? 

does everyone just deploy to production without running it through a test environment?
