### ISSUE TITLE
Build throws error 'String reference not set to an instance of a String. (Parameter 's')'

### ISSUE THREAD

**Issue by RemyDuijkeren** [nuke-build/nuke#965]
### Usage Information

NUKE 6.1.1

### Description

With a new local folder where first Git commit is done and has no remotes yet.

Running NUKE build fails with the message:
`String reference not set to an instance of a String. (Parameter 's')`

### Reproduction Steps

- Locally initialize a solution folder with Git. 
- Add first commit (and has no remote yet).
- start NUKE from commandline

### Expected Behavior

NUKE Build runs normally

### Actual Behavior

```
14:07:25.404 | V |                      | ArgumentsFromParametersFile.OnBuildCreated (150)
14:07:25.441 | V |                      | Passing value for Build.Solution (NServiceBus.Extensions.Diagnostics.ApplicationInsights.sln)
14:07:25.450 | V |                      | InjectParameterValues.OnBuildCreated (100)
14:07:25.489 | V |                      | HandleShellCompletion.OnBuildCreated (75)
14:07:25.575 | V |                      | GenerateBuildServerConfigurations.OnBuildCreated (50)
14:07:25.575 | V |                      | InvokeBuildServerConfigurationGeneration.OnBuildCreated (45)
14:07:25.585 | V |                      | UpdateNotification.OnBuildCreated (10)
14:07:25.590 | V |                      | UnsetVisualStudioEnvironmentVariables.OnBuildCreated (0)
14:07:25.591 | V |                      | HandleVisualStudioDebugging.OnBuildCreated (0)
14:07:25.592 | V |                      | HandleSingleFileExecution.OnBuildCreated (-50)
14:07:25.592 | V |                      | EventInvoker.OnBuildCreated (-3.4028235E+38)
14:07:25.607 | V |                      | HandleHelpRequests.OnBuildInitialized (5)
14:07:25.607 | V |                      | CheckBuildProjectConfigurations.OnBuildInitialized (0)
14:07:25.755 | V |                      | Telemetry.OnBuildInitialized (0)
14:07:26.073 | V |                      | Target-unrelated exception was thrown
System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)
   at Nuke.Common.Utilities.StringExtensions.GetSHA256Hash(String str) in /_/source/Nuke.Common/Utilities/String.GetHash.cs:line 24
   at Nuke.Common.Execution.Telemetry.GetRepositoryProperties(String directory) in /_/source/Nuke.Common/Execution/Telemetry.Properties.cs:line 67
   at Nuke.Common.Execution.Telemetry.BuildStarted(NukeBuild build) in /_/source/Nuke.Common/Execution/Telemetry.Events.cs:line 18
   at Nuke.Common.Execution.TelemetryAttribute.OnBuildInitialized(NukeBuild build, IReadOnlyCollection`1 executableTargets, IReadOnlyCollection`1 executionPlan) in /_/source/Nuke.Common/Execution/TelemetryAttribute.cs:line 21
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.NukeBuild.ExecuteExtension[TExtension](Expression`1 action)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions) in /_/source/Nuke.Common/Execution/BuildManager.cs:line 58
14:07:26.093 | V |                      | UpdateNotification.OnBuildFinished (10)
14:07:26.093 | V |                      | SerializeBuildServerState.OnBuildFinished (0)
14:07:26.094 | V |                      | ShutdownDotNetAfterServerBuild.OnBuildFinished (-50)
14:07:26.094 | V |                      | EventInvoker.OnBuildFinished (-3.4028235E+38)
```

### Known Workarounds

- Remove .git folder
- Adding remote seems also to work

**Comment by Mourad57** [comment]
Hi,

The other workaround is to opt out of the telemetry now that the bug is reported until this is fixed.

**Comment by PandaWood** [comment]
> * Remove .git folder
> * Adding remote seems also to work

Not sure I'm adding anything, but FYI, I get this error (first-time tool user NUKE 6.1.2) when running in an existing git repository (with > 100 commits) and with a remote. So this seems to rule out most of the original description/requirements. I'm running `nuke :setup`

**Comment by derrichter1997** [comment]
@PandaWood I had the same issue. Discovered that the issue is related to the .git/config file.
Mine had the following structure:
>[core]
>	repositoryformatversion = 0
>	filemode = false
>	bare = false
>	logallrefupdates = true
>	symlinks = false
>	ignorecase = true
>[remote "**leica-gcs**"]
>	url = \*url to repo\*
>	fetch = +refs/heads/\*:refs/remotes/**leica-gcs**/\*

After replacing **leica-gcs** with **origin** it worked again.

Internally the issue is probably caused by the following line:
>["repo_url"] = repository.SshUrl.GetSHA256Hash().Substring(startIndex: 0, length: 6) 

at Telemetry.Properties.cs:71

SshUrl is dependent from the Endpoint property (both from the GitRepository class) and null if Endpoint is null.
Endpoint is generated by the following segment of the .git/config file.

>[remote "**leica-gcs**"]
>	url = \*url to repo\*
>	fetch = +refs/heads/*:refs/remotes/**leica-gcs**/*

I hope this helps. BR

**Comment by PandaWood** [comment]
Thanks @derrichter1997, Right, my git remote is also not called 'origin' - though I'm not willing to change this, so I might have to look at turning telemetry off, if that suggestion was valid.
From my .git/config
`fetch = +refs/heads/*:refs/remotes/gogs/*`

*update*
For completeness, turning telemetry off does get passed the error eg using a Windows/DOS console
`set NUKE_TELEMETRY_OPTOUT=true`

For GitBash on Windows (or maybe just non Windows)
`export NUKE_TELEMETRY_OPTOUT=true`
