### ISSUE TITLE
DockerTasks.Run

### ISSUE THREAD

**Issue by masaanli** [nuke-build/nuke#979]
### Usage Information

NUKE 6.1.2 / SDK 6.0.102 / MacOS

### Description

Got an issue with **dockerTasks**, When running **DockerTasks** its not working, and when running **Docker** a **PathExecutable** it’s working.

**Working:**
```
[PathExecutable("docker")]
readonly Tool? Docker;

Docker?.Invoke($"run --env-file {envFilePath} {DockerContainerRegistry}/platform-agent:latest {terraformModuleName} {BuildId} {ghUsername} {ghPat} -y", logOutput: true);
```

**outputs:**
`/usr/bin/docker run --env-file /home/runner/work/platform-backend/platform-backend/output/aspnetcore/api.env xxx.azurecr.io/platform-agent:latest backend 7472435931 *** *** -y`

---------------------------------------------

**Not working:**
```
   DockerTasks.DockerRun(_ => _
                    .SetImage($"{DockerContainerRegistry}/platform-agent:latest")
                    .SetEnvFile(envFilePath)
                    .SetArgs($"{terraformModuleName} {BuildId} {ghUsername} {ghPat} -y")
                    .EnableProcessLogOutput()
                );
```

**outputs:**
`/usr/bin/dockerrun --env-file /home/runner/work/platform-backend/platform-backend/output/aspnetcore/api.env xxx.azurecr.io/platform-agent:latest "backend 7472694175 *** *** -y"`

Issue, the quotes, how can we run DockerTasks and not set it?
Issue, dockerrun instead of docker run?

### Reproduction Steps

Create a task and put this code inside it:

```
DockerTasks.DockerRun(_ => _
                    .SetImage($"{DockerContainerRegistry}/platform-agent:latest")
                    .SetEnvFile(envFilePath)
                    .SetArgs($"{terraformModuleName} {BuildId} {ghUsername} {ghPat} -y")
                    .EnableProcessLogOutput()
                );
```

When it's running it runs as `dockerrun` and is putting `quotes` around the arguments and commands.

### Expected Behavior

1. Make docker run like: `docker run` instead of `dockerrun`
2. Remove the quotes when setting **SetArgs**, or/and remove quotes while setting **SetCommand**, or maybe add an **extension** to add something behind it without quotes?

### Actual Behavior

```
DockerTasks.DockerRun(_ => _
                    .SetImage($"{DockerContainerRegistry}/platform-agent:latest")
                    .SetEnvFile(envFilePath)
                    .SetArgs($"{terraformModuleName} {BuildId} {ghUsername} {ghPat} -y")
                    .EnableProcessLogOutput()
                );
```

When it's running it runs as `dockerrun` and is putting `quotes` around the arguments and commands.

### Known Workarounds

Not use the **DockerTasks.DockerRun** but:

```
[PathExecutable("docker")]
readonly Tool? Docker;

Docker?.Invoke($"run --env-file {envFilePath} {DockerContainerRegistry}/platform-agent:latest {terraformModuleName} {BuildId} {ghUsername} {ghPat} -y", logOutput: true);
```

**Comment by matkoch** [comment]
`SetArgs` receives an array. Please ask questions under discussions next time, and please also star the project. 😉
