### ISSUE TITLE
Support ability to install CI/CD CLI tools in runners before Nuke Build is launched

### ISSUE THREAD

**Issue by Simonl9l** [nuke-build/nuke#980]
### Description

If for example one needs to install other CLI's into the CI/CD runner, it would be very helpful such that one can the define a `InstallExecutable ` (similar to a `PathExecutable`) `Tool` for that tool, and have it instal and resolve correctly as part of the Nuke build initiation.

This could be generated as applicable into the build tool configuration

### Usage Example

```code
class Build : NukeBuild
{
...

   [InstallExecutable(install: "npm install -g aws-cdk" name: "cdk")] readonly Tool Cdk; 
...
}

This would result in the following addition to the GitHub workflow.yml:

steps:
   ... (checkout etc)
  - name Install Tool cdk
    run: npm install -g aws-cdk
  - name  Run './build.cmd <Target>'
    run: ./build.cmd <Target>
```

### Alternative

Current alternative is to add a Target as a predecessor of any Task that need to tool, This Target can run the requisite Tool Task to install the new CLI:

```C#
class Build : NukeBuild
{
...

   [PathExecutable(name: "cdk")] readonly Tool Cdk; 

    Target InstallTools => _ => _
        .Executes(() =>
        {
            NpmTasks.NpmInstall(settings =>
                settings
                    .EnableGlobal()
                    .SetPackages(new[] { "aws-cdk" })
            );
        });
...
}

```

However one gets Warnings at initialization of the Nuke build that the tool can't be found.

**Comment by matkoch** [comment]
I don't think this is a good approach. It leaks build requirements into the YAML files.

**Comment by Simonl9l** [comment]
We’ll it’s a toolset requirement that means a build won’t work. 

What do you recommend if we can’t pre install tools. Not use Nuke?

I guess nuke is highly opinionated than adaptive to even considering different use cases. Very unfortunate.

**Comment by matkoch** [comment]
Your suggested solution simply doesn't align with the fundamental philosophy, which is to optimize for a self-contained build. It's neither about being opinionated nor not being adaptive.

**Comment by Simonl9l** [comment]
OK what this the recommend approach for dealing with this ?

**Comment by Simonl9l** [comment]
@matkoch curious would [npx](https://www.npmjs.com/package/npx) be an option of a default supported tool as an alternate to just npm?

In that way we can use Nuke with a `Npx" command to (if needed) install the requester tool supposed in the arguments on demand. This would cover a whole host of other tools that are node based, and avoid having to implement a predecessor Target with Npm Tool to install said tool and then use a custom tool on basis it's installed.

**Comment by msergein** [comment]
I ran into the same problem and solved it like this:
```c#
//[LocalExecutable("allurectl.exe")]
Tool _allureCtl;
Tool AllureCtl => _allureCtl ??= ToolResolver.GetLocalTool("allurectl.exe");
```
