### ISSUE TITLE
Logger.Block(..) alternative?

### ISSUE THREAD

**Issue by czdietrich** [nuke-build/nuke#987]
### Description

For an unclear reason logging was revamped without an obvious strategy to me.
Commit 5e1fbefcafb689202950dbfd985041f8b2b5d2c7 simply made almost the whole `Logger` class obsolete and now I see no way to create blocks as I could do before with `Logger.Block(..)`. Though there is `NukeBuild.Host.WriteBlock(..)`, but it is not public for an unclear reason. Grouping log messages together is a very useful feature. So what is the intended way here?

Off-topic: Generally spoken I am not a fan of all these breaking changes. What is the use of making useful things internal but also breaking the public API in the next major release? Please, do not make keeping Nuke up to date a nightmare for dev ops people. And please leave the public API stable or if there is really a need for a breaking change then please include an obvious migration path. Commit comments like "Reimplement logging" really is not helping in any way.

Still, thank you for all the work that was invested in this project.

**Comment by czdietrich** [comment]
By the way there seems to be no issue type to represent such issues.

**Comment by czdietrich** [comment]
Does that mean there is no longer an intended way to create custom groupings?

**Comment by matkoch** [comment]
https://nuke.build/faq/#public-api
