### ISSUE TITLE
SolutionSerializer.GetGlobalSection throws a null reference exception on empty line inside GlobalSection

### ISSUE THREAD

**Issue by HuibertJan** [nuke-build/nuke#993]
### Usage Information

6.0.0 / 6.0.302 / net6.0 / windows

### Description

See SolutionSerializer.GetGlobalSection here: https://github.com/nuke-build/nuke/blob/e36bc0c0160b8f7eb68fd75fc7a00aa2aa79ad9f/source/Nuke.Common/ProjectModel/SolutionSerializer.cs#L84

After looping through the solution and finding GlobalSection it will process each subsequent line until EndGlobalSection is found. The processing assumes that each line has an equals (`=`) sign and at least 1 thing before and after the equals sign.

If you have an empty line, `x => x[0].Trim()` will throw a nullref exception from line 97.

As far as I know an empty line is allowed inside a GlobalSection.

### Reproduction Steps

Create any solution with an empty line inside the GlobalSection. Point Nuke at it and build.

### Expected Behavior

Nuke ignores the empty line and builds without error.

### Actual Behavior

A null reference exception is thrown.

### Regression?

I am positive it worked in 5.0.2.

I think this might be the commit that broke it: https://github.com/nuke-build/nuke/pull/158/files#diff-b6a43fcde82b20714225596a985345e8f2e26b5e3ed7d95e7187b68bff7ea6b6

The previous code appears to check the lines inside the GlobalSection for a certain pattern (ProjectPattern).

### Known Workarounds

Remove the empty line from the solution file.

**Comment by estei** [comment]
This looks familiar
Is it not the same as was fixed in #915?

If it then I do believe it was fixed in version 6.0.3 and you are running 6.0.0?

**Comment by HuibertJan** [comment]
It looks like I am a buffoon. It is fixed in a subsequent release. 

Thank you for listening.

**Comment by matkoch** [comment]
By the way, you could also star the project ;)
